### ISSUE TITLE
JsonElement casting methods don't all tell the user what actual type is when cast fails

### ISSUE THREAD

**Issue by kevinmost** [google/gson#1000]
`JsonElement.getAsJsonObject()` [shows the user the JSON in the exception when it fails to cast](https://github.com/google/gson/blob/master/gson/src/main/java/com/google/gson/JsonElement.java#L86). The other 3 `getAsJson___` methods do not. It would be nice if this style of exception message was adopted for the other 3 as well.

I can send a PR if this is a desired change.

**Comment by JakeWharton** [comment]
A PR would be great.
