### ISSUE TITLE
Wrong Import-Package for OSGi

### ISSUE THREAD

**Issue by mickaelistria** [google/gson#1001]
Using GSon in the OSGi world, the directive `Import-Package: com.google.gson.annotations` drives to errors when multiple versions of GSon are available in the container. See https://github.com/eclipse/lsp4j/issues/44#issuecomment-272819326 for reference. The error it produces is
```
java.lang.NoClassDefFoundError: com/google/gson/annotations/JsonAdapter
	at com.google.gson.internal.bind.JsonAdapterAnnotationTypeAdapterFactory.create(JsonAdapterAnnotationTypeAdapterFactory.java:45)
	at com.google.gson.Gson.getAdapter(Gson.java:423)
	at com.google.gson.Gson.toJson(Gson.java:661)
```

The reason is that the Import-Package directive here is too open. Either it should be removed and the GSon bundle would be expected to always use the package it contains, or it should set a version constraint to make sure it's using a good version of the package. Currently, the directive without version cosntraints makes OSGi use the 2.2.4 version of the annotations package when a newer version seems necessary.

**Comment by Marcono1234** [comment]
Seems to be related to #735

**Comment by mickaelistria** [comment]
I didn't see this issue happen again with recent versions. I see the MANIFEST.MF seems richer and now has some `uses` constraints. So let's close.
