### ISSUE TITLE
[Question] Deserialize json with complex polymorphic structure

### ISSUE THREAD

**Issue by memfis19** [google/gson#1003]
Hi, sorry if I duplicate the question, but I can't find what I need and this [answer](https://github.com/google/gson/issues/869) is not enough for me. I have next task:

1. I have base interface
`interface IPolymorphicModel`

2. I have few nested interfaces:
```
interface IContentItem extends IPolymorphicModel
interface IAttachment extends IPolymorphicModel
```

3. I have few implementations:
```
public class MediaAttachment implements IAttachment
```
and 
```
public class Article implements IContentItem {
private List<IAttachment> attachements;
}
```
I am using approach from this [answer](https://github.com/google/gson/issues/869)  to parse json structure using `TypeAdapterFactory` for  `IPolymorphicModel` . But it doesn't solve the problem with inner `IPolymorphicModel` fields. Is it possible to parse such case? Which approach is better to use?

**Comment by Marcono1234** [comment]
Is this still relevant? If so could you please describe a bit more in detail what you mean by "the problem with inner `IPolymorphicModel` fields". Ideally extend the sample code you provided to be a small self contained example which demonstrates the issue you are currently facing.

**Comment by Marcono1234** [comment]
I am going to close this because no answer has been provided. If you still experience this with the latest Gson version, feel free to comment here again with more details.
