### ISSUE TITLE
Can someone publish the old versions of google-gson to central?

### ISSUE THREAD

**Issue by zymzxq** [google/gson#1022]
My company is still using google-gson 1.3. We used to get them from googlecode's maven repo. But now the repo is gone. We can try to upgrade to newer version. But considering the number of projects that depends on it, it will be a lot of work. It would be nice if someone can release it to maven central or jcenter.

Cheers,
Chandler

**Comment by inder123** [comment]
Can you share some steps on how to publish an old version, and I can try...

**Comment by eamonnmcmanus** [comment]
I don't think it is relevant anymore. Maven Central has versions of Gson going back over 10 years. It happens not to have 1.3, but since that release was in 2009 I think we can consider that that is not a problem.
