### ISSUE TITLE
When is the next release /snapshot version being planned ?

### ISSUE THREAD

**Issue by anirudhramanan** [google/gson#1030]
We did some benchmarking on the data sets, and have noticed around 25 % gain with the changes that went in #1015 

<img width="404" alt="screen shot 2017-03-04 at 1 05 09 am" src="https://cloud.githubusercontent.com/assets/16556984/23566545/51d6d4e2-0078-11e7-924a-11e518888b51.png">

**Comment by JakeWharton** [comment]
We don't really plan releases. Ideally Gson development would slowly come to a stop and it would just stay stable.

That said, there's some fixes on master that could go into a 2.8.1 in the coming weeks: https://github.com/google/gson/compare/gson-parent-2.8.0...master

**Comment by anirudhramanan** [comment]
Ok. Thanks!

**Comment by inder123** [comment]
Nice gains. Let's plan a cut @JakeWharton  @swankjesse in the coming weeks.

**Comment by yasirmhd** [comment]
@swankjesse , @inder123  : any updates on the next release?

**Comment by inder123** [comment]
@swankjesse @JakeWharton  Let's do a release now. I will go ahead and do the needful.

**Comment by yasirmhd** [comment]
@inder123 : gentle reminder for this. Please do let us know if we can be of any help with this.

**Comment by hzsweers** [comment]
For anyone interested, I saw similar reading speed improvements - https://github.com/hzsweers/json-serialization-benchmarking/pull/1

**Comment by inder123** [comment]
@hzsweers  Thanks for the benchmarks links. Great to see a real performance improvement. Keep such suggestions coming.
