### ISSUE TITLE
Fluent interface for the `add*` methods

### ISSUE THREAD

**Issue by lyubomyr-shaydariv** [google/gson#1031]
Not sure if it was asked before, but would it be possible to let the `add*` method family work in fluent interface style? Say, the following JSON

```json
{"key":"whatever","value":["foo","bar"]}
```

can be easily built as a `JsonObject` with

```java
final JsonObject jsonObject = new JsonObject();
jsonObject.addProperty("key", "whatever");
final JsonArray jsonArray = new JsonArray();
jsonArray.add("foo");
jsonArray.add("bar");
jsonObject.add("value", jsonArray);
```

However, if the `add*` methods family would be non-`void` and return their respective instances, it could be done with:

```java
final JsonElement root = new JsonObject()
	.addProperty("key", "whatever")
	.addProperty("value", new JsonArray()
		.add("foo")
		.add("bar")
	);
```

As the pros I can see eliminating redundant variables; "tree-shaped" code; should not break if the `add*` methods are used without any "hacks". As the cons: probably would break if someone analyzes the return type for the `add*` methods via reflection or byte-code processing. I believe you also had such a scenario in mind before, but I'm wondering: what would you say for pros and cons? Thanks.

**Comment by JakeWharton** [comment]
This would be a great change but it's backward incompatible and we have no plans to ever do a Gson 3.0.

**Comment by lyubomyr-shaydariv** [comment]
@JakeWharton thanks for the reply. I have a few more questions: could you please clarify more on the backwards compatibility? (I seem to have some misunderstanding here) And, would adding a "satellite" `addFluently*` (or whatever it could be called) methods family be considered some kind of code bloat and something that should never be a part of Gson? Thanks.

**Comment by JakeWharton** [comment]
Yep. We could add new methods but I'm not sure that we should because it
adds API surface for very little benefit.

**Comment by lyubomyr-shaydariv** [comment]
@JakeWharton Ok, got it, so the issue can be closed. Thanks for your time.
