### ISSUE TITLE
Github has this repository marked as HTML in search results

### ISSUE THREAD

**Issue by morungos** [google/gson#1036]
Just a tiny meta-issue, I was doing some Github API tests and found that this repository is tagged as language `HTML`, which doesn't seem right. It might be worth amending that, not that it is especially visible, except to search results.

**Comment by JakeWharton** [comment]
We don't really control this. It's based on the contents of the repo.

**Comment by morungos** [comment]
Hmm, you're right, although there are overrides: https://github.com/github/linguist#overrides

**Comment by lyubomyr-shaydariv** [comment]
This issue has a duplicate #1348 and an attempt to fix in #1349.
