### ISSUE TITLE
About JsonReader 's skipValue() API:

### ISSUE THREAD

**Issue by fredwang01** [google/gson#1048]
Here is my case, i write a jar using at client to communicate with server, the protocol data is serialized/unserialized by GSON, most protocol elements are resolved in my jar. 
but the 3rd party using my jar have the need to add an element in the protocol whose value is opaque to my jar. i.e. the caller of my jar is responsible for convert the opaque value to java object.

I look through `JsonReader` class and found that the API `public void skipValue() throws IOException`  is not suitable. what i need looks like `public byte[] skipAndGetValue()`.

**Comment by JakeWharton** [comment]
So you want the key's value—regardless of what it is (string, number, object, or array)—as a JSON string?

**Comment by fredwang01** [comment]
yes,  the API return the key's value, moreover, the type of the return value is raw `byte[]`.

**Comment by JakeWharton** [comment]
JSON is text based so it'd return String if we were to do this, which seems
unlikely. Why don't you embed the nested JSON inside of a String value?
Then the normal behavior of returning a String can work.

**Comment by Marcono1234** [comment]
You could probably also parse it as `JsonElement` and then let the third party JAR parse that `JsonElement`. If it is not possible to adjust the third party JAR, then you could convert the `JsonElement` to JSON again first. Not very efficient, but it would work.
Though not sure if this is still relevant given that this question was asked 5 years ago.
