### ISSUE TITLE
Why Gson fromJson get List is null ?

### ISSUE THREAD

**Issue by letie** [google/gson#1057]
Hi ,guys
**1. Json String is like this:**
{
    "mac":"56:78:90:12:34:56",
    "pin":"[
        {\"pin\":\"0\",\"status\":\"0\"},    
        {\"pin\":\"1\",\"status\":\"0\"},
        {\"pin\":\"2\",\"status\":\"1\"},
        {\"pin\":\"3\",\"status\":\"1\"},
        {\"pin\":\"4\",\"status\":\"0\"},
        {\"pin\":\"5\",\"status\":\"0\"},
        {\"pin\":\"6\",\"status\":\"0\"},
        {\"pin\":\"7\",\"status\":\"0\"},
        {\"pin\":\"8\",\"status\":\"0\"},
        {\"pin\":\"9\",\"status\":\"0\"},
        {\"pin\":\"10\",\"status\":\"0\"},
        {\"pin\":\"11\",\"status\":\"0\"},
        {\"pin\":\"12\",\"status\":\"0\"}
    ]
"} 

**2. Class is :**

import java.util.List;

public class ESP8266 {

	public String mac;
	public List<pin> pins;
	
	public class pin {
		int pin;
		int status;
		
		public int getPin() {
			return pin;
		}
		public void setPin(int pin) {
			this.pin = pin;
		}
		public int getStatus() {
			return status;
		}
		public void setStatus(int status) {
			this.status = status;
		}
	}

	public String getMac() {
		return mac;
	}

	public void setMac(String mac) {
		this.mac = mac;
	}

	public List<pin> getPins() {
		return pins;
	}

	public void setPins(List<pin> pins) {
		this.pins = pins;
	}

}

**3. Gson vesion is 2.8.0 Use like this :**

Gson gson = new Gson();
ESP8266 esp = gson.fromJson(data,ESP8266.class);
System.out.println("json:"+esp.pins);                        //out   json:null

Why esp.mac is ok , just the list esp.pins is null ?
Is anybody help me , thanks very much!

**Comment by gajeralalji** [comment]
- Your  json structure has problem.  In your structure you have an array of  pin as 
`"pin":"[]"`
Instead it should be `"pin" :  []`

- Your POJO class has this property : `public List<pin> pins;`
you have to initialize that list, change it to:  `public List<pin> pins = new ArrayList<pin>();`

- Please use stackoverflow for this kind of issues.

**Comment by letie** [comment]
**Hi , gajeralalji .
Thank you !**
My json String is ESP8266(nodeMCU) lua created:
    the lua code is :
    _json={}
    pins="["
    for pin=0,12,1 do
        pins=pins..'{"pin":"'..pin..'","status":"'..gpio.read(pin)..'"},'
    end
    
    pins=string.sub(pins,1,string.len(pins)-1).."]"
    json.mac=wifi.sta.getmac()
    json.pin=pins
  
    ok,data = pcall(cjson.encode, json)
    print(data)_

I can't change it !
I changed the pojo just you say

it  result :json []

I think the error is json type.

**Comment by letie** [comment]
it's running
one place changed the json string name must be same as class,like:public List<pin> `pins` = new ArrayList<pin>();

thank you !

**Comment by letie** [comment]
Yes , i get it.
thank you !

At 2017-03-28 17:57:44, "Lalji Gajera" <notifications@github.com> wrote:


Your json structure has problem. In your structure you have an array of pin as
"pin":"[]"
Instead it should be "pin" : []

Your POJO class has this property : public List<pin> pins;
you have to initialize that list, change it to: public List<pin> pins = new ArrayList<pin>();

Please use stackoverflow for this kind of issues.
