### ISSUE TITLE
Individual Chinese garbled, use the same data.

### ISSUE THREAD

**Issue by liuqingdada** [google/gson#1062]
![qq 20170411093553](https://cloud.githubusercontent.com/assets/15871280/24889134/e3d46fb8-1e9a-11e7-857e-a46f1b8971e1.png)

**Comment by liuqingdada** [comment]
private static final String PATTERN = "yyyy-MM-dd HH:mm:ss";
    private static final Gson gson = new GsonBuilder().setDateFormat(PATTERN)
                                                      .disableHtmlEscaping()
                                                      .create();

    // 对象转json
    public static String toJson(Object src) {
        return gson.toJson(src);
    }

use toJson method , appear this kind of circumstance

**Comment by inder123** [comment]
Please provide a JUnit test that reproduces this problem.

**Comment by Marcono1234** [comment]
No unit test was provided and this was reported 5 years ago, so this is probably no longer relevant.
