### ISSUE TITLE
JsonAdapterAnnotationTypeAdapterFactory exception when wrong type is used for @JsonAdapter could be more helpful

### ISSUE THREAD

**Issue by kevinmost** [google/gson#1067]
The exception thrown [here](https://github.com/google/gson/blob/master/gson/src/main/java/com/google/gson/internal/bind/JsonAdapterAnnotationTypeAdapterFactory.java#L71) when you pass an invalid type to `@JsonAdapter` doesn't tell you what the invalid type was that was registered. It might be nice if it also included `instance.getClass().getName()` in the exception message.

Can submit a PR if this is something of interest.

**Comment by kevinmost** [comment]
Might also be nice to include the `type` that was targeted by the `@JsonAdapter` annotation? Having both of these pieces of info in the exception message would make it very easy to track down where the error is.

**Comment by inder123** [comment]
Good suggestion. Fixed in https://github.com/google/gson/pull/1068

**Comment by kevinmost** [comment]
Great, thanks for the quick fix!
