### ISSUE TITLE
Gson keep parse my Double value to Long value

### ISSUE THREAD

**Issue by seatkgame89** [google/gson#1078]
Hi GSON team,

I used GSON 2.8.0 and today i faced a problem when trying to parse a JSON String into Map<String, Object>. GSON keep parse my Double value into Long value and i don't know why.

My json to test
`String testJson = "{\"dropLatitude\":10.801679,\"dropLongitude\":-106.5986286}";`

My parsing code:
```
        GsonBuilder gsonBuilder = new GsonBuilder();
        gsonBuilder.registerTypeAdapter(new TypeToken<Map<String, Object>>() {
        }.getType(), new GsonMapDeserializer());

        son = gsonBuilder.create();

        Type type = new TypeToken<Map<String, Object>>() {
        }.getType();

        Map<String, Object> myMap = son.fromJson(testJson, type);
        Console.gI().log("Test json " + testJson + " parse " + myMap.size());
        for (Map.Entry<String, Object> entry : myMap.entrySet()) {
            String key = entry.getKey();
            Object value = entry.getValue();
            String valueString = value.toString();

            System.out.println("" + key + "(" + key.getClass() + ")" + "=>" + valueString + "(" + value.getClass() + ")");
        }
```

And the result logs:
```
dropLatitude(class java.lang.String)=>10.801679(class java.lang.Double) 
dropLongitude(class java.lang.String)=>-106(class java.lang.Long)
```

But when i try to parse like this, the value return right
`String testJson = "{\"dropLatitude\":10.801679,\"dropLongitude\":106.5986286}";`

```
dropLatitude(class java.lang.String)=>10.801679(class java.lang.Double)
dropLongitude(class java.lang.String)=>106.5986286(class java.lang.Double)
```

I don't know if this is a bug. When i try to parse a Double value that < 0, GSON parse wrong.

**Comment by seatkgame89** [comment]
Can anyone support me please? Point me if i do something wrong, thank you very much :)

**Comment by inder123** [comment]
Ask this question on Stackoverflow...

**Comment by inder123** [comment]
Map of String,Object is not a very smart idea.
Use, String,Double?
