### ISSUE TITLE
how should i convert a map to json String with gson

### ISSUE THREAD

**Issue by wykCN** [google/gson#1080]
My code likes:
```

    @Test
    public void testGsonTransferMap(){
        HashMap<String, Object> map = new HashMap<String, Object>() {{
            put("Request", new HashMap<String ,Object>(){{
                put("Data",new HashMap<String,Object>(){{
                    put("NWExID", "7019");
                    put("OrgOrderNo", "123");
                    put("OrgTransDate", "20170518");
                }});
            }});
        }};
        Gson gson = new Gson();
        Type gsonType = new TypeToken<HashMap<String ,Object>>(){}.getType();
        String gsonString = gson.toJson(map,gsonType);
        System.out.println(gsonString);
    } 

```

and the output is : "{}"
so,what's wrong with my code , how should i do.

**Comment by NightlyNexus** [comment]
You are trying to serialize an anonymous inner class. Don't.

**Comment by henrik242** [comment]
All other json implementations I can find seems to handle this well.  `new Gson().toJson()` returns null when I give it an one-liner map:

    Map map = new HashMap() {{ put("hei", "sann"); }};
    new Gson().toJson(map);  // returns null!

Other implementations I can find works as expected:

    new JSONObject(map).toString();             // returns {"hei":"sann"}
    JsonOutput.toJson(map);                     // returns {"hei":"sann"}
    new ObjectMapper().writeValueAsString(map); // returns {"hei":"sann"}

It works if I wrap the map:

    new Gson().toJson(new HashMap(map));  // returns {"hei":"sann"}

A regular map works too:

    map = new HashMap();
    map.put("hei", "sann");
    new Gson().toJson(map);  // returns {"hei":"sann"}

Is this an expected Gson feature, @NightlyNexus ?

I've created a test project at https://github.com/henrik242/map2json

**Comment by JakeWharton** [comment]
Yes. This is working as intended.

**Comment by ebuildy** [comment]
what about to throw exception if anonymous inner class? (instead of returning just ``"null"``)

**Comment by fpemud** [comment]
Running @wykCN's code with gson-2.8.5.jar (under openjdk-1.8) still returns "{}".
I thinkg @NightlyNexus's answer is irresponsible, using anonymous inner class is convinent and elegant, why gson doesn't support it?

**Comment by lovelock** [comment]
> Running @wykCN's code with gson-2.8.5.jar (under openjdk-1.8) still returns "{}".
> Using anonymous inner class is convinent and elegant, why gson doesn't support it?

In my case it still returns null with version 2.8.6
