### ISSUE TITLE
exclude NULL from JsonArray while de-serializing json

### ISSUE THREAD

**Issue by harsh-mittal** [google/gson#1081]
I receive an invalid json (extra comma in the end of the list) in request body, which is being successfully deserialized by GSON library. On inspection I see that GSON is inserting a NULL object in the end.

    {
	    "content": "Test 2",
	    "timestamp": 1494311947530,
	    "entities": [
		    {"name": "entity1"},
		    {"name": "entity2"},
		    {"name": "entity3"},
		    {"name": "entity4"},
		    {"name": "entity5"},
	    ]
    }

Is there a way by which I can either instruct GSON not to accept invalid json or remove NULL objects from JsonArray.

I have tried registering type adapter for Set.class but I can't proceed further with this solution as it is not possible to get `Type` of the parameterized object.

    public class RemoveNullCollectionSerializer<T> implements JsonDeserializer<Set<T>> {
        @Override
        public Set<T> deserialize(JsonElement jsonElement, Type type, JsonDeserializationContext context) throws JsonParseException {
            JsonArray elements = jsonElement.getAsJsonArray();

            Set<T> result = new HashSet();
            for (JsonElement element : elements) {
                if (element.isJsonNull()) continue;

                T value = (T) context.deserialize(element, Object.class);
                result.add(value);
            }
            return result;
        }
    }

**Comment by kelvinsleonardo** [comment]
Is there any solution to solve this problem?

**Comment by calvin101** [comment]
check out [this](https://stackoverflow.com/a/44066592/2225648) answer by @lyubomyr-shaydariv
