### ISSUE TITLE
kotlin's default value don't work 

### ISSUE THREAD

**Issue by shibenli** [google/gson#1083]
when i deserialize json without the “age”， it give “0” not the default value("18")
![qq 20170523102034](https://cloud.githubusercontent.com/assets/7353956/26335936/d8923d88-3fa1-11e7-80ce-13239f244326.png)

**Comment by JakeWharton** [comment]
This is also true in Java. You need a zero-arg constructor for it to work. Add default values to all properties and add `@JvmOverloads` to the constructor

**Comment by JakeWharton** [comment]
Or write a reflection-based type adapter using kotlin-reflect. You can copy the Moshi one for inspiration.

**Comment by shibenli** [comment]
Thanks，Add default values to all properties，it work.
