### ISSUE TITLE
Convert a map initialized by inner class to JSON is null?

### ISSUE THREAD

**Issue by xho22** [google/gson#1086]
Map<String, Integer> overviewData1 = new ConcurrentHashMap<String, Integer>() {
            {
                put("1", 44);
                put("2", 44);
            }
        };
        Map<String, Integer> overviewData2 = new ConcurrentHashMap<>();
        overviewData2.put("1", 44);
        overviewData2.put("2", 44);

        System.out.println(GSON.toJson(overviewData1)); // output null
        System.out.println(GSON.toJson(overviewData2)); // correct

The Fastjson in this place is all right.

**Comment by JakeWharton** [comment]
Gson doesn't not serialize anonymous classes as it has no way to deserialize them.
