### ISSUE TITLE
The  default value don't work!

### ISSUE THREAD

**Issue by iQuick** [google/gson#1097]
when i deserialize json without the “code”， it give “0” not the default value("1")
![](http://ww1.sinaimg.cn/mw690/874a93b1gy1fgblrny7ioj20nt0cxjs0.jpg)

**Comment by Marcono1234** [comment]
In general please include code snippets as text and not as screenshot. The reason for this issue might be that this a non-`static` inner class and therefore Gson cannot call the no-args constructor, see also [`GsonBuilder.disableJdkUnsafe()`](https://javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/GsonBuilder.html#disableJdkUnsafe()).
