### ISSUE TITLE
gson-extras is not available as a Maven artifact

### ISSUE THREAD

**Issue by nivs** [google/gson#1104]
`gson-extras` is not distributed as part of the main artifact, and there is no independent artifact for it.
This leads to either including the source code, or relying on [3rd party artifacts](https://mvnrepository.com/artifact/org.danilopianini/gson-extras) (outdated).

**Comment by inder123** [comment]
That is by design. We have no intention of maintaining backward compatibility on extras. You should include source-code.

**Comment by nivs** [comment]
It seems there is now a `gson-extras` artifact available. Is it an official artifact? Was the decision mentioned in @inder123's comment changed? 

https://mvnrepository.com/artifact/com.google.code.gson/gson-extras/2.8.5

**Comment by euyuil** [comment]
The link: https://mvnrepository.com/artifact/com.google.code.gson/gson-extras/2.8.5

It's not on Maven Central. The page says:

```
Note: this artifact it located at CronApp repository (https://artifactory.cronapp.io/public-release/)
```

**Comment by DanySK** [comment]
I am currently maintaining a build of gson-extras and shipping it to Central.
https://search.maven.org/artifact/org.danilopianini/gson-extras/
