### ISSUE TITLE
Unable to deserialize a map of generic objects

### ISSUE THREAD

**Issue by lauradP** [google/gson#1106]
Hi, I'm trying to deserialize the following json map:
```
{
   "result":true,
   "duration":"3603.312",
   "output-json":"smb://usr:pwd@172.17.0.8/secured/file.json",
   "success":true,
   "isValid":"true",
   "output-xml":"smb://usr:pwd@172.17.0.8/secured/file.xml"
}
```
but I get the following result:

- result => java.lang.Object@202d8fd4;
- duration => java.lang.Object@241d929c;
- output-json => java.lang.Object@3e16d488;
- success => java.lang.Object@5f916590;
- isValid => java.lang.Object@138e0299;
- output-xml => java.lang.Object@5bcfeb06

I use the following code to deserialize maps:
```
public Map<String, Object> deserializeMapOfObj(String jsonString) {
		Gson gson = new Gson();
		Map<String, Object> result = gson.fromJson(jsonString, new TypeToken<Map<String, Object>>() {}.getType());
		return result;
	}
```

Is there any error? Can you help me deserializing this map?

Thanks, 
Laura

**Comment by NightlyNexus** [comment]
using your code above:
```java
String json = "{\n"
    + "   \"result\":true,\n"
    + "   \"duration\":\"3603.312\",\n"
    + "   \"output-json\":\"smb://usr:pwd@172.17.0.8/secured/file.json\",\n"
    + "   \"success\":true,\n"
    + "   \"isValid\":\"true\",\n"
    + "   \"output-xml\":\"smb://usr:pwd@172.17.0.8/secured/file.xml\"\n"
    + "}";
System.out.println(deserializeMapOfObj(json));
```
prints
`{result=true, duration=3603.312, output-json=smb://usr:pwd@172.17.0.8/secured/file.json, success=true, isValid=true, output-xml=smb://usr:pwd@172.17.0.8/secured/file.xml}`

Do you have a reproducible test case to show the problem?
