### ISSUE TITLE
gson bug

### ISSUE THREAD

**Issue by shizhongyu** [google/gson#1108]
![_20170703103603](https://user-images.githubusercontent.com/13025541/27776240-7c1b9338-5fdb-11e7-9dd3-05fa942a4be8.png)

**Comment by JakeWharton** [comment]
This is not enough information to create an actionable report. Please
provide more info.

**Comment by Harlber** [comment]
What he means is that the order of the two member variables has changed(`TotalDist` and`ToatlDistance2D`).

**Comment by JakeWharton** [comment]
That is not what the screenshot shows. It shows a single object with an additional property.

**Comment by Harlber** [comment]
Sorry, it's my fault

**Comment by Marcono1234** [comment]
Closing because no further information was provided by the author.
