### ISSUE TITLE
gson 2.8.1 toJson NullPointerException bug 

### ISSUE THREAD

**Issue by magicbest** [google/gson#1111]
Using gson2.8.1, set "Gson gson = new GsonBuilder().setDateFormat("yyyyMMddHHmmss").create();".
When the object which needs to be serialized into Json has Date type attribute, and the value of that attribute is null, using method "toJson" will throw NullPointerException. gson2.8.0 does not have this problem under same situation.

**Comment by JakeWharton** [comment]
Dupe #1098
