### ISSUE TITLE
  compile 'com.google.code.gson:gson:2.4'，will happen ANR(anroid 4.42,but 7.0 is ok).

### ISSUE THREAD

**Issue by lucklyone** [google/gson#1113]
this issue happened the Android 4.4.2.But the 7.0 is ok.This is the build gradle.
 compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:24.2.1'
    compile 'com.android.support:support-v4:24.2.1'
    compile project(':easeui')
    compile project(':pulltorefresh_library')
    compile files('libs/butterknife-7.0.1.jar')
    compile files('libs/umeng-analytics-v6.0.9.jar')
    compile files('libs/eventbus-3.0.0.jar')
    compile files('libs/alipaySdk-20161222.jar')
    compile files('libs/wechat-sdk-android-with-mta-1.0.2.jar')
    compile 'com.youth.banner:banner:1.4.9'
    compile 'com.android.support:recyclerview-v7:24.2.1'
    compile 'com.meiqia:meiqiasdk:3.4.0@aar'
    compile 'com.squareup.okhttp3:okhttp:3.5.0'
    compile 'com.android.support:multidex:1.0.1'
    compile 'com.github.PhilJay:MPAndroidChart:v3.0.2'
    debugCompile 'com.squareup.leakcanary:leakcanary-android:1.3'
    compile 'com.google.code.gson:gson:2.4'

**Comment by JakeWharton** [comment]
It's not clear why you think Gson causes this.

**Comment by lucklyone** [comment]
ok,i have handler it.thank you.
