### ISSUE TITLE
JsonObject's members should be ConcurrentHashMap

### ISSUE THREAD

**Issue by arass** [google/gson#1117]
Otherwise simply cycling through the elements causes a concurrent exceptions.

**Comment by Marcono1234** [comment]
> Otherwise simply cycling through the elements causes a concurrent exceptions.

This sounds more like you are also modifying the object at the same time you are iterating its members.

In case this is still relevant could you please try this with the latest Gson version and provide a small self contained example showing where the exception occurs for you?

**Comment by Marcono1234** [comment]
I am going to close this because no answer has been provided. If you still experience this with the latest Gson version, feel free to comment here again with more details.
