### ISSUE TITLE
Export extra folder to maven central

### ISSUE THREAD

**Issue by cheninator** [google/gson#1123]
Currently, only https://github.com/google/gson/tree/master/gson is available on maven central and it would be nice to have https://github.com/google/gson/tree/master/extras also available. Thus, we can reuse the type adapters for deserializing nested interfaces

**Comment by JakeWharton** [comment]
The classes in there are not versioned nor have API stability guarantees.

**Comment by DanySK** [comment]
If you need them, you can use this package: https://search.maven.org/artifact/org.danilopianini/gson-extras/

**Comment by TWiStErRob** [comment]
See also https://github.com/google/gson/issues/1104

Is the fact that there are no compat guarantees a blocker for publishing an artifact? Version 0.x would be pretty clear that it's not stable. + A documentation in Readme.md that it exists, but use at your own.

**Comment by DanySK** [comment]
@TWiStErRob, I know it's not the same as having google publishing the package themselves, but I am keeping the artifact mentioned before aligned with the mainline. I also intend (and help is welcome) to automate the pull / release.

**Comment by eamonnmcmanus** [comment]
We don't have plans to publish new Gson-related artifacts to Maven Central.
