### ISSUE TITLE
JsonWriter don't work correctly with float

### ISSUE THREAD

**Issue by votoanthuan** [google/gson#1127]
float x = 3.723379;
JsonWriter writer = ...
writer.value(x); //is will call value(double value), so it will wrong
result is 3.723378896713257

Please add new function for float.
Thank you.

**Comment by Harlber** [comment]
see `ObjectTypeAdapter`  

```java

@Override public Object read(JsonReader in) throws IOException {
    JsonToken token = in.peek();
    switch (token) {
    case BEGIN_ARRAY:
      List<Object> list = new ArrayList<Object>();
      in.beginArray();
      while (in.hasNext()) {
        list.add(read(in));
      }
      in.endArray();
      return list;

    case BEGIN_OBJECT:
      Map<String, Object> map = new LinkedTreeMap<String, Object>();
      in.beginObject();
      while (in.hasNext()) {
        map.put(in.nextName(), read(in));
      }
      in.endObject();
      return map;

    case STRING:
      return in.nextString();

    case NUMBER:
      return in.nextDouble();

    case BOOLEAN:
      return in.nextBoolean();

    case NULL:
      in.nextNull();
      return null;

    default:
      throw new IllegalStateException();
    }
  }
```
NUMBER defaults to double

Solutions:
 - https://stackoverflow.com/questions/36508323/how-can-i-prevent-gson-from-converting-integers-to-doubles/36529534#36529534
 - float ->String ->float

**Comment by votoanthuan** [comment]
@Harlber this is a bug, and i report for gson to fix it. The simple way to avoid this bug is convert float to Float, like this:
float x = 3.723379;
JsonWriter writer = ...
writer.value(Float.valueOf(x)); //The simple way to avoid this bug but it is not an effective way

**Comment by Harlber** [comment]
Similar issue see #1084
