### ISSUE TITLE
Stream Base64-String to JsonWriter

### ISSUE THREAD

**Issue by fab1an** [google/gson#1129]
When using a `JsonWriter`, is it possible to directly output a base64 String loaded from the file-system without having to construct the entire String in memory first?

**Comment by inder123** [comment]
Sure. use JsonWriter(Writer) constructor?

**Comment by fab1an** [comment]
No, I mean I'm somewhere deep in a hierarchy using a `JsonWriter` to construct a stream.

Then I want to add a `String` with using `.value(str)` but rather stream it directly into the `JsonWriter`.
