### ISSUE TITLE
Stackoverflow with toJson when pojo annotated with @Entity

### ISSUE THREAD

**Issue by tnguyen-lh** [google/gson#1131]
new Gson().toJson(object) has error Stackoverflow with any pojo annotated with @entity javax.persistence. It is working fine with Jackson Object mapper.

import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Getter;
import lombok.Setter;

@Entity
@Table(name="customer_account")
public class CustomerAccount implements BaseEntity{ 

	@Getter
	@Id
	private Long id;
	@Getter
	@Setter
	private String name;
	@Getter
	@Setter
	private String description;
	
}

**Comment by aCoder2013** [comment]
you'd better provide a unit test which can reproduces this problem.

**Comment by tnguyen-lh** [comment]
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Getter;
import lombok.Setter;

@Entity
@Table(name="customer_account")
public class CustomerAccount{ 

	@Getter
	@Id
	private Long id;
	@Getter
	@Setter
	private String name;
	@Getter
	@Setter
	private String description;
	
}

public class TestGson {

	@Test
	public void test() {
		Gson gson = (new GsonBuilder()).create();
		
		CustomerAccount user = new CustomerAccount();
		user.setName("name");
		user.setDescription("description");
		
		String userjson = gson.toJson(user);
		
		user = gson.fromJson(userjson, CustomerAccount.class);
		
	}

}

**Comment by inder123** [comment]
Can you revise your test to write an assertion that will fail? 
As far as I can see, Gson will have no problem serializing/deserializing CustomerAccount claass with fields id, name and description.

**Comment by Marcono1234** [comment]
Probably no longer relevant given that this was created 5 years ago.
