### ISSUE TITLE
Serializes nulls by default

### ISSUE THREAD

**Issue by alexfu** [google/gson#1133]
I came across something recently that kind of took me by surprise, which is that Gson will serialize nulls by default if you decide to serialize using `TypeAdapter`s directly. I went through the `TypeAdapter` documentation to make sure I didn't miss anything and it didn't seem like this would be the default behavior. 

I have the following test as an example of this behavior:
```java
public class GsonNullTest {
  @Test
  public void doesNotSerializeNulls() {
    Gson gson = new Gson();
    Circle circle = new Circle(12, null);

    JsonElement result1 = gson.toJsonTree(circle);
    JsonElement result2 = gson.getAdapter(new TypeToken<Circle>(){}).toJsonTree(circle);

    assertFalse(result1.getAsJsonObject().has("color")); // Color field doesn't exist, pass
    assertFalse(result2.getAsJsonObject().has("color")); // Color field exists and is set to null, fail
  }

  public static class Circle {
    public Integer radius;
    public String color;

    public Circle(Integer radius, String color) {
      this.radius = radius;
      this.color = color;
    }
  }
}
```

Is this the expected behavior? If so, I think the documentation could be a little more clear on this.

**Comment by JakeWharton** [comment]
TypeAdapter instances know nothing about your configuration on the Gson object. If you want your settings to be reflected use the `newJsonWriter` to create a `JsonWriter` with the appropriate configuration that matches the `Gson` instance.

**Comment by alexfu** [comment]
Gotcha. The documentation made it seemed like dropping null fields would happen automatically (unless i'm reading it wrong).

> If your Gson instance has been configured to GsonBuilder.serializeNulls(), these nulls will be written to the final document. Otherwise the value (and the corresponding name when writing to a JSON object) will be omitted automatically. In either case your type adapter must handle null

**Comment by JakeWharton** [comment]
That's for the toJson and fromJson methods which use newJsonWriter and
newJsonReader internally to construct JsonWriter and JsonReader instances
which are pre-configured using the defaults form the Gson instance.

**Comment by Marcono1234** [comment]
Going to close this since this has been answered above.
