### ISSUE TITLE
GSON deserialize value of JSON property to Null

### ISSUE THREAD

**Issue by siddheshswnt** [google/gson#1144]
I have json String userJson = {"id" : "2221", "name" : "xyz" }

I am using following code to deserialize it to User class :

```
Gson gson = new Gson();
User user  = gson.fromJson(userJson, User.class}
```

And I am getting User class with id : null and name : null.

Can someone tell me where I am making mistake ?

**Comment by JakeWharton** [comment]
Works fine for me:
```java
public class Blah {
  public static void main(String[] args) {
    String json = "{\"id\" : \"2221\", \"name\" : \"xyz\" }";
    User user = new Gson().fromJson(json, User.class);
    System.out.println(user.id);
    System.out.println(user.name);
  }
}

class User {
  public final String id;
  public final String name;

  User(String id, String name) {
    this.id = id;
    this.name = name;
  }
}
```
```
2221
xyz
```
If you think you have a bug please provide a failing test case like above. Otherwise for usage questions StackOverflow and the 'gson' tag is your best bet.
