### ISSUE TITLE
2.8.2 release?

### ISSUE THREAD

**Issue by eamonnmcmanus** [google/gson#1153]
Any chance of a 2.8.2 release? We're running into #1128, which was fixed by https://github.com/google/gson/commit/03a72e752ef68269990f984c9fd613cfd59224bc.

**Comment by inder123** [comment]
Let's do it this week. Thanks.

**Comment by naturalwarren** [comment]
Maybe we cut this as 2.9 if #1142 makes it into the release?

**Comment by inder123** [comment]
Done http://repo1.maven.org/maven2/com/google/code/gson/gson/2.8.2/
