### ISSUE TITLE
mismatch size of array response if we have comma after last item in array

### ISSUE THREAD

**Issue by vysokoprevoskhoditelstvo** [google/gson#1154]
example json response: 

> {
>   "items": [
>     {
>       "id": 1
>     },
>     {
>       "id": 2
>     }**,**
>   ]
> }
> 

items is array. so if we have comma after last item in array, we have issue here:
size of ArrayList after json parsing via Gson library is 3, but in fact item at index 2 is null.
is it correct? 
if we check our example  via online validator(http://json.parser.online.fr/ , https://jsonlint.com/), we will see that our json is incorrect.

May be it will be better to throw JsonSyntaxException

version gson 2.8.1

**Comment by JakeWharton** [comment]
This is the behavior when in lenient mode, which is tragically the Gson default. You can get strict behavior by using `gson.typeAdapter(typeToken).fromJson(gson.newJsonReader(json))` instead of `gson.fromJson(json, typeToken)`.
