### ISSUE TITLE
Gson Proguard Config 

### ISSUE THREAD

**Issue by naturalwarren** [google/gson#1155]
The sample proguard config specifies to keep `sun.misc`. This seems really strange since that package ships with the runtime. 

https://github.com/google/gson/blob/d9cc7bc60b492664fe9f328d1bab9f9ae873f4d4/examples/android-proguard-example/proguard.cfg#L10

Should we update the proguard config to use don't warn? This seems to the precedent:

RxJava: https://github.com/ReactiveX/RxJava/issues/1415
PlayServices: https://github.com/krschultz/android-proguard-snippets/issues/116

**Comment by JakeWharton** [comment]
The 'android-proguard-snippets' repo is a tragedy of the commons and should never be used to justify correct rules.

But yeah, this should be `-dontwarn`. Want to PR?

**Comment by naturalwarren** [comment]
Will do, thanks Jake.
