### ISSUE TITLE
I want to parse array but the value in json string is ""

### ISSUE THREAD

**Issue by Joy-Whale** [google/gson#1164]
json:
```
{
  "user":[
    {
      "name": "a",
      "interest": [
        "game",
        "music"
      ]
    },
    {
      "name": "b",
      "interest": ""
    }
  ]
}
```

bean:
```
class User{
  String name;
  List<String> interest;
}
```

I want parse the json String to User list, but the 'interest' value of 'b' is "", so the Gson will not work, how should I do to parse the empty string value as a empty list

**Comment by JakeWharton** [comment]
Please ask general usage questions on StackOverflow with the 'gson' tag. This issue tracker is for bug reports and feature requests only.
