### ISSUE TITLE
Invalid LOC header (bad signature)

### ISSUE THREAD

**Issue by pushbit** [google/gson#1165]
I'm using Eclipse Neon.3 and the m2e plugin.  When depending on Gson 2.8.2, the `Gson` class cannot be resolved.  If I try to open it in Eclipse (Maven Dependencies > gson-2.8.2.jar > com.google.gson > Gson.class), I get an error, `java.util.zip.ZipException: invalid LOC header (bad signature)`.  Other files, like JsonArray.class, open fine.  Depending on 2.8.1 resolves this.  Just maybe something to watch out for in the next release.

**Comment by pushbit** [comment]
Seems I just had a corrupt download.  Deleting my `.m2/repository/com/google/code/gson/gson/2.8.2` directory and updating the Maven project resolved it.

**Comment by aleksandra49** [comment]
Hi, i have the same problem, but i dont know how to delete that .m2 file and dont know how to find it. can u help me?
