### ISSUE TITLE
User Guide: primitive missing entries in JSON 

### ISSUE THREAD

**Issue by elharo** [google/gson#1166]
The user guide states, "While deserializing, a missing entry in JSON results in setting the corresponding field in the object to null."

This is incomplete. What happens when the missing entry in the JSON is a primitive type such as boolean or int that cannot be null?

**Comment by inder123** [comment]
Right, those are set to default values. Feel free to send a PR with edits. Thanks

**Comment by elharo** [comment]
I can send a PR but this issue should be reopened until the PR is committed.
