### ISSUE TITLE
API report for Gson

### ISSUE THREAD

**Issue by lvc** [google/gson#1167]
Hi,

I'd like to share report on API changes and backward binary compatibility for the Gson library with the community: https://abi-laboratory.pro/java/tracker/timeline/gson/

The report is generated by the https://github.com/lvc/japi-tracker tool, which I've created recently. The basic https://github.com/lvc/japi-compliance-checker tool verifies changes in all public API methods and classes according to the article https://wiki.eclipse.org/Evolving_Java-based_APIs_2.

Hope it will be helpful for users and maintainers of the library to be aware of past and future API changes.

Thank you.

![gson-2](https://user-images.githubusercontent.com/1517837/31372734-df0b6ed4-ad9f-11e7-9197-d756235ab961.png)

![gson-1](https://user-images.githubusercontent.com/1517837/31372735-df277a70-ad9f-11e7-80df-3cf484d7bc43.png)

**Comment by inder123** [comment]
Good info. Added it to the README.md
Thanks.
