### ISSUE TITLE
Gson change default Boolean Value to false if the field doesn't exist in json

### ISSUE THREAD

**Issue by farazbern** [google/gson#1168]
I have  model like  this 

  ```
  public class testModel {
    
        public boolean a = true;
        public Test2 test2 = new Test2();
    
        public class Test2 {
            public boolean b = true;
        }
    }
```

and a  json like this

  ```
  {
    "test2":{}
    }

```
when i parse this json with Gson 

```
    testModel testModel = new Gson().fromJson("{ \"test2\":{}}", testModel.class);
        Log.e("test", testModel.a + " " + testModel.test2.b);
      
```
and the log is:
 

`    E/test: true false `

testModel.a is 'true'  but testmodel.test2.b is 'false' 
why Gson changed the default value of b while b is not exist in json?
what is the difference between b and a ?

is it a Gson bug?
i used 2.8.1 version of Gson

**Comment by JakeWharton** [comment]
TestModel has a no-arg constructor while Test2 implicitly has one that
takes an instance of TestModel. Mark Test2 as a static class and it will
work.

**Comment by farazbern** [comment]
@JakeWharton  yes it  solved my problem . thank you for quick answer
