### ISSUE TITLE
Add module-info.java

### ISSUE THREAD

**Issue by hrchu** [google/gson#1172]
So that projects depend on this can be published to a public artifact repository.
Note that this is not breaking backward compatibility. All codes except this file can be still compiled in Java 6.

**Comment by michaelsavich** [comment]
https://github.com/google/gson/pull/1179

![resize](https://user-images.githubusercontent.com/24902181/32078727-00475198-ba76-11e7-83f3-f2af7f3ac496.jpeg)

**Comment by Foorack** [comment]
Any update on this? :confused:

**Comment by Foorack** [comment]
@hrchu The pull request has now been merged. I suggest closing this as done. ✅

**Comment by hrchu** [comment]
@Foorack

**Comment by cjohnstoninv** [comment]
Is there any plans for when this will be released?

**Comment by cjohnstoninv** [comment]
Is there going to be a 2.9 or 3.0 release that has a module-info.class file in it?

**Comment by JakeWharton** [comment]
No, there will probably never be a module-info.class. We can merge an automatic module name.

**Comment by cjohnstoninv** [comment]
Is there something I am missing about modules then? Automatic modules seem like glorified backwards compatibility hacks and maven builds introduce a big fat warning to not publish your module in a public repo if it depends on an automatic module. Unless I am missing something about modules, wouldn't this mean that now project that wants to properly move forward with Java 9+ cannot depend on GSON?
