### ISSUE TITLE
parse error that parse the 0 to 0-E8 

### ISSUE THREAD

**Issue by nb312** [google/gson#1173]
As the title, when I parse the network JSON string to model, the parse error occurs changing 0 to 0-E8.

**Comment by JakeWharton** [comment]
Please provide a failing test case that demonstrates your problem.

**Comment by nb312** [comment]
example as this: 
{"age":0} change to a Java model Person with field age. 
`
public class Person{
private String age;
public void setAge(String age){
this.age=age;
}
public String getAge(){
  return this.age;
}
} 
` 
then the age person.age have became to "0-E8".

**Comment by BrokenDream** [comment]
which version of gson in your case?  i can't see the problem with 2.8.x  @nb312

**Comment by nb312** [comment]
this is should be closed, I found that this error is about the fast JSON. Sorry about this.
