### ISSUE TITLE
parse error

### ISSUE THREAD

**Issue by zhengoogle** [google/gson#1181]
{"mAllOutputFormats":{"mKeys":[32,33,34,35,0,0,0,0,0,0,0],"mSize":4,"mValues":[1,11,21,21,0,0,0,0,0,0,0]},"mConfigurations":[{"mFormat":32,"mHeight":3456,"mInput":false,"mWidth":4608},{"mFormat":33,"mHeight":480,"mInput":false,"mWidth":640},{"mFormat":33,"mHeight":240,"mInput":false,"mWidth":320},{"mFormat":33,"mHeight":720,"mInput":false,"mWidth":1280},{"mFormat":33,"mHeight":1080,"mInput":false,"mWidth":1920},{"mFormat":33,"mHeight":2448,"mInput":false,"mWidth":3264},{"mFormat":33,"mHeight":3456,"mInput":false,"mWidth":3456},{"mFormat":33,"mHeight":3456,"mInput":false,"mWidth":4608},{"mFormat":33,"mHeight":1536,"mInput":false,"mWidth":2048},{"mFormat":33,"mHeight":1952,"mInput":false,"mWidth":2592},{"mFormat":33,"mHeight":1840,"mInput":false,"mWidth":3264},{"mFormat":33,"mHeight":2592,"mInput":false,"mWidth":4608},{"mFormat":34,"mHeight":3456,"mInput":false,"mWidth":4608},{"mFormat":34,"mHeight":2592,"mInput":false,"mWidth":4608},{"mFormat":34,"mHeight":3456,"mInput":false,"mWidth":3456},{"mFormat":34,"mHeight":2448,"mInput":false,"mWidth":3264},{"mFormat":34,"mHeight":1840,"mInput":false,"mWidth":3264},{"mFormat":34,"mHeight":1952,"mInput":false,"mWidth":2592},{"mFormat":34,"mHeight":1536,"mInput":false,"mWidth":2048},{"mFormat":34,"mHeight":1080,"mInput":false,"mWidth":1920},{"mFormat":34,"mHeight":1080,"mInput":false,"mWidth":1440},{"mFormat":34,"mHeight":960,"mInput":false,"mWidth":1280},{"mFormat":34,"mHeight":720,"mInput":false,"mWidth":1280},{"mFormat":34,"mHeight":720,"mInput":false,"mWidth":960},{"mFormat":34,"mHeight":720,"mInput":false,"mWidth":720},{"mFormat":34,"mHeight":414,"mInput":false,"mWidth":736},{"mFormat":34,"mHeight":480,"mInput":false,"mWidth":640},{"mFormat":34,"mHeight":408,"mInput":false,"mWidth":544},{"mFormat":34,"mHeight":400,"mInput":false,"mWidth":400},{"mFormat":34,"mHeight":288,"mInput":false,"mWidth":352},{"mFormat":34,"mHeight":240,"mInput":false,"mWidth":320},{"mFormat":34,"mHeight":144,"mInput":false,"mWidth":208},{"mFormat":34,"mHeight":144,"mInput":false,"mWidth":176},{"mFormat":35,"mHeight":3456,"mInput":false,"mWidth":4608},{"mFormat":35,"mHeight":2592,"mInput":false,"mWidth":4608},{"mFormat":35,"mHeight":3456,"mInput":false,"mWidth":3456},{"mFormat":35,"mHeight":2448,"mInput":false,"mWidth":3264},{"mFormat":35,"mHeight":1840,"mInput":false,"mWidth":3264},{"mFormat":35,"mHeight":1952,"mInput":false,"mWidth":2592},{"mFormat":35,"mHeight":1536,"mInput":false,"mWidth":2048},{"mFormat":35,"mHeight":1080,"mInput":false,"mWidth":1920},{"mFormat":35,"mHeight":1080,"mInput":false,"mWidth":1440},{"mFormat":35,"mHeight":960,"mInput":false,"mWidth":1280},{"mFormat":35,"mHeight":720,"mInput":false,"mWidth":1280},{"mFormat":35,"mHeight":720,"mInput":false,"mWidth":960},{"mFormat":35,"mHeight":720,"mInput":false,"mWidth":720},{"mFormat":35,"mHeight":414,"mInput":false,"mWidth":736},{"mFormat":35,"mHeight":480,"mInput":false,"mWidth":640},{"mFormat":35,"mHeight":408,"mInput":false,"mWidth":544},{"mFormat":35,"mHeight":400,"mInput":false,"mWidth":400},{"mFormat":35,"mHeight":288,"mInput":false,"mWidth":352},{"mFormat":35,"mHeight":240,"mInput":false,"mWidth":320},{"mFormat":35,"mHeight":144,"mInput":false,"mWidth":208},{"mFormat":35,"mHeight":144,"mInput":false,"mWidth":176}],"mDepthConfigurations":[],"mDepthMinFrameDurations":[],"mDepthOutputFormats":{"mKeys":[0,0,0,0,0,0,0,0,0,0,0],"mSize":0,"mValues":[0,0,0,0,0,0,0,0,0,0,0]},"mDepthStallDurations":[],"mHighResOutputFormats":{"mKeys":[0,0,0,0,0,0,0,0,0,0,0],"mSize":0,"mValues":[0,0,0,0,0,0,0,0,0,0,0]},"mHighSpeedVideoConfigurations":[{"mBatchSizeMax":1,"mFpsMax":120,"mFpsMin":30,"mFpsRange":{"mLower":30,"mUpper":120},"mHeight":720,"mSize":{"mHeight":720,"mWidth":1280},"mWidth":1280},{"mBatchSizeMax":1,"mFpsMax":120,"mFpsMin":120,"mFpsRange":{"mLower":120,"mUpper":120},"mHeight":720,"mSize":{"mHeight":720,"mWidth":1280},"mWidth":1280}],"mHighSpeedVideoFpsRangeMap":{"[30, 120]":1,"[120, 120]":1},"mHighSpeedVideoSizeMap":{"1280x720":2},"mInputFormats":{"mKeys":[0,0,0,0,0,0,0,0,0,0,0],"mSize":0,"mValues":[0,0,0,0,0,0,0,0,0,0,0]},"mInputOutputFormatsMap":{"mEntry":[],"mInputCount":0},"mListHighResolution":false,"mMinFrameDurations":[{"mDurationNs":33331760,"mFormat":32,"mHeight":3456,"mWidth":4608},{"mDurationNs":33331760,"mFormat":33,"mHeight":480,"mWidth":640},{"mDurationNs":33331760,"mFormat":33,"mHeight":240,"mWidth":320},{"mDurationNs":33331760,"mFormat":33,"mHeight":720,"mWidth":1280},{"mDurationNs":33331760,"mFormat":33,"mHeight":1080,"mWidth":1920},{"mDurationNs":50000000,"mFormat":33,"mHeight":2448,"mWidth":3264},{"mDurationNs":50000000,"mFormat":33,"mHeight":3456,"mWidth":3456},{"mDurationNs":50000000,"mFormat":33,"mHeight":3456,"mWidth":4608},{"mDurationNs":50000000,"mFormat":33,"mHeight":1536,"mWidth":2048},{"mDurationNs":50000000,"mFormat":33,"mHeight":1952,"mWidth":2592},{"mDurationNs":50000000,"mFormat":33,"mHeight":1840,"mWidth":3264},{"mDurationNs":50000000,"mFormat":33,"mHeight":2592,"mWidth":4608},{"mDurationNs":50000000,"mFormat":34,"mHeight":3456,"mWidth":4608},{"mDurationNs":50000000,"mFormat":34,"mHeight":2592,"mWidth":4608},{"mDurationNs":50000000,"mFormat":34,"mHeight":3456,"mWidth":3456},{"mDurationNs":50000000,"mFormat":34,"mHeight":2448,"mWidth":3264},{"mDurationNs":50000000,"mFormat":34,"mHeight":1840,"mWidth":3264},{"mDurationNs":50000000,"mFormat":34,"mHeight":1952,"mWidth":2592},{"mDurationNs":50000000,"mFormat":34,"mHeight":1536,"mWidth":2048},{"mDurationNs":33331760,"mFormat":34,"mHeight":1080,"mWidth":1920},{"mDurationNs":33331760,"mFormat":34,"mHeight":1080,"mWidth":1440},{"mDurationNs":33331760,"mFormat":34,"mHeight":960,"mWidth":1280},{"mDurationNs":33331760,"mFormat":34,"mHeight":720,"mWidth":1280},{"mDurationNs":33331760,"mFormat":34,"mHeight":720,"mWidth":960},{"mDurationNs":33331760,"mFormat":34,"mHeight":720,"mWidth":720},{"mDurationNs":33331760,"mFormat":34,"mHeight":414,"mWidth":736},{"mDurationNs":33331760,"mFormat":34,"mHeight":480,"mWidth":640},{"mDurationNs":33331760,"mFormat":34,"mHeight":408,"mWidth":544},{"mDurationNs":33331760,"mFormat":34,"mHeight":400,"mWidth":400},{"mDurationNs":33331760,"mFormat":34,"mHeight":288,"mWidth":352},{"mDurationNs":33331760,"mFormat":34,"mHeight":240,"mWidth":320},{"mDurationNs":33331760,"mFormat":34,"mHeight":144,"mWidth":208},{"mDurationNs":33331760,"mFormat":34,"mHeight":144,"mWidth":176},{"mDurationNs":50000000,"mFormat":35,"mHeight":3456,"mWidth":4608},{"mDurationNs":50000000,"mFormat":35,"mHeight":2592,"mWidth":4608},{"mDurationNs":50000000,"mFormat":35,"mHeight":3456,"mWidth":3456},{"mDurationNs":50000000,"mFormat":35,"mHeight":2448,"mWidth":3264},{"mDurationNs":50000000,"mFormat":35,"mHeight":1840,"mWidth":3264},{"mDurationNs":50000000,"mFormat":35,"mHeight":1952,"mWidth":2592},{"mDurationNs":50000000,"mFormat":35,"mHeight":1536,"mWidth":2048},{"mDurationNs":33331760,"mFormat":35,"mHeight":1080,"mWidth":1920},{"mDurationNs":33331760,"mFormat":35,"mHeight":1080,"mWidth":1440},{"mDurationNs":33331760,"mFormat":35,"mHeight":960,"mWidth":1280},{"mDurationNs":33331760,"mFormat":35,"mHeight":720,"mWidth":1280},{"mDurationNs":33331760,"mFormat":35,"mHeight":720,"mWidth":960},{"mDurationNs":33331760,"mFormat":35,"mHeight":720,"mWidth":720},{"mDurationNs":33331760,"mFormat":35,"mHeight":414,"mWidth":736},{"mDurationNs":33331760,"mFormat":35,"mHeight":480,"mWidth":640},{"mDurationNs":33331760,"mFormat":35,"mHeight":408,"mWidth":544},{"mDurationNs":33331760,"mFormat":35,"mHeight":400,"mWidth":400},{"mDurationNs":33331760,"mFormat":35,"mHeight":288,"mWidth":352},{"mDurationNs":33331760,"mFormat":35,"mHeight":240,"mWidth":320},{"mDurationNs":33331760,"mFormat":35,"mHeight":144,"mWidth":208},{"mDurationNs":33331760,"mFormat":35,"mHeight":144,"mWidth":176}],"mOutputFormats":{"mKeys":[32,33,34,35,0,0,0,0,0,0,0],"mSize":4,"mValues":[1,11,21,21,0,0,0,0,0,0,0]},"mStallDurations":[{"mDurationNs":33331760,"mFormat":33,"mHeight":480,"mWidth":640},{"mDurationNs":33331760,"mFormat":33,"mHeight":240,"mWidth":320},{"mDurationNs":33331760,"mFormat":33,"mHeight":720,"mWidth":1280},{"mDurationNs":33331760,"mFormat":33,"mHeight":1080,"mWidth":1920},{"mDurationNs":33331760,"mFormat":33,"mHeight":2448,"mWidth":3264},{"mDurationNs":33331760,"mFormat":33,"mHeight":3456,"mWidth":3456},{"mDurationNs":33331760,"mFormat":33,"mHeight":3456,"mWidth":4608},{"mDurationNs":33331760,"mFormat":33,"mHeight":1536,"mWidth":2048},{"mDurationNs":33331760,"mFormat":33,"mHeight":1952,"mWidth":2592},{"mDurationNs":33331760,"mFormat":33,"mHeight":1840,"mWidth":3264},{"mDurationNs":33331760,"mFormat":33,"mHeight":2592,"mWidth":4608}]}

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 3918 path $.mHighSpeedVideoFpsRangeMap.

**Comment by JakeWharton** [comment]
This is a disagreement between your Java model and the supplied JSON, not a bug in the library.
