### ISSUE TITLE
Problem while parsing List(or array) as String

### ISSUE THREAD

**Issue by kvipul** [google/gson#1188]
I need to parse a list as String form. Why is it giving an exception while parsing a list as a simple string?
While an int or a float variable is easily accessible as String.

**Comment by Marcono1234** [comment]
In case this is still relevant, could you please provide a small self-contained example showing the issue?

**Comment by Marcono1234** [comment]
I am going to close this because no answer has been provided. If you still experience this with the latest Gson version, feel free to comment here again with more details.
