### ISSUE TITLE
com.google.gson.JsonSyntaxException error some devices.

### ISSUE THREAD

**Issue by makarna35** [google/gson#1189]
com.google.gson.JsonSyntaxException error have some devices. Some devices not have this error.

Huawei P10 (HWVTR), 4096MB RAM, Android 7.0

com.google.gson.JsonSyntaxException: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java)
 
  at com.google.gson.Gson.doubleAdapter (Gson.java)
  or                     .checkValidFloatingPoint (Gson.java)
  or                     .longAdapter (Gson.java)
  or                     .atomicLongAdapter (Gson.java)
  or                     .getAdapter (Gson.java)
  or                     .getDelegateAdapter (Gson.java)
  or                     .newJsonReader (Gson.java)
  or                     .fromJson (Gson.java)
  or                     .assertFullConsumption (Gson.java)
 
  at com.google.gson.Gson.doubleAdapter (Gson.java)
  or                     .checkValidFloatingPoint (Gson.java)
  or                     .longAdapter (Gson.java)
  or                     .atomicLongAdapter (Gson.java)
  or                     .getAdapter (Gson.java)
  or                     .getDelegateAdapter (Gson.java)
  or                     .newJsonReader (Gson.java)
  or                     .fromJson (Gson.java)
  or                     .assertFullConsumption (Gson.java)
 
  at com.google.gson.Gson.doubleAdapter (Gson.java)
  or                     .checkValidFloatingPoint (Gson.java)
  or                     .longAdapter (Gson.java)
  or                     .atomicLongAdapter (Gson.java)
  or                     .getAdapter (Gson.java)
  or                     .getDelegateAdapter (Gson.java)
  or                     .newJsonReader (Gson.java)
  or                     .fromJson (Gson.java)
  or                     .assertFullConsumption (Gson.java)
 
  at com.google.gson.Gson.doubleAdapter (Gson.java)
  or                     .checkValidFloatingPoint (Gson.java)
  or                     .longAdapter (Gson.java)
  or                     .atomicLongAdapter (Gson.java)
  or                     .getAdapter (Gson.java)
  or                     .getDelegateAdapter (Gson.java)
  or                     .newJsonReader (Gson.java)
  or                     .fromJson (Gson.java)
  or                     .assertFullConsumption (Gson.java)
 
  at com.mydomain.myapp.MyTodayIntentService.onHandleIntent (MyTodayIntentService.java)
 
  at android.app.IntentService$ServiceHandler.handleMessage (IntentService.java:67)
 
  at android.os.Handler.dispatchMessage (Handler.java:105)
 
  at android.os.Looper.loop (Looper.java:156)
 
  at android.os.HandlerThread.run (HandlerThread.java:61)
Caused by: java.lang.IllegalStateException: 	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java)
 
  at <OR> com.google.gson.stream.JsonReader.skipQuotedValue (JsonReader.java)

**Comment by Marcono1234** [comment]
Are you still experiencing this issue with the latest Gson version? If so could you please include the full stack trace?

**Comment by Marcono1234** [comment]
I am going to close this because no answer has been provided. If you still experience this with the latest Gson version, feel free to comment here again with more details.
