### ISSUE TITLE
Warning with 2.8.2 with Java 9

### ISSUE THREAD

**Issue by JThomp2000** [google/gson#1190]
Recently changed to java 9 from java 8 and now this warning is popping up

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.gson.internal.bind.ReflectiveTypeAdapterFactory (file:/C:/Users/JThompson/.m2/repository/com/google/code/gson/gson/2.8.2/gson-2.8.2.jar) to field java.time.LocalDate.year
WARNING: Please consider reporting this to the maintainers of com.google.gson.internal.bind.ReflectiveTypeAdapterFactory
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by jfbenckhuijsen** [comment]
As a temporary fix: add this as a VM option: --add-opens java.base/java.time=gson

**Comment by FabianPerl** [comment]
Does not works for me. It gives me the message:

> Error: Could not find or load main class java.base.java.time=gson

Any advice?

**Comment by danorton2** [comment]
@FabianPerl You seem to be reporting an entirely different issue. If you're sure it's related to Gson, please post a new issue at https://github.com/google/gson/issues

**Comment by FabianPerl** [comment]
@danorton2 Thanks for your fast comment! I should write it a little bit more about my Problem. When I start my project, I get this warnings:

> WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.gson.internal.bind.ReflectiveTypeAdapterFactory (file:/...../repository/com/google/code/gson/gson/2.8.2/gson-2.8.2.jar) to field javafx.beans.property.SimpleStringProperty.bean
WARNING: Please consider reporting this to the maintainers of com.google.gson.internal.bind.ReflectiveTypeAdapterFactory
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

I tried @jfbenckhuijsen suggestion with his temporary fix, but unfortunately I received the message up below.

**Comment by danorton2** [comment]
@FabianPerl You seem to be putting the option in the wrong place.  It should be before `-jar`. Please post the full java command line you are using.

**Comment by FabianPerl** [comment]
@danorton2 

Here's my command line: 
> /Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/Home/bin/java
 --add-opens java.base/java.time=gson "-javaagent:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar=52288:/Applications/IntelliJ IDEA.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath /Users/FabianPerl/Desktop/Project/thurn-und-taxis/target/classes:/Users/FabianPerl/.m2/repository/org/apache/commons/commons-lang3/3.7/commons-lang3-3.7.jar:/Users/FabianPerl/.m2/repository/com/google/code/gson/gson/2.8.2/gson-2.8.2.jar:/Users/FabianPerl/.m2/repository/org/jetbrains/annotations/15.0/annotations-15.0.jar de.oceans.tut.Main



and after all

> WARNING: Unknown module: gson specified to --add-opens
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.gson.internal.bind.ReflectiveTypeAdapterFactory (file:/Users/FabianPerl/.m2/repository/com/google/code/gson/gson/2.8.2/gson-2.8.2.jar) to field javafx.beans.property.SimpleStringProperty.bean
WARNING: Please consider reporting this to the maintainers of com.google.gson.internal.bind.ReflectiveTypeAdapterFactory
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by davidmoten** [comment]
What is the plan for a permanent fix? Is this a difficult one?

**Comment by unk1911** [comment]
is there a plan to fix this for JDK9?

**Comment by JakeWharton** [comment]
No. You should not be serializing types you don't control with reflection as you cannot guarantee their internals are stable. Register a TypeAdpater for platform types and serialize/deserialize them using their public APIs.

**Comment by davidmoten** [comment]
Thanks Jake, a project I am contributing to was serialising Void. I'll register a TypeAdapter and should be sorted.

**Comment by JakeWharton** [comment]
Yeah unfortunately it's too late to change Gson's default behavior here so it's easy to fall into this trap. Moshi prevents all serialization of things inside `java.*` (and `kotlin.*`, `scala.*`, `android.*`, etc.) for the same reasons unless you explicitly specify a custom adapter.

You can register a custom TypeAdapter which logs when types in `java.*` are being requested (ignoring List, Set, etc.) and then just `return null` to let the real one handle it to audit your code bases. And then once you migrate everything away, change that adapter to throw!

**Comment by davidmoten** [comment]
>You can register a custom TypeAdapter which logs when types in java.* are being requested (ignoring List, Set, etc.) and then just return null to let the real one handle it to audit your code bases. And then once you migrate everything away, change that adapter to throw!

Excellent idea!

My stuff all working now, needed to register a custom `TypeAdapterFactory` to handle fields in serialized objects.
