### ISSUE TITLE
No documentation on creating java object from arbitrary json

### ISSUE THREAD

**Issue by 7--** [google/gson#1192]
Given some JSON like this. How would I know what object to create so gson can desalinize to it. 

For example JSON:
https://poloniex.com/public?command=returnOrderBook&currencyPair=BTC_LTC

This Java works, but List<double[]> doesnt describe the data enough :
```
public OrderBook(List<double[]> asks, List<double[]> bids, String isFrozen, long seq){
        this.asks = asks;
        this.bids = bids;
        this.isFrozen = isFrozen;
        this.seq = seq;
    }
```
This didnt work. So how do I describe my data better like this?
```
   public OrderBook(List<Ask> asks, List<Bid> bids, String isFrozen, long seq){
        this.asks = asks;
        this.bids = bids;
        this.isFrozen = isFrozen;
        this.seq = seq;
    }

    public static final class Ask {
    	double price;
    	double quantity;
    	
        public Ask(double[] ask){
            this.price = ask[0];
            this.quantity = ask[1];
        }
    }
```

**Comment by NightlyNexus** [comment]
You'll want to use the [TypeAdapter](https://github.com/google/gson/blob/master/gson/src/main/java/com/google/gson/TypeAdapter.java) API.
Check StackOverflow for countless examples of its usage.

**Comment by 7--** [comment]
Thanks
