### ISSUE TITLE
Complete list of escaped characters

### ISSUE THREAD

**Issue by winteraz** [google/gson#1193]
Where can I find the complete list of escaped characters and the corresponding (escaped)values? So far the only resource I've found is [this](https://groups.google.com/forum/#!msg/google-gson/JDHUo9DWyyM/U0kCy7MUcYsJ).  I need this so that I can decode some GSON encoded strings  using a different language(Go)

```
 Characters such as  <, >, =, etc. are escaped because if the JSON
string evaluated by Gson is embedded in an XHTML page then....
```

**Comment by Marcono1234** [comment]
For these HTML characters escaping can be disabled with [`GsonBuilder.disableHtmlEscaping()`](https://javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/GsonBuilder.html#disableHtmlEscaping()). However, even when escaped, the output is valid JSON, see [RFC 8259](https://datatracker.ietf.org/doc/html/rfc8259#section-7):
> Any character may be escaped.

So any compliant JSON parser (even if written in a different language) should accept the produced JSON.
