### ISSUE TITLE
Support for ISO 8601 Calendar format

### ISSUE THREAD

**Issue by SaifurRahmanMohsin** [google/gson#1194]
I'm using an ISO 8601 format (yyyy-MM-dd'T'HH:mm:ssZ) in one of my Android apps and gson keeps throwing this error:

```
java.lang.NumberFormatException: For input string: "2017-11-23 19:30:26.000000"
at java.lang.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1306)
```

I used [this](https://stackoverflow.com/a/10621553/997147) to perform the conversions. I realize that the problem lies with the TypeAdapters and one solution might be to write my own custom converter but wouldn't it be better if this library supports it out of the box? I can see that the current adapter is [written here](https://github.com/google/gson/blob/9e44d60b83d667d96150eeff4e3f04cd4f157e9a/gson/src/main/java/com/google/gson/internal/bind/TypeAdapters.java#L592-L655) and I guess the solution would be to adapt that StackOverflow answer's code into it or using Calendar class' timezone field in to achieve it?

**Comment by danorton2** [comment]
You specify the ISO-8601 format with a "T" separator, but you show an example for a slightly different format, without the "T".

Can you provide the actual JSON string that is failing? Does it include the quotation marks?

**Comment by SaifurRahmanMohsin** [comment]
I finally figured out the issue. I thought that something was going wrong on my app and then I realized that the server was returning the object json for every successful request and gson was converting it back to the original object format. The server messed up and was returning a non-ISO8601 complaint json output as shown in my initial comment which was the reason the app was crashing. Anyway, I've fixed it now so it solves the issue. My apologies for the trouble and thank you for your time.

**Comment by SaifurRahmanMohsin** [comment]
Does GSON still require the incoming data to be formatted as an object like `{year:2017,month:1,dayOfMonth:13,hourOfDay:2,minute:20,second:23}`. I tried returning the data as an ISO 8601 format string from the server but it gave me a **JsonSyntaxException: Expected BEGIN_OBJECT but was STRING** exception. [Looking at the code](https://github.com/google/gson/blob/9e44d60b83d667d96150eeff4e3f04cd4f157e9a/gson/src/main/java/com/google/gson/internal/bind/TypeAdapters.java#L592-L655) it appears to be parsing an object of the abovesaid format but would it be better if it parses a proper ISO 8601 format string?
