### ISSUE TITLE
Allow more control over factories in Gson/GsonBuilder

### ISSUE THREAD

**Issue by ia3andy** [google/gson#1200]
I am using Gson with Immutables code generation and I have a generated adapter for each of my values.

I would like to be able to build a "strict" version of Gson regarding adapters. I would like Gson to throw an exception when trying to serialize/deserialize types that are not registered manually (when strict mode is enabled).

I think it would mean giving the builder some control over actual factories and not hard code them inside the Gson constructor. It could be done without loosing backward compat..

**Comment by ia3andy** [comment]
Any update on this?

**Comment by inder123** [comment]
Can you propose something concrete? May be even create a PR.

**Comment by ia3andy** [comment]
About the issue:
The main problem in my opinion is that it's very hard to control what a Gson instance is allowed to convert. It makes it really easy then to forget to add an adapter without noticing.

The case I want to avoid is having the reflection adapter (or another) taking the place of a user defined adapter without the user knowing (Even with unit tests, if names aren't modified, it wouldn't be noticed).

About the PR:
I was looking at the code and noticed there are user defined parameters to initialize some of the base factories and 'jsonAdapterFactory' is used for a hack is another place. It is therefore more difficult to give the user control over the base factories. 
Another approach would be to add a user defined predicate on types to use in Gson#getAdapter and throw an exception on unexpected types.

I could create a PR, it would be nice thought to find the best possible approach with you before.

**Comment by inder123** [comment]
Accurately predicting what a Gson instance should be allowed to convert is hard.
You may reference system classes that may have transitive dependencies because of their fields.

**Comment by ia3andy** [comment]
I agree with you in some cases but there are some other cases where you want to know exactly what and how data are converted. 

My own case is for a micro service api. I have a set defined data (Immutables) for my api with GsonAdapters for each of them. I have also control over system classes that are used in my data.

Am I the only one with this use case?

**Comment by NightlyNexus** [comment]
Could you install a factory last in your GsonBuilder that throws when trying to create with an error that says the type is unhandled by your manually installed type adapter factories?

(Or, cheat by making a delegating factory that checks for an instance of ReflectiveTypeAdapterFactory.Adapter and throws.)

**Comment by Marcono1234** [comment]
Could you please check whether the [`ReflectionAccessFilter`](https://javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/ReflectionAccessFilter.html) added in Gson 2.9.1 works for your use case?

**Comment by ia3andy** [comment]
> Could you please check whether the [`ReflectionAccessFilter`](https://javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/ReflectionAccessFilter.html) added in Gson 2.9.1 works for your use case?

I am not working anymore on the project with the use-case so I won't be able to check. Feel free to close the issue.
