### ISSUE TITLE
serialization exclusion strategy is getting triggered for deserialization too

### ISSUE THREAD

**Issue by krishnarama** [google/gson#1202]
I have added exclusion strategy for serialization using `addSerializationExclusionStrategy`. But this is getting triggered during deserialization too. As per the documentation this strategy should trigger only for serialization.

**Comment by Marcono1234** [comment]
In case this is still relevant, could you please try the latest Gson version and provide a small self-contained example showing this issue?

**Comment by Marcono1234** [comment]
I am going to close this because no answer has been provided. If you still experience this with the latest Gson version, feel free to comment here again with more details.
