### ISSUE TITLE
Why is the JsonParser always lenient?

### ISSUE THREAD

**Issue by xfxyjwf** [google/gson#1208]
See this line:
https://github.com/google/gson/blob/6b20e3aaec0b3280f01c7785b5dd391ab6de9cc7/gson/src/main/java/com/google/gson/JsonParser.java#L82

It basically makes the JsonReader.setLenient() API useless. 

How can we make the parser strict? For reference this is for http://b/34734814

**Comment by JakeWharton** [comment]
You can call `getAdapter(type).fromJson(gson.newJsonReader(input))` instead of just `fromJson(input)` to get strict parsing. We should really deprecate all of the `fromJson` methods and add new versions that are strict by default.

The reason is bad decisions long ago that we can no longer change 😢

**Comment by xfxyjwf** [comment]
Thanks for the quick reply! I'm not sure how to apply this to our code though. Our code currently looks like this:

```java
JsonParser jsonParser = new JsonParser();
JsonReader reader = new JsonReader(json);
reader.setLenient(false);
JsonElement element = jsonParser.parse(reader);
... use element ...
```

See: https://github.com/google/protobuf/blob/master/java/util/src/main/java/com/google/protobuf/util/JsonFormat.java#L1170

How do I apply `getAdapter(type).fromJson(gson.newJsonReader(input))`?

**Comment by NightlyNexus** [comment]
unfortunate there's no `public JsonElement JsonReader.readJsonValue()` to expose this.

you might be have to mix in the object binding APIs. something like:
```java
private static TypeAdapter<JsonElement> JSON_ELEMENT_ADAPTER = new Gson().getAdapter(JsonElement.class);

JsonElement jsonElement(JsonReader reader) {
  JSON_ELEMENT_ADAPTER.read(reader);
}
```

There may be subtle behavior difference in there. I don't recall!

**Comment by vkopichenko** [comment]
Here is an example of Gson strict parsing workaround proposed here with extensive test case: https://stackoverflow.com/questions/43233898/how-to-check-if-json-is-valid-in-java-using-gson/47890960#47890960
