### ISSUE TITLE
Dynamic JSON structure

### ISSUE THREAD

**Issue by redradist** [google/gson#1212]
Hello guys,

I need to create model with dynamic structure, something like this:

    class DataInfo {
        @SerializedName("status")
        public String status;
        @SerializedName("id")
        public long id;
        @SerializedName("type")
        public String type;
        @SerializedName(value="dynamicData0",
                        alternate={"Data", "Name"}) // Depends on requests parameters
        public String dynamicData0;
        @SerializedName(value="dynamicData1",
                        alternate={"Name", "Data"}) // Depends on requests parameters
        public String dynamicData1;
    }

The issue is that **dynamicData0** and **dynamicData1** have dynamic names in json and alternatives does not work because dynamicData0 and dynamicData1 could have similar alternative names like "Name" == "Name" depending on arguments, but in different requests.
How to handle such case ? the above model does not compile because the similar alternates in dynamicData0 and dynamicData1.

For example, for first request model is:

    class DataInfo {
        @SerializedName("status")
        public String status;
        @SerializedName("id")
        public long id;
        @SerializedName("type")
        public String type;
        @SerializedName(**"Name"**) // Depends on requests parameters
        public String dynamicData0;
        @SerializedName(**"Data"**) // Depends on requests parameters
        public String dynamicData1;
    }

For second request:

    class DataInfo {
        @SerializedName("status")
        public String status;
        @SerializedName("id")
        public long id;
        @SerializedName("type")
        public String type;
        @SerializedName(**"Data"**) // Depends on requests parameters
        public String dynamicData0;
        @SerializedName(**"Name"**) // Depends on requests parameters
        public String dynamicData1;
    }

Is there a solution for such cases ?

**Comment by inder123** [comment]
Write a type adapter for DataInfo? 
Also, please post questions like this on StackOverflow. The GitHub issues is already way too cluttered
