### ISSUE TITLE
toJson returns empty string though there are @Expose annotation defined on properties in Spring MVC/Virgo

### ISSUE THREAD

**Issue by vijaybhatt1** [google/gson#1214]
public MyHostGroupObject customSerializeMyHostGroupObject(MyHostGroupObject objMyHostGroup, String serverGuid, String hostId, String type, List<String> hostList)
	{
		System.out.println("VijayDebug::insidecustomserial::");
		Gson objGson = new GsonBuilder().excludeFieldsWithoutExposeAnnotation().create();
		System.out.println("VijayDebug::aftergsonbulder::");
		String resString = "";
		resString = objGson.toJson(objMyHostGroup);
		System.out.println("VijayDebug::resString::" + resString);
		MyHostGroupObject retMyHostGroup = objGson.fromJson(resString, MyHostGroupObject.class);
		return retMyHostGroup;
	}

This method works fine in standalone java application, but gives empty response when used in Spring MVC application deployed on Eclipse Virgo server. There are properties in the class with @Expose annotation.

Any pointers to isolate the issue?
Thanks,
Vijay

**Comment by Marcono1234** [comment]
Are you still experiencing this issue with the latest Gson version? If so, could you please provide a small self-contained sample project demonstrating the issue?

**Comment by Marcono1234** [comment]
I am going to close this because no answer has been provided. If you still experience this with the latest Gson version, feel free to comment here again with more details.
