### ISSUE TITLE
A collection of strings json turn null

### ISSUE THREAD

**Issue by zzy1147** [google/gson#1226]
`public static void main(String[] args) {
		 List<String> list=new ArrayList<String>() {
			{
				add("1");
				add("2");
				add("3");
			}
		
	};
		
		Gson gson=new Gson();
                String jsonStr=gson.toJson(list);
		System.out.println(json);
		
	}`
the jsonStr is null,
Why is this, thank you

**Comment by NightlyNexus** [comment]
Don't make an anonymous inner class subtype of ArrayList.
Gson has no way to deserialization them.
