### ISSUE TITLE
How to deserialize this format with 

### ISSUE THREAD

**Issue by tksiaokia** [google/gson#1228]
{
  "status": 0,
  "result": true,
  "accounts": [{
    "bank_name": "xx",
    "id": 1,
    "account_id": "xxx"
  }]
}
i Just want the Account Array
Option:
1. Create class ResponseAccount{
int status;
boolean result;
List<Account> accounts;
}
ResponseAccount model = new Gson().fromJson(response,ResponseAccount.class);
List<Account> accounts = model.account

2.
TypedValue typedValue = xxx;
List<Account> accounts = new Gson().fromJson(response.getJsonObject("accounts",typedValue);

What i want is 
List<Account> accounts = new Gson().fromJson(response,Account.class);
which can ignore the first layer and straight go to "accounts"

**Comment by JakeWharton** [comment]
Please ask generate usage questions on StackOverflow with the 'gson' tag. This issue tracked is for bugs and feature requests only. Thanks.
