### ISSUE TITLE
Serializer/Deserializer Annotation

### ISSUE THREAD

**Issue by julianostarek** [google/gson#1231]
I'd like to see the possibility of annotating classes with something like an @Serializer annotation in the following way:

```java
@Serializer(FooSerializer.class)
@Deserializer(FooDeserializer.class)
public class Foo {
    ...
}
```

This would tell Gson to use an instance of the denoted class (default constructor being a requirement) for (De-)Serialization of the annotated type. 
As we're messing with Gson-specific annotations in our model classes anyway, I feel like this shouldn't be too much of a complication/overhead. Thoughts?

**Comment by JakeWharton** [comment]
This already exists. You can use `@JsonAdapter` with a `TypeAdapterFactory`, `TypeAdapter`, `JsonSerializer`, or `JsonDeserializer` to provide custom logic for a type or member.
