### ISSUE TITLE
Include an automatic module name in the manifest

### ISSUE THREAD

**Issue by kashike** [google/gson#1238]
While #1179 adds a (broken) `module-info.java`, it is disabled. Adding an `Automatic-Module-Name` manifest entry will not break on previous versions of Java, and will allow gson to be used without becoming a full module.

Related:
https://github.com/google/guava/pull/2846
https://github.com/google/guava/pull/2961
https://github.com/vigna/fastutil/issues/89#issuecomment-361202718

**Comment by Marcono1234** [comment]
Probably obsolete now. The latest Gson versions contain a valid `module-info.class`, which additionally should (hopefully) also work well for Java versions < 9, see #2013.

(Also, hello kashike :wave:)
