### ISSUE TITLE
Unable to add gson library to maven

### ISSUE THREAD

**Issue by shruthikakwe** [google/gson#1240]
Build fails with this error:
---------------------------------------------------------------------
------------------------------------------------------------------------
Building helloworld-web 1.0-SNAPSHOT
------------------------------------------------------------------------
The POM for com.google.code.gson:gson:jar:2.8.0 is missing, no dependency information available
------------------------------------------------------------------------

Failed to execute goal on project helloworld-web: Could not resolve dependencies for project com.twitter:helloworld-web:war:1.0-SNAPSHOT: Failure to find com.google.code.gson:gson:jar:2.8.0 in http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

**Comment by JakeWharton** [comment]
It's definitely there: http://repo1.maven.org/maven2/com/google/code/gson/gson/2.8.0/. This is likely a hiccup with your internet connection.

**Comment by shruthikakwe** [comment]
Yes, I can see it there. But when I build my project after adding the jar
file I get this error.

Can you give me the pom.xml details for this library?

Regards,
Shruthi

**Comment by JakeWharton** [comment]
They're available at the link above to browse.
