### ISSUE TITLE
java.lang.StackOverflowError at com.google.gson.internal.$Gson$Types.resolve

### ISSUE THREAD

**Issue by SashaAV** [google/gson#1243]
**while doing code** 

```
  import java.util.Timer;

  Gson gson = new Gson();
   Timer tmr = new Timer();
   System.out.println(gson.toJson(tmr));
```

**I have got error**
```

java.lang.StackOverflowError
	at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:353)
	at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:378)
	at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:383)
	at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:378)
	at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:383)
	at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:378)
```

**Comment by NightlyNexus** [comment]
What's `Timer`? See https://github.com/google/gson/pull/1128
As a blind guess, update to the latest Gson.

**Comment by SashaAV** [comment]
I,ve edited message. tmr - it's java.util.Timer.  I've tried on 2.8.2 version

**Comment by Dhirajpandit** [comment]
Hi @SashaAV  
as per my opinion.
 1) Timer class schedule the task.  please refer this link https://www.geeksforgeeks.org/java-util-timer-class-java/ 
2)  if you use timer  so there must be a limits, where to stop this timer,

**Comment by SashaAV** [comment]
I see.
I have marked this field with transient and do not serialize it.
I just give you an example of error while gson resolve type java.util.Timer

The point is **only** in $Gson$Types.resolve   error.

Thank you.
ps: possibly I have to provide   example with more additional info.

**Comment by amogilev** [comment]
The line numbers in your stacktrace do not correspond to $Gson$Types.resolve calls in 2.8.2. Probably you have got it on older version.

In 2.8.2, there is StackOverflowError for Timer as well, but it is related to actual circular references, and do not include any $Gson$Types.resolve() lines in the stacktrace

**Comment by Marcono1234** [comment]
Gson does not provide a built-in adapter for `java.util.Timer` and therefore uses reflection to serialize it. In general you should avoid using reflection-based serialization for third party classes because you will then depend on their internal implementation details which could change at any point.

Most likely this specific issue with `$Gson$Types.resolve` has also already been fixed in the latest Gson version because some pull requests related to this have been merged in the past.
