### ISSUE TITLE
how to format  two date attributes in one object as different ?

### ISSUE THREAD

**Issue by HongKing** [google/gson#1245]
the class like this:
```
class User {
  private Date serviceBgn;
  private Date serviceEnd;
  private Date createTime;
}
```
to json string like :
```
{
  serviceBgn : "2017-10-01",
  serviceEnd : "2018-09-30",
  createTime : "2017-09-10 10:50:55",
}
```
I can register a type adapter to deserializer, but I can't serializer. I think can I create an annotations do this like :
```
class User {
  @DateFormat("yyyy-mm-dd")
  private Date serviceBgn;

  @DateFormat("yyyy-mm-dd")
  private Date serviceEnd;

  @DateFormat("yyyy-mm-dd hh:mm:ss")
  private Date createTime;
}
```
but I try it as failed, how can I do it? It would be better if gson supports custom annotations.

**Comment by JakeWharton** [comment]
Please ask general usage questions on StackOverflow. This issue tracker is for bug reports and feature requests only.
