### ISSUE TITLE
How to convert ArrayListMultimap to json use Gson?

### ISSUE THREAD

**Issue by passionofvc** [google/gson#1248]
I use below code to convert map to json,
how to resolved my problem?
```
final Multimap<String, String> data = ArrayListMultimap.create();
data.put("addr1", "20.44");
data.put("addr2", "10.44");
data.put("addr2", "40.44");
Gson gson = new Gson();  
String json = gson.toJson(data.asMap()); 
System.out.printf( "JSON: %s", json.toString() );
```
the result is
`JSON: {"addr2":["10.44","40.44"],"addr1":["20.44"]}
`
but I want the below result[key:value], not [key:list].
`JSON: {"addr2":"10.44","addr2":"40.44","addr1":"20.44"}`

**Comment by JakeWharton** [comment]
You can write a TypeAdapter for this, although the latter is not valid JSON and might be mangled by other tools. If you need assistance please ask on StackOverflow.
