### ISSUE TITLE
Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $ 

### ISSUE THREAD

**Issue by SiddarthG** [google/gson#1256]
Hi onFailure in retrofit is throwing this exception mentioned in title and this happened all of a sudden previously it was working fine,i'm having a real hard time analyzing what has changed that led to this problem,can someone please have a look at this and help me out,

if the formatting here is not clear, i have posted in stackoverflow
[https://stackoverflow.com/questions/48840747/onfailure-methods-throws-exception-expected-begin-array-but-was-string-at-line](https://stackoverflow.com/questions/48840747/onfailure-methods-throws-exception-expected-begin-array-but-was-string-at-line)

I have this Json Response coming from server:

[{ "disposal_type_category": { "category_entry_total": "21" }, "disposal_types": [{ "ID": "78", "entries": [{ "ID": 2584, "entry_tally": "1" }, { "ID": 2578, "entry_tally": "1" } ] }, { "ID": "1323", "entries": [{ "ID": 2583, "entry_tally": "1" }, { "ID": 2579, "entry_tally": "1" } ] } ] }, { "disposal_type_category": { "category_entry_total": "25.2" }, "disposal_types": [{ "ID": "80", "entries": [] }, { "ID": "84", "entries": [] } ] } ]

This is in my ApiClient.java:

public static Retrofit getClient() { if (retrofit==null) { Gson gson = new GsonBuilder().setLenient().create(); retrofit = new Retrofit.Builder() .baseUrl(BASE_URL) .addConverterFactory(ScalarsConverterFactory.create()) .addConverterFactory(GsonConverterFactory.create(gson)) .build(); } return retrofit; }

This is in ApiInterface.java:

`Call<List<Disposal>> getCollection(@Header("Authorization") String token);`

Disposal.java:

public class Disposal { @SerializedName("disposal_type_category") @Expose public DisposalTypeCategory disposalTypeCategory; @SerializedName("disposal_types") @Expose public List<DisposalType> disposalTypes = null; }

DisposalTypeCategory.java:

public class DisposalTypeCategory { @SerializedName("category_entry_total") @Expose public String categoryEntryTotal; }

DisposalType.java:

public class DisposalType { @SerializedName("ID") @Expose public String iD; @SerializedName("entries") @Expose public List<Entries> entries = null; }

Entries.java:

public class Entries { @SerializedName("ID") @Expose private int iD; }

I have set setLineant(true) for Gson because if i remove it i will get malformed json exception, even this issue started recently previously was fine, not sure if its related.
The issue started after 2-3 new fields were added to API and the base url was changed but still the core remains same.

**Comment by JakeWharton** [comment]
StackOverflow is the correct place for this question. It's not a Gson feature or bug.
