### ISSUE TITLE
ObjectTypeAdapter error when the value type is a Number

### ISSUE THREAD

**Issue by marcgise** [google/gson#1257]
Hi,
I found an error in the read method of the ObjectTypeAdapter when the value is a Number, as it always transforms it to a double value. But maybe the expected value is an Integer. I made the following change, and it seems to work fine:
```
switch (token) {
    case NUMBER:
        String value = in.nextString();
        if (value.contains(",") || value.contains(".")) {
            return new BigDecimal(value); // or Double.valueOf(value);
        } else {
            return Integer.valueOf(value);
        }
    case....:
}
```

**Comment by marcgise** [comment]
Another error I found, is that the ObjectTypeAdapter could not be overriden: neither by extending the class (because it's final) nor by adding another factory to the Gson, because ObjectTypeAdapter is always processed first.

**Comment by liweys** [comment]
I copied this file into my project, modified it as you did. This way it worked. But need to figure out how to make my version take precedence always.

**Comment by zenglian** [comment]
Gson team is aware of that since its 1st version (9 Sep 2011).

**Comment by SiemelNaran** [comment]
Maybe we don't want people to be able to override ObjectTypeAdapter or put it second in the list of factories as it could change the default behavior of parsing JSON objects.  But can we try out the following way of customizing the behavior of ObjectTypeAdapter?  That is, change the following code:

```
    case NUMBER:
      return in.nextDouble();
```

to

```
    case NUMBER:
      return numberReader.read(in);
```

And there will be a new function in GsonBuilder like registerObjectNumberReader(NumberReader). The default NumberReader will just call `in.nextDouble()`.  But the new one will have functions/enums to prefer BigInteger, long, int, or short when the token is an integer type, and similar stuff for float types.  This is similar to Jackson's DeserializationFeature.USE_BIG_DECIMAL_FOR_FLOATS.

Would this work?  I can work on this.

Another thing I'd like is to ability to force types based on the path.  For example, when parsing `{ "finance": { "cost": 23000 }}`, we could specify that $.finance.cost is always a BigDecimal.  By looking at the value of in.getPath() in the debugger, it does not look to be right.  For example in `{ "cost": 23000 }` the path is "$." when reading 23000 but I want "$.cost".  In `{ "finance":{ "cost": 23000 }}` the path is "$..cost" but I 'd like "$.finance.cost".
