### ISSUE TITLE
Add InputStream constructor to JsonReader

### ISSUE THREAD

**Issue by elharo** [google/gson#1259]
Per RFC, JSON can come in UTF-8, UTF-16, or UTF-32 and must not contain a byte order mark. Detecting this is really tricky, especially in the absence of a byte order mark. It is extremely error prone.

We should add a constructor that take an `InputStream` instead of a `Reader` and autodetects the encoding correctly so this doesn't have to be done by every user of this class. 

```
/**
   * Creates a new instance that reads a JSON-encoded stream from {@code in}.
   */
  public JsonReader(InputStream in) {
```

**Comment by Marcono1234** [comment]
The latest JSON RFC (RFC 8259) says:
> [8.1](https://datatracker.ietf.org/doc/html/rfc8259#section-8.1).  Character Encoding
> 
>   JSON text exchanged between systems that are not part of a closed
>   ecosystem MUST be encoded using UTF-8 [[RFC3629](https://datatracker.ietf.org/doc/html/rfc3629)].
>
>   Previous specifications of JSON have not required the use of UTF-8
>   when transmitting JSON text.  However, the vast majority of JSON-
>   based software implementations have chosen to use the UTF-8 encoding,
>   to the extent that it is the only encoding that achieves
>   interoperability.
>
>   Implementations MUST NOT add a byte order mark (U+FEFF) to the
>   beginning of a networked-transmitted JSON text.  In the interests of
>   interoperability, implementations that parse JSON texts MAY ignore
>   the presence of a byte order mark rather than treating it as an
>   error.

Though the previous RFCs did not require that.

Do you have a specific use case in mind? Often the user code can better determine the encoding, for example for HTTP requests the HTTP headers indicate the encoding.

(Note that I am not a member of this project.)

**Comment by elharo** [comment]
It's fine to always emit UTF-8.

It is not OK to reject or misparse JSON that is fully conformant to earlier versions of the specification; e.g. because it is in UTF-16.

Users are routinely awful at detecting encoding. This is something for experts only, which is why it should be included in the library so users don't have to become experts to do it right. E.g. in the case you mention, there is no http charset for JSON because the MIME media type is application/json, not text/json. See https://www.iana.org/assignments/media-types/application/json

**Comment by eamonnmcmanus** [comment]
> It is not OK to reject or misparse JSON that is fully conformant to earlier versions of the specification; e.g. because it is in UTF-16.

To the extent that we are rejecting or misparsing JSON, that is something that is already true, right? This issue is proposing a way for new code to avoid it, in the very specific case where (1) it has to handle UTF-16 or UTF-32 input (which as noted in the RFC quote above hardly ever happens), and (2) it doesn't have an external indication of what the encoding actually is.

Given that Gson is in maintenance mode, I don't think the project maintainers are likely to make this change. However if you (@elharo) want to send a PR we can certainly review it. In that case, feel free to reopen this issue and close it again with the PR.

**Comment by elharo** [comment]
No, not really. That was my response to https://github.com/google/gson/issues/1259#issuecomment-1193410627

We do still really need an InputStream constructor. Currently, GSON relies on the client to correctly determine the encoding, and clients routinely get this wrong.

**Comment by eamonnmcmanus** [comment]
> We do still really need an InputStream constructor

I guess that remains to be proven. We haven't seen a lot of issues from people who have had this sort of problem. Google [shows](https://www.google.com/search?q=gson+utf-16) a few mentions over the years, but it's not clear to me that even those ones would have been avoided if we had had an `InputStream` constructor. People would have to think to use it. Meanwhile UTF-16 JSON is obsolete so we may expect that these issues will become even rarer over time.
