### ISSUE TITLE
How to deal with false values instead of object

### ISSUE THREAD

**Issue by prsolucoes** [google/gson#1269]
Hi,

Im using an old API that come with a false value instead of object. The structure is:

```
{
    "customer": {
          "subscription": {  }
     }
}
```

But sometime it come:

```
{
    "customer": {
          "subscription": false
     }
}
```

But gson throw exception because the expected object come as false value.

There is any easy way to deal with it?

Thanks for any help.

**Comment by JakeWharton** [comment]
You can write a TypeAdapter for this. Please ask this question on StackOverflow.
