### ISSUE TITLE
Invalid number: Dec trying to parse date

### ISSUE THREAD

**Issue by saldous** [google/gson#1282]
If I have a date of: **Dec 22, 2014 12:00:00 PM**

and I set the gson format like below:

`val gson = GsonBuilder().setDateFormat("MMM d, yyyy HH:mm:ss a").create() `
`val json = gson.toJson(input)`

When I read back the date the app crashes.

```
val caseType = object : TypeToken<ArrayList<MyCase>>() {}.type
return gson.fromJson<ArrayList<MyCase>>(json, caseType)
```

`java.lang.NumberFormatException: Invalid number: Dec at com.google.gson.internal.bind.util.ISO8601Utils.parseInt(ISO8601Utils.java:311)`

Any ideas why / how to fix?

thank you.

**Comment by NightlyNexus** [comment]
```
Gson gson = new GsonBuilder().setDateFormat("MMM d, yyyy HH:mm:ss a").create();
gson.toJson("Dec 22, 2014 12:00:00 PM"));
```
works for me.
Do you have a failing test case?
I'd also be interested in seeing the full stack trace.

**Comment by saldous** [comment]
sorry, I think I found the issue, it was in a different file, my bad.

**Comment by Gabrix94** [comment]
could you specify where the problem originated? I'm finding a similar error
