### ISSUE TITLE
Remove final from public classes such as Gson

### ISSUE THREAD

**Issue by dhoffer** [google/gson#1283]
Remove final from public classes such as Gson so Gson can be mocked in unit testing.  How can Gson be used in unit testing with final classes?  We use EasyMock for our mocking framework.

**Comment by JakeWharton** [comment]
There's no reason to mock Gson or any of its types. You should only mock types that you control so if you have an abstraction for serialization you could mock that, but if not, just call into Gson and let it do normal serialization.

**Comment by dhoffer** [comment]
That is not the case, one often needs to mock 3rd party objects just like any other.  In my case I will need to mock Gson#fromJson().  I don't want to have to wrap the Gson API with another layer just to be able to mock.

In my case I have used PowerMock to get around this problem.

@RunWith(PowerMockRunner.class)
@PrepareForTest({Gson.class})
