### ISSUE TITLE
JsonParser stops parsing at first whitespace

### ISSUE THREAD

**Issue by hgschwibbe** [google/gson#1286]
The JsonParser stops parsing at the first whitespace. 

The following unit test describes the problem

```
import java.io.StringReader;

import org.junit.Assert;
import org.junit.Test;

import com.google.gson.JsonElement;
import com.google.gson.JsonParser;
import com.google.gson.stream.JsonReader;

public class JsonParserTest {
    @Test
    public void whitespaceTest() {
        StringReader stringReader = new StringReader("ABC_DEF GHI");
        JsonReader jsonReader = new JsonReader(stringReader);
        final JsonParser jsonParser = new JsonParser();
        JsonElement parsed = jsonParser.parse(jsonReader);
        Assert.assertEquals("ABC_DEF GHI", parsed.getAsString());
    }
}
```

The unit test results with the following error: 
`org.junit.ComparisonFailure: expected:<ABC_DEF[ GHI]> but was:<ABC_DEF[]>`

**Comment by hgschwibbe** [comment]
Escaping the string with doulbe quotes works: `new StringReader("\"ABC_DEF GHI\"")`.
But the main question is: why do I have to quote the strings?
When I pass a `StringReader` to the `JsonReader` it should be clear that I want to parse a string literal.
If I want to parse an integer I will pass an 'IntegerReader' to the `JsonReader`.

**Comment by hgschwibbe** [comment]
Reopened it because from my opinion its a big pitfall. The unit test should work as it is, regardles of quoting strings or not.

**Comment by SimonVT** [comment]
> But why do I have to quote the strings?

Because [RFC 7159](https://tools.ietf.org/html/rfc7159) says so.
`ABC_DEF GHI` is not valid JSON, while `"ABC_DEF GHI"` is.
