### ISSUE TITLE
List of Object having Nested HashMap,String,ArrayList & HashMap converting to JSON is incorrect

### ISSUE THREAD

**Issue by swapnil0504** [google/gson#1294]
I have a List<Object> and that list has nested hashmaps,json,maps,array and string, whenever I am converting  into JSON, GSON library  is skipping few hashmaps.

**Comment by JakeWharton** [comment]
Provide a failing test case.

**Comment by swapnil0504** [comment]
I have got the problem my implementation was incorrect.
Thanks
