### ISSUE TITLE
Deserialization of java.time.OffsetDateTime with zero time offset

### ISSUE THREAD

**Issue by smile18** [google/gson#1309]
When serializing / deserializing an object with the java.time.OffsetDateTime  API, the results are diferent from expected if zero sec are given.

For excample, here's a  java.time.OffsetDateTime serialized with gson (using version 2.8.0):
 @SerializedName("orderTime")
 private OffsetDateTime orderTime = null;

"orderTime":"2018-05-02T14:23:00Z" 

but I get the value as 2018-05-02T14:23Z where I should get the value as 2018-05-02T14:23:00Z

**Comment by JakeWharton** [comment]
`java.time` APIs are not supported by Gson's built-in date format configuration. We generally regard that as a mistake. For all types in `java.time` you should register your own type adapter which uses the type's public API to serialize to and from the JSON primitives.

**Comment by inder123** [comment]
@smile18 we would love to have your contribution for java.time TypeAdapter in gson-extras project
