### ISSUE TITLE
Expected BEGIN_OBJECT but was NUMBER

### ISSUE THREAD

**Issue by jingchangfa** [google/gson#1312]
![image](https://user-images.githubusercontent.com/19325158/39755912-1d94df1e-52fa-11e8-9acf-4f41a72e975b.png)

![image](https://user-images.githubusercontent.com/19325158/39755958-3f76b120-52fa-11e8-840c-5e9a85be3f0d.png)

**Comment by JakeWharton** [comment]
This is not a bug in Gson but a data mismatch between your JSON and your model object. Your model expects an object but the JSON had a number.
