### ISSUE TITLE
Gson serialized integers to decimals

### ISSUE THREAD

**Issue by DearBo7** [google/gson#1313]
A json string containing an integer, serialized into an Object, how to avoid the integer into a decimal.

Source code:
String data = "[{"Id":1,"Type":"root","Key":"root"},{"Id":2,"Type":"root"},{"Id":3,"Type":"root"}]";

List<Object> dataList = gson.fromJson(data, new TypeToken<List<Object>>() {}.getType());

![image](https://user-images.githubusercontent.com/29586966/39806457-95bc3dae-53ac-11e8-8ee7-525a6681ba5a.png)

**Comment by eamonnmcmanus** [comment]
Fixed by #1290.
