### ISSUE TITLE
Java 11 disallows sun.misc.unsafe access from a module

### ISSUE THREAD

**Issue by cayhorstmann** [google/gson#1317]
Putting the gson JAR on the module path makes the call 

     unsafeClass = Class.forName("sun.misc.Unsafe");

fail in Java 11. You might as well check that at the place where you check for version numbers, and switch to reflective access. Users who do put the JAR on the module path should know to open any packages whose classes are being accessed by reflection.

**Comment by cayhorstmann** [comment]
Sorry for being obtuse. You have two strategies for looking at the fields of an object: PreJava9ReflectionAccessor and UnsafeReflectionAccessor. The UnsafeReflectionAccessor will fail in Java 11 if the Gson JAR file is on the module path. This is not fatal because each time it fails, you will fall back to PreJava9ReflectionAccessor. But you might as well do the test once in ReflectionAccessor and be done with it.

**Comment by AlanBateman** [comment]
If gson is compiled or deployed as an explicit and it is using sun.misc.Unsafe then it needs `requires jdk.unsupported` in its module declaration. If gon is deployed as an automatic module then it won't read the jdk.unsupported if it's not resolved. The jdk.unsupported module will be resolved if some module `requires jdk.unsupported` or you run with `--add-modules jdk.unsupported`.

**Comment by Marcono1234** [comment]
Might have been fixed by #1993 which added `requires static jdk.unsupported;`.
