### ISSUE TITLE
change the field value 7 to 7%

### ISSUE THREAD

**Issue by LennyYi** [google/gson#1319]
[
{
.......
"prTaxCode":"TH_I_SID_DOM_S"
"prTaxRate":"7",
...
}
].
I build a class named  "IbuySystem"   for this json. This class has 30-40 fields,but I just want change prTaxRate value  to 7%,Please tell me how can I code ？

**Comment by LennyYi** [comment]
I‘m try   (IbuySystemAdapter)TypeAdapter but，others field I don‘t want write one by one，because others fields I don’t want change。

**Comment by JakeWharton** [comment]
This issue tracker is for bug reports and feature requests only. For general usage questions, please as on StackOverflow with the 'gson' tag or on Gson's mailing list.
