### ISSUE TITLE
Cannot find easy way to write type adapter that reads entire object as JsonString

### ISSUE THREAD

**Issue by asocjal** [google/gson#1323]
I have RawJson class:
`public class RawJson implements Serializable {

        private static final long serialVersionUID = 1L;

        private final String str;

        public RawJson(Object toJson) {
            this.str = (new GsonBuilder()).create().toJson(toJson);
        }

        public RawJson(String str) {
            this.str = str;
        }

        public String getJsonStr() {
            return str;
        }

        public String toString() {
            return str;
        }
    }`

For this class I have TypeAdapter:

`
    public class RawJsonAdapter extends TypeAdapter<RawJson> {

        @Override
        public void write(final JsonWriter out, final RawJson value) throws IOException {
            if(value != null) {
                out.jsonValue(value.getJsonStr());
            } else {
                out.jsonValue(null);
            }
        }

        @Override
        public RawJson read(final JsonReader in) throws IOException {
            return null; // What to write here?
        }
    }
`

The issue is I don't know how to implement "read" method in TypeAdapter. I need just to create new RawJson object and place entire json object as parameter as String. It should just pass this test case:

`
    public class RawJsonTest extends TestCase {

        private final class TestClass {
            @SuppressWarnings("unused")
            public String name;
            @SuppressWarnings("unused")
            public RawJson rawJson;
            @SuppressWarnings("unused")
            public int age;
        }

        private final class RawData {
            @SuppressWarnings("unused")
            public String profession;
            @SuppressWarnings("unused")
            public int experience;
        }

        public void testBasic() throws UtilsException {
            TestClass tc = new TestClass();
            tc.name = "Juzek";

            RawData rd = new RawData();
            rd.profession = "spawacz";
            rd.experience = 3;
            tc.rawJson = new RawJson(rd);

            tc.age = 38;

            Gson g = (new GsonBuilder()).registerTypeAdapter(RawJson.class, new RawJsonAdapter()).serializeNulls().create();

            String json = g.toJson(tc);
            Assert.assertEquals("{\"name\":\"Juzek\",\"rawJson\":{\"profession\":\"spawacz\",\"experience\":3},\"age\":38}", json);

            TestClass tc2 = g.fromJson(json, TestClass.class);
            String str = tc2.rawJson.getJsonStr();
            Assert.assertEquals("{\"profession\":\"spawacz\",\"experience\":3}", str);
        }
    }
`

**Comment by lyubomyr-shaydariv** [comment]
Use `value(String)` instead of `jsonValue(String)`.

**Comment by Marcono1234** [comment]
Does #1368 describe the feature you are asking for?

**Comment by Marcono1234** [comment]
I am going to close this because no answer has been provided. If you still experience this with the latest Gson version, feel free to comment here again with more details.
