### ISSUE TITLE
NoSuchMethodException on Android 4.2.2

### ISSUE THREAD

**Issue by gauravarora90** [google/gson#1329]
[Here is my complete question. 
](https://stackoverflow.com/questions/50565875/gson-nosuchmethodexception-for-android-4-2-2-devices)

I am using latest gson library version

**Comment by JakeWharton** [comment]
No need to cross post

**Comment by gauravarora90** [comment]
@JakeWharton. Can you pls update ? Why my issue is closed. ?

**Comment by Sdghasemi** [comment]
We are now experiencing the exact same problem.
Here are crash reports on Crashlytics:
[http://crashes.to/s/c226c112c6b](http://crashes.to/s/c226c112c6b)
[http://crashes.to/s/c226c112c6b](http://crashes.to/s/591ae5372f4)
Need to mention that all of the models are using empty constructors as:

    public class MessageNotification {
        public MessageNotification() {}
    }

Any help would be appreciated.
