### ISSUE TITLE
java.lang.IncompatibleClassChangeError: Class 'com.google.gson.internal.bind.JsonAdapterAnnotationTypeAdapterFactory' does not implement interface 'com.google.gson.FieldNamingStrategy' in call to 'java.lang.String com.google.gson.FieldNamingStrategy.translateName(java.lang.reflect.Field)'

### ISSUE THREAD

**Issue by armen301** [google/gson#1331]
Here is log
`E/AndroidRuntime(26599): at com.google.gson.Gson.fromJson(Gson.java:773)
E/AndroidRuntime(26599): at com.google.gson.Gson.fromJson(Gson.java:801)
E/AndroidRuntime(26599): at com.google.gson.Gson.fromJson(Gson.java:852)
E/AndroidRuntime(26599): at com.google.gson.Gson.fromJson(Gson.java:886)
E/AndroidRuntime(26599): at com.google.gson.Gson.getAdapter(Gson.java:423)
E/AndroidRuntime(26599): at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100)
E/AndroidRuntime(26599): at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:159)
E/AndroidRuntime(26599): at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getFieldNames(ReflectiveTypeAdapterFactory.java:74)
E/AndroidRuntime(26599): java.lang.IncompatibleClassChangeError: Class 'com.google.gson.internal.bind.JsonAdapterAnnotationTypeAdapterFactory' does not implement interface 'com.google.gson.FieldNamingStrategy' in call to 'java.lang.String com.google.gson.FieldNamingStrategy.translateName(java.lang.reflect.Field)'`

Here is code which throws this exception:
`MyClass class = new MyClass();`
`String json = new Gson().toJson(class);`
`new Gson().fromJson(json, MyClass.class);`

`class MyClass implements Serializable {
member1;
member2;
}`

Used version is 2.7

**Comment by inder123** [comment]
Can you try the latest version 2.8.5? It prints the Gson version in some error cases so we can find out if there is a conflict with some preinstalled version.

**Comment by armen301** [comment]
I will try and let you know.

**Comment by Sdghasemi** [comment]
@inder123 I'm using Gson 2.8.5 and still facing the issue. Here's a bug report from Crashlytics: http://crashes.to/s/57554ed9414
Any solution?

**Comment by Marcono1234** [comment]
Are you still experiencing this with the latest Gson version?
