### ISSUE TITLE
Extract getContainerElementType() method in $Gson$Types

### ISSUE THREAD

**Issue by tlinkowski** [google/gson#1334]
Currently, `$Gson$Types` class contains the following public method:
```
public static Type getCollectionElementType(Type context, Class<?> contextRawType)
```

This method works like a charm for all kind of `Collection`s but it is unnecessarily fixed to work only on `Collection`s, and it cannot be applied to work on other `Iterable`s (e.g. on `Stream`s, or any other type of containers that do not implement `Collection`).

I suggest extracting from this method a method like:
```
public static Type getContainerElementType(Type context, Class<?> contextRawType, Class<?> containerSupertype) {
  Type containerType = getSupertype(context, contextRawType, containerSupertype);

  if (containerType instanceof WildcardType) {
    containerType = ((WildcardType) containerType).getUpperBounds()[0];
  }
  if (containerType instanceof ParameterizedType) {
    return ((ParameterizedType) containerType).getActualTypeArguments()[0];
  }
  return Object.class;
}
```
and rewrite `getCollectionElementType` as:
```
public static Type getCollectionElementType(Type context, Class<?> contextRawType) {
  return getContainerElementType(context, contextRawType, Collection.class);
}
```

PS. I came upon this issue when trying to implement a `TypeAdapterFactory` for `Stream`s - see https://stackoverflow.com/questions/50881488/is-it-possible-to-pass-a-java-util-stream-to-gson/50895699#50895699

**Comment by JakeWharton** [comment]
This method isn't for public use though.

**Comment by tlinkowski** [comment]
I understand - the package with the "internal" keyword (`com.google.gson.internal`) and the class name with dollar signs (`$Gson$Types`) clearly tells it's not an API that you want your users to rely on (or even use at all). I guess that if the library were modularized, this entire package wouldn't be exported.

On the other hand, when you look at #1335, you'll see that it's not possible to implement a reliable generic interface-based `TypeAdapterFactory` without resorting to this class. So maybe you could consider providing this one method (`getContainerElementType`) in a public API?

Or you could simply provide such public method in `$Gson$Types` (as I proposed in this issue) which would mean: "This is internal API. It may change anytime without prior notice. Use at your own risk if you must."

**Comment by inder123** [comment]
@tlinkowski  We don't want you to use an internal class as a binary dependency. Please copy it over and change it to suit your needs.

**Comment by tlinkowski** [comment]
Fair enough.

I wonder, however, what you are going to do about the `Multiset` example in `TypeAdapterFactory`s JavaDoc (#1335) because I cannot see a way to make it work without resorting to `$Gson$Types.getCollectionElementType`.
