### ISSUE TITLE
Java 8 time jsr310 support

### ISSUE THREAD

**Issue by thedarkdestructor** [google/gson#1336]
Gson do **NOT** support jsr310 out of the box. To the best of my knowledge there is no ufficial support for the new Java 8 API.

I am well awere that there are already two similiar tickets (#878 and #739) however they are old and not "really" solved. 

Jackson has its [dedicated serializer and de-serializer](https://github.com/FasterXML/jackson-modules-java8), I know that for Gson we have serveral community-driven projects that do the same (e.g. [this one](https://github.com/gkopff/gson-javatime-serialisers))

**I'm sincerly really frustrated that a library like gson do not have yet an official support for deadling with stardard Java 8 date and time object**s. For me is a key feature: in almost all applications there is the need to deal with a date or a datetime, so I expect the serialzier/deserializers to be there...

Am I missing something here?

**Comment by JakeWharton** [comment]
#739 is still open so you should voice your support there.
