### ISSUE TITLE
Add hierarchy to the RuntimeTypeAdapterFactory

### ISSUE THREAD

**Issue by manfred4** [google/gson#1345]
In the gson extra class **RuntimeTypeAdapterFactory** I want to use a similar behavior to the example above the code, except that I use interfaces with multiple Layers of Hierarchy. This causes in the _create_ method that the raw type does not equal the base type. To fit my need the first line in that method needs to be changed from
`if (type.getRawType() != baseType) {`
to 
`if (!baseType.isAssignableFrom(type.getRawType())) {`.

This can be a new feature of this class, if it is desired to be handled like this.

**Comment by Marcono1234** [comment]
It looks like this was resolved by #2160.
