### ISSUE TITLE
One key to multiple fields

### ISSUE THREAD

**Issue by fcontreras** [google/gson#1347]
First of all, thanks for the awesome job you do. I have a question regarding the following specific situation:

I have a field that comes with a value that I need to split into various fields, a simplistic example below

```
public class User {
    public int userId;
    public String username;
}
```
the json will be something like this

`{ "userinfo": "001:myusername" }`

In this example, I need to take the value, split them and the first will be the "userId" and the second the "username". Any ideas on how to do this? Thanks in advance.

**Comment by JakeWharton** [comment]
This can be achieved using a TypeAdapter through a `@JsonAdapter` annotation on the type.

Since this is a usage question and not a bug or feature request for the library, can you ask on the mailing list or on StackOverflow with the 'gson' tag?

**Comment by fcontreras** [comment]
Will do. Thanks
