### ISSUE TITLE
java.lang.NoClassDefFoundError  in kotlin data class due to gson converter 

### ISSUE THREAD

**Issue by geniushkg** [google/gson#1352]
just assume you have same data class in one file with similar name,
then android runtime throws Noclassdef due to JSON converter factory used in retrofit GSON converter.

I am not sure this is a Correct place to report but, I solved by creating subpackage different file and data class for those items and it worked fine.

**Comment by Marcono1234** [comment]
Are you still experiencing this? If so could you please create a small self-contained example showing this issue?

Note that Gson in general does not support Kotlin very well, maybe it would be worth switching to https://github.com/square/moshi which has in parts a similar API as Gson and has Kotlin support.

**Comment by Marcono1234** [comment]
I am going to close this because no answer has been provided. If you still experience this with the latest Gson version, feel free to comment here again with more details.
