### ISSUE TITLE
Gson Issue

### ISSUE THREAD

**Issue by ZebpayDipen** [google/gson#1354]
Fatal Exception: java.lang.NoSuchMethodError: No direct method <init>(Lcom/google/gson/Gson;)V in class Lcom/google/gson/Gson$1; or its super classes (declaration of 'com.google.gson.Gson$1' appears in /data/app/com.google.android.apps.mtaas.crawler-1/base.apk)
       at com.google.gson.Gson.doubleAdapter(Gson.java:312)
       at com.google.gson.Gson.(Gson.java:241)
       at com.google.gson.Gson.(Gson.java:185)
       at managers.WarningMessageManager.getWarningMessagesList(WarningMessageManager.java:73)
       at zebpay.firebase.WarningMessageListener.onDataChange(WarningMessageListener.java:59)
       at com.google.android.gms.internal.firebase_database.zzfc.zza(Unknown Source)
       at com.google.android.gms.internal.firebase_database.zzgx.zzdr(Unknown Source)
       at com.google.android.gms.internal.firebase_database.zzhd.run(Unknown Source)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5538)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by Iucone** [comment]
The Google pre-launch report reported the exact same exception on the following devices:

Huawei P8 Lite (hwALE-H) - Android 5.0
Huawei Mate 9 (HWMHA) - Android 7.0
Samsing Galaxy S7 Edge (hero2lte) - Android 6.0
Google Pixel (sailfish) - Android 7.1
Google Pixel 2 (walleye) - —
LGE LG G6 (lucye) - Android 7.0
Google Pixel (sailfish) - Android 8.0

I cannot replicate it on the emulators. I use the version 2.8.2.

**Comment by Kyanto86** [comment]
Can confirm. Had the same exact problem just now on the pre-launch report. 
My app just worked fine while testing, so I was shocked that the report had so many crashes.

I also think it's caused by the crawler, even mentions it in the error report.
(declaration of 'com.google.gson.Gson$1' appears in /data/app/com.google.android.apps.mtaas.crawler-1/base.apk)

No idea what that means though.

**Comment by adnanali282** [comment]
I'm also facing the same exact crashes on pre-launch report. I also downgrade my Gson library version from 2.8 to 2.6 but issue remain the same.

Please have any suggestion.

**Comment by jays91** [comment]
Me too. I have upgraded to v2.8.5. But still issue remains. Added code in proguard to keep the gson classes under package: com.google.gson.** . Im using retrofit gson converter too: com.squareup.retrofit2:converter-gson.

**Comment by lavkush-verma** [comment]
I am also facing the same issue.
Play store sending prelaunch report with errors.
Issue: java.lang.NoSuchMethodError: No virtual method a(Ljava/lang/String;Ljava/lang/Class;)Ljava/lang/Object; in class Lcom/google/gson/d; or its super classes (declaration of 'com.google.gson.d' appears in /data/app/com.google.android.apps.mtaas.crawler-1/base.apk)

java.lang.IllegalAccessError: Illegal class access: <my_package>.Network.e' attempting to access 'com.google.gson.d' (declaration of '<my_package>.Network.e' appears in /data/app/<my_package>-1/base.apk)

Any quick work around for this issue.

**Comment by SadMonk** [comment]
Facing the same issue here.
We tried creating a single Gson instance and using this for everything, as the pre-launch videos showed the bot using the app pretty smoothly for some time before anything crashed. So we suspected some kind of memory leak. But the changes didn't have any effect.

**Comment by jongha** [comment]
+1 How can I fix it?

**Comment by GauravCreed** [comment]
Facing same issue for last 3 days
`Crash java.lang.NoSuchMethodError: No direct method <init>(Lcom/google/gson/Gson;)V in class Lcom/google/gson/Gson$1; or its super classes (declaration of 'com.google.gson.Gson$1' appears in /data/app/com.google.android.apps.mtaas.crawler-1/base.apk)`

**Comment by tajchert** [comment]
Same issue here. It also affects "Internal Testing", and can confirm it is related to Google Play testing procedure as we are seeing it only on devices that aren't enrolled to internal channel.

**Comment by afattahi54** [comment]
Using it in a web based application and have this issue version 2.8.2 works fine.

**Comment by Oziomajnr** [comment]
I am having this issue with instrumentation testing locally with my device and also on firebase test lab.

**Comment by marek-vanco** [comment]
I have the same issue _Unresolved reference: Gson_.  I'm using version 2.8.5 by _com.github.kittinunf.fuel:fuel-gson:2.2.0_. How can I bypass this problem? Constructor of Gson is not recongnised.

**Comment by Marcono1234** [comment]
The comments above might be right, this might indeed be a false positive caused by pre-launch. See also [this StackOverflow question](https://stackoverflow.com/q/47099757) where commenters claim that this is a false positive and that there were no issues on the real physical devices. Maybe it would be good if someone created an issue on Google's [issue tracker](https://issuetracker.google.com/issues?q=componentid:192633) (I am not familiar with Android development).

Or has someone experienced the same issue on a real physical device yet?

----

Also note that I am not a maintainer of this project.

**Comment by anonlatte** [comment]
> I have the same issue _Unresolved reference: Gson_. I'm using version 2.8.5 by _com.github.kittinunf.fuel:fuel-gson:2.2.0_. Please, how can I bypass this problem? Constructor of Gson is not recongnised.

The same for `2.8.6` but I'm using Gson by google. Just downgraded to `2.8.5` and everything is resolved. Seems like it doesn't affect on build just an error highlighting.

**Comment by iostyle** [comment]
addConverterFactory(GsonConverterFactory.create())

**Comment by eamonnmcmanus** [comment]
I don't think this is a problem with Gson itself. Probably due to ProGuard? I'm not sure there's anything the project maintainers can do about this.
