### ISSUE TITLE
Overtime issue on handling large streams

### ISSUE THREAD

**Issue by avcial** [google/gson#1357]
I have a dataset that i get it from server via url connection to my  android device. The response body averagely 10Mb and i have to deserialize it to a java class instance. If i use a script like 
`result = new GsonBuilder().create().fromJson(new InputStreamReader(connection.getInputStream(), CharsetNames.Utf8.value), PersonInformationListResponse.class);` the process never continues. I can follow the logs from console there some memory allocations but after couple of them console outputs are ending too.

So as i assumed before using Gson library since my data has no line endings it is hard to read its stream since most of stream readers reads line by line.
I use chunks and then it is ok to get string of body. But after i use same fromJson method with string first argument overload. It takes almost 10 minutes to finish instantiation.

I use your library to avoid large memory allocations but now i can't even get my result.

Is it my way to use deserialization or you didn't consider this large data inputs.

Anyway could you give me a working example to read 10Mb sized imput stream. Thnx.

BTW my target classes are :
```
public class PersonInformationListResponse {
    public int StatusCode;
    public String ResultCode;
    public String ResultMessage;
    public PersonInformation[] PersonInformationList;
}

public class PersonInformation {
    public String ServerId;
    public String Number;
    public String FirstName;
    public String LastName;
    public String Title;
    public String AFiled;
    public String AnotherField;
    public String SearchKey;
}

```

**Comment by lyubomyr-shaydariv** [comment]
Do you really need deserialization to a single object there? Reading JSON in stream manner is better when processing large amount of data.

**Comment by Marcono1234** [comment]
Is this still relevant? If so, as mentioned above do you need all this data in a single object or are you maybe only interested in a subset of the data (for example only the first _X_ `PersonInformationList` entries)?

**Comment by Marcono1234** [comment]
I am going to close this because no answer has been provided. If you still experience this with the latest Gson version, feel free to comment here again with more details.
