### ISSUE TITLE
MapTypeAdapter does not serialize into Date objects

### ISSUE THREAD

**Issue by dev-JE02** [google/gson#1360]
I have a use case where I get the object as  a json string and consecutively needs to transform it into a HashMap<String, Object>. My code is as follows:

```
public Map<String, Object> toMap(String jsonString) {
        Gson gson = new Gson();

        Type type = new TypeToken<Map<String, Object>>() {
        }.getType();
        Map<String, Object> mapped = gson.fromJson(jsonString, type);
        return mapped;
    }
```
The date value I get from jsonString is `"date": "2018-07-29T23:52:35.814Z"` but upon serialization into HashMap, the "date" value is a String and not a Date object. Is there a way around it?

**Comment by JakeWharton** [comment]
How is Gson supposed to know that? Without a proper model with type information all it can do is deserialize to the types that are declared in the JSON which is a string. The fix is to define a proper class with fields and types corresponding to the properties in the JSON.
