### ISSUE TITLE
DeSerializerAdapter lead field missing while serializing

### ISSUE THREAD

**Issue by 82295007** [google/gson#1365]
com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper#write 

 @SuppressWarnings({"rawtypes", "unchecked"})
  @Override
  public void write(JsonWriter out, T value) throws IOException {
   ...
    if (runtimeType != type) {
      TypeAdapter runtimeTypeAdapter = **context.getAdapter(TypeToken.get(runtimeType));**
      if (!(runtimeTypeAdapter instanceof ReflectiveTypeAdapterFactory.Adapter)) {
        // The user registered a type adapter for the runtime type, so we will use that
        chosen = runtimeTypeAdapter;
      } else if (!(delegate instanceof ReflectiveTypeAdapterFactory.Adapter)) {
        // The user registered a type adapter for Base class, so we prefer it over the
        // reflective type adapter for the runtime type
        chosen = delegate;
      } else {
     ...
  }

I created a Gson instance using GsonBuilder which registered a **JsonDeserializer** for  type BaseQuestion. 

And there is a  class **Form**  has a field of List<BaseQuestion>  holding BaseQuestion's instances ( i.g ScoreQuestion extends BaseQuestion ).  

When I trying to serialize **Form** by using gson.toJson(form),  I found that variable delegate was used as variable chosen but it was just a JsonDeserializer. It leads ScoreQuestion declare fields missed.  

Should variable delegate distinguish by read or write operation ? For example , readDelegate ,writeDelegate, not just a TreeTypeAdapter.

**Comment by Marcono1234** [comment]
Does #2032 describe your issue? If not, and this is still relevant, could you please create a small self-contained sample showing this?

**Comment by Marcono1234** [comment]
I am going to close this because no answer has been provided. If you still experience this with the latest Gson version, feel free to comment here again with more details.
