### ISSUE TITLE
Change the obsolete 'compile' to 'implementation'

### ISSUE THREAD

**Issue by knjk04** [google/gson#1372]
In your "[Using Gson with Gradle/Android](https://github.com/google/gson/blob/master/UserGuide.md#using-gson-with-gradleandroid)" section within your user guide, you have ```compile``` instead of ```implementation```. Since this will be removed at the end of 2018, perhaps it will be better to advise programmers to use 'implementation'?

**Comment by NightlyNexus** [comment]
send a PR?

**Comment by knjk04** [comment]
Will do, thanks.
