### ISSUE TITLE
proguard null pointer 

### ISSUE THREAD

**Issue by PascalTang** [google/gson#1384]
hi
I have Crashlytics on my user .
All about NullPointerException with network.

`Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{com.ilulutv.lulu/com.ilulutv.lulu.main.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.ilulutv.lulu.e.a.a.a$a.a()' on a null object reference`

I set my json string to object by gson when volley callback.

Then I cant copy this issue , its not always happen.
I follow the solution from google .
But not work . 
Plz help

<img width="1017" alt="2018-09-13 10 32 45" src="https://user-images.githubusercontent.com/12624322/45495971-feaced00-b7a6-11e8-9f9d-1e6046306f26.png">
<img width="1111" alt="2018-09-13 10 57 48" src="https://user-images.githubusercontent.com/12624322/45496770-cc03f400-b7a8-11e8-82fb-a3110db70a7c.png">
<img width="765" alt="2018-09-13 8 48 18" src="https://user-images.githubusercontent.com/12624322/45495968-fe145680-b7a6-11e8-82b8-074562f177da.png">
<img width="320" alt="2018-09-13 8 48 42" src="https://user-images.githubusercontent.com/12624322/45495969-feaced00-b7a6-11e8-8181-ffe436b68a83.png">
<img width="806" alt="2018-09-13 8 49 04" src="https://user-images.githubusercontent.com/12624322/45495970-feaced00-b7a6-11e8-9ba9-10f96865179b.png">

**Comment by JakeWharton** [comment]
Seems like your JSON contained null and you didn't check for it? Or your serialized name annotation was being removed and so the property wasn't being matched?

In either case, this isn't a problem with Gson itself. If it works with ProGuard disabled then Gson is behaving correctly. You'll have to consult assistance for using the ProGuard tool from its documentation such that you configure it correctly. Code obfuscation is designed to mangle your code so you'll need to figure out how to keep around what Gson requires.
