### ISSUE TITLE
@Transient breaks Kotlin's non-null guarantees

### ISSUE THREAD

**Issue by salamanders** [google/gson#1388]
Annotating a field with `@Transient` correctly skips saving that field to the JSON representation.  

However, when deserializing back to a class, it skips the in-class and in-constructor defaults, leaving the value = null, which breaks Kotlin's promises about not-null values.

I couldn't work around it using `@delegate:Transient val myVal:Double by lazy { 0.0 }` either, it seems to think it is initialized, but to null.  (again, not something that should ever happen in Kotlin)

```
class Temp(@Transient val myVal1:Double = 0.0) {
    @Transient val myVal2:Double = 0.0
}
```
both myVal1 and myVal2 are missing when saved to disk (which is correct) and null when reloaded `GSON.fromJson(it, this::class.java)` (which is unexpected.)

**Expected behavior:** Values are set to their default if they are not included in the deserialized value.

**Comment by JakeWharton** [comment]
This also happens in Java because Gson skips calling the constructor. You need to provide a default constructor either explicitly or in the bytecode with `@JvmOverloads` if you want class initializers to run.

Or, give Moshi and its first-party Kotlin support a try!
