### ISSUE TITLE
Deserialize JSON to nested objects with default values

### ISSUE THREAD

**Issue by kraskkrz** [google/gson#1392]
```
@Getter
@Setter
@NoArgsConstructor
@ToString
public class Destination {
    @Getter
    @Setter
    @NoArgsConstructor
    @ToString
    public class Inner {
        private Integer e1 = 200; 
        private String  e2 = "...";
        private Integer e3 = 500;
    }

    private int p1 = 100;
    private Inner[ ] p2;
}

@Getter
@Setter
@NoArgsConstructor
@ToString
public class Source {
    private int p1;
    private Destination.Inner[ ] p2;
}

public class Main {
   private static final String JSON = "{ `p1`: `100`, `p2`: [ { `e1`:`300` } ] }".replaceAll( "`", "\"" );
   
   public static void main(String...args)  {
        Source source = new GsonBuilder( ).create( ).fromJson( JSON, Source.class );
        System.out.println( source );
    }
}
```
The output is:

`Source(p1=100, p2=[Destination.Inner(e1=300, e2=null, e3=null)]) `

I expected default values for the Inner nested objects, i.e.:

`Source(p1=100, p2=[Destination.Inner(e1=300, e2=..., e3=500)])`

but nested objects don't have them. What is a problem?

**Comment by lyubomyr-shaydariv** [comment]
Once you make the `Inner` class `static`, it will work as you're expecting.

**Comment by kraskkrz** [comment]
I'm aware that Gson works correctly for static nested classes. In my real code it's not possible to convert a non-static inner class to a static nested class.
I also know the following solution (registering a custom InstanceCreator):

```
public class Main {
   private static final String JSON = "{ `p1`: `100`, `p2`: [ { `e1`:`300` } ] }".replaceAll( "`", "\"" );
   
   public static void main(String...args)  {
        Source source = new GsonBuilder()
                .registerTypeAdapter(Destination.Inner.class, (InstanceCreator<Destination.Inner>) (type) -> new Destination().new Inner())
                .create().fromJson(JSON, Source.class);
        System.out.println( source );
    }
}
```


But I wonder if there is a more concise (maybe more elegant) solution to this problem? After all, without the custom InstanceCreator, GSON creates new instances of the Inner class, but doesn't give them default values for fields.

**Comment by lyubomyr-shaydariv** [comment]
@kraskkrz 
I don't think it's possible to find a better way than registering a custom instance creator in your case. The reason of your issue is that Gson omits invoking constructors while instantiating classes that do not have default constructors, with `UnsafeAllocator`. Since the fields default values are assigned in constructors, creating an inner class instance using `UnsafeAllocator` makes the created object unconstructed with the fields left uninitialized. For example, here is an example output for `java -p -c Destination\$Inner.class`:

```
  public i1392.Destination$Inner(i1392.Destination);
    Code:
       0: aload_0
       1: aload_1
       2: putfield      #4                  // Field this$0:Li1392/Destination;
       5: aload_0
       6: invokespecial #5                  // Method java/lang/Object."<init>":()V
       9: aload_0
      10: sipush        200
      13: invokestatic  #6                  // Method java/lang/Integer.valueOf:(I)Ljava/lang/Integer;
      16: putfield      #1                  // Field e1:Ljava/lang/Integer;
      19: aload_0
      20: ldc           #7                  // String ...
      22: putfield      #2                  // Field e2:Ljava/lang/String;
      25: aload_0
      26: sipush        500
      29: invokestatic  #6                  // Method java/lang/Integer.valueOf:(I)Ljava/lang/Integer;
      32: putfield      #3                  // Field e3:Ljava/lang/Integer;
      35: return
```

If inner class implicit constructors would not have the only parameter referencing its enclosed class, Gson would use regular Reflection API `outerClass.newInstance()` therefore all fields would be initialized. So, registering an instance creator is a hint to Gson for a way how an particular instance can be created and properly constructor. I don't think you can make it all more concise, sorry.

**Comment by critterloversrv** [comment]
To all of you that took time and patience I m sorry I'm  just know responding to you .please accept my apology.
But I dont understand how things work on your website. For instance did you make the changes that was requested or do I.
I diffently understand all the string line stuff
The was 2 that said this issue when I tried I cannot do.
All these issues are on zte Grand X4 Z956 Android smartphone.
It was even hard for me to tell which messages where mine.
I'm sorry I wasted your time.
If someone could explain things to me what I'm suppose to or not, explain how to I give up 
I can't any response from what help center
One scan thank you & I'm sorry I wasted your time
Critterloversrv

**Comment by kraskkrz** [comment]
@lyubomyr-shaydariv Thank you for your help. The `UnsafeAllocator `source code explains how Gson works.
