### ISSUE TITLE
Strange issue between release and debug build variants

### ISSUE THREAD

**Issue by nielsnl68** [google/gson#1399]
I just found out that the result is different between my release and debug build's
When i use the debug version all data is loaded properly but when i switch to the release build the data is empty.
---
`public class SearchItem implements Serializable {
    private long   id;
    private String title ="";

    private String url ="";
    private int rating =0;
    private String description ="";
    private String twitter ="";
    private String facebook ="";
    private String other ="";
    private String schedule ="";
    private String genres ="";
    private String banner ="";
    private int active =0;

    public SearchItem() {
    }

    public long getID() {  return id; }
    public String getTitle() {  return title; }
    public int getRating() {  return rating; }
    public String getUrl() {     return url; }
    public String getDescription() {    return description;   }
    public String getTwitter()  {  return twitter; }
    public String getFacebook() {  return facebook; }
    public String getOther()    {    return other;   }
    public String getSchedule() {  return schedule; }
    public String getGenres()   {  return genres; }
    public String getBanner()   {    return banner;   }
    public int getActive()      { return active; }
}
`

`loadjson() {
String response = '[{"id":488,"title":"\"Avibus\"","url":"http:\/\/topwebcomics.com\/twcout\/22197","description":"After bringing home a strange homeless girl named 'Scarlet,' Kelley Russo discovers a fascinating hidden world of cryptids and legends. \r\nBut she is far from welcome.","twitter":"https:\/\/twitter.com\/LotMinx","facebook":"https:\/\/www.facebook.com\/LotMinx\/","other":"http:\/\/avibus.thewebcomic.com","schedule":"Friday","genres":"Adventure, Fantasy","banner":"https:\/\/s3-us-west-2.amazonaws.com\/twc.images\/images\/comicbanner\/22197_468 x 60 banner ad avi 2.jpg","active":"1","rating":"2"},{"id":7282,"title":"\"Curing Cancer\"","url":"http:\/\/topwebcomics.com\/twcout\/15443","description":"A webcomic that does much. Except cure your cancer.","twitter":"","facebook":"","other":"http:\/\/www.curingcancercomics.com","schedule":"","genres":"","banner":"","active":"1","rating":"3"},{"id":8744,"title":"\"HAPPiNESS\"","url":"http:\/\/topwebcomics.com\/twcout\/19216","description":"\"HAPPiNESS\" is a comic about a consumer culture controlled by an artificially intelligent media guide.","twitter":"","facebook":"","other":"http:\/\/heartofevol.com\/happiness.html","schedule":"Wednesday","genres":"Crazy, Sci-Fi, Humor","banner":"https:\/\/s3-us-west-2.amazonaws.com\/twc.images\/images\/comicbanner\/19216_Evol_ad.jpg","active":"1","rating":"2"},{"id":2014,"title":"$5 Fate","url":"http:\/\/topwebcomics.com\/twcout\/4602","description":"All Liam wanted was to be free, but when he let an ancient dragon-slaying sword get stolen, he's cursed to wear the scabbard until the sword is returned to it!","twitter":"","facebook":"","other":"http:\/\/www.drunkduck.com\/Five_Dollar_Fate\/","schedule":"Monday","genres":"Adventure, Fantasy, Drama","banner":"","active":"1","rating":"2"}]';
                            Type listType = new TypeToken<List<SearchItem>>() {}.getType();
                            List<SearchItem> items = new Gson().fromJson(response,  listType);
}`

The list is created with all the SearchItems but the SearchItems objects are empty.

**Comment by JakeWharton** [comment]
This is a build configuration problem and not a problem with Gson, likely as the result of the use of ProGuard. Since it's not a Gson problem, we are not equipped to assist. You'll have better luck on StackOverflow provided you can supply more detail about your build configuration and the tool which is (presumably) obfuscating your code.

**Comment by nielsnl68** [comment]
I'm using the default Android studio settings. So i dont get why this should not be an GSON issue.

**Comment by bynante** [comment]
You can fix this adding a line like this: "-keep class com.example.project.models.device.** { *; }" in proguard-rules file to avoid obfuscation for the field variables and that are sent outside the app via OkHttpClient or similar.
