### ISSUE TITLE
JsonDeserializer API doc example may be incomplete-cannot resolve symbol 'id'

### ISSUE THREAD

**Issue by Padmahas** [google/gson#1425]
Hello,
The example provided in [JsonDeserializer API documentation](http://static.javadoc.io/com.google.code.gson/gson/2.8.5/com/google/gson/JsonDeserializer.html) may be incomplete.

Executing the same program giving out compilation error "cannot resolve symbol 'id'".

Please tell me how to get "Id" class's object and it's value.

Thank you.

**Comment by Marcono1234** [comment]
The example code might also not make much sense. `typeOfT` seems to be the class being deserialized. Because this is an deserializer for `Id` it would therefore always create a `new Id(Id.class, ...)`.

**Comment by deeptimarrivada1** [comment]
I am working on contributing to this bug.

**Comment by Marcono1234** [comment]
Thanks @deeptimarrivada1! Maybe the `IdDeserializer` in that example should have a `Map<Integer, Class<?>>` where it looks up the class for a given ID (or throws an exception if the ID is unknown).

**Comment by deeptimarrivada1** [comment]
@Marcono1234 @Padmahas Please review the changes

**Comment by Padmahas** [comment]
Will check @deeptimarrivada1
