### ISSUE TITLE
toJson() serialize a object of HashMap<String, List<Map.Entry<String, String>>> (android targetSdkVersion 28 and device os 9.0)

### ISSUE THREAD

**Issue by AcHsu104** [google/gson#1426]
library : "com.google.code.gson:gson:2.8.5"   
gradle :   'com.android.tools.build:gradle:3.0.0'

when serialize a object of HashMap<String, List<Map.Entry<String, String>>> 
it working properly on Android 6.0, 7.0 
( ex: {"area":[{"key":"xxxxx,xxxx","value":"xxxxx,xxxxx"}]} )

but only Android 9.0 
it always get null value ( ex : {"area":[{}]} )  

How can I solve it?

**Comment by Marcono1234** [comment]
In case you are still experiencing this with the latest Gson version, can you please provide a small self-contained example showing this issue?

Additionally do you have a custom type adapter registered for `Map.Entry`? If not you might rely on reflection-based serialization for Android SDK classes, which makes you dependent on their implementation details and might explain why this works in one Android version but not in another.

**Comment by Marcono1234** [comment]
I am going to close this because no answer has been provided. If you still experience this with the latest Gson version, feel free to comment here again with more details.
