### ISSUE TITLE
Exception on toJson

### ISSUE THREAD

**Issue by JuanJTorres11** [google/gson#1429]
I'm trying to generate a JSON from an object that represents an undirected Graph, but when I run the program it throws this Exception over and over again until the program stops
`at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:127)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:245)
	at com.google.gson.Gson$FutureTypeAdapter.write(Gson.java:1018)`
The weird thing is that it generates the JSON, the size is 57MB and I don't know if that is normal or if is correct because is too big for reviewing it all.
This is the code that I use to create the JSON
`Gson gson = new GsonBuilder().setPrettyPrinting().create();
			File file = new File ("data/test.json");
			if (!file.exists())
				file.createNewFile();
			FileWriter writer = new FileWriter(file);
			gson.toJson(graph,writer);
			writer.close();`

**Comment by JakeWharton** [comment]
Does the graph contain cycles?

**Comment by JuanWTF** [comment]
It doesn't, this is my implementation, some variable names are in Spanish, but I think it is easy to understand, I use an adjacency list with a hashmap of LinkedList instead of an array because the number of vertexes can vary and I need to save information about the weight of the edges.

`public class Grafo <K extends Comparable <K>, V extends Vertice<A>, A > implements IGrafo<K, V, A>
{
	private int vertices;

	private int arcos;

	HashChain <K,DoublyLinkedList<K,V>>listaAdyacencia;

	public Grafo ()
	{
		vertices = 0;
		arcos = 0;
		listaAdyacencia = new HashChain <K, DoublyLinkedList<K,V>>(80000);
	}
	@Override
	public int V()
	{
		return vertices;
	}

	@Override
	public int E()
	{
		return arcos;
	}

	@Override
	public void addVertex(K idVertex, V infoVertex)
	{
		DoublyLinkedList<K,V> temp = new DoublyLinkedList <K,V>(idVertex, infoVertex);
		listaAdyacencia.put(idVertex, temp);
		vertices++;
	}

	@Override
	public void addEdge(K idVertexIni, K idVertexFin, A infoArc)
	{
		DoublyLinkedList<K,Vertice <A>> temp = (DoublyLinkedList<K, Vertice<A>>) listaAdyacencia.get(idVertexIni);
		temp.add(idVertexFin, new Interseccion<A>((int) idVertexFin,infoArc));
		arcos++;
	}

	@Override
	public V getInfoVertex(K idVertex)
	{
		return listaAdyacencia.get(idVertex).getFirst().darValor();
	}

	@Override
	public void setInfoVertex(K idVertex, V infoVertex)
	{
		listaAdyacencia.get(idVertex).getFirst().cambiarElemento(idVertex, infoVertex);
	}

	@Override
	public A getInfoArc(K idVertexIni, K idVertexFin)
	{
		return listaAdyacencia.get(idVertexIni).get(idVertexFin).darValor().darInformaciónArco();
	}

	@Override
	public void setInfoArc(K idVertexIni, K idVertexFin, A infoArc)
	{
		listaAdyacencia.get(idVertexIni).get(idVertexFin).darValor().cambiarInformacionArco(infoArc);
	}

	@Override
	public Iterator<K> adj(K idVertex)
	{
		return listaAdyacencia.get(idVertex).iteradorK();
	}
}`

**Comment by JakeWharton** [comment]
A doubly-linked list seems like a pretty obvious place where a reference
cycle would exist and cause infinite recursion. Did you register a custom
type adapter for it?

**Comment by JuanWTF** [comment]
Do you mean something like this?
` Type tipoGrafo = new TypeToken<Grafo<Integer, Vertice<Double>, Double>>() {}.getType();` 
Or something for the doubly-linked list, if is the latter, how can I do it?

**Comment by gplayer123** [comment]
Hard level

**Comment by Marcono1234** [comment]
In case this is still relevant, could you please try the latest Gson version and provide a small self-contained code example demonstrating this issue?

**Comment by JuanJTorres11** [comment]
This is no longer relevant, I have lost access to that project and cannot reproduce the error.
