### ISSUE TITLE
Fix tests with java 11

### ISSUE THREAD

**Issue by fridrich** [google/gson#1432]
Java 11 changed the name of UTC timezone for DateTime.FULL in Locale.FRANCE, and thus the tests fail.
This is the fix:
<pre>
--- gson-gson-parent-2.8.5/gson/src/test/java/com/google/gson/DefaultDateTypeAdapterTest.java	2018-11-21 09:00:13.758469543 +0100
+++ gson-gson-parent-2.8.5/gson/src/test/java/com/google/gson/DefaultDateTypeAdapterTest.java	2018-11-21 10:27:42.149213110 +0100
@@ -88,8 +88,9 @@
           new DefaultDateTypeAdapter(DateFormat.MEDIUM, DateFormat.MEDIUM));
       assertParsed(String.format("1 janvier 1970%s00:00:00 UTC", afterYearSep),
           new DefaultDateTypeAdapter(DateFormat.LONG, DateFormat.LONG));
-      assertParsed(JavaVersion.isJava9OrLater() ?
+      assertParsed(JavaVersion.isJava9OrLater() ? (JavaVersion.getMajorJavaVersion() < 11 ?
                       "jeudi 1 janvier 1970 Ã  00:00:00 Coordinated Universal Time" :
+                      "jeudi 1 janvier 1970 Ã  00:00:00 Temps universel coordonnÃ©") :
                       "jeudi 1 janvier 1970 00 h 00 UTC",
           new DefaultDateTypeAdapter(DateFormat.FULL, DateFormat.FULL));
     } finally {
</pre>

**Comment by fridrich** [comment]
Rather:
<pre>
--- gson-gson-parent-2.8.5/gson/src/test/java/com/google/gson/DefaultDateTypeAdapterTest.java	2018-11-21 09:00:13.758469543 +0100
+++ gson-gson-parent-2.8.5/gson/src/test/java/com/google/gson/DefaultDateTypeAdapterTest.java	2018-11-21 10:27:42.149213110 +0100
@@ -88,8 +88,9 @@
           new DefaultDateTypeAdapter(DateFormat.MEDIUM, DateFormat.MEDIUM));
       assertParsed(String.format("1 janvier 1970%s00:00:00 UTC", afterYearSep),
           new DefaultDateTypeAdapter(DateFormat.LONG, DateFormat.LONG));
-      assertParsed(JavaVersion.isJava9OrLater() ?
+      assertParsed(JavaVersion.isJava9OrLater() ? (JavaVersion.getMajorJavaVersion() < 11 ?
                       "jeudi 1 janvier 1970 à 00:00:00 Coordinated Universal Time" :
+                      "jeudi 1 janvier 1970 à 00:00:00 Temps universel coordonné") :
                       "jeudi 1 janvier 1970 00 h 00 UTC",
           new DefaultDateTypeAdapter(DateFormat.FULL, DateFormat.FULL));
     } finally {
</pre>
In a proper UTF-8

**Comment by paulkass** [comment]
Hmm can you considered opening a PR?

**Comment by Marcono1234** [comment]
This can probably be closed now since this was fixed by #1454, right?

**Comment by eamonnmcmanus** [comment]
Yes. What's more our CI [uses Java 11](https://github.com/google/gson/blob/503c20bb392e10fd6ffa9a12afdc33d2ba2d2c38/.github/workflows/build.yml#L15).
