### ISSUE TITLE
Exception on toJson only at Android 8.1

### ISSUE THREAD

**Issue by SangerZhong** [google/gson#1435]
java.lang.IllegalMonitorStateException: unlock of unowned monitor on object of type 'java.lang.StringBuffer' on thread 'Thread[74,tid=3655,Runnable,Thread*=0xcb3b0800,peer=0x13a83f40,"NetworkReport"]'
java.lang.StringBuffer.append(StringBuffer.java:381)
java.io.StringWriter.write(StringWriter.java:77)
com.google.gson.stream.JsonWriter.void beforeName()(SourceFile:614)
com.google.gson.stream.JsonWriter.void writeDeferredName()(SourceFile:401)
com.google.gson.stream.JsonWriter.com.google.gson.stream.JsonWriter value(java.lang.String)(SourceFile:417)
com.google.gson.internal.bind.TypeAdapters$29.void write(com.google.gson.stream.JsonWriter,com.google.gson.JsonElement)(SourceFile:745)
com.google.gson.internal.bind.TypeAdapters$29.void write(com.google.gson.stream.JsonWriter,com.google.gson.JsonElement)(SourceFile:759)
com.google.gson.internal.bind.TypeAdapters$29.void write(com.google.gson.stream.JsonWriter,com.google.gson.JsonElement)(SourceFile:751)
com.google.gson.internal.bind.TypeAdapters$29.void write(com.google.gson.stream.JsonWriter,com.google.gson.JsonElement)(SourceFile:759)
com.google.gson.internal.bind.TypeAdapters$29.void write(com.google.gson.stream.JsonWriter,java.lang.Object)(SourceFile:697)
com.google.gson.internal.Streams.void write(com.google.gson.JsonElement,com.google.gson.stream.JsonWriter)(SourceFile:72)
com.google.gson.Gson.void toJson(com.google.gson.JsonElement,com.google.gson.stream.JsonWriter)(SourceFile:745)
com.google.gson.Gson.void toJson(com.google.gson.JsonElement,java.lang.Appendable)(SourceFile:703)
com.google.gson.Gson.java.lang.String toJson(com.google.gson.JsonElement)(SourceFile:688)

**Comment by lyubomyr-shaydariv** [comment]
I don't think it's Gson-related. What does happen if you write your JSON to a custom writer, preferably `StringWriter`?

**Comment by Marcono1234** [comment]
Closing this because no further information was provided and as mentioned above this is most likely not related to Gson. Gson just uses the standard methods of the provided `Writer`.
