### ISSUE TITLE
Parsing HATEOAS HAL has an issue.

### ISSUE THREAD

**Issue by thinksky-sourcecode** [google/gson#1445]
I am using Swagger CodeGen on rest-assured which is using Gson for deserializing JSON to DTOs, but the Gson has an issue to parse this JSON because of HAL format (_links).

**Comment by JakeWharton** [comment]
You haven't provided any information about what the issue is or how we can reproduce it. Without this there's no action to take as it's not clear whether there's an actual problem or whether the library is just being used incorrectly.
