### ISSUE TITLE
Incredibly HUGE bug

### ISSUE THREAD

**Issue by Ansorre** [google/gson#1460]
Gson version 2.8.5.
I think this is so bad and huge and eloquent that no other comment is necessary than showing the code:

import com.google.gson.Gson;

public class Gson_HUGE_Bug
{
 public String fieldOne;
 public String fieldTwo;

 public static void main(String args[])
 {
  Gson_HUGE_Bug workingOk=new Gson_HUGE_Bug();
  workingOk.fieldOne="ok value one";
  workingOk.fieldTwo="ok value two";
  System.out.println(new Gson().toJson(workingOk));

  Gson_HUGE_Bug notWorkingAtAll=new Gson_HUGE_Bug(){{fieldOne="so bad value one";fieldTwo="so bad value two";}};
  System.out.println(new Gson().toJson(notWorkingAtAll));

  System.out.println(
   "Infact notWorkingAtAll.fieldOne=\""+notWorkingAtAll.fieldOne+
    "\" as well notWorkingAtAll.fieldTwo=\""+notWorkingAtAll.fieldTwo+
    "\" and of course notWorkingAtAll is not null at all!");
 }

 /*
 Expected result:
    {"fieldOne":"ok value one","fieldTwo":"ok value two"}
    {"fieldOne":"so bad value one","fieldTwo":"so bad value two"}
    Infact notWorkingAtAll.fieldOne="so bad value one" as well notWorkingAtAll.fieldTwo="so bad value two" and of course notWorkingAtAll is not null at all!

 What instead it produces:
    {"fieldOne":"ok value one","fieldTwo":"ok value two"}
    null
    Infact notWorkingAtAll.fieldOne="so bad value one" as well notWorkingAtAll.fieldTwo="so bad value two" and of course notWorkingAtAll is not null at all!

  */

}

**Comment by coutPKprintf** [comment]
the gson  ingnore Anonymous Class!
please see
com.google.gson.internal.Excluder

private boolean excludeClassChecks(Class<?> clazz) {
      if (version != Excluder.IGNORE_VERSIONS && !isValidVersion(clazz.getAnnotation(Since.class), clazz.getAnnotation(Until.class))) {
          return true;
      }

      if (!serializeInnerClasses && isInnerClass(clazz)) {
          return true;
      }

      if (isAnonymousOrLocal(clazz)) {
          return true;
      }

      return false;
  }

**Comment by JakeWharton** [comment]
This is working as intended. Gson doesn't support anonymous classes because they cannot be symmetrically deserialized.
