### ISSUE TITLE
java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2 path $

### ISSUE THREAD

**Issue by AysenurGokdemir** [google/gson#1462]
why am I getting this error ? I'm working on it since two days. Please Help Me !

java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 colum 

public interface BorsaApi {
    @GET("json/all_prices.json?=1548332164791")
    Call<List<Example>> getResult();

}

Example.java

public class Example {
    @SerializedName("altin")

    public List<BorsaResult> altin=new ArrayList<>();

    public List<BorsaResult> getAltin() {
        return altin;
    }

    public void setAltin(List<BorsaResult> altin) {
        this.altin = altin;
    }
}

OncekiKapanis.java class

public class OncekiKapanis {
    @SerializedName("alis")

    public String alis;
    @SerializedName("satis")

    public String satis;
    @SerializedName("tarih")

    public String tarih;

    public OncekiKapanis(String alis, String satis, String tarih) {
        this.alis = alis;
        this.satis = satis;
        this.tarih = tarih;
    }

    public String getAlis() {
        return alis;
    }

    public void setAlis(String alis) {
        this.alis = alis;
    }

    public String getSatis() {
        return satis;
    }

    public void setSatis(String satis) {
        this.satis = satis;
    }

    public String getTarih() {
        return tarih;
    }

    public void setTarih(String tarih) {
        this.tarih = tarih;
    }
}
public class BorsaResult{
 @SerializedName("alis")
    public String alis;
    @SerializedName("satis")
    public String satis;
    @SerializedName("tarih")

    public String tarih;
    @SerializedName("onceki_kapanis")

    public List<OncekiKapanis> onceki_kapanis;

    public BorsaResult(String alis, String satis, String tarih,List<OncekiKapanis> onceki_kapanis) {

        this.alis = alis;
        this.satis = satis;
        this.tarih = tarih;
        this.onceki_kapanis = onceki_kapanis;

        /*onceki_kapanis.alis=o_alis;
        onceki_kapanis.satis=o_satis;
        onceki_kapanis.tarih=o_tarih;*/
    }

    public String getAlis() {
        return alis;
    }

    public void setAlis(String alis) {
        this.alis = alis;
    }

    public String getSatis() {
        return satis;
    }

    public void setSatis(String satis) {
        this.satis = satis;
    }

    public String getTarih() {
        return tarih;
    }

    public void setTarih(String tarih) {
        this.tarih = tarih;
    }

    public List<OncekiKapanis> getOnceki_kapanis() {
        return onceki_kapanis;
    }

    public void setOnceki_kapanis(List<OncekiKapanis> onceki_kapanis) {
        this.onceki_kapanis = onceki_kapanis;
    }
}
FragmentResult .java

public class FragmentResult extends Fragment {
    public static final Object TAG="";
    LinearLayoutManager layoutManager;
    List<Example> borsaResultList=new ArrayList<>();

    BorsaAdapter borsaAdapter;
    RecyclerView recyclerView;
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the layout for this fragment
      View view=inflater.inflate(R.layout.fragment_result, container, false);

        recyclerView = view.findViewById(R.id.rv_result);
        layoutManager = new LinearLayoutManager(this.getActivity());

        borsaAdapter = new BorsaAdapter(getActivity(),borsaResultList);

        BorsaApi apiService= ClientApi.getRetrofit().create(BorsaApi.class);
        Call<List<Example>> call=apiService.getResult();
        call.enqueue(new Callback<List<Example>>() {
            @Override
            public void onResponse(Call<List<Example>> call, Response<List<Example>> response) {
                List<Example>models=response.body();
                BorsaAdapter shopAdap = new BorsaAdapter((Example) models, R.layout.fragment_result,getActivity());

                recyclerView.setLayoutManager(layoutManager);
                recyclerView.setHasFixedSize(true);
                recyclerView.setAdapter(shopAdap);

                int x=0;
            }

            @Override
            public void onFailure(Call<List<Example>> call, Throwable t) {
                int x=0;
            }
        });

        return view;
    }}

Adapter class

public class BorsaAdapter extends RecyclerView.Adapter<BorsaAdapter.MyHolder>implements ListAdapter {

    private Context context;
    public List<Example> borsa_result=new ArrayList<Example>();

    public BorsaAdapter(Context context, List<Example> borsa_result) {
        this.context = context;
        this.borsa_result=borsa_result;

    }
    public BorsaAdapter(Example models, int fragment_result, FragmentActivity activity) {
        this.borsa_result= (List<Example>) models;
    }

    @NonNull
    @Override
    public BorsaAdapter.MyHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
        View view= LayoutInflater.from(parent.getContext()).inflate(R.layout.result_recyclerview_items,null,false);
        view.setLayoutParams(new RecyclerView.LayoutParams(RecyclerView.LayoutParams.MATCH_PARENT,RecyclerView.LayoutParams.WRAP_CONTENT));
        MyHolder myHolder=new MyHolder(view);
        return myHolder;
    }

    @Override
    public void onBindViewHolder(@NonNull BorsaAdapter.MyHolder holder, int position) {
                holder.onceki_kapanis_tarih.setText((CharSequence) borsa_result.get(position).getAltin());
    }
    public static  class  MyHolder extends  RecyclerView.ViewHolder{
        TextView tv_altin,alis,satis,tarih,onceki_kapanis,onceki_kapanis_alis,onceki_kapanis_satis,onceki_kapanis_tarih;

        public MyHolder(View itemView) {
            super(itemView);
            tv_altin=itemView.findViewById(R.id.altin);
            alis=itemView.findViewById(R.id.alis);
            satis=itemView.findViewById(R.id.satis);
            tarih=itemView.findViewById(R.id.tarih);
            onceki_kapanis=itemView.findViewById(R.id.onceki_kapanis);
            onceki_kapanis_alis=itemView.findViewById(R.id.onceki_kapanis_alis);
            onceki_kapanis_satis=itemView.findViewById(R.id.onceki_kapanis_satis);
            onceki_kapanis_tarih=itemView.findViewById(R.id.onceki_kapanis_tarih);

        }
    }

**Comment by JakeWharton** [comment]
Your JSON does not match the model you asked Gson to bind. This is fairly common and is a usage question which has been written about a lot on blogs, mailing lists, and StackOverflow. I would suggest you consult StackOverflow questions of similar nature.

**Comment by AysenurGokdemir** [comment]
Thank you for answer.
problem is resolved .

**Comment by QuangRunin** [comment]
You have solved the problem, I need help

**Comment by yunusbedir** [comment]
how did you solve the problem?

**Comment by AysenurGokdemir** [comment]
> problem





 I was explained in my website.
http://aysenurgokdemir.com/2020/03/16/solution-of-the-java-lang-illegalstate-exception/

**Comment by yunusbedir** [comment]
thank you

**Comment by AysenurGokdemir** [comment]
Did this blog post solve the you are problem ?

**Comment by monikakambojofficial96** [comment]
> Thank you for answer.
> problem is solved .

how you can solve your problem?
please answer me because i have a same problem.

**Comment by AysenurGokdemir** [comment]
I was explained in my website.
http://aysenurgokdemir.com/2020/03/16/solution-of-the-java-lang-illegalstate-exception/

**Comment by aerhakim** [comment]
> > problem
> 
> I was explained in my website. http://aysenurgokdemir.com/2020/03/16/solution-of-the-java-lang-illegalstate-exception/

thanks
