### ISSUE TITLE
Issue with toGson method

### ISSUE THREAD

**Issue by vineelya** [google/gson#1467]
Apparently when we try to convert a Java object to String(JSONified) and try to save it to a file using toGson(obj, writer) , this methods seems asynchronous . But it is not clearly mentioned in the documentation like that.  I ended up in a race condition because of that and lost my sleep 👎 to find out the race condition is because of this being asynchronous and the documentation not being clear about it.

**Comment by JakeWharton** [comment]
What led you to believe is was asynchronous? It doesn't accept an `Executor` and/or return a `Future`. How would it report errors? Where would it run?

**Comment by lyubomyr-shaydariv** [comment]
The code from the [original question at S.O.](https://stackoverflow.com/questions/54558027/does-google-gson-perform-serialization-synchronously):

```java
Gson gson = new GsonBuilder().setPrettyPrinting().create();
String statusStringified = gson.toJson(result);

writer = new BufferedWriter(new FileWriter(filePath));
writer.write(statusStringified);
```

> Apparently when we try to convert a Java object to String(JSONified) and try to save it to a file using toGson(obj, writer) , this methods seems asynchronous.

(at S.O.)
>  File persistence is happening a split second after the response is returned.

Do you `flush`/`close` your `writer`?

**Comment by vineelya** [comment]
Thanks for referring my question from SO.

Yes I m closing the filewriter ( and not flushing it though )

Regards
Vineel

**Comment by lyubomyr-shaydariv** [comment]
@vineelya 
It's a bit strange then. According to your code, you're generating a _complete_ JSON string for your `result`, and the string (and the JSON it holds) is fully stored in memory. There are no I/O operations related to the `toJson` method in your code, so I believe this is not a Gson issue.

**Comment by Marcono1234** [comment]
Are you still affected by this issue? If so please try the latest Gson version and provide a small self-contained code example showing this issue.

**Comment by Marcono1234** [comment]
I am going to close this because no answer has been provided. If you still experience this with the latest Gson version, feel free to comment here again with more details.
