### ISSUE TITLE
Third level Object crash with "NullPointerException" only on Release build

### ISSUE THREAD

**Issue by Raylis** [google/gson#1470]
After latest androidx updates and with new obfuscation systems my app is crashing when compiled in release mode.
I handle an object which contains a second one which contains a third one. Compiling in debug mode GSon is able to parse all three levels correctly, but in release mode the third level object can't be parsed and is left to null, under Crashalytics reports I can see it except with "NullPointerException" in any point where is called.
This happens only in relase mode and only when minifyEnabled = true. If MinifyEnabled is set to false, all works good.

**Comment by JakeWharton** [comment]
If it works when the minification tool is disabled then that indicates a problem with that tool and it's configuration and not this library.

**Comment by Marcono1234** [comment]
As mentioned above, this is most likely a configuration issue with ProGuard / R8; please have a look at the [`android-proguard-example`](https://github.com/google/gson/tree/master/examples/android-proguard-example).
