### ISSUE TITLE
Gson Nested classes are null while using proguard

### ISSUE THREAD

**Issue by kksingla** [google/gson#1476]
Warning: class 'com.google.gson.internal.bind.ReflectiveTypeAdapterFactory' is calling Class.getDeclaredFields on class.

After enabling proguard found some issues mentioned below:
1. Nested static classes are null.
2. List of a custom object in a class is null

**Comment by JakeWharton** [comment]
What is Gson supposed to do here? This sounds like you've failed to configure ProGuard correctly for use of Gson.
