### ISSUE TITLE
java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 2 path $

### ISSUE THREAD

**Issue by NodeGIS** [google/gson#1477]
code is:
`
 String userInfoStr = new Gson().fromJson("{\"name\":\"admin\"}", String.class);
`

**Comment by JakeWharton** [comment]
This is not a bug in the library. Your JSON contains an object but you asked it to deserialize as a string. There are many questions on StackOverflow which explain this error. I would also recommend going through the Gson documentation about binding to objects which talks about how you create objects which represent JSON.
