### ISSUE TITLE
Failed to invoke public com.amazonaws.services.s3.model.lifecycle.LifecycleFilterPredicate() with no args

### ISSUE THREAD

**Issue by dharmeshmehta** [google/gson#1478]
I am trying to apply Lifecycle Configurations on S3 bucket. Trying to apply using following JSON:

	[{
	"id": "tmpdelete",
	"status": "Enabled",
	"filter": {
		"predicate": {
			"prefix": "tmp"
		}
	},
	"transitions": [{
		"days": "1",
		"storageClass": "GLACIER"
	}],
	"noncurrentVersionTransitions": [{
		"days": "1",
		"storageClass": "GLACIER"
	}],
	"expirationInDays": "2",
	"noncurrentVersionExpirationInDays": "2",
	"expiredObjectDeleteMarker": "true"
	}]

When i am trying to map it with Rule[].class it is not working. I am using following code:

    String json = above_json;
    Rule[] rules = null;

    Gson gson = new GsonBuilder().serializeNulls().excludeFieldsWithModifiers(Modifier.FINAL,
				Modifier.TRANSIENT, Modifier.STATIC, Modifier.ABSTRACT).create();
    rules = gson.fromJson(json, Rule[].class);

    try {

        amazonS3.setBucketLifecycleConfiguration(bucketName, new BucketLifecycleConfiguration().withRules(rules));
    } catch (Exception e) {
        throw e;
    }

LifecycleFilterPredicate is an abstract class which implements Serializable and it doesn't have no-args contructor

How to solve this problem.?

**Comment by JakeWharton** [comment]
You need to write an instance creator which knows how to create instances of this abstract class: https://github.com/google/gson/blob/master/UserGuide.md#writing-an-instance-creator

**Comment by dharmeshmehta** [comment]
I tried following: 
               String json = "[{\"id\":\"tmpdelete\",\"status\":\"Enabled\",\"filter\":{\"predicate\":{\"prefix\":\"tmp\"}},\"transitions\":[{\"days\":\"1\",\"storageClass\":\"GLACIER\"}],\"noncurrentVersionTransitions\":[{\"days\":\"1\",\"storageClass\":\"GLACIER\"}],\"expirationInDays\":\"2\",\"noncurrentVersionExpirationInDays\": \"2\",\"expiredObjectDeleteMarker\":\"true\"}]";
                Rule[] rules = null;
		Gson gson = new GsonBuilder().serializeNulls().registerTypeAdapter(Rule[].class, new RuleInstanceCreator())
				.excludeFieldsWithModifiers(Modifier.FINAL, Modifier.TRANSIENT, Modifier.STATIC, Modifier.ABSTRACT)
				.create();

		rules = gson.fromJson(json, Rule[].class);


And My InstanceCreator

public class RuleInstanceCreator implements InstanceCreator<LifecycleFilterPredicate> {

	@Override
	public LifecycleFilterPredicate createInstance(Type type) {

		return new LifecycleFilterPredicate() {

			private static final long serialVersionUID = 1L;

			@Override
			public void accept(LifecyclePredicateVisitor lifecyclePredicateVisitor) {

				try {
					getClass().newInstance();
				} catch (InstantiationException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (IllegalAccessException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}

		};
	}

}

It throws Failed to invoke public com.amazonaws.services.s3.model.lifecycle.LifecycleFilterPredicate() with no args. Caused by: java.lang.InstantiationException

**Comment by dharmeshmehta** [comment]
I got the solution I was pointing to parent class i should have point the class which doesn't have no-arg. Only change is Gson gson = new GsonBuilder().registerTypeAdapter(LifecycleFilterPredicate.class, new RuleInstanceCreator()).create();

**Comment by dharmeshmehta** [comment]
Found solution of that too. Used TypeAdapter instead of InstanceCreator
