### ISSUE TITLE
Returning null arrays when use toJson parsing arraylist

### ISSUE THREAD

**Issue by adrisonjrgomez** [google/gson#1483]
hellow igotsome trouble trying to parse a list to json returnig null element

**Comment by Ad0197** [comment]
the problem is the following
`list = db.mostrar() //returning a object collection with 2 object
`return new Gson().toJson(list); //returning [null],[null]`

**Comment by JakeWharton** [comment]
Please provide a failing test case that demonstrates the beahvior.

**Comment by Marcono1234** [comment]
I am going to close this because no answer has been provided. If you still experience this with the latest Gson version, feel free to comment here again with more details.
