### ISSUE TITLE
JsonObject/JsonArray not extendable

### ISSUE THREAD

**Issue by jredfox** [google/gson#1485]
I wanted to expand the library and add more features via my own code like java libraries are suppose to do. I wanted the ability to have methods called add that are overloaded for various objects and convert them to string if not valid before entering them.

I also had reason to add more utility methods like add a static array > converts to json array then puts it into the json object/array many other utilities I had written for another json library but, wanted to use this one as the others appear to be broken.

Cannot do this as the classes are all freaken final. Undo the final on these objects as people want to expand upon them. I realize this would include on adding the ability to change the json classes in the gjson builder for json obj and json arrays.

**Comment by JakeWharton** [comment]
These are value types. There's no reason to extend them with inheritance. You can use composition to mix in behavior and/or use a language like Kotlin which allows defining extension methods on types you don't control.

**Comment by jredfox** [comment]
Right and some people want to extend this behavior and add their own logic there are lots of reasons to extend class lookup object orientation. Using a wrapper would create a weird json as you also don't have control now what said json looks like this is now unacceptiable behavior.

**Comment by JakeWharton** [comment]
Inheritance isn't a good way to accomplish this. You don't extend String
when you want to add functionality around something represented as a
string. You encapsulate and expose a semantic API because it composes.

**Comment by jredfox** [comment]
When you use composition as a wrapper class at least you have control over what the string now looks like. With your gson system there is no no way of controlling what the json string looks like besides using gson.toJSon(wrapperObject())

**Comment by JakeWharton** [comment]
If you want to control the JSON representation you should use a normal
object with fields and annotate it with @JsonAdapter pointing at a
TypeAdapter, TypeAdapter.Factory, or JsonSerializer

**Comment by jredfox** [comment]
how about a pr directly to the json object that adds lazy methods for modern versions? And for minecraft and older gson versions I simply do what you said above?

 I will have to look into controlling the output of said json as gson is the only thing that seems to work out there fully with pretty print and parsing.

Thank you you have been helpful.

**Comment by JakeWharton** [comment]
Possibly. You haven't explained what's missing in any detail yet.
