### ISSUE TITLE
Java 11 LocalDateTime problem

### ISSUE THREAD

**Issue by colesico** [google/gson#1507]
When deserialize an object with LocalDateTime field an error occurring:

InaccessibleObjectException: Unable to make field private final java.time.LocalDate java.time.LocalDateTime.date accessible: module java.base does not "opens java.time" to module gson
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.time.LocalDate java.time.LocalDateTime.date accessible: module java.base does not "opens java.time" to module gson

**Comment by colesico** [comment]
I fix this with custom converter. Close pls.

**Comment by aakiohri** [comment]
> I fixed this with custom converter. Close pls.

Can you provide the custom code implementation ?

**Comment by colesico** [comment]
> > I fixed this with custom converter. Close pls.
> 
> Can you provide the custom code implementation ?

here is package with code

https://github.com/colesico/colesico-framework/tree/master/modules/colesico-restlet/src/main/java/colesico/framework/restlet/internal/gsonconv

custom handler is registered in GsonConverter.java

**Comment by ifeLawal** [comment]
For anyone else landing on this who might be using ObjectMapper or Jackson to try and deserialize their class / object that has a LocalDateTime.

You can also resolve this by having

```xml
// pom.xml file
<dependency>
    <groupId>com.fasterxml.jackson.datatype</groupId>
    <artifactId>jackson-datatype-jsr310</artifactId>
    <version>2.11.0</version>
</dependency>
```

```java
// Java file
// The import below comes from the jackson-datatype-jsr310 dependency 
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;

ObjectMapper objectMapper = new ObjectMapper();
objectMapper.registerModule(new JavaTimeModule());
// Then read or write the object or class with the LocalDateTime
``` 

You can read more about this at the baeldun article detailing jackson serialization: https://www.baeldung.com/jackson-serialize-dates#142-serialization-to-single-date-object

**Comment by MarkRx** [comment]
The out-of-the-box gson library should default to being able to handle this class since it is from vanilla Java
