### ISSUE TITLE
&mid replace with |

### ISSUE THREAD

**Issue by iBotasky** [google/gson#1517]
@admtnnr 
Hello,
I got an issue that gson parse a json and there has a http address string,
and the http address contains `&mid`, and the parsed result replace `&mid`with `|`.
How can I avoid this?
And I didn't call the `disableHtmlEscaping()` method;

**Comment by Marcono1234** [comment]
In case this is still relevant, could you please test this with the latest Gson version and provide a complete code example showing this issue?

**Comment by Marcono1234** [comment]
I am going to close this because no answer has been provided. If you still experience this with the latest Gson version, feel free to comment here again with more details.
