### ISSUE TITLE
Update https://google.github.io/gson/apidocs/ or take it down

### ISSUE THREAD

**Issue by Marcono1234** [google/gson#1520]
The documentation on https://google.github.io/gson/apidocs/ appears to be outdated (is for 2.6.2 while the current version is 2.8.5). It appears the doc is now hosted on http://www.javadoc.io/doc/com.google.code.gson/gson.

Could you therefore please either update the docs on https://google.github.io/gson/apidocs/, or take it down and remove the links to it from https://github.com/google/gson/blob/master/UserGuide.md

Otherwise it might be confusing for new users.

**Comment by inder123** [comment]
Deleted gh-pages branch to stop publishing github.io javadocs
