### ISSUE TITLE
Kotlin inline classes not correctly serialised in HashMap

### ISSUE THREAD

**Issue by geertberkers** [google/gson#1524]
I am using the following code:

    inline class Identifier(val value: String)

    data class FormInstance(
        var formId: Identifier,
        var createdAt: Date = Date(),
        var modifiedAt: Date = Date(),
        var fieldValues: HashMap<Identifier, String> = hashMapOf()
    )

And the result is serialized as:

    {
        "formId": "ADDISON_DIARY",
        "modifiedAt": "2019-05-01T23:44:22.703+0200"
        "createdAt": "2019-04-30T23:44:22.701+0200",
        "fieldValues": {
          "Identifier(value\u003dfrustration)": "VERYMUCH",
          "Identifier(value\u003dstress)": "NONE",
          "Identifier(value\u003dlimitations)": "ALITTLE",
          "Identifier(value\u003dsleep)": "ALOT",
          "Identifier(value\u003dnegative_effect_partner)": "ALITTLE",
          "Identifier(value\u003dsomber_feelings)": "VERYLITTLE",
    }

So the problem is that the Identifier gets it value when its parsed itself, but when parsing the hashmap, it uses the following code: (screenshot line 207)
<img width="993" alt="Screenshot 2019-05-01 23 48 31" src="https://user-images.githubusercontent.com/8653723/57044698-afe79100-6c6b-11e9-91f5-7f9bef469449.png">

I think the code needs to check for inline classes if this is possible, because these are experimental in kotlin 1.3, and the library is written in java.

**Comment by lyubomyr-shaydariv** [comment]
I don't believe Gson should support Kotlin or its experimental features. It's _probably_ a design problem that the `Map` type adapter uses static `String.valueOf` instead of a key-to-string strategy (and not rejecting non-String-keyed maps), but I would consider implementing a `FormInstance` to `FormInstanceDto` (having a map with true `String` keys, not inline classes) converter and vice versa.

**Comment by JakeWharton** [comment]
You can write a TypeAdapter which unwraps the class yourself or just override `toString()` and write out the wrapped property value. Gson won't be seeing updates for Kotlin.

**Comment by Marcono1234** [comment]
Relates to #1722
