### ISSUE TITLE
Convert key value to lowercase

### ISSUE THREAD

**Issue by lucalves** [google/gson#1533]
Hello sirs,

I have a problem with convert json key value to lowercase, using gson. I have this json:

`{"CODIBEG":2704302,"CODESTADO":27,"CEP":"57072","LOGRADOURO":"Rua E","COMPLEMENTO":"(Cj Eustáquio Gomes)","BAIRRO":"Eslovênia","CIDADE":"Barreiras","ESTADO":"AL"};`

Using gson, how I convert this key's (ex, to: codibge, codestado, cep, logradouro)?

I develop to Android, using Java.

**Comment by guptaaditya13** [comment]
using annotations?

**Comment by lucalves** [comment]
I have solved the problem using the RetroFit library. Thanks! @guptaaditya13
