### ISSUE TITLE
gson doesn't parse when upload on play store 

### ISSUE THREAD

**Issue by Kernelzero** [google/gson#1541]
hi

I was test it on debug mode. that's no problems.
but gson doesn't work when upload on play store.

so, I did change gradle setting for disable to minifyEnabled false
and upload on play store again. then gson does work well~

but I aleady set proguard-rules.pro file to manual
what is the problem?

my gson version is 'com.google.code.gson:gson:2.8.1'
and tested lastest version 2.8.5
I think version is not influence this issue.

**Comment by Kernelzero** [comment]
I have known why this.
java bean class must be except obfuscation by proguard.
add your bean class where proguard-rules.

**Comment by Marcono1234** [comment]
Sounds like you was able to solve this problem, so I will close this issue. Also note that Gson provides [ProGuard configuration examples](https://github.com/google/gson/tree/master/examples/android-proguard-example).
