### ISSUE TITLE
Constructors called fromJson?

### ISSUE THREAD

**Issue by Perzan** [google/gson#1543]
How do I find out which constructors _**will**_ get invoked _**before**_ I call fromJson?

**Comment by mjd0** [comment]
get

**Comment by Marcono1234** [comment]
Gson only calls the no-args constructor, or creates an instance [without calling any constructor at all](https://javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/GsonBuilder.html#disableJdkUnsafe()), unless you have registered an [`InstanceCreator`](https://javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/InstanceCreator.html) or a [`TypeAdapter`](https://javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/TypeAdapter.html) or smilar, or if there is a built-in adapter.

Does this answer your question? If not could you please describe your use case a bit more in detail?

**Comment by Perzan** [comment]
@Marcono1234 Thank you
