### ISSUE TITLE
ReflectiveTypeAdapterFactory Handling numeric errors

### ISSUE THREAD

**Issue by TxcA** [google/gson#1551]
Object :
```
public class BaseResponse<T> implements Serializable {
    public int code;
    public String message;
    public T data;

    public BaseResponse(int code, String message, T data) {
        this.code = code;
        this.message = message;
        this.data = data;
    }
...}
```

Json String:
{"code":0,"message":"Add Success","data":{"date":"2019-07-17 09:24:50"}}

Parsed object:
code=3 (This is wrong and should be resolved to 0)
message=“Add Success”
data...

Debug:
```
@Override void read(JsonReader reader, Object value)
          throws IOException, IllegalAccessException {
        Object fieldValue = typeAdapter.read(reader);  // fieldValue is already 3, but it should be 0
        if (fieldValue != null || !isPrimitive) {
          field.set(value, fieldValue);
        }
      }
```
```
JsonReader.nextInt() ->result=0(succeed)
```

**Fix: Modify BaseResponse the 'code' type in the object to be int->long, then normal~**
I would like to ask the specific reasons for this problem, and how can I avoid similar problems.

![](https://i.loli.net/2019/07/17/5d2ed752664d324365.jpg)
![](https://i.loli.net/2019/07/17/5d2ed794d41f995902.jpg)

**Comment by Marcono1234** [comment]
Do you still experience this problem with the latest Gson version? If so, could you please provide a small self contained code example which demonstrates this issue?

**Comment by Marcono1234** [comment]
I am going to close this because no answer has been provided. If you still experience this with the latest Gson version, feel free to comment here again with more details.
