### ISSUE TITLE
Add R8/Proguard keep-rules to JAR

### ISSUE THREAD

**Issue by justcla** [google/gson#1559]
To help users with code shrinking, it would be useful to add keep-rules to the JAR.

Can you please add reliable keep-rules to the source?
e.g. in src/main/resources/META-INF/proguard/okhttp3.pro

**Comment by 4face-studi0** [comment]
+1

**Comment by Marcono1234** [comment]
This has been implemented by #2397 and will be available in the next (not yet released) Gson version, probably 2.11.0.

However, this will require that you use `@SerializedName` on fields and ideally have a no-args constructor for you class.
