### ISSUE TITLE
Json data parsing

### ISSUE THREAD

**Issue by liuchuanbao** [google/gson#1567]
json data ：For example
{
    "strsdata": "for example",
    "strdata": "",
    "intdata": 10.0,
    "htmldata": "\u003cp\u003e\r\n\t12312：\r\n\u003c/p\u003e\r\n\u003cp\u003e\r\n\t1.12312\r\n\u003c/p\u003e\r\n\u003cp\u003e\r\n\t21231\r\n\u003c/p\u003e\r\n\u003cp\u003e\r\n\t3.adasd。\r\n\u003c/p\u003e"
}
code ：
Example mData = gson.fromJson(gson.toJson(baseEntity.getData()), Example.class); 
 
but I use  mData.getPay_to_address()  == null；

**Comment by KJS1124** [comment]
@liuchuanbao can you provide me you class model? it will help get better idea about the situation.

**Comment by Marcono1234** [comment]
Closing because no further information was provided. In case you still experience this issue with the latest Gson version, please provide a small complete example showing this issue.
