### ISSUE TITLE
解析之后无数据

### ISSUE THREAD

**Issue by taishuhongye** [google/gson#1583]
解析之后实体类有值，但内部数据都是默认值。
json中的一段：
"reward_rank": {
		"reward_count": 3,
		"fans_avatar": ["https:\/\/static.shengri.cn\/uploads\/image\/avatar\/dAvatar21.jpg", "https:\/\/img.shengri.cn\/forum\/2018\/09\/FipSlQSXd2NA0tP4mroB3rvGmWeN.jpg", "https:\/\/img.shengri.cn\/forum\/2018\/09\/FpIrXzWnUDP1XfH9kFfwOlQDqoHS.jpg"],
		"uri": "birthdayplus:\/\/fansrewardlist?intent=%7B%22uid%22%3A23298643%7D"
	}

实体类：
public class RewardRankEntity{

    /**
     * reward_count : 14
     * fans_avatar : ["https://cdn1.shengri.cn/MjMyOTg2NDM/aF8xNTY1OTUyMTQwMjIyXzM0NjU.jpg","https://img.shengri.cn/forum/2018/09/FipSlQSXd2NA0tP4mroB3rvGmWeN.jpg","https://img.shengri.cn/forum/2019/06/FuARznR5MQNeKQavy5Cd2XdP2SUP.jpg"]
     * uri : birthdayplus://fansrewardlist?intent=%7B%22uid%22%3A24462735%7D
     */

    private int reward_count;
    private String uri = "";
    private List<String> fans_avatar = new ArrayList<>();

    public int getReward_count() {
        return reward_count;
    }

    public void setReward_count(int reward_count) {
        this.reward_count = reward_count;
    }

    public String getUri() {
        return uri;
    }

    public void setUri(String uri) {
        this.uri = uri;
    }

    public List<String> getFans_avatar() {
        return fans_avatar;
    }

    public void setFans_avatar(List<String> fans_avatar) {
        this.fans_avatar = fans_avatar;
    }
}

解析代码：
if (o.has("reward_rank")) {
            RewardRankEntity rewardRankEntity = new RewardRankEntity();
            try {
                Gson gson = new Gson().newBuilder().create();
                                rewardRankEntity = gson.fromJson(o.optString("reward_rank"), RewardRankEntity.class);
                if (rewardRankEntity != null) {
                    Log.e("xwq", "profileParser,parsersuccess");
                    Log.e("xwq", "profileParser," + o.optString("reward_rank"));
                    Log.e("xwq", "profileParser," + rewardRankEntity.getReward_count());
                    Log.e("xwq", "profileParser," + rewardRankEntity.getFans_avatar().size());
                    Log.e("xwq", "profileParser," + rewardRankEntity.getUri());
                }else{
                    Log.e("xwq","rewardRankEntity == null");
                }
            } catch (Exception e) {
                Log.e("xwq", "profileParser" + e.toString());
            }
            
            profileEntity.setRewardRankEntity(rewardRankEntity);
        }

打印的日志：
E/xwq: profileParser,parsersuccess
E/xwq: profileParser,{"reward_count":3,"fans_avatar":["https:\/\/static.shengri.cn\/uploads\/image\/avatar\/dAvatar21.jpg","https:\/\/img.shengri.cn\/forum\/2018\/09\/FipSlQSXd2NA0tP4mroB3rvGmWeN.jpg","https:\/\/img.shengri.cn\/forum\/2018\/09\/FpIrXzWnUDP1XfH9kFfwOlQDqoHS.jpg"],"uri":"birthdayplus:\/\/fansrewardlist?intent=%7B%22uid%22%3A23298643%7D"}
E/xwq: profileParser,0
E/xwq: profileParser,0
E/xwq: profileParser,

**Comment by Rocketer2018** [comment]
混淆文件都配置了。之前用2.8.3的时候还是没问题的。升级到2.8.5之后就有问题了。

**Comment by Omega-Ariston** [comment]
解析代码需要修改

写了一个测试方法，是可以解析的
```java
public static void test() {
		JsonObject o = new JsonObject();
		JsonElement value = new JsonParser().parse(
				"{\"reward_count\":3,\"fans_avatar\":[\"https://static.shengri.cn/uploads/image/avatar/dAvatar21.jpg\",\"https://img.shengri.cn/forum/2018/09/FipSlQSXd2NA0tP4mroB3rvGmWeN.jpg\",\"https://img.shengri.cn/forum/2018/09/FpIrXzWnUDP1XfH9kFfwOlQDqoHS.jpg\"],\"uri\":\"birthdayplus://fansrewardlist?intent=%7B%22uid%22%3A23298643%7D\"}");
		o.add("reward_rank", value);
		if (o.has("reward_rank")) {
			RewardRankEntity rewardRankEntity = new RewardRankEntity();
			try {
				Gson gson = new Gson().newBuilder().create();
				rewardRankEntity = gson.fromJson(o.get("reward_rank"), RewardRankEntity.class);
				if (rewardRankEntity != null) {
					System.out.println("profileParser,parsersuccess");
					System.out.println("profileParser," + rewardRankEntity.getReward_count());
					System.out.println("profileParser," + rewardRankEntity.getFans_avatar().size());
					System.out.println("profileParser," + rewardRankEntity.getUri());
					System.out.println("profileParser," + rewardRankEntity.getFans_avatar());
				} else {
					System.out.println("rewardRankEntity == null");
				}
			} catch (Exception e) {
				System.out.println("profileParser" + e.toString());
			}

		}
	}
```
你可以试一下。

**Comment by Marcono1234** [comment]
Are you still experiencing this issue with the latest Gson version? If so could you please provide a small self-contained example showing this issue?
If the machine translation is correct, it sounds like you are talking about (ProGuard?) obfuscation, in that case the [`android-proguard-example`](https://github.com/google/gson/tree/master/examples/android-proguard-example) might be helpful.

**Comment by Marcono1234** [comment]
I am going to close this because no answer has been provided. If you still experience this with the latest Gson version, feel free to comment here again with more details.
