### ISSUE TITLE
2.9.0

### ISSUE THREAD

**Issue by elharo** [google/gson#1588]
Per the semantic versioning spec, the last release should have been 2.9.0 since it added new compatible public API and deprecated a method. This is a minor release, not a patch release.

**Comment by Marcono1234** [comment]
Closing this because there is unfortunately nothing which can be done to fix this now (especially since 2.9.0 has been released as well). #2159 proposes some changes to `ReleaseProcess.md` which explicitly mentions Semantic Versioning.
