### ISSUE TITLE
JsonTreeWriter.put(): IllegalStateException

### ISSUE THREAD

**Issue by cqjason** [google/gson#1592]
After calling JsonTreeWriter.name(null), calling JsonTreeWriter.vule() will cause JsonTreeWriter.put(): IllegalStateException because of internal calling JsonTreeWriter.put(). So why not check if the param of name() is null?  The check is done in super class！

**Comment by fmmmlee** [comment]
Can you provide more detail on how to reproduce the issue?

**Comment by cqjason** [comment]
public void testNullStringNameInSuperClass() throws IOException {
    StringWriter stringWriter = new StringWriter();
    JsonWriter jsonWriter = new JsonWriter(stringWriter);
    jsonWriter.beginObject();
    jsonWriter.name(null);     //throw  java.lang.NullPointerException: name == null
                                           //at com.google.gson.stream.JsonWriter.name(JsonWriter.java:386)
    jsonWriter.value((String) null);
    jsonWriter.endObject();
  }

public void testNullStringName() throws IOException {
    JsonWriter jsonWriter = new JsonTreeWriter();
    jsonWriter.beginObject();
    jsonWriter.name(null);
    jsonWriter.value((String) null);//throw java.lang.IllegalStateException
	//at com.google.gson.internal.bind.JsonTreeWriter.put(JsonTreeWriter.java:89)
	//at com.google.gson.internal.bind.JsonTreeWriter.nullValue(JsonTreeWriter.java:153)
	//at com.google.gson.internal.bind.JsonTreeWriter.value(JsonTreeWriter.java:146)
    jsonWriter.endObject();
  }

       I think it is appropriate behavior that throw NullPointerException when name(null). Because It can help client discover problem early. It has done in super class. But it‘s poor that JsonTreeWriter.name() didn't do it when JsonTreeWriter.name() override it in super class.

**Comment by fmmmlee** [comment]
(Note: your reply has the response in code ticks, while the code is in normal text formatting - it's switched around for some reason)

I'll look more at the relevant areas of the code and most likely make a pull request; I agree that it makes sense for the behavior here to be consistent with the superclass unless there is a demonstrable use case in which the inconsistent behavior is necessary.

**Comment by cqjason** [comment]
It's fine to fix it and it‘s very nice to commit it quickly.  I‘ll close the issue for solving.
