### ISSUE TITLE
V2.8.6  java.lang.RuntimeException

### ISSUE THREAD

**Issue by santa955** [google/gson#1597]
I have using gson in my android application with latest version 2.8.6. but if I config as below:
```
compileOptions {
     sourceCompatibility 1.8 
    targetCompatibility 1.8
 }

```

will get an error :
```
error processing C:\Users\xxx\.gradle\caches\modules-2\files-2.1\com.google.code.gson\gson\2.8.6\9180733b7df8542621dc12e21e87557e8c99b8cb\gson-2.8.6.jar java.lang.RuntimeException
```

![](https://n1image.hjfile.cn/res7/2019/10/23/964d54f4a41b4c4923b28e3ec2ebb57a.png)

But I change to v2.8.5 will work fine.

**Comment by moneeWong** [comment]
me too

**Comment by salonkasoli** [comment]
Any updates?

**Comment by liangxianshen** [comment]
me too

**Comment by mike-clover-com** [comment]
Having an issue as well...

**Comment by AhhhhDong** [comment]
me too，but is working on my another project

**Comment by AhhhhDong** [comment]
classpath 'com.android.tools.build:gradle:3.5.3'，build successful.

**Comment by stopiccot** [comment]
Bumping com.android.tools.build:gradle version fixed issue for me

**Comment by ngocnd0242** [comment]
> classpath 'com.android.tools.build:gradle:3.5.3'，build successful.
It's works fine!

**Comment by Marcono1234** [comment]
Closing this because based on the comments above, it looks like upgrading the Android Gradle Plugin solves this issue.
