### ISSUE TITLE
Not able to use JsonObject as ResponseEntity

### ISSUE THREAD

**Issue by IvanKaloyanov** [google/gson#1598]
I've used ResponseEntity<JsonObject> for one of the endpoints and noticed a strange behavior. Even though the logic was executed properly and no exception occurs, every time I requested the resource I get a status 500 response.

After that, I've created a dummy endpoint for testing and realized that the reason for this 500 result is using JsonObject for the ResponseEntity. 
```
    @GetMapping
    public ResponseEntity<JsonObject> status() {
        JsonObject test = new JsonObject();
        test.addProperty("key","value");
        return ResponseEntity.ok(test);
    }
```

What's the reason for this behavior? The object is not able to be serialized properly or it's something completely different?

P.S. I am using Gson v2.8.5 and Spring Boot v2.1.1

**Comment by lyubomyr-shaydariv** [comment]
Spring Boot must log 5xx errors by default. What exception log entries are you getting + are you using Gson message converter instead of the default one that's built on top of Jackson?

**Comment by IvanKaloyanov** [comment]
Hi, @lyubomyr-shaydariv I am using the standard Gson JsonObject. The interesting part is that I do not see any exception being logged or even thrown and even though I am starting the service on a port and excess it directly referring to the port seems to me that there is some 3rd party involved because I tried it on a completely isolated environment and it was working fine. 

Still the rest of the JSON Libraries I've tried worked fine and even though I've managed to solve it for myself I am really interested in what's actually causing this. I am attaching 3 screenshots with status 200 using a string literal and status 500 using Gson JsonObject.
![1](https://user-images.githubusercontent.com/16307530/67506396-a88ec680-f695-11e9-94f0-f2eb1e0d629f.png)
![2](https://user-images.githubusercontent.com/16307530/67506397-a88ec680-f695-11e9-9c20-aa00398f8b78.png)
![3](https://user-images.githubusercontent.com/16307530/67506398-a88ec680-f695-11e9-850a-7b0d0b0f0305.png)

Any recommendations on how can I troubleshoot it efficiently?

Thanks!

**Comment by lyubomyr-shaydariv** [comment]
@IvanKaloyanov 
No idea, but I guess you have your Spring Boot instance configured improperly missing `GsonHttpMessageConverter` (I meant this class above). As far as I remember how Spring MVC work, its default JSON message converter is Jackson-oriented (instance of `AbstractJackson2HttpMessageConverter`). I don't have a test Spring Boot application right at me, but having the controller method like you mentioned in the screenshot gives HTTP 500 for my Spring MVC-based test I have in my project after adding Gson and the exact controller method. It gets working properly with HTTP 200 by adding `GsonHttpMessageConverter` to the message converters registry in my tests:

```java
final MockMvc mockMvc = MockMvcBuilders
	.standaloneSetup(...)
	.setControllerAdvice(...)
	// default
	.setMessageConverters(new MappingJackson2HttpMessageConverter(objectMapper))
	// new
	.setMessageConverters(new GsonHttpMessageConverter())
	.build();

```

I believe it would work for you once you do the same in your MVC configuration (not mocks in tests like mine):

```java
@Configuration
@EnableWebMvc
public class MvcConfiguration
		extends WebMvcConfigurerAdapter {

	...

	@Override
	public void configureMessageConverters(final List<HttpMessageConverter<?>> converters) {
		...
		converters.add(new GsonHttpMessageConverter());
		...
	}

	...

}
```
