### ISSUE TITLE
Remove oss-parent pom

### ISSUE THREAD

**Issue by elharo** [google/gson#1605]
It's [deprecated](https://github.com/sonatype/oss-parents) and a source of flakes:

[FATAL] Non-resolvable parent POM for com.google.code.gson:gson-parent:2.8.7-SNAPSHOT: Could not transfer artifact org.sonatype.oss:oss-parent:pom:7 from/to google-maven-central (https://maven-central.storage-download.googleapis.com/repos/central/data/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target and 'parent.relativePath' points at wrong local POM @ com.google.code.gson:gson-parent:2.8.7-SNAPSHOT, /home/travis/build/google/gson/pom.xml, line 6, column 11
 @

**Comment by Marcono1234** [comment]
While it is probably a good idea to remove this anyways, the source for the build failure seems to be the usage of OpenJDK 9 with an empty `cacerts`, see #1606
