### ISSUE TITLE
Do JsonObject/Array too hard to implements Serializable ? 

### ISSUE THREAD

**Issue by qaz4042** [google/gson#1624]
I use JsonObject and JsonArray as my entitys's property,and want serialize entitys to cacheManager.
I think it can be inneed a strong demand, using jsonObject/Array as a common object within our Json Features, doesn't it?
And If it can serialize  getter method, gson will be better for user.

**Comment by lyubomyr-shaydariv** [comment]
Does Ehcache support custom serializers?

**Comment by Marcono1234** [comment]
Sounds like a duplicate of #485.
