### ISSUE TITLE
2.8.6 breaks Android Proguard

### ISSUE THREAD

**Issue by skonstant** [google/gson#1630]
In my app, proguarding fails when I use gson 2.8.6, some NullPointerException, without any info, it does not even say it is from gson, but when I downgrade to 2.8.5, it is fine as it has been.

One visible warning is that "module-info.class" appears more than once. I see in some commits that you have added the module-info file in this release.

I found no workaround for proguard.

This is the proguard that is bundled with Android Studio / Android SDK, I don't know which version it is. It is possibly a bug in proguard but despite loading quite a few other libraries, it fails only with gson (I do not know if the other libraries have a module-info file in there).

**Comment by baha2046** [comment]
you need to change your module-info.
for 2.8.5 or before its require gson;
for 2.8.6 its require com.google.gson;

**Comment by Marcono1234** [comment]
Can you please check if this issue still occurs with the latest Gson version? The way the `module-info.class` is included in the Gson JAR was changed and should hopefully now cause fewer issues. Also make sure to use the latest build tools and plugins (e.g. Gradle).

**Comment by Marcono1234** [comment]
I am going to close this because no answer has been provided. If you still experience this in the latest Gson version, feel free to comment here again with more details.
