### ISSUE TITLE
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was END_DOCUMENT at line 1 column 64 path $

### ISSUE THREAD

**Issue by ghost** [google/gson#1633]
i get json data for：{"errno":"200","rst":{"name":"tom","age":"25"},"errmsg":"ok"}
but at GsonResponseBodyConverter 

 public T convert(ResponseBody value) throws IOException {
        String s = value.string();
        Reader reader = new StringReader(s);
        JsonReader jsonReader = gson.newJsonReader(reader);
        jsonReader.setLenient(true);

        try {
            return adapter.read(jsonReader);
        } catch (Exception e) {
            e.printStackTrace();
          //got exception
//com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was END_DOCUMENT at line 1 column 64 path $
            return null;
        } finally {
            value.close();
        }
    }

i check java bean but not found error ,how to fix it ?

**Comment by lyubomyr-shaydariv** [comment]
It has nothing to do with the bean. Is your `s` value really the value you provided? The parsing error tells that it reaches the end of the token stream not encountering `{`, so it is blank (not empty as it reaches position 64).

**Comment by jacome-truelogic** [comment]
Hi , I have the curly braces in my json, and everything looks correct, but it still throws the error 
This is my Json:

{"expiresIn":1200,"tokenType":"Bearer","accessToken":"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6In"}

Thank you in advance for your help.

**Comment by Marcono1234** [comment]
For all these issues, it would be good to create a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

Though in this case here, the author of the issue has deleted their GitHub account, so this can probably be closed.
