### ISSUE TITLE
Android: Gson serialization is missing one specific field

### ISSUE THREAD

**Issue by ghost** [google/gson#1634]
This is the class

```
    class TransactionDetails {
    
        @SerializedName("item")
        private String item;
        @SerializedName("itemPrice")
        private double itemPrice;
        @SerializedName("commissions")
        private double commissions;
        @SerializedName("itemCount")
        private double itemCount;
        @SerializedName("when")
        private long when;
        @SerializedName("tax")
        private double tax;
    
        TransactionDetails(String item, double itemPrice, double commissions, double itemCount, long when, double tax) {
            this.item = item;
            this.itemPrice = itemPrice;
            this.commissions = commissions;
            this.itemCount = itemCount;
            this.when = when;
            this.tax = tax;
        }
    
        String getItem() {
            return item;
        }
    
        double getItemPrice() {
            return itemPrice;
        }
    
        double getCommissions() {
            return commissions;
        }
    
        double getItemCount() {
            return itemCount;
        }
    
        long getWhen() {
            return when;
        }
    
        double getTotalPrice() {
            return itemCount * itemPrice;
        }
    
        String getWhenStr() {
            return Utils.getInstance().getDateStr(when);
        }
        
        double getTax() {
            return tax;
        }
    
    }

```
double getTax() is the only method I don't use in my code because I have no use for it in my app, so I see "method getTax() is never used" though I'm not sure it is related

This is the instance

    ArrayList<TransactionDetails> transactionDetailsFull = new ArrayList<>();

This is the failing code

    new Gson().toJson(Utils.getInstance().transactionDetailsFull);

For some reason, the above code serializing all the fields of the class except for tax. That happens ONLY when in release mode:

    minifyEnabled true
    shrinkResources true
    proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'

In debug mode, it works. Notice that I did @SerializedName so I don't understand what am I missing and what is causing only tax not to be serialized.

**Comment by Amosss** [comment]
This happens with 2.8.5 and 2.8.6 version of com.google.code.gson:gson

**Comment by Amosss** [comment]
Well, apparently this part was wrong: double getTax() is the only method I don't use in my code because I have no use for it in my app, so I see "method getTax() is never used" though I'm not sure it is related. 

I added a reference in my code to getTax() and now Gson serializing it....

A bug? Something I don't understand with how serializing works?

**Comment by ytRino** [comment]
Please check proguard rule. It is not gson's problem.
https://github.com/google/gson/blob/master/examples/android-proguard-example/proguard.cfg#L13-L14

**Comment by Amosss** [comment]
I thought it is proguard but how can you explain that once I added one reference in my code to the only not-used property and then Gson did serialize it?

**Comment by desaibhavesh92** [comment]
> This is the class
> 
> ```
>     class TransactionDetails {
>     
>         @SerializedName("item")
>         private String item;
>         @SerializedName("itemPrice")
>         private double itemPrice;
>         @SerializedName("commissions")
>         private double commissions;
>         @SerializedName("itemCount")
>         private double itemCount;
>         @SerializedName("when")
>         private long when;
>         @SerializedName("tax")
>         private double tax;
>     
>         TransactionDetails(String item, double itemPrice, double commissions, double itemCount, long when, double tax) {
>             this.item = item;
>             this.itemPrice = itemPrice;
>             this.commissions = commissions;
>             this.itemCount = itemCount;
>             this.when = when;
>             this.tax = tax;
>         }
>     
>         String getItem() {
>             return item;
>         }
>     
>         double getItemPrice() {
>             return itemPrice;
>         }
>     
>         double getCommissions() {
>             return commissions;
>         }
>     
>         double getItemCount() {
>             return itemCount;
>         }
>     
>         long getWhen() {
>             return when;
>         }
>     
>         double getTotalPrice() {
>             return itemCount * itemPrice;
>         }
>     
>         String getWhenStr() {
>             return Utils.getInstance().getDateStr(when);
>         }
>         
>         double getTax() {
>             return tax;
>         }
>     
>     }
> ```
> 
> double getTax() is the only method I don't use in my code because I have no use for it in my app, so I see "method getTax() is never used" though I'm not sure it is related
> 
> This is the instance
> 
> ```
> ArrayList<TransactionDetails> transactionDetailsFull = new ArrayList<>();
> ```
> 
> This is the failing code
> 
> ```
> new Gson().toJson(Utils.getInstance().transactionDetailsFull);
> ```
> 
> For some reason, the above code serializing all the fields of the class except for tax. That happens ONLY when in release mode:
> 
> ```
> minifyEnabled true
> shrinkResources true
> proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
> ```
> 
> In debug mode, it works. Notice that I did @SerializedName so I don't understand what am I missing and what is causing only tax not to be serialized.

Same problem i am facing with Kotlin data class.

If we use @Keep annotation then it working fine or need to add all model classes in pro guard rule using keep.

[Same Issue!](https://github.com/google/gson/issues/1632#issue-535573653)

**Comment by Marcono1234** [comment]
Looks like this was answered in https://github.com/google/gson/issues/1634#issuecomment-567771989; additionally the author deleted their GitHub account, so this issue can probably be closed.
