### ISSUE TITLE
2.8.6不能用

### ISSUE THREAD

**Issue by roushanburou** [google/gson#1636]
2.8.6不能用，降一版本就可以，不是，你没用你更新个啥？

**Comment by XieEDeHeiShou** [comment]
请提供可复现问题的样本代码或者样本工程.

**Comment by m30102** [comment]
> 请提供可复现问题的样本代码或者样本工程.

module-info.class文件应该是多余的吧，能删掉上传吗？

**Comment by baha2046** [comment]
module名改了、以前在module-info要require gson; 現在是require com.google.gson;

**Comment by Marcono1234** [comment]
Closing this issue because it appears that the original author did not provide much information about what exactly is not working.
