### ISSUE TITLE
Could not find com.google.code.gson:gson:2.8.5.

### ISSUE THREAD

**Issue by REALalphas** [google/gson#1637]
![image](https://user-images.githubusercontent.com/26285012/71617817-da5c6600-2bcd-11ea-87e7-aee0f74f1822.png)
```
Could not find com.google.code.gson:gson:2.8.5.
Searched in the following locations:
  - https://dl.google.com/dl/android/maven2/com/google/code/gson/gson/2.8.5/gson-2.8.5.pom
  - https://dl.google.com/dl/android/maven2/com/google/code/gson/gson/2.8.5/gson-2.8.5.jar
Required by:
    project : > com.google.gms:google-services:4.3.3

```

**Comment by kiborg** [comment]
Same issue.

**Comment by AdvertiserM** [comment]
Any fixes?

**Comment by quentinthai** [comment]
Hey Guys,

Look at this page : 
[](https://github.com/firebase/quickstart-android/blob/master/messaging/build.gradle)

Copy the blocks "buildscript" and "allprojects" into your build.gradle (complete if already defined).
Try to sync again. It works for me. What's about you ?

**Comment by chukwudidike** [comment]
..thanks

**Comment by tranthanhlam10** [comment]
ok thanks
