### ISSUE TITLE
gson don't support parse Anonymous-Class-Object

### ISSUE THREAD

**Issue by programluo** [google/gson#1639]
if i create a Anonymous-Class object, gson can't parse it, will set null value.
I create object like this way。
```
new List() {
  {
    add(new Filter() {
      {
        setName("");
        setCode("dd")
      }
    });
    add(new Filter() {
      {
        setName("");
        setCode("dd")
      }
    });
  }
}
```

and gson parse like that
```
'filter':[
    	null,
    	null
    ]
```

**Comment by baha2046** [comment]
u should read the front page about how to due with non static inner class

**Comment by programluo** [comment]
i search issue for inner class and find many same issues，and the answer is gson will not support to this, cause by gson design boundary? #298 
there are other issues about serialize anonymous object, and the answers are will not support:
#1510
