### ISSUE TITLE
Android R8 issue with version 2.8.6

### ISSUE THREAD

**Issue by shubhambansal** [google/gson#1641]
I started getting the following error after updating to version 2.8.6.  Until 2.8.5 everything works fine.

```
> Task :app:transformClassesAndResourcesWithR8ForBetaRelease FAILED
R8 is the new Android code shrinker. If you experience any issues, please file a bug at
https://issuetracker.google.com, using 'Shrinker (R8)' as component name. You can
disable R8 by updating gradle.properties with 'android.enableR8=false'.

.../transforms/FirebasePerformancePlugin/beta/release/66/module-info.class:
D8: Unsupported source file type 
```

`gradle.properties configuration`
android.enableR8.fullMode=true

**Comment by elirex** [comment]
I have the same issue when used Android Gradle plugin v3.4.0 and Gradle v5.1.1 to build Apk. My workaround is Android Gradle plugin upgrades to 3.5.3 and Gradle upgrades to v5.5 then succeed to build Apk. But in build log still seen

```
Can't instrument module-info.class
java.lang.RuntimeException
        at org.objectweb.asm.ClassVisitor.visitModule(ClassVisitor.java:148)
        at org.objectweb.asm.ClassReader.readModule(ClassReader.java:731)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:632)
        at com.google.firebase.perf.plugin.instrumentation.Instrument.instrument(Instrument.java:151)
        at com.google.firebase.perf.plugin.instrumentation.Instrument.instrumentClassesInJar(Instrument.java:100)
...
```

**Comment by Marcono1234** [comment]
Can you please check if this issue still occurs with the latest Gson version? The way the `module-info.class` is included in the Gson JAR was changed and should hopefully now cause fewer issues. Also make sure to use the latest build tools and plugins (e.g. Gradle).

**Comment by Marcono1234** [comment]
I am going to close this because no answer has been provided. If you still experience this with the latest Gson version, feel free to comment here again with more details.
