### ISSUE TITLE
System-dependent line separator when generate json

### ISSUE THREAD

**Issue by ALEUT** [google/gson#1645]
Currently `newline` method in `JsonWriter` looks like
```
private void newline() throws IOException {
    if (indent == null) {
      return;
    }

    out.write('\n');
    for (int i = 1, size = stackSize; i < size; i++) {
      out.write(indent);
    }
  }
```

As we can see it just prints \n for new line. As result for Windows we have jsons with LF line ends (UNIX standard) instead of standard CRLF for Windows.

As an option to have `out.write(System.lineSeparator());` (it will have LF for UNIX and CRLF for Windows) or even have an option what to use as separator.

**Comment by inder123** [comment]
The problem with your proposal is that Gson will output different JSON depending on the machine it ran on.  We opted for consistency of the response.

**Comment by ALEUT** [comment]
@inder123 JSON will be the same, just the correct line-endings will be used. Btw, Jackson generated JSON correctly using system-defined line separators.
