### ISSUE TITLE
Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $

### ISSUE THREAD

**Issue by Sandeep485** [google/gson#1652]
Go to Build Option and Clean Project. this error will be resolved

**Comment by Marcono1234** [comment]
In general if you encounter an issue please provide as much information as possible and ideally include a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). The exception message in this issue title indicates that the JSON data does not have the expected format.
