### ISSUE TITLE
The rule '-keep class * implements com.google.gson.TypeAdapter' uses implements but actually matches extends.

### ISSUE THREAD

**Issue by JasonTian23** [google/gson#1658]
“-keep class * implements com.google.gson.TypeAdapter” in examples/android-proguard-example/proguard.cfg is not valid. TypeAdapter is abstract class, not a interface.

Should use: -keep class * extends com.google.gson.TypeAdapter

**Comment by Marcono1234** [comment]
Fixed by  #1693

**Comment by Marcono1234** [comment]
As mentioned above, this has been fixed.
