### ISSUE TITLE
merge method for JsonObject

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gson#166]
```
What about new method(s) merge for JsonObject... it would be something
simmilar to JsonArray.addAll

void    merge(JsonObject value) 
void    merge(Object value) 
```

Original issue reported on code.google.com by `adamchuk` on 20 Oct 2009 at 3:47

**Comment by anshunjain** [comment]
plus one to Sebas' suggestion ! to do a deep copy is non-trivial and more scope for bugs. the strategies suggested could handle this, and one could always plug-in their own strategy
