### ISSUE TITLE
Custom parser is not called in case of undefined field

### ISSUE THREAD

**Issue by fzoli** [google/gson#1662]
First of all here is a sample project with **unit tests**:
https://github.com/fzoli/gson-bugreport

Short description of the bug:
We have a custom data-type. It behaves like an `Optional` wrapper so it is never `null`.
If the JSON does not contain the field, its value should be "empty" so there is no need to check `null`.
We could not solve this with `TypeAdapter`. It works if the field is `null` in the JSON, **but** if the field is `undefined` then `TypeAdapter#read` is not called.

**Comment by lyubomyr-shaydariv** [comment]
Gson does not touch missing values for, I guess, performance reasons and simplicitiy. You can easily implement a post-processing type adapter that would set the unaffected null-fields supposed to be optional to their default values (must precede `ValidatingTypeAdapterFactory` in the `gsonBuilder`):

```java
final class OptionalTypeTypeAdapterFactory
		implements TypeAdapterFactory {

	private static final TypeAdapterFactory instance = new OptionalTypeTypeAdapterFactory();

	private OptionalTypeTypeAdapterFactory() {
	}

	static TypeAdapterFactory get() {
		return instance;
	}

	@Nullable
	@Override
	public <T> TypeAdapter<T> create(final Gson gson, final TypeToken<T> typeToken) {
		final Collection<Field> optionalTypeFields = classesOf(typeToken.getRawType())
				.stream()
				.flatMap(c -> Stream.of(c.getDeclaredFields()))
				.filter(field -> field.getAnnotation(OptionalType.class) != null)
				.peek(field -> field.setAccessible(true))
				.collect(Collectors.toList());
		if ( optionalTypeFields.isEmpty() ) {
			// if the class does not have any OptionalType-annotated fields, delegate it elsewhere
			return null;
		}
		final TypeAdapter<T> delegateTypeAdapter = gson.getDelegateAdapter(this, typeToken);
		return new TypeAdapter<T>() {
			@Override
			public void write(final JsonWriter out, final T value)
					throws IOException {
				delegateTypeAdapter.write(out, value);
			}

			@Override
			public T read(final JsonReader in)
					throws IOException {
				final T read = delegateTypeAdapter.read(in);
				normalizeAbsents(read, optionalTypeFields);
				return read;
			}
		};
	}

	private static Collection<Class<?>> classesOf(final Class<?> clazz) {
		final List<Class<?>> classes = new ArrayList<>();
		for ( Class<?> c = clazz; c != null && c != Object.class; c = c.getSuperclass() ) {
			classes.add(0, c);
		}
		return classes;
	}

	private static void normalizeAbsents(final Object o, final Iterable<Field> optionalTypeFields) {
		for ( final Field field : optionalTypeFields ) {
			try {
				final Object fieldValue = field.get(o);
				if ( fieldValue == null ) {
					final Class<?> fieldType = field.getType();
					final Object absent;
					// Maintain the supported classes somehow...
					if ( fieldType == PhoneNumber.class ) {
						absent = PhoneNumber.absent();
					} else {
						throw new UnsupportedOperationException("Cannot normalize " + fieldType);
					}
					field.set(o, absent);
				}
			} catch ( final IllegalAccessException ex ) {
				throw new RuntimeException(ex);
			}
		}
	}

}
```

P.S. Gson has a special "extra" code to implement common tasks, but these are not the core Gson: https://github.com/google/gson/tree/master/extras/src/main/java/com/google/gson/interceptors
P.P.S. Well-designed sample project!

**Comment by fzoli** [comment]
Thanks for the working solution :-)

Here is my solution based on the code snippet:
https://github.com/fzoli/gson-bugreport/tree/0149a48a6e75d766e7021d044e73f538a6fe1887

I implemented a simple `PhoneNumberTypeAdapter` so it can handle the `present` and `null` cases.
`DefaultValueFactoryContainer` holds a strategy to create an empty `PhoneNumber` and `OptionalTypeTypeAdapterFactory` uses that immutable container.

I accept that Gson does not touch missing values so I close the issue.
