### ISSUE TITLE
How to serialize an object to a list of one elements with gson

### ISSUE THREAD

**Issue by bestbugwriter** [google/gson#1663]
I have some json string like this:
example1
`{
  "path":{
    "start":"abc"
  },
  "name":"Fork1"
}`

example2
`{
  "path":[{
    "start":"abc"
  },
  {
    "start":"def"
  }],
  "name":"Fork1"
}`

and I want to serialize with **one** JAVA object like this:

    @Data
    public static class ForkNode {
        private List<Path> path;
        private String name;
    }

    @Data
    public static class Path {
        private String start;
    }
    new Gson().fromJson(jsonStr, ForkNode.class)

but it will throw an exception 
`IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 2 column 11 path $.path`

So how do I treat the first example as a list of one elements? 
Or is there any way I can serialize two different types of json strings with one object?

**Comment by Coney484** [comment]
I don't think it is a good way to serialize two different types of json strings with ONE object.

For example 1, the Object should be like this:

@Data
public static class ForkNode {
    // only one path 
    private Path path;
    private String name;
}

@Data
public static class Path {
    private String start;
}
new Gson().fromJson(jsonStr, ForkNode.class)
While For example 2, the Object should be like this:

@Data
public static class ForkNode {
    // several paths 
    private List<Path> path;
    private String name;
}

@Data
public static class Path {
    private String start;
}
new Gson().fromJson(jsonStr, ForkNode.class)
In JSON:

Objects are enclosed directly in curly brackets {} While JSON
Arrays that are enclosed in square brackets [] inside JSON Objects.
One more thing, If you do really want to do that, I think you need to implement a custom deserializer by yourself. Please ref the doc of Gson.

**Comment by bug-author** [comment]
> I don't think it is a good way to serialize two different types of json strings with ONE object.
> 
> For example 1, the Object should be like this:
> 
> @DaTa
> public static class ForkNode {
> // only one path
> private Path path;
> private String name;
> }
> 
> @DaTa
> public static class Path {
> private String start;
> }
> new Gson().fromJson(jsonStr, ForkNode.class)
> While For example 2, the Object should be like this:
> 
> @DaTa
> public static class ForkNode {
> // several paths
> private List path;
> private String name;
> }
> 
> @DaTa
> public static class Path {
> private String start;
> }
> new Gson().fromJson(jsonStr, ForkNode.class)
> In JSON:
> 
> Objects are enclosed directly in curly brackets {} While JSON
> Arrays that are enclosed in square brackets [] inside JSON Objects.
> One more thing, If you do really want to do that, I think you need to implement a custom deserializer by yourself. Please ref the doc of Gson.

Why are your answers the same? Are you the same person?
https://stackoverflow.com/a/60824041/3126580

**Comment by Coney484** [comment]
> > I don't think it is a good way to serialize two different types of json strings with ONE object.
> > For example 1, the Object should be like this:
> > @DaTa
> > public static class ForkNode {
> > // only one path
> > private Path path;
> > private String name;
> > }
> > @DaTa
> > public static class Path {
> > private String start;
> > }
> > new Gson().fromJson(jsonStr, ForkNode.class)
> > While For example 2, the Object should be like this:
> > @DaTa
> > public static class ForkNode {
> > // several paths
> > private List path;
> > private String name;
> > }
> > @DaTa
> > public static class Path {
> > private String start;
> > }
> > new Gson().fromJson(jsonStr, ForkNode.class)
> > In JSON:
> > Objects are enclosed directly in curly brackets {} While JSON
> > Arrays that are enclosed in square brackets [] inside JSON Objects.
> > One more thing, If you do really want to do that, I think you need to implement a custom deserializer by yourself. Please ref the doc of Gson.
> 
> Why are your answers the same? Are you the same person?
> https://stackoverflow.com/a/60824041/3126580

No, I was trying to help in any possible manner so that  it becomes easy for you and everyone who is having same problem.

**Comment by lyubomyr-shaydariv** [comment]
It's kind of shame copying/pasting someone else's quotation not even giving a link to the source and missing the original answer author. Especially, copying/pasting an answer to the cross-posted question of presumably the same author who would probably read the original answer first. Shame.

@bestbugwriter 
The _**de**serialization_ problem you're facing is pretty common for JSON documents generated by serializers that save two characters for `[` and `]` when serializing a single element array. Please refer [Make GSON accept single objects where it expects arrays](https://stackoverflow.com/questions/43412261/make-gson-accept-single-objects-where-it-expects-arrays) that addresses the same issue.

I believe the issue can be closed as "not a bug". Thanks.

**Comment by bestbugwriter** [comment]
@lyubomyr-shaydariv thanks, it is not a bug.
