### ISSUE TITLE
Gson doesn't give any "feedback"

### ISSUE THREAD

**Issue by Nathipha** [google/gson#1664]
I'm using Gson 2.8.6. to map a JSON text to multiple Java objects that my app can then work with easily:

```
Gson gson = new Gson();
Person p = gson.fromJson(somePersonText, Person.class);
```

Example for the JSON text (the actual text is more complicated, including an array):

    {
    "firstname" : "John",
    "lastname" : "Smith",
    "age" : 23
    }

and the `Person` class:

    public class Person {
        public String firstname;
        public String lastname;
        public int age;
    
        public Person(String f,String l,int a) {
            firstname = f;
            lastname = l;
            age = a;
        }
    }

According to Gson's javadoc problems doing that should throw an exception:

> JsonSyntaxException - if json is not a valid representation for an
> object of type classOfT

But if I give it e.g. `"age" : "23"`, Gson doesn't throw an exception, instead it silently converts `"23"` to an `int`.

If there's a typo, e.g. `"firstnam" : "John"`, `firstname` ends up as `null` (because it can't map "firstnam" to "firstname" of course) but there's still no exception, which later on causes problems when working with the `Person`.

There's an answer about this [here](https://stackoverflow.com/a/48064529/2016165):

> The JSON that you're giving to GSON is 100% completely valid. There are no syntax errors in it. So that's why you're not getting a JsonSyntaxException.
> Though it will return a User [`Person` in my case] object with completely default values, since it can't map any of the fields from the input JSON to the User object fields.

This doesn't address how to deal with this though.

How do I make Gson give me some type of feedback after mapping/parsing? Is there any way to ask Gson for a "report" (and if it's just a simple "error" boolean), so I can be sure that it didn't silently convert between types or even fail to map?

**Comment by LorenzNickel** [comment]
From my understanding the thing with the automatic conversion between types can't be disabled or connected with a warning. We have automatic conversion [String -> Boolean](https://github.com/google/gson/blob/46d0f58d1266c17a9fe6354344e9b1b7145fcb3d/gson/src/main/java/com/google/gson/JsonPrimitive.java#L105), [String -> Number](https://github.com/google/gson/blob/46d0f58d1266c17a9fe6354344e9b1b7145fcb3d/gson/src/main/java/com/google/gson/JsonPrimitive.java#L125), [Number -> String](https://github.com/google/gson/blob/46d0f58d1266c17a9fe6354344e9b1b7145fcb3d/gson/src/main/java/com/google/gson/JsonPrimitive.java#L145), [Boolean -> String](https://github.com/google/gson/blob/46d0f58d1266c17a9fe6354344e9b1b7145fcb3d/gson/src/main/java/com/google/gson/JsonPrimitive.java#L147), [Number, String -> Double](https://github.com/google/gson/blob/46d0f58d1266c17a9fe6354344e9b1b7145fcb3d/gson/src/main/java/com/google/gson/JsonPrimitive.java#L161), [String -> BigDecimal](https://github.com/google/gson/blob/46d0f58d1266c17a9fe6354344e9b1b7145fcb3d/gson/src/main/java/com/google/gson/JsonPrimitive.java#L172), [String -> BigInteger](https://github.com/google/gson/blob/46d0f58d1266c17a9fe6354344e9b1b7145fcb3d/gson/src/main/java/com/google/gson/JsonPrimitive.java#L184), [Number, String -> Float](https://github.com/google/gson/blob/46d0f58d1266c17a9fe6354344e9b1b7145fcb3d/gson/src/main/java/com/google/gson/JsonPrimitive.java#L195), [Number, String -> Long](https://github.com/google/gson/blob/46d0f58d1266c17a9fe6354344e9b1b7145fcb3d/gson/src/main/java/com/google/gson/JsonPrimitive.java#L206), [Number, String -> Short](https://github.com/google/gson/blob/46d0f58d1266c17a9fe6354344e9b1b7145fcb3d/gson/src/main/java/com/google/gson/JsonPrimitive.java#L217), [Number, String -> Integer](https://github.com/google/gson/blob/46d0f58d1266c17a9fe6354344e9b1b7145fcb3d/gson/src/main/java/com/google/gson/JsonPrimitive.java#L228), [Number, String -> Byte](https://github.com/google/gson/blob/46d0f58d1266c17a9fe6354344e9b1b7145fcb3d/gson/src/main/java/com/google/gson/JsonPrimitive.java#L233) and finally [String -> Character](https://github.com/google/gson/blob/46d0f58d1266c17a9fe6354344e9b1b7145fcb3d/gson/src/main/java/com/google/gson/JsonPrimitive.java#L238). These are converted without any warnings or something like this.

**Comment by Marcono1234** [comment]
@LorenzNickel, I think those conversions would only apply if Gson methods which work with `JsonElement` and subclasses are used.

For the example code in this issue, Gson's internal `TypeAdapters.INTEGER` is probably used. That adapter then calls `JsonReader#nextInt` which intentionally also supports the case where the number is stored as JSON string. Maybe that was done to account for other programming languages which cannot precisely represent all numbers as number type, but only as string.

Regarding the handling of property names with typo, the underlying issue is that Gson ignores unknown (#188) and missing (#1005) properties.

Since this GitHub issue here includes multiple issues in one, and since there already existing GitHub issues I am going to close this one here.
