### ISSUE TITLE
Gson @Expose annotations doesn't work on kotlin data classes

### ISSUE THREAD

**Issue by bpappin** [google/gson#1669]
The @Expose annotation is ignored by GSON when applied to a Kotlin data class. For example:

data class MyDataClass (@Expose val firstValue:String, val secondValue:String)

println(GsonBuilder()
            .excludeFieldsWithoutExposeAnnotation()
            .create().toJson(MyDataClass("first", "second")))

output:
{}

you mucst not set the exclude option to get any output

**Comment by lyubomyr-shaydariv** [comment]
Works fine for me. What versions of Gson and the Kotlin runtime are you using?

**Comment by bpappin** [comment]
Android Studio 3.6.1
Gson 2.8.6
Kotlin 2.1.4

I've been messing with it for a while. If you try @get:Expose you get an error that you can't use it on the value property target, or something like that. It's just an annotation in java that doesn't know the difference.

it *does* serialize, it just ignores the Expose annotation, and exposes all value properties.

**Comment by bpappin** [comment]
It appears i may be mistaken.

I'm not sure what caused gson not to handle the '@'Expose in my previous tests, but if I set up a basic clean test for just this ticket, it works just fine.

So, I will close this ticket as bogus, but I will include the test I wrote to check it.

```kotlin
class GsonKotlinTest {

    private lateinit var poko: Poko
    private lateinit var gson: Gson

    @Before
    fun setUp() {
        gson = GsonBuilder()
            .excludeFieldsWithoutExposeAnnotation()
            .create()

        poko = Poko(one = "1 (one)", two = "2 (two)", three = "3 (three)")
    }


    @Test
    fun onlyExposedPropertiesAreIncludedInJson() {
        val actual = gson.toJson(poko)
        assertEquals("{\"mytwo\":\"2 (two)\"}", actual)
    }

    data class Poko(
        val one: String,
        @Expose @SerializedName("mytwo") val two: String,
        @Expose(serialize = false) val three: String
    )
}
```
