### ISSUE TITLE
2.8.6 Throws exception when building with Android Studio

### ISSUE THREAD

**Issue by dissident76** [google/gson#1670]
gradle task : :app:transformClassesWithProfilers-transformForDebug
when trying to run on SDK 21, transforms need to be made for Advanced profiling throws exception (no error message)

**it does not happen with 2.8.5**

**Comment by Suchomel** [comment]
same

**Comment by kbmaradiya** [comment]
I am also facing the same problem.

**Comment by sachinkr34** [comment]
Same issue, Any solutions found yet for this ?

**Comment by dissident76** [comment]
Yeah, switch to moshi:
https://github.com/square/moshi/

**Comment by namgk** [comment]
same here

**Comment by skhack** [comment]
This seems like https://issuetracker.google.com/issues/143467035 and has been fixed in Android Studio 4.1.

**Comment by Marcono1234** [comment]
Could you please check if this still occurs with the latest Gson version and Android Studio version (maybe also upgrade Gradle and Gradle plugins)?

**Comment by Marcono1234** [comment]
I am going to close this because no answer has been provided. If you still experience this with the latest Gson version, feel free to comment here again with more details.
