### ISSUE TITLE
GSON 2.8.6 does not support on lower JavaSE environment

### ISSUE THREAD

**Issue by BharathViki** [google/gson#1677]
Hi,

I have already been using gson 2.8.5 as one of my project dependency. It works properly without any issue. 

Now I am trying to use the latest gson version 2.8.6, but end up with below error in OSGI container.

Looks like the requirement capability need to be revisit in gson 2.8.6 mainfest.

**Note**: I have Java SE 8.

  `_  Caused by: org.osgi.framework.BundleException: Could not resolve module: com.google.gson [110]
  Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=9.0))"
                at org.eclipse.osgi.container.Module.start(Module.java:444)
                at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:383)
                at org.apache.karaf.bundle.command.Start.executeOnBundle(Start.java:38)
                at org.apache.karaf.bundle.command.BundlesCommand.doExecute(BundlesCommand.java:62)
                ... 14 common frames omitted
_`

**Comment by AxeTheAxe** [comment]
According to https://github.com/google/gson/blob/master/gson/bnd.bnd this issue will be fixed in 2.8.7

**Comment by markwoon** [comment]
Any chance of a release soon?

**Comment by msohn** [comment]
also this header seems to be wrong:
Bundle-RequiredExecutionEnvironment: J2SE-1.5, JavaSE-1.6, JavaSE-1.7, JavaSE-1.8

I think this should be
Bundle-RequiredExecutionEnvironment: JavaSE-1.6
since all classes except the module-info.class have class file version 50 corresponding to JavaSE-1.6

**Comment by eamonnmcmanus** [comment]
I assume this is fixed since 2.8.7. Feel free to reopen if not.
