### ISSUE TITLE
GitHub does not check Travis build anymore

### ISSUE THREAD

**Issue by Marcono1234** [google/gson#1691]
It appears GitHub is not checking the Travis build anymore. This might mean that a broken build would therefore pass (show a green checkmark) on GitHub.

See 55acc23 which when clicking on the green checkmark shows that Travis was checked.
And compare it with recent commits or pull requests.
You will see that they only check CLA and "Validate Gradle Wrapper".

However, Travis is still building the project, which can be seen on https://travis-ci.org/github/google/gson, but GitHub is for some reason not considering it anymore in its commit checks.

**Comment by inder123** [comment]
Thanks for pointing that out. Would welcome a PR to fix the issue.

**Comment by Marcono1234** [comment]
I assume this has to be managed in the GitHub project settings, though I am not sure.

Anyways, it looks like this has been resolved because the Travis build was checked for ceae88b again, so I am closing this issue.
