### ISSUE TITLE
Unable to deserialize JsonNull as Option.none() in customized JsonDeserializer

### ISSUE THREAD

**Issue by luochen1990** [google/gson#1696]
I'm trying to customize the Serializer/Deserializer for Option<T> (using io.vavr.control.Option, or Optional<T> if using java.utils.*, which is similar here).

And there are 2 requirement for what I want:

1. serialize `Option.none()` as `null` in JSON, and `Option.some("hello")` as `"hello"`, so that there is no redundancy (I'm assuming that both the value inside `Option.some` and the value itself are @NotNull).
2.  Option<T> value keep not changed after serialize and deserialze.

And following is my code:

```
@Override
public Option<T> deserialize(JsonElement json, Type typeOfRes, JsonDeserializationContext context) {
     if (json.isJsonNull()) {
          return Option.none();  //NOTE: this branch seems never reached!
     } else {
          return Option.some(context.deserialize(json, typeOfT));
     }
}
```

And the corresponding test code:

```
JsonElement jsome = jsonParser.parse("\"abcd\"");
JsonElement jnone = jsonParser.parse("null");
Object r1 = JsonHelper.gson.fromJson(jsome, new TypeToken<Option<String>>(){}.getType());
Object r2 = JsonHelper.gson.fromJson(jnone, new TypeToken<Option<String>>(){}.getType());
System.out.println("r1: " + r1); // `Some("abcd")`
System.out.println("r2: " + r2); // `null`  (expecting `Option.none()`)
```

My entire example code: https://gist.github.com/luochen1990/bd63b2d6e9c7c9b77961208920ec3edf

related SO questions:
- https://stackoverflow.com/questions/33301036/gson-ignore-null-when-deserializing-object
- https://stackoverflow.com/questions/61892161/how-to-customize-serializer-and-deserializer-for-option-in-gson-without-redundan

**Comment by Marcono1234** [comment]
It appears the `GsonBuilder.registerTypeAdapter` makes `JsonSerializer` and `JsonDeserializer` `null`-safe, i.e. they are not called for `null` values, see #1697.

So you should use `TypeAdapter` respectively `TypeAdapterFactory` instead. See [this StackOverflow answer](https://stackoverflow.com/a/25078422/) for a working implementation (except that `read(...)` has to consume the `null`, which is currently wrong in the answer).

**Comment by luochen1990** [comment]
@Marcono1234 Thanks very much!

I have solved this problem referecing your SO answer, and [here](https://gist.github.com/luochen1990/319de4c73f7269d197a2a3fe4523a1f7) is my full code, just for anybody which might need it.

**Comment by Marcono1234** [comment]
No problem.
Instead of `in.peek() != JsonToken.END_ARRAY` you can also use [`in.hasNext()`](https://javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/stream/JsonReader.html#hasNext()).
