### ISSUE TITLE
Consistently refer to RFC 7159

### ISSUE THREAD

**Issue by Marcono1234** [google/gson#1710]
Parts of Gson refer to RFC 4627 while other parts refer to RFC 7159 (which updates 4627).
It would be good to consistently refer to RFC 7159. This requires:
- Updating the links
- Updating any section references / quotations of the RFC

**Comment by marcus-h** [comment]
It might make sense to directly refer to RFC 8259. For the JsonReader class, this is already part of
PR #1609 (which adds a new parsing mode to ensure that only JSON text is accepted that
complies to RFC 8259).

**Comment by Marcono1234** [comment]
Has been fixed by #2437, which consistently refers to RFC 8259.
