### ISSUE TITLE
android 8.0 引用库导致app崩溃

### ISSUE THREAD

**Issue by weiwenqiang** [google/gson#1714]
经过数天调试定位到gson不支持1.8，运行时异常

then you are telling android to use java 8.

then the problem happens if you are using a library that does not support java 8 (i.e it uses something from java 7 that is not allowed in java 8)

for me the problem happens because I had the following in my gradle

implementation 'com.google.code.gson:gson:2.8.6'

which seems not to support java 8 , I have solved it be removing the Gson library and used moshi instead of it for json to model parsing

**Comment by Marcono1234** [comment]
In case of exceptions or other errors, could you please attach their stack trace here?
Gson should support Java 8 and even Java 11 and newer versions, and others have been able to successfully use it in that versions.

**Comment by androidyue** [comment]
> 经过数天调试定位到gson不支持1.8，运行时异常
> 
> then you are telling android to use java 8.
> 
> then the problem happens if you are using a library that does not support java 8 (i.e it uses something from java 7 that is not allowed in java 8)
> 
> for me the problem happens because I had the following in my gradle
> 
> implementation 'com.google.code.gson:gson:2.8.6'
> 
> which seems not to support java 8 , I have solved it be removing the Gson library and used moshi instead of it for json to model parsing

I think you should upgrade the gradle plugin in your project to the latest version. It works for me.

**Comment by Marcono1234** [comment]
Closing because no further information was provided.
