### ISSUE TITLE
Can not get rid of blackslashes? Shouldn't be there optiont o exclude backslashes?

### ISSUE THREAD

**Issue by omeryounus** [google/gson#1724]
Using it to show the JSON response. But due to some reason not able to show the response properly. 
Gson gson = new Gson().toJSON(new MyModel());
response: {
        "data" : "\any value"
}

**Comment by Marcono1234** [comment]
Can you please provide a small code example which shows this issue?
Gson should normally only use escape sequences where necessary and should only use the escape sequences which are described in the JSON specification, which does not include `\a`.
See also
https://github.com/google/gson/blob/ceae88bd6667f4263bbe02e6b3710b8a683906a2/gson/src/main/java/com/google/gson/stream/JsonWriter.java#L143

**Comment by Marcono1234** [comment]
Closing this issue because no further information was provided.
