### ISSUE TITLE
object values has "\u", to json string .it has problem

### ISSUE THREAD

**Issue by stl714** [google/gson#1725]
when I use gson to convert a object to a json string, I found a problem. When the object which field value contains "\u", gson convert object to json string will generate two "\\"  ,it comes "\\u". Result json like 

object field     
     path = /abc\u6d4b\u8bd5test.pdf
json string 
{"autorename":true,"mode":"add","mute":false,"path":"/abc\\u6d4b\\u8bd5test.pdf","strict_conflict":false}

**Comment by lyubomyr-shaydariv** [comment]
Gson should not process there characters in any way. Are you sure you're not confused with these wto:

```java
System.out.println("/abc\u6d4b\u8bd5test.pdf");
System.out.println("/abc\\u6d4b\\u8bd5test.pdf");
```

?

**Comment by stl714** [comment]
Sorry, I make a mistake. Thanks your suggestion.
