### ISSUE TITLE
GSON fails to read/map a field with name like USERId

### ISSUE THREAD

**Issue by ramakrishnagvss** [google/gson#1732]
Response from a client (rest call) has a json element like USERId. The related java variable is as below
@JsonProperty("USERId")
private String uSERId;

I am using spring RestTemplate to make this rest call and for mapping from JSON to JAVA I am using GSON. I have completely excluded jackson databind which is spring rest template's default mapper like below.

this.getMessageConverters().removeIf(converter -> converter.getClass().getName().equals(MappingJackson2HttpMessageConverter.class.getName()));
GsonHttpMessageConverter messageConverter = new GsonHttpMessageConverter();
messageConverter.setGson(gson);
this.getMessageConverters().add(messageConverter);

This way, I made sure only GSON is used for mapping.

When I directly hit client rest service on postman, I see this filed has a value - "USERId": "025076373". However the response object from RestTemplate doesnt have this field i.e., all other fields with proper java camel case naming are mapped properly. I mean all other fields in the respone object are mapped with values from response json. Response object doesnt have uSERId or the corresponding value.

I believe this issue is probably because of the weird naming convention, however the same works fine with MappingJackson2HttpMessageConverter.

I have tried debugging by writing an adapter and assigning it to gsonBuilder and then setting that to GsonHttpMessageConverter.

gsonBuilder.registerTypeHierarchyAdapter(String.class, new StringTypeAdapter().nullSafe())
While debugging the adapter, I could see all other fields except USERId.

Object mapper of jackson databind has a property MapperFeature.ACCEPT_CASE_INSENSITIVE_PROPERTIES, which I believe is the reason why the same field is working jackson. I couldnt find a similar property with GSON. Any pointers on how to fix this issue would be very helpful.

Technologies used : spring boot, spring rest template, com.google.code.gson:gson:2.8.6

**Comment by lyubomyr-shaydariv** [comment]
This might help: #1728.

**Comment by ramakrishnagvss** [comment]
I tried adding the adapter that you have mentioned in 1728 however I am getting "**Expected a name but was BEGIN_OBJECT" at line 1 column 46 path $.response**". I believe this might be because there were multiple json tokens(number, boolean, name) in my response object which cannot be accessed by **nextName()**
The class in which I have uSERId field is present is provided via a client and the property is annotated with jackson @JsonProperty("USERId"), which I cannot manipulate as @SerializedName(value="USERId", alternatives={"userId"}) (gson annotations).

Is there anyway that I can override GSON to fetch "USERId":"12345" from a json response and map it to the below java variable. 
@JsonProperty("USERId")
private String uSERId;

I know this is a weird field name but I have to live with it since the client cannot change the jar file.

**Comment by lyubomyr-shaydariv** [comment]
Not sure whether I can really see the issue, but would this help:

```java
private static final Gson gson = new GsonBuilder()
	...
	.setFieldNamingStrategy(field -> {
		@Nullable
		final JsonProperty jsonProperty = field.getAnnotation(JsonProperty.class);
		if ( jsonProperty == null ) {
			return FieldNamingPolicy.IDENTITY.translateName(field);
		}
		return jsonProperty.value();
	})
	...
	.create()
```

?

**Comment by Marcono1234** [comment]
Closing this because it looks like this has been answered above. To support using field names from Jackson's `@JsonProperty` annotation you have to specify a custom field naming strategy.
