### ISSUE TITLE
Serialize/deserialize SparseArray on targetVersion 29

### ISSUE THREAD

**Issue by Cryperian** [google/gson#1742]
I'm using Gson for serialize SparsArray from Object to json and I have empty json like `{}` .
I added custom SparseArrayTypeAdapter but it did not help for my case (its work on OnePlus but dont work on Xiaomi).

Gson : v2.8.6

**Comment by Marcono1234** [comment]
Do you mean Android's `android.util.SparseArray`? Could you please provide your code (reduced to the relevant parts)?

**Comment by Cryperian** [comment]
> Do you mean Android's `android.util.SparseArray`? Could you please provide your code (reduced to the relevant parts)?

Yes I mean android.util.SparseArray. I got round this issue by Array Map in TypeAdapter

`  @Override
    public void write(JsonWriter jsonWriter, SparseArray<T> tSparseArray) throws IOException {
        if (tSparseArray == null) {
            jsonWriter.nullValue();
            return;
        }

        ArrayMap<Integer, T> arrayMap = new ArrayMap<>();
        for (int i = 0; i < tSparseArray.size(); i++) {
            arrayMap.put(tSparseArray.keyAt(i), tSparseArray.get(tSparseArray.keyAt(i)));
        }

        gson.toJson(gson.toJsonTree(arrayMap, typeOfArrayMapOfT), jsonWriter);
    }

    @Override
    public SparseArray<T> read(JsonReader jsonReader) throws IOException {
        if (jsonReader.peek() == JsonToken.NULL) {
            jsonReader.nextNull();
            return null;
        }

        ArrayMap<Integer, Object> arrayMap = gson.fromJson(jsonReader, typeOfArrayMapOfObject);
        SparseArray<T> result = new SparseArray<>(arrayMap.size());
        int key;
        JsonElement tElement;
        for (int i = 0; i < arrayMap.size(); i++) {
            key = arrayMap.keyAt(i);
            tElement = gson.toJsonTree(arrayMap.get(key));
            result.put(key, gson.fromJson(tElement, classOfT));
        }
        return result;
    }`

**Comment by Marcono1234** [comment]
If you want you can also have a look at [this implementation](https://stackoverflow.com/a/63381578) which is likely more efficient because it does not create an intermediate ArrayMap. (Feedback for that implementation is appreciated.)
