### ISSUE TITLE
MalformedJsonException: Unterminated string at line 1 column xxxxxxxxx path $.fieldname[random index].fieldname[random index].fieldname

### ISSUE THREAD

**Issue by a916057886** [google/gson#1747]
I am using `JsonReader` from `Gson` to read and parse huge JSON file line by line, however, recently I have found that the parsing could go wrong with the exception message of `MalformedJsonException: Unterminated string at line 1 column xxxxxxxxx path $.fieldname[random index].fieldname[random index].fieldname`, but the position that caused this exception to be thrown will be varied every time I tested it with the exact same file, and I have also tested the same JSON file with a different parsing library (different than I parsed line by line using `Gson`, for this library I just loaded everything into the memory and then convert to an object), and there was no parsing error at all, so I am guessing this could be a BUG in the `JsonReader` class.

PS: I am afraid I cannot provide any file that caused this problem to occur at this point since they are from the company I am working with, I can ask for a permission to share it if you really need it for debugging

**Comment by lyubomyr-shaydariv** [comment]
You should provide:

- your platform;
- exact `JsonReader`-driven code you're using to reproduce it (it might tell why your Gson might fail, but other libraries succeed);
- stacktrace you're getting when reproducing it (obfuscate your company/product packages to keep them in secret);
- the most common `xxxxxxxx` range and the size of your files, or unusual things like huge string literals (their length actually);
- a JSON file that mimics your real file somehow (not sure if you really need several GBs shared elsewhere), or a simple Java generator tool that can generate the mimicking file (in both cases all your company/product secrets remain secret).

**Comment by lyubomyr-shaydariv** [comment]
You seem to have resolved it already. https://stackoverflow.com/questions/63252842/gson-library-is-not-working-reliably-as-intended-for-parsing-large-json-file/63274792#63274792 I don't think huge JSON oneliners are the very cause though.

**Comment by a916057886** [comment]
I apologize for not providing enough details for this issue
Unfortunately, I asked my direct supervisor and colleague, we are not allowed to share any JSON file that has this issue since they contain sensitive data from our customers, I personally did my best to try to create a JSON file that can reproduce the above problem, however, I failed to do so
But I do can provide you the error stacktrace (the platform is `JAVA` and I used `Gson-2.8.6`):
`com.google.gson.stream.MalformedJsonException: Unterminated string at line 1 column 45301761 path $.new_rows[113].new_rows[70].sql_query at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568) at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1031) at com.google.gson.stream.JsonReader.nextString(JsonReader.java:815) at xxxxx.parseEachNewRow(MultiplierResponseSubscriber.java:369) at xxxxx.processNewRows(MultiplierResponseSubscriber.java:210) at xxxxx.processNewRows(MultiplierResponseSubscriber.java:214) at xxxxx.processMultiplicationResults(MultiplierResponseSubscriber.java:176) at xxxxx.processMultiplierResponse(MultiplierResponseSubscriber.java:113) at xxxxx.consume(MultiplierResponseSubscriber.java:60) at org.springframework.cloud.gcp.pubsub.core.subscriber.PubSubSubscriberTemplate.lambda$subscribe$0(PubSubSubscriberTemplate.java:136) at com.google.cloud.pubsub.v1.MessageDispatcher$4.run(MessageDispatcher.java:438) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748)`
