### ISSUE TITLE
Missing methods

### ISSUE THREAD

**Issue by priand** [google/gson#1755]
Would be great if you can add a few missing methods:
JsonObject/JsonArray: clear() -> empty the container, similar to Collection.clear()
JsonArray: addAt() -> insert an element at a defined index, similar to List addAt()

Would also help to have a JsonPrimitive get() that doesn't do any check, but just returns the raw value (Boolean, Number or String)

These are easy, non breaking add-ons that can simplify some code :-)

**Comment by Marcono1234** [comment]
#2225 has added the methods `JsonArray.asList` and `JsonObject.asMap` so it is at least now possible to use `clear()` and `addAt` (respectively `add(int, JsonElement)`) with the `List` and `Map` views from these methods.
