### ISSUE TITLE
Can not infer generic type arguments after upgrading to 2.8.6

### ISSUE THREAD

**Issue by hstaudacher** [google/gson#1788]
We recently updated our gson version from 2.7 to 2.8.6 and noticed some serialization test failures. The reason for this is that we have a data structure that makes extensive use of generics. On certain scenario fails were ObjectTypeAdaper always serializes NUMBER as Double. 

Here is a unit test that passes with 2.7 and fails with 2.8.6

```java
import static org.assertj.core.api.Assertions.assertThat;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import org.junit.Test;

import com.google.gson.Gson;

public class GsonTest {

	static abstract class ParentPojo<T, V> {

		List<T> list;

		V value;

		public ParentPojo(List<T> list, V value) {
			this.list = list;
			this.value = value;
		}

	}

	static class InBetweenPojo<T extends Number & Comparable<T>> extends ParentPojo<T, Optional<T>> {

		public InBetweenPojo(Optional<T> value) {
			super(new ArrayList<>(), value);
		}

	}

	static class Pojo extends InBetweenPojo<Long> {

		public Pojo(Optional<Long> value) {
			super(value);
		}
	}

	@Test
	public void canInferTypeArguments() {
		Long v = 12345678910L;

		Gson gson = new Gson();
		String json = gson.toJson(new Pojo(Optional.of(v)));
		Pojo pojo = gson.fromJson(json, Pojo.class);

		assertThat(pojo.value.get()).isInstanceOf(Long.class);
	}

}
```

**Comment by Marcono1234** [comment]
Sounds similar to #1731. This might be the same bug which has the pull request #1391 fixing it.
Also note that Gson currently has no built-in type adapter for `java.util.Optional` so unless you are providing your own custom one you are relying on implementation details of the JDK.


Note however that I am not a maintainer and therefore do not know when that pull request will be merged.

**Comment by Marcono1234** [comment]
It looks like at least the specific test case you have given works fine in Gson 2.9.1; therefore I am closing this issue. Please create a new issue in case you still experience a similar problem.
