### ISSUE TITLE
What is the difference when I use `toJson` and `toJsonTree`?

### ISSUE THREAD

**Issue by zxa4fd** [google/gson#1805]
What is the difference between the two and when should they be used?

**Comment by Marcono1234** [comment]
[`Gson.toJson`](https://www.javadoc.io/doc/com.google.code.gson/gson/2.8.6/com.google.gson/com/google/gson/Gson.html#toJson(java.lang.Object)) and its overloads are for serializing an object to a JSON string. They are useful for sending the JSON data to a different host, saving it to file, ... They are probably the most commonly used methods.

[`Gson.toJsonTree`](https://www.javadoc.io/doc/com.google.code.gson/gson/2.8.6/com.google.gson/com/google/gson/Gson.html#toJsonTree(java.lang.Object)) is for serializing an object into an in-memory representation of the JSON document represented by [`JsonElement`](https://www.javadoc.io/doc/com.google.code.gson/gson/2.8.6/com.google.gson/com/google/gson/JsonElement.html). This might be useful when want to modify the JSON before further processing it. For example when you have two objects which you want to merge to one JSON object you could serialize both to `JsonObject` and then copy the members of one object to the other one.

Do you have a specific use case where this question came up?

**Comment by zxa4fd** [comment]
Yeah I saw it in an example
