### ISSUE TITLE
proto/pom.xml refers to non-existent repository

### ISSUE THREAD

**Issue by scovetta** [google/gson#1810]
I noticed that the [pom.xml](https://github.com/google/gson/blob/master/proto/pom.xml#L26) file in the proto directory still refers to the non-existent http://google-gson.googlecode.com/svn/mavenrepo. 

I suspect this can be removed now that Gson is available in Maven Central.

**Comment by Marcono1234** [comment]
Thanks! This was resolved by #2008.
