### ISSUE TITLE
I Found a serious issue with the RuntimeTypeAdapterFactory.java

### ISSUE THREAD

**Issue by rafaelsetragni** [google/gson#1817]
Inside the file:
https://github.com/google/gson/blob/ceae88bd6667f4263bbe02e6b3710b8a683906a2/extras/src/main/java/com/google/gson/typeadapters/RuntimeTypeAdapterFactory.java#L204

While the application is running with debug and normal release mode, everything works just fine. The problem is when is necessary to compile a compress version of an app with the option `minifyEnabled`.

This option do a lot of changes in the source and really compress the final APK (almost 40% somethimes and even more).

One of the changes is the classes renaming of the entirely project, using the standard "h.a.a.e.i.b", "h.a.a.e.i.c", "h.a.a.e.i.f.b", and etc.

When you register some those classes with `registerSubtype` and the app is running on normal modes everything works ok. But when `minifyEnabled` is turned on, it changes all the classes names. So, the method `getSimpleName` inside `registerSubtype` starts to output only single letters, and they are easly equal to another, and you get the error "types and labels must be unique".

This is a really hard to find and simple to solute issue, because while the app is running with `minifyEnabled` the logs get messy with those names changed and there is a lot of debug restrictions. This kind of error could make many gson users to take a wrong impression of an inconsistent library.

I suggest to change `getSimpleName` by `getName`.
Yes, the resulted String is bigger, but it will not produce the error in any compilation case.

Ill put bellow the bug tread in my Github project, to you see how i got this error and how i fix it:

[awesome_notifications only works in debug mode, in release mode the notification doesn't appear at all #29](https://github.com/rafaelsetragni/awesome_notifications/issues/29)

**Comment by lyubomyr-shaydariv** [comment]
May I ask you? Why are you trying to rely on the behavior of a certain minification tool that may change the outcome class names merely in a previous/next release or adding/removing a class in a package? Additionally, there is a `registerSubtype` overload allowing to specify an arbitrary concrete label for each subclass not even bothering for what the minification tool outcome is. (UPD: You've realized it yourself in the referenced bugfix.)

> This kind of error could make many gson users to take a wrong impression of an inconsistent library.

True to some extent: if `RuntimeTypeAdapterFactory` were a part of the library JAR bundle, and not a part of the `extras` directory that mainly serves demo purposes, where everything can be 100% adapted to your even very specific needs.

I don't see anything serious here.

**Comment by rafaelsetragni** [comment]
> May I ask you? Why are you trying to rely on the behavior of a certain minification tool that may change the outcome class names merely in a previous/next release or adding/removing a class in a package?

Remember, the `minifyEnabled` option and `RuntimeTypeAdapterFactory` are completely separated projects, but commonly used combined.

This option is the default option for many release APK process and many developers use it deliberately. For Flutter, one of the most used Frameworks for build hybrid applications for Android and iOS, this is the ONLY WAY to release a final App to publish in stores.

I GUARANTEE you that every single project that used `registerSubtype` will have issues in release mode with `minifyEnabled` activated, and they probably won't understand what is going on, except when they decide to take off your library and use another one.

> Additionally, there is a `registerSubtype` overload allowing to specify an arbitrary concrete label for each subclass not even bothering for what the minification tool outcome is. (UPD: You've realized it yourself in the referenced bugfix.)

YES, you could use the overload method to give the classes a personal name, but also you **_COULD NOT_**. And if you didnt, the app will work perfectly in every single release mode, EXCEPT the most important one, that is the final and compressed release mode. The most hardful to debug and the last one.

And there is another error thrown by this class when using `minifyEnabled` option, "NoSuchFieldException", and i honestly do not have more patient to find it and to fight to explain this issue for developers who are so emotionally attached to their source code that they don't recognize a serious problem anymore.

I won't waste any more time on this and I will take my project's Gson library and use another one.
Good luck finding the next problem. I did my part trying to help you.

Do what you think is right to do.

**Comment by lyubomyr-shaydariv** [comment]
Mate, Gson is not a special Android library, it has zero dependencies and it is not aware of whatever toolchain you're using on a particular Java-based solution, and you should understand any implications. If you're using Java reflection, the main implication is just in front of you, and your code is always weak against minification, package mutations, obfuscation and so on just by definition: you're using Java reflection. Craft it first. Classic case: who to blame for using `Class.forName` that refers a pre-processed class by its full name in a constant of dynamically built string? Where might the `type` property value (essentially a true class name) come from if the classes are reorganized, and have you inspected the contents of the JSON payload? What would happen if the minification strategy changes and your fully qualified names get changed too breaking your previous JSON documents that refer other classes (if they even exist though, so `getName` will not help at all -- do `h.a.a.e.i.b` and `h.a.a.e.i.c` still have the same meaning they had in a previous release)? The main thing here is that no Java reflection-oriented library would help you and you'll face the same issue unless you get rid of reflection at all (zero-reflection type adapters, build-time code generators, etc).

**Comment by rafaelsetragni** [comment]
> What would happen if the minification strategy changes and your fully qualified names get changed too breaking your previous JSON documents that refer other classes (if they even exist though, so getName will not help at all -- do h.a.a.e.i.b and h.a.a.e.i.c still have the same meaning they had in a previous release)?

Yes, the previously json data will not be compatible with the compressed one, and the execution will break. Thats why i decide to use the class name as part of file reference where i store de Json data. If the class change his name, also the file will be changed.

To let the solution easy to use, will be necessary to implement some strategy to surround it inside `RuntimeTypeAdapterFactory `.

**Comment by rafaelsetragni** [comment]
https://github.com/google/gson/issues/1456

**Comment by 911992** [comment]
For situations like this, why not using low-level manual like `Json[Writer|Reader]` classes? I believe they will work for any kind of situations.

**Comment by rafaelsetragni** [comment]
Yes, i did it.

But if a mechanic tells to his client that “there is no problem, he can
drive his car perfectly, just no to use the 6th broken gear”, guess what?
the 6th gear continuous broken and the car still have a issue.

Em sáb., 14 de nov. de 2020 às 22:57, 911992 <notifications@github.com>
escreveu:

**Comment by 911992** [comment]
I understand Rafael,  

Yes I believe GSON(*and not just this, millions of libs out there*) could be much flexible to cover many data/API schemes, but sometimes more you try to make something flex/compatible, more you make it complex, and hard to maintain/fix.

Situations like this are very rare(of my pov), and may not even worth to impl, besides that, you may contribute, and have your own impl to cover this issue, totally `win-win`.

**Comment by rafaelsetragni** [comment]
So, if no one uses it and it is so rare, it is not worth anybody's effort.
Let it burn. I've already stopped to use this lib.

Just a tip: if you made a tool to help people, why do you abandon the cause as soon as it points out a single problem? Wasn't it better to have done nothing in the first place? False information is much worse than a lack of information.

**Comment by rafaelsetragni** [comment]
I don't care to this problem anymore. Issue closed.
