### ISSUE TITLE
json string to map，int Type conversion Double

### ISSUE THREAD

**Issue by lsm1998** [google/gson#1823]
The cases are as follows：

`
**package test;

import com.google.gson.Gson;
import org.junit.Test;

import java.util.Map;

public class MyTest
{
    private Integer id;
    private String name;
    private float number;

    @Test
    public void test()
    {
        Gson gson=new Gson();

        MyTest test=new MyTest();
        test.number = 3.14f;
        test.id = 10;
        test.name = "lsm";
        System.out.println(gson.toJson(test));

        String str="{\"id\":10,\"name\":\"lsm\",\"number\":3.14}";
        Map map = gson.fromJson(str, Map.class);
        map.forEach((k,v)-> System.out.println(k+" type is"+v.getClass()));
    }
}**
`

id type is int，but the print result is Double

**Comment by Marcono1234** [comment]
Relates to #968 and #1290

**Comment by komminen** [comment]
Hi, we will volunteer to work on this issue in October/November. For the project maintainer, please let us know if this is okay and if you want it fixed.

**Comment by Marcono1234** [comment]
Closing because this is most likely solved (at least to some extent) with the introduction of `ToNumberPolicy` and the author did not provide more information about their use case.
