### ISSUE TITLE
Illegal reflective access by com.google.gson.internal.reflect.UnsafeReflectionAccessor (/com/google/code/gson/gson/2.8.6/gson-2.8.6.jar) to field java.time.LocalDate.year

### ISSUE THREAD

**Issue by FrederickFrance** [google/gson#1836]
Hi

I have this warning message but I don't find the place to trace it and, of course, how to fix that :+1: 

> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by com.google.gson.internal.reflect.UnsafeReflectionAccessor (file:/home/fred/.m2/repository/com/google/code/gson/gson/2.8.6/gson-2.8.6.jar) to field java.time.LocalDate.year
> WARNING: Please consider reporting this to the maintainers of com.google.gson.internal.reflect.UnsafeReflectionAccessor
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release
 

I don'y know which information I can add.

```
    <java.version>1.8</java.version>
    <tomcat.version>9.0.37</tomcat.version>
```

Do not hesitate to ask me any information if my message isn't enough clear

**Comment by lyubomyr-shaydariv** [comment]
Gson is a Java 6 oriented library. All standard runtime library classes to appear in Java 8 are not supported by Gson out of box. All "simple" data classes of java.time.* are among of those. You should create a custom type adapter to support `java.time.LocalDate`, and do the same for all the classes you need from that package. See also: #1059, #1807, and please don't forget to close the issue.
