### ISSUE TITLE
Java 9 gson not found

### ISSUE THREAD

**Issue by mattyleung** [google/gson#1839]
Hi everyone,

I am trying to migrate a project from java1.8 to 9 or above. I noticed that in Gson 2.8.6 version, we have a module-info.java added with in the class. 

I have created an really simple project that takes an object and use Gson to convert it to a String. 
But when I run the project, `error: module not found: com.google.gson` , 

My build.gradle
`dependencies {

    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.6.0'

    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine'

    implementation 'com.google.code.gson:gson:2.8.6'
}`

Module-info.java
`
module gsonTest.main {
    requires com.google.gson;
}`

**Comment by darkos** [comment]
I have exactly the same issue.
If I remove module-info.java from the project, issue disappears.
Unfortunately, I need my library, that I am building, to be modular.

// build.gradle
plugins {
    id 'java-library'
}

repositories {
    jcenter()
}

dependencies {
    api 'org.apache.commons:commons-math3:3.6.1'
    implementation 'com.google.guava:guava:28.2-jre'
    testImplementation 'junit:junit:4.12'
    implementation 'com.google.code.gson:gson:2.8.6'
}

// module-info.java
...
requires com.google.gson;
...

**Comment by KevinTyrrell** [comment]
Whenever I try to import via gradle, I receive the following:

> Could not find method implementation() for arguments [com.google.code.gson:gson:2.8.6] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

My build file is the following:
```
dependencies {
    implementation 'com.google.code.gson:gson:2.8.6'
}
```

**Comment by Marcono1234** [comment]
@KevinTyrrell, that might be a different issue, see #1885. Please try updating your Gradle installation.

**Comment by Marcono1234** [comment]
@mattyleung or anyone else experiencing this issue, could you please try the latest Gson version? Additionally, please provide a small self-contained example project showing this issue.

**Comment by Marcono1234** [comment]
I am going to close this because no answer has been provided. If you still experience this with the latest Gson version, feel free to comment here again with more details.
