### ISSUE TITLE
The code may throw an exception before the reader is closed，you should use try-catch-finally or try-with-resource to close resource

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [google/gson#1841]
https://github.com/google/gson/blob/ceae88bd6667f4263bbe02e6b3710b8a683906a2/metrics/src/main/java/com/google/gson/metrics/ParseBenchmark.java#L117-L130

**Comment by Marcono1234** [comment]
This code was refactored by #2019 and the current version uses `try-finally`.
