### ISSUE TITLE
Gson serialized HashMap object returns null

### ISSUE THREAD

**Issue by wujiuye** [google/gson#1849]
Gson serialized HashMap object returns null

The unit test is as follows:
```java
public class JsonTest {
    @Test
    public void testGsonMap() {
        Map<String, Object> data = new HashMap<String, Object>() {{
            put("xxx", "yyy");
        }};
        System.out.println(JsonUtils.toJsonString(data));
    }
}
```
JsonUtils#toJsonString actually calls Gson#toJson, and the test outputs null. But switching to the jackson framework can be serialized successfully.

It can be seen from the compiled bytecode that “data” is actually an anonymous class object. The anonymous class inherits HashMap and the anonymous class ends with "$1".

The following is the call stack traced by DEBUG:
```java
com.google.gson.internal.Excluder#create
  >com.google.gson.internal.Excluder#excludeClassChecks
       >com.google.gson.internal.Excluder#isAnonymousOrLocal
            >java.lang.Class#isAnonymousClass
```

java.lang.Class#isAnonymousClass
```java
public final class Class<T> {
    public boolean isAnonymousClass() {
        return "".equals(getSimpleName());
    }
}
```

The getSimpleName method removes the "$" of the anonymous class "$1" and the following number and returns "", so the serialization of the anonymous class object is skipped.

**Comment by a983132370** [comment]
路过.... 今天也碰见这个事了,上来看看
