### ISSUE TITLE
Can't process class [module-info.class] (Unsupported class version number [53.0] (maximum 52.0, Java 1.8))

### ISSUE THREAD

**Issue by raminhbbAU** [google/gson#1850]
Hey There,

I'm facing with a trouble while compiling my android project with gson-2.8.6.jar. The following error has appeared:

Warning:Exception while processing task java.io.IOException: Can't read [D:\Parsic Source\ParsiLab\ParsiLab\app\libs\gson-2.8.6.jar(;;;;;;**.class)] (Can't process class [module-info.class] (Unsupported class version number [53.0] (maximum 52.0, Java 1.8)))

Any help would be appreciated
RaminHbb

**Comment by Marcono1234** [comment]
Probably related to #1627

**Comment by Marcono1234** [comment]
Can you please check if this issue still occurs with the latest Gson version? The way the `module-info.class` is included in the Gson JAR was changed and should hopefully now cause fewer issues. Also make sure to use the latest build tools and plugins (e.g. Gradle).

**Comment by Marcono1234** [comment]
I am going to close this because no answer has been provided. If you still experience this with the latest Gson version, feel free to comment here again with more details.
