### ISSUE TITLE
Is Gson dead ?

### ISSUE THREAD

**Issue by HybridGaw** [google/gson#1854]
last release was 2019 , now it's 2021 , is it dead ???

**Comment by A248** [comment]
There are projects which have went without a release for longer periods of time, but which aren't "dead" either.

**Comment by inder123** [comment]
Yeah, we can create a new release when we want. What specific problems are you looking to solve with a new release?
Overall, Gson is a mature library with massive usage. We have to be very careful in adding features that may break backward compatibility.

**Comment by Marcono1234** [comment]
@inder123, do you mind having a look at #1821?
There are a few severe issues (most of them have pull requests) which have been open for years. It appears multiple people who want to contribute have the impression that this project is not actively maintained anymore.

**Comment by rrowlands** [comment]
Honestly without [native support for polymorphism](https://github.com/google/gson/issues/231) I don't see how this project can compete with jackson.

**Comment by HybridGaw** [comment]
已收到，谢谢
