### ISSUE TITLE
Copyright year and owner are missing in license - replace placeholders

### ISSUE THREAD

**Issue by ts-twt** [google/gson#1855]
https://github.com/google/gson/blob/ceae88bd6667f4263bbe02e6b3710b8a683906a2/LICENSE#L190

**Comment by eamonnmcmanus** [comment]
That line is part of the [template](https://github.com/google/gson/blob/ceae88bd6667f4263bbe02e6b3710b8a683906a2/LICENSE#L179) to be used by people applying the Apache license to their own work. It is supposed to look like that.
