### ISSUE TITLE
ToJson makes a dictionnary with alphabetical keys for each entry instead of key name

### ISSUE THREAD

**Issue by Saursinet** [google/gson#1856]
On Android I have a model as follow:
```
data class Visibility(val id: VisibilityId, var visible: Boolean, val type: String)

data class VisibilityId(val ids: Any) {
    fun getIds(): Array<Int> {
        @Suppress("UNCHECKED_CAST")
        return when (ids) {
            is Int -> arrayOf(ids)
            is Array<*> -> ids.map { it as Int }.toTypedArray()
            is IntArray -> ids.toTypedArray()
            // Invalid parameter
            else -> arrayOf(-1)
        }
    }

    override fun equals(other: Any?): Boolean {
        if (other is Int) {
            return getIds().contains(other)
        }
        val lengthIds = getIds().size
        val lengthOtherIds = (other as VisibilityId).getIds().size
        return if (lengthIds == 1 && lengthOtherIds == 1 || lengthIds > 1 && lengthOtherIds > 1) {
            other.getIds().contentEquals(getIds())
        } else if (lengthIds == 1) {
            other.getIds().contains(getIds().first())
        } else if (lengthOtherIds == 1) {
            getIds().contains(other.getIds().first())
        } else super.equals(other)
    }

    override fun hashCode(): Int {
        return ids.hashCode()
    }
}
```

Then in my class I have an ArrayList<Visibility>() with the elements built like `Visibility(VisibilityId(3), false, "poi")`.

I then try to serialize my json data with **Gson().toJson()**

When I executed the code with **debug** flavour in my Android app everything was fine we end up with :
`[{"id":{"ids":3},"type":"poi","visible":false}]`
But when i switched my app to be in the **release** flavour then I ended up with this serialization : 
`[{"a":{"ids":3},"b":false,"c":"poi"}]`

The only solution i found is to create a **JsonSerializer** and force the name upon my variables. This is okay but I still didn't figured out why I ended up with a dictionary having alphabetical keys instead of my var key names.

I'd like to understand to avoid any bug later in my app that can happen on other models serialized by Gson().toJson() without personalised **JsonSerializer**

**Comment by lyubomyr-shaydariv** [comment]
You're most likely using a tool like ProGuard that obfuscates field names renaming the latter to `a`, `b` and upwards (whatever obfuscator). Of course, you don't need a custom type adapter per each such a class, but either take care of disabling obfuscation for a particular set of classes like those you want to serve as DTOs (`Visibility`, etc), or annotate each field with `@SerializedName` (a more clean and preferable way to me) and make sure the obfuscator does not obfuscate the annotation or strip it from the fields.

This is what comes to mind at first glance, but not sure why the `ids` field didn't get obfuscated though.

**Comment by Marcono1234** [comment]
As mentioned above, this is most likely caused by a code obfuscator. Maybe also have a look at the [android-proguard-example](https://github.com/google/gson/tree/master/examples/android-proguard-example).
