### ISSUE TITLE
Version 2.8.6 JDK 7 jar export error

### ISSUE THREAD

**Issue by wansleynery** [google/gson#1859]
Good morning,

The version 2.8.6 compiles the jar with module-info with JDK 9, at least. It looks wrong when compared with the compatibility of another versions.

![image](https://user-images.githubusercontent.com/42624198/107504403-004a8d00-6b7a-11eb-8c39-ad2093c895d0.png)
![image](https://user-images.githubusercontent.com/42624198/107503954-5ff46880-6b79-11eb-894e-37b98066a85d.png)
![image](https://user-images.githubusercontent.com/42624198/107504814-9a123a00-6b7a-11eb-9f3a-ae11dc799031.png)
![image](https://user-images.githubusercontent.com/42624198/107504598-54ee0800-6b7a-11eb-8262-4867f0c0b69a.png)

**Comment by Marcono1234** [comment]
Similar to  #1850 and #1627

**Comment by Marcono1234** [comment]
Can you please check if this issue still occurs with the latest Gson version? The way the `module-info.class` is included in the Gson JAR was changed and should hopefully now cause fewer issues. Also make sure to use the latest build tools and plugins (e.g. Gradle).

**Comment by Marcono1234** [comment]
I am going to close this because no answer has been provided. If you still experience this with the latest Gson version, feel free to comment here again with more details.
