### ISSUE TITLE
fromJson(String json, Class<T> classOfT) does not throw JsonSyntaxException when passing invalid json string

### ISSUE THREAD

**Issue by tandt53** [google/gson#1860]
Gson v2.8.6

Example code:
```
String text = "{name:\"sample name\",\"phone\":\"0117000532\",\"email\":\"sample_mail@gmail.com\",\"legalName\":\"sample legal name\",\"representPhone\":\"01170000001\"}";
        Gson gson = new Gson();
        try {
            gson.fromJson(text, JsonElement.class);
            System.out.println("text is VALID json string");
        } catch (JsonSyntaxException e) {
            System.out.println("text is INVALID json string");
        }
```
Ouput
```
text is VALID json string
```

`text` in sample is invalid json string, cause it does not contain double quote in `name`

**Comment by Marcono1234** [comment]
`Gson.fromJson` always parses leniently, regardless of what settings you used for the `GsonBuilder` or `JsonReader`, see also #372. Sadly this is not documented.

If you want strict parsing, you could first get the corresponding adapter for the class you want to parse through [`Gson.getAdapter(...)`](https://www.javadoc.io/doc/com.google.code.gson/gson/2.8.6/com.google.gson/com/google/gson/Gson.html#getAdapter(com.google.gson.reflect.TypeToken)) and then call `fromJson(...)` on the adapter.

**Comment by tandt53** [comment]
Thanks @Marcono1234 
I found a workaround solution for that [here](https://stackoverflow.com/questions/43233898/how-to-check-if-json-is-valid-in-java-using-gson/47890960#47890960)
