### ISSUE TITLE
#equals for JsonPrimitive with the same Float and LazilyParsedNumber values says they aren't equal

### ISSUE THREAD

**Issue by TimeConqueror** [google/gson#1864]
I have two `JsonObject`s, one is parsed from the file, and one is created manually.
Both contains some properties, where some are converted to `JsonPrimitive`s.

`JsonPrimitive` from the first object contains `LazilyParsedNumber` as a value.
`JsonPrimitive` from the second object, which I set manually, contains `Float` as a value.

Let's imagine that both of them contain the value `4558.08`, so it should be the same.
But when I try to compare them using `JsonPrimitive#equals`, it says, that they are not the same.

While calling this method, `JsonPrimitive` values are compared, using `Number#doubleValue()`.
When converting to double, `JsonPrimitive` with `LazilyParsedNumber` value becomes `4558.08`.
But` JsonPrimitive` with `Float` value becomes `4558.080078125`, so they are not the same.

So how can properly compare them?

**Comment by lyubomyr-shaydariv** [comment]
>  so they are not the same.

They [cannot](https://stackoverflow.com/questions/916081/convert-float-to-double-without-losing-precision) be equal.

> So how can properly compare them?

* either using the "[epsiloned](https://stackoverflow.com/questions/1088216/whats-wrong-with-using-to-compare-floats-in-java)" way;
* or using a container, say strings or `BigDecimal`s.

```java
public final class ComparisonTest {

	@Test
	public void testDoubleEquals() {
		final double v1 = 4558.08D;
		final double v2 = 4558.08F;
		Assertions.assertFalse(Math.abs(v1 - v2) < 0.00000001D);
	}

	@Test
	public void testBigDecimalEquals() {
		final JsonPrimitive v1 = new JsonPrimitive(new LazilyParsedNumber("4558.08"));
		final JsonPrimitive v2 = new JsonPrimitive(4558.08);
		Assertions.assertTrue(v1.getAsBigDecimal().equals(v2.getAsBigDecimal()));
	}

}
```

**Comment by TimeConqueror** [comment]
Got it, thanks!
