### ISSUE TITLE
GsonBuilder.create(): NoSuchMethodError

### ISSUE THREAD

**Issue by gafain** [google/gson#1867]
Hello, 
TOday I recompile my tomcat applicatio and I get this strange Error:
Before I use Gson 2.4, I try to upgrade to version 2.8.6 and same error.
My source is :
```
                GsonBuilder gsb = new GsonBuilder();
                Gson gs = gsb.create();

```
I get this error:
 java.lang.NoSuchMethodError: com.google.gson.Gson.<init>(Lcom/google/gson/internal/Excluder;Lcom/google/gson/FieldNamingStrategy;Ljava/util/Map;ZZZZZZZLcom/google/gson/LongSerializationPolicy;Ljava/lang/String;IILjava/util/List;Ljava/util/List;Ljava/util/List;)V
	at com.google.gson.GsonBuilder.create(GsonBuilder.java:597)

I get the source and I see that I get the error at this:

```
    return new Gson(excluder, fieldNamingPolicy, instanceCreators,
        serializeNulls, complexMapKeySerialization,
        generateNonExecutableJson, escapeHtmlChars, prettyPrinting, lenient,
        serializeSpecialFloatingPointValues, longSerializationPolicy,
        datePattern, dateStyle, timeStyle,
        this.factories, this.hierarchyFactories, factories);
```

**Comment by Marcono1234** [comment]
Most likely you have somewhere a direct or transitive dependency which uses an older Gson version, which causes issues at runtime. Please check your dependency hierarchy and make sure all dependencies use the latest version, 2.8.6.

**Comment by Marcono1234** [comment]
Are you still affected by this? If so, please try the latest Gson version and provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
