### ISSUE TITLE
Is this project actively maintained? Do you need help?

### ISSUE THREAD

**Issue by yeikel** [google/gson#1868]
Hi team, 

Last release for this project was in Oct, 2019 and there are over 400 issues and 155 PRs open at the time of this issue. 

Is this project still maintained?  Do you need help to manage it? 

Thank you!

**Comment by inder123** [comment]
Hi Yeikel,

The project is in mostly a maintenance mode, with few updates being accepted at this time. Gson is used very widely and 100% backward compatibility is very critical to us. We are also quite averse to expanding the API footprint substantially.

You can certainly help by looking at the open PRs that are small scoped and add review comments to help us accept or reject them. Also, please look at whether good test-cases are added.

Thanks
Inder
