### ISSUE TITLE
why ? to json return null

### ISSUE THREAD

**Issue by YanQin-JAVA** [google/gson#1872]
public static void main(String[] args) throws JsonProcessingException {
		class User{
			private String a;

			public User() {
			}

			public User(String a) {
				this.a = a;
			}

			@Override
			public String toString() {
				return "User{" +
						"a='" + a + '\'' +
						'}';
			}

			public String getA() {
				return a;
			}

			public void setA(String a) {
				this.a = a;
			}
		}

		ArrayList<Object> users = Lists.newArrayList(new User("a"), new User("b"));
		Gson gson = new GsonBuilder().create();
		String s = gson.toJson(new User("c"));
		String s1 = (new ObjectMapper()).writeValueAsString(users);
		System.out.println("s = " + s);
		System.out.println("s1 = " + s1);

	}

//return :
s = null
s1 = [{"a":"a"},{"a":"b"}]

**Comment by YanQin-JAVA** [comment]
gson version : 2.8.6

**Comment by Marcono1234** [comment]
Local classes are not supported. See #1510 and https://github.com/google/gson/blob/master/UserGuide.md#finer-points-with-objects.

(comment copied from lyubomyr-shaydariv's comment [here](https://github.com/google/gson/issues/1795#issuecomment-706591619))
