### ISSUE TITLE
InaccessibleObjectException with JDK 16 

### ISSUE THREAD

**Issue by tomparle** [google/gson#1875]
GSon (2.8.6) has trouble with JDK 16, seemingly due to https://bugs.openjdk.java.net/browse/JDK-8256358 and https://bugs.openjdk.java.net/browse/JDK-8260600 which prevent access through reflection to JDK internals.

This leads to these errors (for example when trying to serialize an empty list constructed with `Collections.emptyList()`) : 

```
java.lang.reflect.InaccessibleObjectException: Unable to make private java.util.Collections$EmptyList() accessible: module java.base does not "opens java.util" to unnamed module @ffaa6af
	at com.google.gson.internal.reflect.UnsafeReflectionAccessor.makeAccessible(UnsafeReflectionAccessor.java:44)
	at com.google.gson.internal.ConstructorConstructor.newDefaultConstructor(ConstructorConstructor.java:103)
	at com.google.gson.internal.ConstructorConstructor.get(ConstructorConstructor.java:85)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:54)
	at com.google.gson.Gson.getDelegateAdapter(Gson.java:541)
	at io.gsonfire.gson.WrapTypeAdapterFactory.create(WrapTypeAdapterFactory.java:26)
	at com.google.gson.Gson.getAdapter(Gson.java:458)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:56)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:208)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:145)
	at com.google.gson.Gson.toJson(Gson.java:704)
	at com.google.gson.Gson.toJson(Gson.java:683)
...
```

I would be happy to contribute but I do not even know how to fix this in Gson. Any ideas ?

**Comment by Marcono1234** [comment]
The problem might be that the internal class `ConstructorConstructor` always first tries to get the constructor using reflection before using a default constructor for `Collection` subtypes.

Though I am not sure if this can easily be solved. Maybe the simplest solution which also keeps backward compatibility would be to change this line to handle the exception from `setAccessible` and return `null` as well:
https://github.com/google/gson/blob/ceae88bd6667f4263bbe02e6b3710b8a683906a2/gson/src/main/java/com/google/gson/internal/ConstructorConstructor.java#L124-L126
Though [`InaccessibleObjectException`](https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/lang/reflect/InaccessibleObjectException.html) which is thrown there only exists since Java 9, but this project targets Java 6.
Therefore it might be necessary to catch `RuntimeException` (the subclass).

Note that I am not a maintainer of this project.

**Comment by roman-dzhadan** [comment]
@tomparle
One of many reasons, why Java introduced its modules was an attempt to encapsulate the internal JDK code and make sure that end-developers will not use it. It gives more flexibility for the Java language evolution, it allows to change the internals quickly and without obligation to support backward compatibility.

In the case of "gson" library, which uses reflection quite a lot. You still can use it with JDK16.
But you have to manually open and export the required modules with JAVA_OPTS arguments.

**Comment by tomparle** [comment]
Thank you for all your answers.
I tried a few hours but eventually could not even build the gson project, alone trying any modification.
I tried with gradle (plugin maven id not found) and Maven (ConcurrentException in bnd-maven-plugin) as well.
Unless someone kindly helps me to build the project, I unfortunately will not be able to progress any more for now.

**Comment by tomparle** [comment]
Update : I found it too hard to patch gson directly, so in a custom TypeAdapter I check if a type is not accessible (like the private class `java.util.Collections$EmptyCollection`), and use the corresponding accessible `ArrayList` instead. It works for now, so I consider it a good workaround for now.

**Comment by Marcono1234** [comment]
Would you mind leaving the issue open anyways?
That way other others might find this issue more easily, and it indicates to the maintainers that this issue is still unresolved (even if it may have a workaround).

**Comment by tomparle** [comment]
@Marcono1234 Sure, I wanted to mark it as "workaround available" but could not find how, other than closing it.
Reopened !

**Comment by masbaehr** [comment]
![image](https://user-images.githubusercontent.com/38694044/121309085-0bcc7b80-c902-11eb-81c4-cb278f05bbab.png)
Also having issues with JDK16 Cant use LinkdTreeMap anymore.
e.g to do the following:
	LinkedTreeMap translationMapR = gson.fromJson(reader, LinkedTreeMap.class);

**Comment by Marcono1234** [comment]
@masbaehr, that is unrelated to this issue. As the package name suggests (<code>com.google.gson.<b>internal</b></code>) `LinkedTreeMap` is an internal `Map` implementation of Gson. This issue has nothing to do with JDK 16; 2.8.6 added a module declaration which enforces that classes from the `internal` package cannot be used.
For your case should be able to simply use `Map` instead:
```java
Map translationMapR = gson.fromJson(reader, Map.class);
```
(Also note that for better type safety should should probably use [`TypeToken`](https://javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/reflect/TypeToken.html).)

**Comment by Marcono1234** [comment]
@tomparle (and everyone else interested), to spare you the duplicate work, I have implemented a potential fix for this in #1902. I don't know when / if the maintainers will merge it, but feel free to try it out and let me know whether is solves this issue.
(The incompatibility mentioned in that pull request won't affect you if you are running with JDK 16 or if you explicitly using `--illegal-access=deny`.)

**Comment by masbaehr** [comment]
> @masbaehr, that is unrelated to this issue. As the package name suggests (`com.google.gson.internal`) `LinkedTreeMap` is an internal `Map` implementation of Gson. This issue has nothing to do with JDK 16; 2.8.6 added a module declaration which enforces that classes from the `internal` package cannot be used.
> For your case should be able to simply use `Map` instead:
> 
> ```java
> Map translationMapR = gson.fromJson(reader, Map.class);
> ```
> 
> (Also note that for better type safety should should probably use [`TypeToken`](https://javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/reflect/TypeToken.html).)

Thanks for answering, I tried but now i get a classcast exception, i'm not using the internal class anymore (made a copy of it and called it "MyLinkedTreeMap". I've added the related imports.

Any idea why this happens? Maybe this is for a new issue though (unless im doing something wrong)

```
Caused by: java.lang.ClassCastException: class com.google.gson.internal.LinkedTreeMap cannot be cast to class xxxxxxx.xxxxxxxxxx.utils.MyLinkedTreeMap (com.google.gson.internal.LinkedTreeMap is in unnamed module of loader 'app'; xxxxxxx.xxxxxxxxxx.utils.MyLinkedTreeMap is in  `
```

```
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import java.lang.reflect.Type;
import java.util.Map;


	Gson gson = new Gson();
		try {
			JsonReader reader = new JsonReader(new InputStreamReader(inputStream, "UTF-8"));
			Type mapType = new TypeToken<Map<String,Map<String,String>>>() {}.getType();
			MyLinkedTreeMap translationMapR = gson.fromJson(reader, mapType);
			translationMap = translationMapR;
			reader.close();
		} catch (IOException e) {
			e.printStackTrace();
		}
```

![image](https://user-images.githubusercontent.com/38694044/121356405-17836680-c931-11eb-9628-18f8a5244ac2.png)

**Comment by tomparle** [comment]
@Marcono1234 congratulations for this PR !
It seems to have been quite some work, and to handle errors better than before.
I'm still not sure about what would be ideal for my use case, other than mapping some specific types like java.util.Collections$EmptyCollection to their corresponding, constructible equivalent like ArrayList. 
I'll consider this issue as a documentation for the workaround, as you suggested !

**Comment by Marcono1234** [comment]
The change required to fix this was actually not that big, most of it are whitespace changes because I changed the scope of the `try` block. The other changes are mostly to get helpful exception messages and to add a useful test for this.

> I'm still not sure about what would be ideal for my use case, other than mapping some specific types like java.util.Collections$EmptyCollection to their corresponding, constructible equivalent like ArrayList.

Just to make sure we are on the same page: The pull request should exactly handle your use case. Gson only uses the `ConstructorConstructor` during **de**serialization, however it creates it when the type adapter is request, even if only serialization is performed. In your use case the runtime type `java.util.Collections.EmptyList` will only ever be used using serialization, so you should never see the exception which the `ObjectConstructor` would throw, since you are likely either not performing any deserialization at all, or are using public types such as `List` as compile-time type (which Gson would then pick for deserialization).

**Comment by KENNYSOFT** [comment]
Workaround: add `--add-opens java.base/java.io=ALL-UNNAMED` to JVM.

**Comment by lvca** [comment]
Adding `--add-opens java.base/java.net=ALL-UNNAMED` worked for me (the issue was with using Stripe libs that depend on GSON).
