### ISSUE TITLE
[Question]: Return new ParameterizedType

### ISSUE THREAD

**Issue by Drjacky** [google/gson#1879]
In Moshi library, we could do something like this:
```kotlin
val observableEmissionType = getParameterUpperBound(0, returnType)
val successBodyType = getParameterUpperBound(0, observableEmissionType)
val delegateType = Types.newParameterizedType( //Types: com.squareup.moshi.Types -> https://square.github.io/moshi/1.x/moshi/com/squareup/moshi/Types.html#newParameterizedType-java.lang.reflect.Type-java.lang.reflect.Type...-
    Observable::class.java,
    successBodyType
)
```

How we could do the same in Gson?

In old versions, we had a similar thing:
https://javadoc.io/doc/com.google.code.gson/gson/1.7.1/com/google/gson/internal/$Gson$Types.html

**Comment by Marcono1234** [comment]
It sounds like you are looking for [`TypeToken.getParameterized(...)`](https://www.javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/reflect/TypeToken.html#getParameterized(java.lang.reflect.Type,java.lang.reflect.Type...)). This gives you a `TypeToken` on which you can then invoke `getType()` to get a `Type` (which is actually a `ParameterizedType`).
