### ISSUE TITLE
New FieldNamingPolicy: UPPER_CASE_WITH_UNDERSCORES

### ISSUE THREAD

**Issue by OmarHawk** [google/gson#1886]
Hi,

currently, I do try to integrate a service that uses a UPPER_CASE_WITH_UNDERSCORES naming scheme for their field names, e.g.:

```
{
  "PRODUCT_LIST" : {
    "PRODUCT" : [
      {
      "APPLICATION_CODE" : "secret application code",
      "PRODUCT_TYPE" : "product type value",
      "PRODUCT_NAME" : "product name"
      }
    ]
  }
}
```

Currently, GSON only supports LOWER_CASE_WITH_UNDERSCORES by default, so I would have to implement my own FieldNamingStategy class and possibly duplicate some code, like this:

```
this.gson = new GsonBuilder()
                .setFieldNamingStrategy(
                        f -> FieldNamingPolicy.LOWER_CASE_WITH_UNDERSCORES.translateName(f).toUpperCase(Locale.ENGLISH))
                .create();
```

So, ideally, something like this would be supported by GSON itself and I could use a new enum value.

**Comment by eamonnmcmanus** [comment]
Fixed by #2024.
