### ISSUE TITLE
How to I deserialize different json response for the same request to different bean object

### ISSUE THREAD

**Issue by duwangthefirst** [google/gson#1901]
for example, for the same request, the server may return:
```json
{
  "code":200,
  "data":{
    "xxx":"xxx"
  }
}
```
or:
```json
{
  "code":666,
  "error":"error detail"
}
```

And I'm using Android and Retrofit, so how should I handle this desrialization task?

the above question could be summarized as:
**how could hanndle deserialization on different condition(the json struction of response may differ)?**

Or maybe should I adjust the response structure?
**But many 3rdparty api return stuff just like above so It's impossible to adjust the response structure.**

**Comment by duwangthefirst** [comment]
and type and num of target bean object is pre-defined

**Comment by Marcono1234** [comment]
You can solve this by implementing a custom [`JsonDeserializer`](https://javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/JsonDeserializer.html) or [`TypeAdapterFactory`](https://javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/TypeAdapterFactory.html). `JsonDeserializer` parses the JSON data into an in-memory representation of `JsonElement` (and subtypes). `TypeAdapterFactory` creates `TypeAdapter` instances which read the JSON data from the stream and are therefore more efficient. However, `TypeAdapterFactory` can only be used if `code` is **always** the first member in the JSON data because its value is needed to determine how to parse the JSON data.

The following uses `JsonDeserializer`:
```java
public class GsonTypeSelectingTest {
    static class DataBody {
        public String xxx;
        
        @Override
        public String toString() {
            return "{xxx=" + xxx + "}";
        }
    }
    
    static abstract class Response {
        // Use a constant to make sure field name here and in JsonDeserializer match
        public static final String CODE_NAME = "code";
        
        @SerializedName(CODE_NAME)
        public int code;
    }
    
    static class SuccessResponse extends Response {
        public DataBody data;
        
        @Override
        public String toString() {
            return "success{code=" + code + ",data=" + data + "}";
        }
    }
    
    static class ErrorResponse extends Response {
        public String error;
        
        @Override
        public String toString() {
            return "error{code=" + code + ",error=" + error + "}";
        }
    }
    
    static class ResponseDeserializer implements JsonDeserializer<Response> {
        public static final ResponseDeserializer INSTANCE = new ResponseDeserializer();
        
        private ResponseDeserializer() {
        }
        
        @Override
        public Response deserialize(JsonElement json, Type typeOfT, JsonDeserializationContext context) throws JsonParseException {
            // Get `code` and depending on its value choose correct subclass
            int code = json.getAsJsonObject().get(Response.CODE_NAME).getAsInt();
            if (code == 200) {
                return context.deserialize(json, SuccessResponse.class);
            } else {
                return context.deserialize(json, ErrorResponse.class);
            }
        }
    }
    
    public static void main(String[] args) {
        // Should use `static final` field to reuse Gson
        Gson gson = new GsonBuilder()
            .registerTypeAdapter(Response.class, ResponseDeserializer.INSTANCE)
            .create();
        
        System.out.println(gson.fromJson("{\"code\":200,\"data\":{\"xxx\":\"test\"}}", Response.class));
        System.out.println(gson.fromJson("{\"code\":666,\"error\":\"error-detail\"}", Response.class));
    }
}
```

**Comment by duwangthefirst** [comment]
> You can solve this by implementing a custom [`JsonDeserializer`](https://javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/JsonDeserializer.html) or [`TypeAdapterFactory`](https://javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/TypeAdapterFactory.html). `JsonDeserializer` parses the JSON data into an in-memory representation of `JsonElement` (and subtypes). `TypeAdapterFactory` creates `TypeAdapter` instances which read the JSON data from the stream and are therefore more efficient. However, `TypeAdapterFactory` can only be used if `code` is **always** the first member in the JSON data because its value is needed to determine how to parse the JSON data.
> 
> The following uses `JsonDeserializer`:
> 
> ```java
> public class GsonTypeSelectingTest {
>     static class DataBody {
>         public String xxx;
>         
>         @Override
>         public String toString() {
>             return "{xxx=" + xxx + "}";
>         }
>     }
>     
>     static abstract class Response {
>         // Use a constant to make sure field name here and in JsonDeserializer match
>         public static final String CODE_NAME = "code";
>         
>         @SerializedName(CODE_NAME)
>         public int code;
>     }
>     
>     static class SuccessResponse extends Response {
>         public DataBody data;
>         
>         @Override
>         public String toString() {
>             return "success{code=" + code + ",data=" + data + "}";
>         }
>     }
>     
>     static class ErrorResponse extends Response {
>         public String error;
>         
>         @Override
>         public String toString() {
>             return "error{code=" + code + ",error=" + error + "}";
>         }
>     }
>     
>     static class ResponseDeserializer implements JsonDeserializer<Response> {
>         public static final ResponseDeserializer INSTANCE = new ResponseDeserializer();
>         
>         private ResponseDeserializer() {
>         }
>         
>         @Override
>         public Response deserialize(JsonElement json, Type typeOfT, JsonDeserializationContext context) throws JsonParseException {
>             // Get `code` and depending on its value choose correct subclass
>             int code = json.getAsJsonObject().get(Response.CODE_NAME).getAsInt();
>             if (code == 200) {
>                 return context.deserialize(json, SuccessResponse.class);
>             } else {
>                 return context.deserialize(json, ErrorResponse.class);
>             }
>         }
>     }
>     
>     public static void main(String[] args) {
>         // Should use `static final` field to reuse Gson
>         Gson gson = new GsonBuilder()
>             .registerTypeAdapter(Response.class, ResponseDeserializer.INSTANCE)
>             .create();
>         
>         System.out.println(gson.fromJson("{\"code\":200,\"data\":{\"xxx\":\"test\"}}", Response.class));
>         System.out.println(gson.fromJson("{\"code\":666,\"error\":\"error-detail\"}", Response.class));
>     }
> }
> ```

this deserializer seems to be effective for all apis globally.
Is there a solution for the following scene?
```
{
    "code":200,
    "data":[
        {
            "type":1,
            "xxx1":"xxx"
        },
        {
            "type":2,
            "xxx2":"xxx"
        }
    ]
}

```
as you can see, the data in success response is a json list. and I want to deserialize the item with `"type":1` to DataBean1 and deserialize the item with `"type":2` to DataBean2.
how could I make it work?
or is this api designed  badly?

**Comment by Marcono1234** [comment]
It would work in a similar way to handling the response. Continuing with the example code provided above, you would edit `SuccessResponse` so that its `data` field has type `List`. As element type of that list you could create an abstract base class, for this example let's call it `DataBeanBase`, and then model the separate types `DataBean1` and `DataBean2` as subclasses:
```java
class DataBeanBase {
    // `type` is common to all bean types
    public int type;
}

class DataBean1 extends DataBeanBase {
    public String xxx1;
}

class DataBean2 extends DataBeanBase {
    public String xxx2;
}

class SuccessResponse extends Response {
    public List<DataBeanBase> data;
}
```

And then similar to the code in the comment above, you would write a custom `JsonDeserializer<DataBeanBase>` which inspects the `type` JSON property and depending on its value tells Gson to either deserialize the object as `DataBean1` or `DataBean2` (or throw an exception for an unknown `type` value).

> or is this api designed badly?

This is difficult to answer for such an example. There are definitely valid use cases for such a pattern.

**Comment by Marcono1234** [comment]
I am closing this because I think this has been answered. Please let us know if you still have questions regarding this.
