### ISSUE TITLE
gson.fromJson returning object with LinkedTreeMap when using Map maptype

### ISSUE THREAD

**Issue by masbaehr** [google/gson#1906]
Hi, any idea why this happens:

MyLinkedTreeMap  is an exact copy of LinkedTreeMap (as this is now marked as internal with 2.8.6+ and cant be used outside)

```
static{
		Gson gson = new Gson();
		try {
			JsonReader reader = new JsonReader(new InputStreamReader(SimpleI18NProvider.class.getResourceAsStream("/translations.json"), "UTF-8"));
			Type mapType = new TypeToken<Map<String,Map<String,String>>>() {}.getType();
			MyLinkedTreeMap translationMapR = gson.fromJson(reader, mapType);
			translationMap = translationMapR;
			reader.close();
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
```

```
Caused by: java.lang.ClassCastException: class com.google.gson.internal.LinkedTreeMap cannot be cast to class xxxxxxx.xxxxxxxxxx.utils.MyLinkedTreeMap (com.google.gson.internal.LinkedTreeMap is in unnamed module of loader 'app'; xxxxxxx.xxxxxxxxxx.utils.MyLinkedTreeMap is in  
```

![image](https://user-images.githubusercontent.com/38694044/121356983-aee8b980-c931-11eb-8080-acc132b58576.png)

**Comment by Marcono1234** [comment]
Even if a class has exactly the same source code as another class (except for name and package), it is still a separate class and therefore you cannot cast to this class.
Is there a reason why you want to use the internal `LinkedTreeMap`? Will using `Map` not work for your use case? If so could you please provide more information or sample code.

**Comment by Marcono1234** [comment]
Closed because author did not respond and previous comment explained the situation.
