### ISSUE TITLE
Gson.fromJson cannot read 2 different Pojo classes

### ISSUE THREAD

**Issue by Jark5455** [google/gson#1921]
Lets say that there are 2 Pojo Classes, Class a, and Class b. If you create a Gson object and use Pojo Class a to de-serialize a string

`gson = com.google.gson.Gson()`
`gson.fromJson(string, a::class.java)`

and then you try de-serializing another string with a different format

`gson.fromJson(other_string, b::class.java)`

the compiler would return 
`Type mismatch: inferred type is b! but a was expected`

The same error occurs if creating a new instance of gson after de-serializing the first string.

Environment: Kotlin 1.5.21, built for android API 29

**Comment by Marcono1234** [comment]
Could you please provide a complete (small) code example?
It sounds like you are trying to assign a deserialized object of type `b` to a variable of type `a`. If `b` is not a subtype of `a`, then this won't work, but this is not specific to Gson. It is like trying to assign an `Int` to a variable of type `String`.

**Comment by Marcono1234** [comment]
Closing because no full example was provided.
