### ISSUE TITLE
Unable to make field private java.lang.String java.lang.Throwable.detailMessage accessible: module java.base does not "opens java.lang" to unnamed module @2baf3d81

### ISSUE THREAD

**Issue by meerpaluten** [google/gson#1922]
Error: https://paste.timo.cloud/vewikidonu.cs
JDK 16

i have regested a StringConverter in the builder, but unfortunately this did not fix this problem and now i am stuck.

**Comment by Marcono1234** [comment]
> StringConverter in the builder, but unfortunately this did not fix this problem and now i am stuck

Do you mean a `TypeAdapter` (or `JsonSerializer`)? Could you please provide a small, runnable example showing the code you are using.

**Comment by meerpaluten** [comment]
I made a JsonSerilizer for a Third Party class with extended RuntimeException, thats solve the issue. Thank you!

**Comment by sanjaydash** [comment]
Can you share the details what you have fixed , I am facing the same issue

**Comment by Marcono1234** [comment]
See https://github.com/google/gson/issues/2352#issuecomment-1481864208 for an explanation why serialization and deserialization is currently not supported for `Throwable` and subclasses and how you can write your own custom type adapter for serialization.
