### ISSUE TITLE
Mistake on Javadoc method description (?)

### ISSUE THREAD

**Issue by cfuendesign** [google/gson#1923]
**It appears to me that you've made a mistake on the description of the `parseReader​(Reader reader)` method of the JsonObject class.**

![image](https://user-images.githubusercontent.com/65634520/126888891-55d791bc-8464-4a6d-a5df-a3d3e93848c0.png)

You can check said method's doc yourself [here](https://javadoc.io/static/com.google.code.gson/gson/2.8.7/com.google.gson/com/google/gson/JsonParser.html)

**I believe it should be _"Parses the specified stream/reader into a parse tree"._**

I hope that my lack of English/Java knowledge isn't the problem here and I'm not wasting your time.

**Comment by eamonnmcmanus** [comment]
Thanks for the report! [This](https://github.com/google/gson/blob/f319c1b8e5ac1135ab253513f91d5ece6719cdf7/gson/src/main/java/com/google/gson/JsonParser.java#L59-L64) is the relevant code of `JsonParser.parseReader(Reader)`:

```java
      JsonReader jsonReader = new JsonReader(reader);
      JsonElement element = parseReader(jsonReader);
      if (!element.isJsonNull() && jsonReader.peek() != JsonToken.END_DOCUMENT) {
        throw new JsonSyntaxException("Did not consume the entire document.");
      }
      return element;
```

The second line calls `JsonParser.parseReader(JsonReader)`, which does not have a similar check for `END_DOCUMENT`. It really does return the next value, as its documentation says. It's certainly regrettable that two methods with the same name have such different behaviour, but the javadoc does appear to be correct.

**Comment by eamonnmcmanus** [comment]
Actually I think we *should* clarify the documentation to make it explicit that these methods behave differently despite having the same name.
