### ISSUE TITLE
RuntimeTypeAdapterFactory depends on internal API (JPMS, Java 9+)

### ISSUE THREAD

**Issue by miasma** [google/gson#1931]
The RuntimeTypeAdapterFactory code example (https://github.com/google/gson/blob/master/extras/src/main/java/com/google/gson/typeadapters/RuntimeTypeAdapterFactory.java) depends on the internal API class `com.google.gson.internal.Streams`, which is not exported when depending on gson in a JPMS project using module path.

Unless there's some easy fix available, currently one has to make a copy of Streams, LazilyParsedNumber, and TypeAdapters classes from the internal packages in order to use this provided class.

**Comment by Marcono1234** [comment]
> one has to make a copy of Streams, LazilyParsedNumber, and TypeAdapters classes

The classes `LazilyParsedNumber` and `TypeAdapters` would only be needed if you wanted to copy the exact code of `TypeAdapters.JSON_ELEMENT`, right? They don't appear to be needed directly by `RuntimeTypeAdapterFactory`.

I have tried implementing a fix in #1959, please let me know if that works for you.

---

Note that I am not a maintainer of this project.
