### ISSUE TITLE
Memory-leak.

### ISSUE THREAD

**Issue by GatitoUwU** [google/gson#1937]
Hi, I'm making a RestAPI that needs to convert data to json and vice versa. (to save that data in MongoDB)
The problem is that Gson#toJson() method generates a memory-leak.

Example:

`JsonArray jsonArray = playerData.getKills();`
`String data = gsonInstance.toJson(jsonArray);`

**Comment by eamonnmcmanus** [comment]
Could you say a bit more about the leak you are observing? What objects specifically are leaking? It's not apparent to me from [the source](https://github.com/google/gson/blob/81f25c8b45266383ab1d0956c22cf58b5af44a3f/gson/src/main/java/com/google/gson/Gson.java#L725) where there might be a leak.

**Comment by eamonnmcmanus** [comment]
Closing due to lack of response.
