### ISSUE TITLE
[Feature Request] bytesRead attribute with JsonReader

### ISSUE THREAD

**Issue by pranshujain22** [google/gson#1939]
Hello Gson Team,

Gson has been very helpful in reading files in stream, especially when the file size is huge.

Is it possible to have a method to get **_bytesRead_** (bytes that have been read so far), while using method <code>gson.fromJson(JsonReader reader, java.lang.reflect.Type typeOfT)</code>.

Please consider the following methods as a part of <code>JsonReader</code> :
- <code>jsonReader.getBytesRead()</code>
- <code>jsonReader.resetBytesRead()</code>, to reinitialize the bytesRead attribute to 0.

>This will be very helpful in splitting huge file into equal sized files.

**Comment by lyubomyr-shaydariv** [comment]
Can't this be done for a custom implementation of `InputStream`? I mean, what if you use `CountingInputStream` from either [Apache Commons](https://commons.apache.org/proper/commons-io/javadocs/api-2.5/org/apache/commons/io/input/CountingInputStream.html) or [Google Guava](https://guava.dev/releases/19.0/api/docs/com/google/common/io/CountingInputStream.html)?

**Comment by pranshujain22** [comment]
> CountingInputStream

No, actually I have a <code>gzip</code> format file, which contain list of objects. 
And I have to decompress it, read it and parse the <code>Objects</code> using <code>gson</code> in stream.

**Comment by lyubomyr-shaydariv** [comment]
I don't see why it doesn't fit your needs since it can be put both before and after decompressing your gzip: say, _open the input stream_ -> `GZIPInputStream` -> `CountingInputStream` -> _read/reset the byte count_ -> `InputStreamReader` -> `JsonReader` -> _inspect the byte count possibly opening a new `JsonWriter`_. Or am I getting it totally wrong, and if so can you please be more specific?

**Comment by pranshujain22** [comment]
I need to get the bytes size read after decompressing the gzip file and it should not write it to a file until the byte limit has been reached.

The process is something like this:
<code>FileInputStream</code> -> <code>GZIPInputStream</code> -> <code>InputStreamReader</code> -> <code>JsonReader</code> -> _parse object one by one from the file, if bytes read size exceeds limit -> write it to separate file -> reset bytesRead and move to next object parsing_.

Here I'll need the bytes read size once an object has been parsed using <code>gson.fromJson(JsonReader reader, Type typeOfT)</code> and based on that I have to write the object list to a separate file.

**Comment by pranshujain22** [comment]
<code>CountingInputStream</code> is working fine and meets the requirement  as well.
Thankyou for the quick help.
