### ISSUE TITLE
Performance - `JsonTreeReader` & `Streams.parse`

### ISSUE THREAD

**Issue by saiimons** [google/gson#1942]
Hi, I wanted to get an advice / or offer an idea that would improve performance in some situations.

To give some context, I have to work with structures where a key/value pair inside an object represents the destination type of said object.

```json
{
    "MyType" : "Foo",
    "bar" : "baz"
}
```

```kotlin
sealed class MyType {
    data class Foo(
        val bar: String
    ) : MyType()
}
```

Because of this specific structure, we have to make a call to `Streams.parse` to access the data within a `JsonObject` and let Gson deal with the rest:

```kotlin
class MyTypeAdapter(private val gson: Gson) : TypeAdapter<MyType>() {
    override fun read(`in`: JsonReader) : MyType {
        val obj = Streams.parse(`in`).asJsonObject
        val type = obj.get("MyType").asString
        return when (type) {
            "Foo" -> gson.fromJson(obj, MyType.Foo::class.java)
            else -> throw IllegalStateException("Unsupported $type")
        }
    }
}
```

When such structures contain other nested structures, we see many calls to `Streams.parse`, which are in fact reading again a document which was already processed, and available as a `JsonElement`.

One interesting improvement for this situation, would be to expose features from `JsonTreeReader` to `Streams`, in order to bypass the parsing, and obtain the current `JsonElement`, which would save a lot of processing, since it won't have to be rebuilt.

Would this be an interesting update to Gson ? Would this risk breaking how Gson operates ?

(I'll try to make a fork quickly with some data and a a flame graph demonstrating where time is being spent and how this could be improved)

**Comment by eamonnmcmanus** [comment]
In the abstract, the idea is interesting. However, Gson is in maintenance mode and we are generally unlikely to add new features such as this. You may find that [Moshi](https://github.com/square/moshi) better suits your needs.

**Comment by saiimons** [comment]
@eamonnmcmanus unfortunately, we heavily rely on `JsonElement` for a couple issues, and switching the whole codebase to Moshi is not something we could do right now.

I'll open a PR with the improvements, as I tested the changes locally, and I reduced some processing time by 90% for very large graphs, with a very small change.
