### ISSUE TITLE
Declare proguard rules automatically

### ISSUE THREAD

**Issue by BugsBunnyBR** [google/gson#1945]
Could gson have basic proguard rules automatically declared as retrofit does ?
https://github.com/square/retrofit/blob/master/retrofit/src/main/resources/META-INF/proguard/retrofit2.pro

**Comment by eamonnmcmanus** [comment]
I think that's exactly what #1929 proposes, but for that PR to proceed someone should write a test for it.

**Comment by thekingrenz23** [comment]
Any update to this one

**Comment by Marcono1234** [comment]
Default rules have been added by #2397 and will be available in the next version. However, would be great if you could try building Gson locally already and see if the snapshot version of Gson correctly applies the rules.

Also keep in mind that these default library rules cannot cover everything; if you have specific classes or fields which should be preserved and you are not using `@SerializedName` you might have to add additional rules for your build.
