### ISSUE TITLE
extras/src/main/java/com/google/gson/extras/examples/rawcollections/RawCollectionsExample.java

### ISSUE THREAD

**Issue by ladykraken** [google/gson#1955]
extras/src/main/java/com/google/gson/extras/examples/rawcollections/RawCollectionsExample.java

_Originally posted by @ladykraken in https://github.com/google/gson/pull/1953#discussion_r703660335_

**Comment by eamonnmcmanus** [comment]
I don't know what this means and I'm guessing it was a mistake.
