### ISSUE TITLE
`FieldNamingPolicy.upperCaseFirstLetter` uppercases trailing non-letters

### ISSUE THREAD

**Issue by Marcono1234** [google/gson#1965]
The internal method `FieldNamingPolicy.upperCaseFirstLetter(String)` which is used by some of the `FieldNamingPolicy` constants erroneously uppercases trailing non-letters. The reason for this is that for the last character it is not checked whether it is a letter or not.
There are some Unicode characters which are not letters, but for which `toUpperCase` returns a different character. An example for this is `U+0345` for which the uppercase character is `U+0399`.

Example:
```java
// Remains unchanged when it is not trailing
Integer.toHexString(upperCaseFirstLetter("\u0345_").charAt(0))
// Erroneously uppercased when trailing
Integer.toHexString(upperCaseFirstLetter("\u0345").charAt(0))
```

However, despite this character being allowed in a field name (`Character.isJavaIdentifierPart('\u0345')` is `true`), this only affects non-ASCII characters and it is therefore rather unlikely that this issue ever occurs in reality.

**Comment by eamonnmcmanus** [comment]
As you say, this is unlikely to matter in practice. But if you want to send a PR to fix it, we'd be happy to merge it.

**Comment by komminen** [comment]
Hi, we will volunteer to work on this issue in October/November. For the project maintainer, please let us know if this is okay and if you want it fixed.

**Comment by Marcono1234** [comment]
@komminen, I already have an alternative implementation which should fix this bug in a [separate project](https://github.com/Marcono1234/gson-record-type-adapter-factory/blob/9ae1f0a37d8492df06baf27365e9f894b861351d/src/main/java/marcono1234/gson/recordadapter/RecordComponentNamingStrategy.java#L128-L148); I just have not created a pull request proposing this implementation yet.
However, if you think that this implementation is flawed or can be improved, feel free to propose an alternative fix for this. I would also recommend using `\u2170` (or a similar char) in the tests then because (unlike the example char mentioned in the description) it can be used as Java identifier start and part (`Character.isJavaIdentifierStart` and `Character.isJavaIdentifierPart`) and might therefore be more realistic test data.

Otherwise I would create a pull request some time in the future.
