### ISSUE TITLE
Is there a way to automatically escape quotes in Java String using Gson

### ISSUE THREAD

**Issue by venkatmandavilli** [google/gson#1970]
This is my sample code:
`
class SampleObject {
    String field;
    public SampleObject() {
        field = "Great 'news'";
    }
    public String getField()
    {
        return field;
    }
}

private static class EscapeStringSerializer implements JsonSerializer<String> {
        @Override
        public JsonElement serialize(String s, Type type, JsonSerializationContext jsonSerializationContext) {
            return new JsonPrimitive(escapeSpecialChar(s));
        }

        public static String escapeSpecialChar(String string) {
            String escapes[][] = new String[][]{
                    {"\'", "\\'"}
            };
            for (String[] esc : escapes) {
                string = string.replace(esc[0], esc[1]);
            }
            return string;
        }
    }

  GsonBuilder builder = new GsonBuilder();
  builder.registerTypeAdapter(String.class, new EscapeStringSerializer());
  builder.disableHtmlEscaping();
  Gson customGson2 = builder.create();
  
  String json = customGson2.toJson(sampleObject);
`

I get two escape chars before the quotes instead of one. This is causing issues with serializing and deserializing the data.
The Output is: {"field":"Great \\'news\\'"} instead of {"field":"Great \'news\'"} Any pointers will be greatly appreciated. Thanks

**Comment by Marcono1234** [comment]
<details>
<summary>Issue description with fixed formatting</summary>

This is my sample code:
```java
class SampleObject {
    String field;
    public SampleObject() {
        field = "Great 'news'";
    }
    public String getField()
    {
        return field;
    }
}

private static class EscapeStringSerializer implements JsonSerializer<String> {
    @Override
    public JsonElement serialize(String s, Type type, JsonSerializationContext jsonSerializationContext) {
        return new JsonPrimitive(escapeSpecialChar(s));
    }

    public static String escapeSpecialChar(String string) {
        String escapes[][] = new String[][]{
                {"\'", "\\'"}
        };
        for (String[] esc : escapes) {
            string = string.replace(esc[0], esc[1]);
        }
        return string;
    }
}
```
```java
GsonBuilder builder = new GsonBuilder();
builder.registerTypeAdapter(String.class, new EscapeStringSerializer());
builder.disableHtmlEscaping();
Gson customGson2 = builder.create();

String json = customGson2.toJson(sampleObject);
```

I get two escape chars before the quotes instead of one. This is causing issues with serializing and deserializing the data.
The Output is: `{"field":"Great \\'news\\'"}` instead of `{"field":"Great \'news\'"}` Any pointers will be greatly appreciated. Thanks

</details>

---

The output `{"field":"Great \\'news\\'"}` looks correct to me. Your EscapeStringSerializer has written `\'` (literally) in the string and when converted to JSON the `\` is escaped and therefore becomes `\\`.
What is the expected content of the string, should it be `Great 'news'` or `Great \'news\'`? It sounds a bit like you are manually trying to escape `'` for the JSON output even though `'` does not need any escaping in JSON, and Gson would handle any necessary escaping on its own anyways.

Could you please give more information about where and in which way this is causing issues?

**Comment by venkatmandavilli** [comment]
I tested with all related combinations here, but it is the same issue.
```
String escapes[][] = new String[][]{
                    {"'", "\'"}
            }```
If you see in the sample code, the original String doesn't have the escape characters.

```
public SampleObject() {
field = "Great 'news'";
}```
I either get single quotes with no escape chars or double escape chars.

**Comment by Marcono1234** [comment]
>I either get single quotes with no escape chars or double escape chars.

That is probably expected. What you are printing is JSON output and characters such as `\` will be escaped in JSON strings. The JSON document will never contain only `\'`, that is not a valid JSON escape sequence, see [JSON string grammar](https://www.json.org/img/string.png).

But that should not be a problem; any compliant JSON library will convert `\` --to-JSON--> `\\` --from-JSON--> `\`, and similarly any compliant JSON library will leave a `'` as is without adding any backslashes.

Why do you have this `escapeSpecialChar` method? Do you really want a `\` in the result string, or are you trying to manually escape `'` in the JSON output?

**Comment by venkatmandavilli** [comment]
Thanks, ultimately I need an escape character in front of every special character. My usecase is to actually load key-value data from a file which has double quotes in some of it's values and being able to serialize and deserialize the data to pass it to couple of child processes. When I try to do this, what I have noticed is that those extra quotes in the values break the deserialization process as they do not let me create a valid json format String without escaping the quotes.

**Comment by Marcono1234** [comment]
> pass it to couple of child processes

Are you passing the data as command line argument when starting the child process? Maybe you should then rather perform escaping on the JSON result. Also in case you are on Windows, maybe the (unfortunately not well documented) System property `jdk.lang.Process.allowAmbiguousCommands` can help. It escapes the arguments to prevent Windows from splitting or merging them. Though in general you should avoid passing it as command line argument, and if possible create a temporary file or similar to transfer the data.

**Comment by Marcono1234** [comment]
Looks like this has been answered, so this issue can probably be closed.
