### ISSUE TITLE
No example in JsonParser/JsonElement specifications

### ISSUE THREAD

**Issue by Chealer** [google/gson#1972]
I never used Gson, but it seems `JsonParser` and `JsonElement` would best mimic how `org.json` works. It would be clearer if the specifications for at least one of these could include an example demonstrating their use though.

An example of JsonParser is available at https://github.com/google/gson/blob/master/extras/src/main/java/com/google/gson/extras/examples/rawcollections/RawCollectionsExample.java

**Comment by Marcono1234** [comment]
It is unfortunately not very well documented, but `JsonParser` parses the JSON data in lenient mode (e.g. it allows single quotes and non-finite floating point values).

The safest way which also respects the lenient setting of the `JsonReader` is to obtain the TypeAdapter for JsonElement from a Gson instance and then use the TypeAdapter:
```java
TypeAdapter<JsonElement> adapter = new Gson().getAdapter(JsonElement.class);

JsonArray array = new JsonArray();
array.add(1);
String json = adapter.toJson(array);
System.out.println(json);

JsonElement deserialized = adapter.fromJson("{\"a\":1}");
System.out.println(deserialized);
```

**Comment by eamonnmcmanus** [comment]
PRs to improve documentation, including javadoc comments, are always welcome!
