### ISSUE TITLE
Invalid time zone indicator ' ' and the solution given didn't work

### ISSUE THREAD

**Issue by mushixuan** [google/gson#2002]
# Gson version
2.8.6

# Java / Android version
java 8

This my Gson code:
`public final class JsonUtils {
    private static Gson gson = new Gson();

    public JsonUtils() {
    }

    public static String objectToJson(Object obj) {
        return gson.toJson(obj);
    }

    public static <T> T parseObject(String jsonString, Class<T> clazz) {
        return StringUtils.isEmpty(jsonString) ? null : gson.fromJson(jsonString, clazz);
    }

    public static <T> T parseObject(String jsonString, TypeToken<T> typeToken) {
        return StringUtils.isEmpty(jsonString) ? null : gson.fromJson(jsonString, typeToken.getType());
    }

    public static <T> List<T> parseArray(String jsonString, Class<T> clazz) {
        TypeToken typeToken = TypeToken.getArray(clazz);
        T[] array = (Object[])gson.fromJson(jsonString, typeToken.getType());
        return Arrays.asList(array);
    }
}
`
and the object code

`
public class SaasUnifiedPaymentDetailDTO implements Serializable {
    private String mobileNo;
    private Date addTime;
}
 `
and the exception:
![image](https://user-images.githubusercontent.com/26340701/139265179-3eaa03fc-e2e4-4c20-8a11-73c6c6a0b69c.png)

after I use the way this issue tells:
https://github.com/google/gson/issues/1297
it still reports the same exception

**Comment by mrzawmyowin** [comment]
.gitattributes

**Comment by mrzawmyowin** [comment]
http://rz350.mdn-119.com

**Comment by eamonnmcmanus** [comment]
Thanks, @Marcono1234 for the list of related bugs. I think we can consider this one a duplicate.

**Comment by PascoalBayonne** [comment]
Hey sir, nice answer but keep in mind that if the in.nextLong() == null then it will throw exception (obviously because it will expect a name).
