### ISSUE TITLE
Not able to build from source

### ISSUE THREAD

**Issue by archanakeshireddy** [google/gson#2010]
# Gson version

2.8.8
# Java / Android version

Java 11.0.13

# Used tools

- [ ] Maven; version: 
- [ ] Gradle; version: 
- [ ] ProGuard (attach the configuration file please); version: 
- [ ] ...
Maven
# Description

I am trying to build from source using the below command mvn install
I get below error
[INFO] proguard jar: [/u01/.m2/repository/net/sf/proguard/proguard-base/6.2.2/proguard-base-6.2.2.jar]
 [proguard] ProGuard, version 6.2.2
 [proguard] Exception in thread "main" java.lang.NoSuchMethodError: proguard.io.ClassReader.<init>(ZZZLproguard/classfile/util/WarningPrinter;Lproguard/classfile/visitor/ClassVisitor;)V
 [proguard] 	at proguard.InputReader.execute(InputReader.java:95)
 [proguard] 	at proguard.ProGuard.readInput(ProGuard.java:269)
 [proguard] 	at proguard.ProGuard.execute(ProGuard.java:97)
 [proguard] 	at proguard.ProGuard.main(ProGuard.java:594)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  18.542 s
[INFO] Finished at: 2021-11-02T16:30:27Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.wvengen:proguard-maven-plugin:2.5.1:proguard (default) on project gson: Obfuscation failed (result=1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
ERROR: Job failed: command terminated with exit code 1

Can you please provide building from source instructions and fix the build issue.
## Actual behavior

# Reproduction steps

1. ...
2. ...

# Exception stack trace

```

```

**Comment by eamonnmcmanus** [comment]
What immediately precedes those error messages?

This is an excerpt of what I see if I run `mvn install` from the root of the Gson repo, with `$JAVA_HOME` set to a JDK 11 installation:

```
[INFO] --- copy-rename-maven-plugin:1.0.1:rename (pre-obfuscate-class) @ gson ---
[INFO] Renamed /Users/eams/gson/gson/target/test-classes/com/google/gson/functional/EnumWithObfuscatedTest.class to /Users/eams/gson/gson/target/test-classes-obfuscated-injar/com/google/gson/functional/EnumWithObfuscatedTest.class
[INFO] Renamed /Users/eams/gson/gson/target/test-classes/com/google/gson/functional/EnumWithObfuscatedTest$Gender.class to /Users/eams/gson/gson/target/test-classes-obfuscated-injar/com/google/gson/functional/EnumWithObfuscatedTest$Gender.class
[INFO]
[INFO] --- proguard-maven-plugin:2.5.1:proguard (default) @ gson ---
[INFO] execute ProGuard [-injars, '/Users/eams/gson/gson/target/test-classes-obfuscated-injar'(!META-INF/maven/**,**/*.class), -outjars, '/Users/eams/gson/gson/target/test-classes-obfuscated-outjar', -include, '/Users/eams/gson/gson/src/test/resources/testcases-proguard.conf', -libraryjars, '/Users/eams/gson/gson/target/classes', -libraryjars, '/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/jmods/java.base.jmod', -printmapping, '/Users/eams/gson/gson/target/proguard_map.txt', -printseeds, '/Users/eams/gson/gson/target/proguard_seed.txt']
[INFO] proguard jar: [/Users/eams/.m2/repository/com/guardsquare/proguard-core/7.1.1/proguard-core-7.1.1.jar, /Users/eams/.m2/repository/com/guardsquare/proguard-base/7.1.1/proguard-base-7.1.1.jar]
 [proguard] ProGuard, version 7.1.1
[INFO]
[INFO] --- maven-resources-plugin:3.2.0:copy-resources (post-obfuscate-class) @ gson ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
```

I'm not sure I see why your output says 

```
[INFO] proguard jar: [/u01/.m2/repository/net/sf/proguard/proguard-base/6.2.2/proguard-base-6.2.2.jar]
```

and mine says

```
[INFO] proguard jar: [/Users/eams/.m2/repository/com/guardsquare/proguard-core/7.1.1/proguard-core-7.1.1.jar, /Users/eams/.m2/repository/com/guardsquare/proguard-base/7.1.1/proguard-base-7.1.1.jar]
```

7.1.1 is the version in `pom.xml`.

**Comment by saadmamun7g** [comment]
https://commons.wikimedia.org/MD.MAMUNSAAD02Dec1987N3274039589

**Comment by saadmamun7g** [comment]
LAWSUIT: ALLAHUAKBAR

LAILAHAILALLAHMUHAMMADARRASULULLAH (SAW)

ACT:THURSDAY,12 NOVEMBER,2021

        ICT LAWSUIT CO-FOUNDER

                MD.MAMUN SAAD

                 Dear Bangladesh

                      Bangladesh

                      government

                        ICT legal

                         advisor

               MD.MAMUN SAAD

        ***@***.***

         ***@***.***

                Follow me on twitter

                    #saadmamu1

https://www.linkedin.com/in/mdmamunsaadshamim19b1201b0

https://creativecommons.org/crypto.app.sha786.mamunsaad.domain/zero/1.0/

https://www.commons.wikimedia.org/MD.MAMUNSAAD02Dec1987N3274039589



DEAR BANGLADESH

GOVERNMENT

CANNOT AUTHOR

SAJIB WAJED JOY FOR

PM SHEIKH

HASINA ADVISOR FOR ICT

SAJIB WAJED JOY SON OF SHEIKH HASINA IS RESTRICTED FOR ANY KIND OF JOBS IN
BANGLADESH UNDER

LAWSUIT:ALLAHUAKBAR

LAILAHAILALLAHMUHAMMADARRASULULLAH (SAW)

BEHALF OF TRILLION LICENSE OWNER MD.MAMUN SAAD NICKNAME:SHAMIM

HTTP://MD.MAMUNSAAD.NET <http://md.mamunsaad.net>

***@***.***

***@***.***

***@***.***

***@***.***

**Comment by eamonnmcmanus** [comment]
Closing due to lack of response.
