### ISSUE TITLE
Fuzzing Gson by way of OSS-Fuzz

### ISSUE THREAD

**Issue by DavidKorczynski** [google/gson#2011]
Hi!

I was wondering if you would be interested in getting Gson fuzzed by OSS-Fuzz? Fuzzing is a technique for stress-testing applications and OSS-Fuzz is a service run by Google for fuzzing important open source projects, and it would be great to get Gson integrated with OSS-Fuzz. OSS-Fuzz will run the fuzzers continuously and report back with bug reports when bugs are found. These reports will have full stack traces, input triggers and more. If you are interested, then the only thing needed is an email(s) connected to a Google account that can be used for receiving the bugs reports, which can be put in the configuration file (project.yaml) over at the OSS-Fuzz repository.

I have set up an initial integration with OSS-Fuzz here: https://github.com/google/oss-fuzz/pull/6742 and this PR on the OSS-Fuzz repository includes a simple initial fuzzer. We can always extend with more fuzzers if you are happy to integrate. I would just need an email and then get this PR merged, following that we should be good to go and down the line we can also migrate fuzzers from OSS-Fuzz to Gson owns repository.

**Comment by eamonnmcmanus** [comment]
Yes, that sounds like it could be very useful! You can use my google.com account as the primary contact. My username is 8 letters: my first initial (without accent) and my last name.

**Comment by DavidKorczynski** [comment]
Am closing this as it has been integrated now!
