### ISSUE TITLE
Drop support for Java 6

### ISSUE THREAD

**Issue by eamonnmcmanus** [google/gson#2018]
Continuing to support Java 6 causes considerable headaches. Building with `-source 6 -target 6` is not supported in JDK versions after 11. I don't think we need to support further back than Java 7 even for the most ancient Android devices still in use.

**Comment by Marcono1234** [comment]
> I don't think we need to support further back than Java 7 even for the most ancient Android devices still in use.

Would it make sense to directly move to Java 8? Then Gson could in the future easily add support for `Optional` (https://github.com/google/gson/issues/1102) and the `java.time` package (https://github.com/google/gson/issues/1059), possibly by integrating https://github.com/google-gson/typeadapters.

**Comment by eamonnmcmanus** [comment]
I think we'll want Gson to be like Guava. Guava supports Java 7 for Android. In reality, Android tooling does support Java 8 language features such as lambdas even for old Android versions, but those old versions don't have Java 8 API features such as `java.util.Optional` and `java.time`. If we wanted to support those, I think we would either have to use reflection or have separate artifacts for Java 7 and Java 8.

At some point, Guava will probably stop supporting these old versions and then Gson can follow suit.
