### ISSUE TITLE
Gson can't parse when a use firebase api

### ISSUE THREAD

**Issue by gaabrielricci** [google/gson#2029]
# Gson version

    implementation 'com.google.code.gson:gson:2.8.9'

# Java / Android version

compileSdk 31
Android Studio Arct fox 20.3.1
i'm using kotlin: 1.6.0

# Used tools

- [Attached file ] Maven; version:  [build.txt](https://github.com/google/gson/files/7638632/build.txt)
- [ ] Gradle; version:  gradle-7.0.2-bin.zip
- [ Attached file] ProGuard (attach the configuration file please); version:  [proguard-rules.txt](https://github.com/google/gson/files/7638633/proguard-rules.txt)
- [ ] ...

    implementation 'com.google.firebase:firebase-firestore-ktx:24.0.0'
    implementation 'com.google.firebase:firebase-database-ktx:20.0.3'

# Description

when i debug my app in test version it works fine. But when i compile the signed version, inside  fragments Gson().fromJson(json,class) returns a class {a="", b="", c=""}, only in signed version, in test version it's ok.

I look it after imports firebase imports 
    implementation 'com.google.firebase:firebase-firestore-ktx:24.0.0'
    implementation 'com.google.firebase:firebase-database-ktx:20.0.3'

val obj = Gson().fromJson(it.asJsonObject,FraseServidor::class.java)

this conversion not works 

json example attached: [json.txt](https://github.com/google/gson/files/7638640/json.txt)

## Expected behavior

Convert my json in a expected class

## Actual behavior

convert my json in an empty different class

# Reproduction steps

1. http request gets a json
{
code:200,
msg:"message",
data:[array]
}

2. val data = json.get("data")

3. val obj = Gson().fromJson(data,myClass:class.java) -- here is the error

it all inside my fragment

# Exception stack trace

```
Has no exception onlye te return is this strange class 

{
a="",
b="",
 c=""
}

```

**Comment by Marcono1234** [comment]
This sounds like ProGuard obfuscated your class and therefore Gson is only seeing the obfuscated field names (`a`, `b` and `c`).
You will have to either use Gson's [`SerializedName`](https://javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/annotations/SerializedName.html) annotation and manually specify the field names or you have to [configure ProGuard to keep these classes](https://www.guardsquare.com/manual/configuration/usage#keepoptions).

There is a [ProGuard example](https://github.com/google/gson/tree/master/examples/android-proguard-example) here in this project; but there are also a lot of guides out there.

Please report back if that helped.

**Comment by gaabrielricci** [comment]
Hi, work's fine with 
    @SerializedName("variable")

Thanks.
