### ISSUE TITLE
toJson escapes "=" unnecessarily in raw strings

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gson#203]
```
What steps will reproduce the problem?
1. Create an object with a single String field.
2. Set field to "http://someUrl.com?a=b"
3. Attempt to convert the object to json via gson.toJson

What is the expected output? What do you see instead?
I would expect the URL to be serialized exactly as it is written. Instead, 
the equals sign is encoded as \u003d.

What version of the product are you using? On what operating system?
1.4


```

Original issue reported on code.google.com by `arcanef...@gmail.com` on 20 Apr 2010 at 5:08

**Comment by jianwu** [comment]
It's un-reasonable to enable html escaping. This escape is un-necessary in most of situation.

**Comment by yubing24** [comment]
I am having exactly the same issue here: trying to export an object that contains an equal sign in URL but only got a string contains the escaping character instead. If the object is exported to JSON in classes of different hierarchies, then each class that may contain the original class needs to use GsonBuilder and explicitly disabling HTML escaping.

A solution should allow that if nested object specifies disabling HTML escaping, then outer classes should not need to specify it again. Redundancy is always the enemy of software engineering.
