### ISSUE TITLE
faill to build from the source, one error in com.google.gson.functional.EnumWithObfuscatedTest 

### ISSUE THREAD

**Issue by sergiomb2** [google/gson#2045]
# Gson version
'2.8.8'
 
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.015 s <<< FAILURE! - in com.google.gson.functional.EnumWithObfuscatedTest
[ERROR] com.google.gson.functional.EnumWithObfuscatedTest.testEnumClassWithObfuscated  Time elapsed: 0.015 s  <<< FAILURE!
junit.framework.AssertionFailedError: Enum is not obfuscated
at com.google.gson@2.8.8/com.google.gson.functional.EnumWithObfuscatedTest.testEnumClassWithObfuscated(EnumWithObfuscatedTest.java:50)

# Java / Android version

11.0.13

# Used tools

- [X] Maven; version: 
- [ ] Gradle; version: 
- [ ] ProGuard (attach the configuration file please); version: 
- [ ] ...

# Description

[ERROR] Tests run: 1063, Failures: 1, Errors: 0, Skipped: 1 

## Expected behavior
Failures:0 

## Actual behavior

# Reproduction steps

1. ...
2. ...

# Exception stack trace

```

```

**Comment by Marcono1234** [comment]
Which build command are you using? For me `mvn clean verify` (which includes the Maven `package` phase) works without issues.
Could you please include the Maven build output as attached text file here? It should contain the following logged plugin executions:
- `copy-rename-maven-plugin:1.0.1:rename (pre-obfuscate-class) @ gson`
- `proguard-maven-plugin:2.5.3:proguard (default) @ gson`
- `maven-resources-plugin:3.2.0:copy-resources (post-obfuscate-class) @ gson`

Could you please also try building with the latest changes from the `master` branch? Though, I am not aware of any build issues in 2.8.8.

**Comment by sergiomb2** [comment]
https://koji.fedoraproject.org/koji/taskinfo?taskID=80734346 ,
Fedora (unfortunately ) don't have copy-rename-maven-plugin , neither proguard-maven-plugin , so I had to remve the plugins is that matters ? 
Thank you

**Comment by Marcono1234** [comment]
Yes the test `EnumWithObfuscatedTest` requires the plugins `copy-rename-maven-plugin`, `proguard-maven-plugin` and `maven-resources-plugin` to work correctly because it tests Gson interaction with a class obfuscated by ProGuard.
However, if you are editing the POM anyways, you could probably [add an exclusion pattern](https://maven.apache.org/surefire/maven-surefire-plugin/examples/inclusion-exclusion.html#Exclusions) for `EnumWithObfuscatedTest`.

**Comment by sergiomb2** [comment]
ok, now I built successfully the package , I will updated it on Fedora.
Many tanks for your support
