### ISSUE TITLE
the url of reademe.Md in invalid.

### ISSUE THREAD

**Issue by vio-lin** [google/gson#2057]
[this page](https://sites.google.com/site/gson/streaming)](https://sites.google.com/site/gson/streaming)

**Comment by Marcono1234** [comment]
Why do you think the URL is invalid? For me the URL works without issues (though that site might be outdated). What is the issue you are experiencing?

**Comment by vio-lin** [comment]
![image](https://user-images.githubusercontent.com/12695349/149721140-d63149c5-9fb8-48a5-ab2f-7de8d2e1ebea.png)
maby i am in china but the other url in readMe is work well for me.

**Comment by HeZean** [comment]
Surely you need VPN to access this cite, having the domain *google.com*, it is blocked by the great firewall.
