### ISSUE TITLE
I have a pickUpLimitTime field in my data bean, which, when using gson transformation ,Its value is always null, why is that?

### ISSUE THREAD

**Issue by aijie1712** [google/gson#2092]
# Gson version

json data :  {
  "pickUpLimitTime": "2022-03-15 10:43:32",
  "name": "zhangsan",
  "age": 1
}
bean: TestBean{pickupLimitTime='null', name='zhangsan', age=1}

I have a pickUpLimitTime field in my data bean, which, when using gson transformation ,Its value is always null, why is that?

**Comment by Marcono1234** [comment]
> bean: TestBean{pickupLimitTime='null', name='zhangsan', age=1}

It looks like your field has a lowercased `u`, but in your JSON it is uppercased: pick<del>u</del><ins>U</ins>pLimitTime

**Comment by lacdyboy10** [comment]
dữ liệu json: {
"pickUpLimitTime": "2022-03-15 10:43:32",
"name": "zhangsan",
"age": 1
}
bean: TestBean {pickupLimitTime = 'null', name = 'zhangsan' , tuổi = 1}
