### ISSUE TITLE
Android parsing exceptions, found three times

### ISSUE THREAD

**Issue by huangdashun** [google/gson#2093]
# Gson version
2.8.5

# Java / Android version
java：1.8
android:  
        compileSdk = 29
        buildVersion = "29.0.3"
        minSdk = 21
        targetSdk = 29

# Description
invoke Gson toJsons Method, The returned result is error. Upload to the server, a total of three errors were found。
  public String toJson(Object src) {
    if (src == null) {
      return toJson(JsonNull.INSTANCE);
    }
    return toJson(src, src.getClass());
  }

Server Log:

![image](https://user-images.githubusercontent.com/16255100/159854482-e203fff4-02f2-4db2-b787-e44a54da9c9e.png)

looking forward to a reply

**Comment by Marcono1234** [comment]
Could you please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), for example in the form of a demo GitHub repository? Additionally please try using the latest Gson version just to be sure (currently 2.9.0).

(Note that I am not a member of this project)

**Comment by huangdashun** [comment]
Ok, thank you. Let's try the new version

**Comment by huangdashun** [comment]
> This looks like memory corruption. I note that the change from `n` to `o` and the change from `"` to `#` both involve changing the low bit from 0 to 1 (0x6e -> 0x6f, 0x22 -> 0x23). I don't think it is Gson that is responsible for the corruption. Possibly your server hardware is defective?
Ok, thank you
