### ISSUE TITLE
When the Object property String type is stored as the Base64 encoding of the image, the property value will change after converting to JSON

### ISSUE THREAD

**Issue by black-and** [google/gson#2107]
# Gson version

# Java / Android version

# Used tools

- [ ] Maven; version: 
- [ ] Gradle; version: 
- [ ] ProGuard (attach the configuration file please); version: 
- [ ] ...

# Description

## Actual behavior

# Reproduction steps

1. ...
2. ...

# Exception stack trace

```

```

**Comment by eamonnmcmanus** [comment]
There isn't enough information here for us to act on the issue. I'm closing, but feel to reopen with code that reproduces the problem and the data that it needs. (You can attach files to the issue if necessary.)
