### ISSUE TITLE
Could all of you experiencing this issue please describe your project:

### ISSUE THREAD

**Issue by Mems1995** [google/gson#2112]
Could all of you experiencing this issue please describe your project:
- the Java version the project is targeting
- the build tool you are using
- the dependency management tool your are using

And describe where this issue is occuring:
- when building your project? (at which build step, attach the relevant part of the log if possible)
- during runtime? (provide the stack trace and some context if possible)

_Originally posted by @Marcono1234 in https://github.com/google/gson/issues/1627#issuecomment-634510150_

**Comment by LuisR091197** [comment]
> no
