### ISSUE TITLE
I've tried `jarjar` solution but it does not work with gradle 4.x due to

### ISSUE THREAD

**Issue by LuisR091197** [google/gson#2117]
I've tried `jarjar` solution but it does not work with gradle 4.x due to 
```
Caused by: org.gradle.internal.resources.ResourceDeadlockException: An attempt was made to execute build operations inside of a resource lock transform.  Aborting to avoid a deadlock.
```

Setting up `jarjar` was not very straightforward to me so I will fragment from my `build.gradle` here:
```groovy
buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'org.anarres.jarjar:jarjar-gradle:1.0.1'
    }
}
apply plugin: 'org.anarres.jarjar'
```

my attempts to fix the problem:
```groovy
...
  dependencies {
    compile jarjar.repackage {
      from('com.google.code.gson:gson:2.8.6') {
        classDelete "com.google.gson"
       }
     }
...
```

`classDelete` does not work with `module-info` or `module-info.class` as `classDelete` expects class name not a file. So the comment https://github.com/seancfoley/IPAddress/issues/16#issuecomment-452564690 is misleading.

Have tried `archiveExclude` and `archiveBypass` but they failed with same error.

I however expect those solutions will work for some other gradle versions (ResourceDeadlockException was added in 4.x)

_Originally posted by @chrmod in https://github.com/google/gson/issues/1627#issuecomment-856734057_

**Comment by eamonnmcmanus** [comment]
I'm not sure what this issue is and I'm closing it for lack of detail. Please reopen if there is a specific context.
