### ISSUE TITLE
Make JsonWriter.deferredName protected

### ISSUE THREAD

**Issue by reinert** [google/gson#2124]
# Problem solved by the feature

I have a "select only" dynamic filtering requirement on instance level and I'm extending JsonWriter to insert the field filtering logic so I can dynamically filter different fields per Gson.toJson call. The problem is that I need to get and set the `deferredName` in order to skip some fields, but this field is private. Currently, I'm doing it using Unsafe, but I would like to do it seamlessly.

ps: The existing exclusion feature doesn't fit my requirements. 

# Feature description

Change the JsonWriter.deferredName modifier from private to protected, so subclasses can get/set this field.

# Alternatives / workarounds

Use Unsafe to modify the field's value.

**Comment by Marcono1234** [comment]
Could you please provide a short example showcasing your use case? Would it not be possible to override the method `JsonWriter.name(String)` and implement your logic there (and maybe override the `value(...)` methods too)?

----

Note that I am not a member of this project.

**Comment by reinert** [comment]
Hey @Marcono1234, thanks for replying. I'm writing an adapter for the [requestor](https://github.com/reinert/requestor/tree/net) library, which I'll be launching a new version soon. I was already overriding all value methods except for the name method. Now overriding the name method I could come up with a solution for my requirement. Thanks for the nudge!
