### ISSUE TITLE
Can't deserialized EnumMap with override toString()

### ISSUE THREAD

**Issue by Evyde** [google/gson#2131]
# Gson version

2.9.0

# Java / Android version

JDK 17.0.2

# Used tools

- [X] Maven; version: 3.8.5

# Description

When serialize EnumMap to Json, it has strange behavior that calls `toString()` instead of `name()` of enum key unlike when serialize the normal enum type do.

## Expected behavior

```json
{"single_fruit":"APPLE","multi_fruit":{"APPLE":3,"BANANA":2}}
```

## Actual behavior

```json
{"single_fruit":"APPLE","multi_fruit":{"Golden Apple":3,"Green Banana":2}}
```

# Reproduction steps

See this simple program below.
```java
import com.google.gson.Gson;

import java.util.EnumMap;
import java.util.ResourceBundle;


public class Main {

    public enum Fruit {
        APPLE,
        BANANA;
        private final ResourceBundle bundle = ResourceBundle.getBundle("Main");

        @Override
        public String toString() {
            return bundle.getString(this.name());
        }
    }
    public static class FruitData {
        public Fruit single_fruit;
        public EnumMap<Fruit, Integer> multi_fruit;
    }
    public static void main(String[] args) {
        Gson jsonParser = new Gson();
        FruitData f = new FruitData();
        f.single_fruit = Fruit.APPLE;
        f.multi_fruit = new EnumMap<>(Fruit.class);
        f.multi_fruit.put(Fruit.APPLE, 3);
        f.multi_fruit.put(Fruit.BANANA, 2);

        System.out.println(jsonParser.toJson(f));

        // it should be successful
        // System.out.println(jsonParser.fromJson(jsonParser.toJson(f), FruitData.class));
    }
}
```

Main.properties
```properties
APPLE=Golden Apple
BANANA=Green Banana
```

# Exception stack trace

```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "key" is null
	at java.base/java.util.EnumMap.typeCheck(EnumMap.java:736)
	at java.base/java.util.EnumMap.put(EnumMap.java:264)
	at java.base/java.util.EnumMap.put(EnumMap.java:78)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:188)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:130)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)
	at com.google.gson.Gson.fromJson(Gson.java:991)
	at com.google.gson.Gson.fromJson(Gson.java:956)
	at com.google.gson.Gson.fromJson(Gson.java:905)
	at com.google.gson.Gson.fromJson(Gson.java:876)
	at Main.main(Main.java:35)
```

## TODO List

- [X] Update README/User Guide to add `enableComplexMapKeySerialization()` things. (Fixed by #2138 )

**Comment by Marcono1234** [comment]
Relates to / duplicates #127, #1722, #1920

(Note that I am not a member of this project.)

**Comment by Evyde** [comment]
> Relates to / duplicates (重复) #127, #1722, #1920
> 
> (Note that I am not a member of this project.)

Thanks for mentioning these issues.
I've checked the source code before but not certitude that problem is caused by [THIS](https://github.com/google/gson/blob/96ab171eb48dcea94fd9b8f425f65c531e6c3aad/gson/src/main/java/com/google/gson/internal/bind/MapTypeAdapterFactory.java#L244). Now I'm certainty this caused this problem: It should process EnumMap independently.
After checking these issues, I also find a temporary method to solve this issue(Also use code above for demonstration):
```java
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import java.util.EnumMap;
import java.util.ResourceBundle;


public class Main {

    public enum Fruit {
        @SerializedName("APPLE")
        APPLE,
        @SerializedName("BANANA")
        BANANA;
        private final ResourceBundle bundle = ResourceBundle.getBundle("Main");

        @Override
        public String toString() {
            return bundle.getString(this.name());
        }
    }
    public static class FruitData {
        public Fruit single_fruit;
        public EnumMap<Fruit, Integer> multi_fruit;
    }
    public static void main(String[] args) {
        Gson jsonParser = new GsonBuilder().enableComplexMapKeySerialization().create();
        FruitData f = new FruitData();
        f.single_fruit = Fruit.APPLE;
        f.multi_fruit = new EnumMap<>(Fruit.class);
        f.multi_fruit.put(Fruit.APPLE, 3);
        f.multi_fruit.put(Fruit.BANANA, 2);

        System.out.println(jsonParser.toJson(f));

        // it should be successful now
        System.out.println(jsonParser.fromJson(jsonParser.toJson(f), FruitData.class));
    }
}
```
Diff from code above:
```java
import com.google.gson.GsonBuilder;
...
        @SerializedName("APPLE")
        APPLE,
        @SerializedName("BANANA")
        BANANA;
...
        Gson jsonParser = new GsonBuilder().enableComplexMapKeySerialization().create();
...
```
But this issue should be maintain open as this bug still exists after those issues & PRs.

**Comment by Marcono1234** [comment]
> I've checked the source code before but not certitude that problem is caused by [THIS](https://github.com/google/gson/blob/96ab171eb48dcea94fd9b8f425f65c531e6c3aad/gson/src/main/java/com/google/gson/internal/bind/MapTypeAdapterFactory.java#L244). Now I'm certainty this caused this problem

I think that is unrelated to your original issue since that code is used for 'complex map key serialization' (which you had not enabled initially). For non-'complex map key serialization' (the default) the problem is the usage of `String.valueOf` here:
https://github.com/google/gson/blob/96ab171eb48dcea94fd9b8f425f65c531e6c3aad/gson/src/main/java/com/google/gson/internal/bind/MapTypeAdapterFactory.java#L206

Your workaround to use `enableComplexMapKeySerialization()` is a good idea. You can probably even use that without having to use `@SerializedName` on the enum constants.

**Comment by Evyde** [comment]
> > I've checked the source code before but not certitude that problem is caused by
https://github.com/google/gson/blob/96ab171eb48dcea94fd9b8f425f65c531e6c3aad/gson/src/main/java/com/google/gson/internal/bind/MapTypeAdapterFactory.java#L244
Now I'm certainty this caused this problem
> 
> I think that is unrelated to your original issue since that code is used for 'complex map key serialization' (which you had not enabled initially). For non-'complex map key serialization' (the default) the problem is the usage of `String.valueOf` here:
> 
> https://github.com/google/gson/blob/96ab171eb48dcea94fd9b8f425f65c531e6c3aad/gson/src/main/java/com/google/gson/internal/bind/MapTypeAdapterFactory.java#L206
> 
> Your workaround to use `enableComplexMapKeySerialization()` is a good idea. You can probably even use that without having to use `@SerializedName` on the enum constants.

Got it, thanks.
Does this or GsonBuilder configuration things need to be mentioned in the User Guide like a table of contents or pointer to JavaDoc?

**Comment by Marcono1234** [comment]
> Does this or GsonBuilder configuration things need to be mentioned in the User Guide like a table of contents or pointer to JavaDoc?

Yes might indeed be good to mention `Map` serialization in general, including `enableComplexMapKeySerialization()` and the `toString()` issue, in the User Guide, maybe below ["Collection Examples"](https://github.com/google/gson/blob/master/UserGuide.md#TOC-Collections-Examples).

What do you think? If you want I can create a pull request with an initial draft for this.

**Comment by Evyde** [comment]
> Yes might indeed be good to mention `Map` serialization in general, including `enableComplexMapKeySerialization()` and the `toString()` issue, in the User Guide, maybe below ["Collection Examples"](https://github.com/google/gson/blob/master/UserGuide.md#TOC-Collections-Examples).
> 
> What do you think? If you want I can create a pull request with an initial draft for this.

I think it is no necessary to open a independent PR to update README especially this only need just a single sentence such as:
> If you are using a Map with complex key such as EnumMap, just call `enableComplexMapKeySerialization()` in GsonBuilder to have your complex key serialized properly as referenced at [JavaDoc].(https://www.javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/GsonBuilder.html).

, you can do this in your next feature PR.

**Comment by Marcono1234** [comment]
Have created #2138 now which also documents Map serialization and deserialization in general. You can see the rendered version here: https://github.com/Marcono1234/gson/blob/marcono1234/map-serialization-user-guide/UserGuide.md#TOC-Maps-Examples

I made this a separate PR and did not include it in any other PR to make it easier for the maintainers to review.

**Comment by Evyde** [comment]
> Have created #2138 now which also documents Map serialization and deserialization in general. You can see the rendered version here: https://github.com/Marcono1234/gson/blob/marcono1234/map-serialization-user-guide/UserGuide.md#TOC-Maps-Examples
> 
> I made this a separate PR and did not include it in any other PR to make it easier for the maintainers to review.

I reviewed this changed README and was extremely satisfied with it. Thanks for your working.
This issue will be closed when this PR been merged.
