### ISSUE TITLE
JsonPrimitive#equals Method behaves incorrect when used with BigInteger

### ISSUE THREAD

**Issue by noeppi-noeppi** [google/gson#2144]
# Gson version
2.9.0

# Java / Android version
Eclipse Adoptium OpenJDK 64-Bit Server VM 17.0.2+8 on Linux

# Used tools
- [ ] Maven; version: 
- [x] Gradle; version: 7.3.3
- [ ] ProGuard (attach the configuration file please); version: 
- [ ] ...

# Description
Two `JsonPrimitive`s with `BigInteger` values return `true` from their `equals` method if their long value obtained from `Number#longValue` is equal. This for example causes the numbers `23648748948963264236478263434` and `808933803388026932016705674` to be considered equal.

This is because both numbers are greater than `Long.MAX_VALUE`, so only the least significant 64 bits of these numbers are considered in the `longValue()` method. These happen to be `6484271001536295050` for both of the numbers, so `JsonPrimitive` considers them equal.

## Expected behaviour
The expected behaviour is that `JsonPrimitive#equals` returns `false` for values which don't actually equal each other.

## Actual behaviour
The actual behaviour is that `JsonPrimitive#equals` returns `true` for `BigIntegers` whose 64 least significant bits are the same.

# Reproduction steps
```java
JsonPrimitive p1 = new JsonPrimitive(new BigInteger("23648748948963264236478263434"));
JsonPrimitive p2 = new JsonPrimitive(new BigInteger("808933803388026932016705674"));
System.out.println(Objects.equals(p1, p2)); // is true, should be false
```

# Exception stack trace
No exception occurred.

**Comment by Marcono1234** [comment]
Seems to be related to #904

**Comment by MaicolAntali** [comment]
This issue can be closed. Related PR: #2311

**Comment by Marcono1234** [comment]
@MaicolAntali, thanks! The reproduction steps provided above print `false` now, as expected.
