### ISSUE TITLE
Cannot resolve symbol 'TypeAdapterRuntimeTypeWrapper'

### ISSUE THREAD

**Issue by DashReza7** [google/gson#2147]
https://github.com/google/gson/blob/cbc0af867b898d9e8244f268f4ffe37dfcaf8ea7/gson/src/main/java/com/google/gson/internal/bind/MapTypeAdapterFactory.java#L153

any idea why I get this error?

```
java: cannot find symbol
  symbol:   class TypeAdapterRuntimeTypeWrapper
  location: class TypeAdapters.MapTypeAdapterFactory.Adapter<K,V>
```

**Comment by Marcono1234** [comment]
I assume this is based on [your StackOverflow question](https://stackoverflow.com/q/73019979). As explained there, `MapTypeAdapterFactory` is an internal class and you should not copy its source code to your project.
