### ISSUE TITLE
Gson can throw StackOverFlowError which will most likely not be caught

### ISSUE THREAD

**Issue by fan87** [google/gson#2161]
# Gson version
2.9.0

# Description
Gson could throw StackOverFlowError with `"[" * 8000`, but most people will only catch Exception, not Error.

I don't think it's a real "security" vuln since most servers would catch every Throwable thrown by the code that handles the request instead of just killing the entire server but just in case.

## Expected behavior
Throws a JSON syntax exception

## Actual behavior
Throws an Error, which most people won't be catching

# Reproduction steps
```java
        Gson gson = new Gson();
        StringBuilder out = new StringBuilder();
        for (int i = 0; i < 8000; i++) {
            out.append("[");
        }

        try {
            gson.fromJson(out.toString(), JsonArray.class);
        } catch (Exception ignored) {
            System.out.println("Invalid Json Body!");
            // Most people will only be catching Exception, not Error
        }
```

# Exception stack trace
(What a normal StackOverFlowError stacktrace looks like)
```
        (repeated until it throws stackoverflowerror)
	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:718)
```

**Comment by eamonnmcmanus** [comment]
I think this is probably fixed by https://github.com/google/gson/pull/1912. However we haven't made a release with that change in it yet. If you're motivated, you could try building a current snapshot and seeing if the problem persists there.

**Comment by Marcono1234** [comment]
@fan87, with Gson 2.9.1 having been released, could you please check if this issue still occurs?

**Comment by fan87** [comment]
Yes it's fixed
