### ISSUE TITLE
Giving merge rights to Marcono1234 

### ISSUE THREAD

**Issue by wetneb** [google/gson#2163]
Dear Gson team,

Looking at the issue tracker, open pull requests, and past commits, I would suggest to give permissions to @Marcono1234 so that they can merge pull requests and cut out new releases for this library. I think their contributions speak for themselves and this project is held back by a lack of maintainer bandwidth.

Thanks for your work!

**Comment by Marcono1234** [comment]
Thanks a lot for proposing this, it is a great honor! However, with merge permissions comes a great amount of responsibility and my pull requests are certainly not without errors, or without overlooking consequences the changes might have. Therefore I don't think I should be able to merge any changes on my own without a second review, let alone create release.
eamonnmcmanus has helped me a lot with the pull requests and gave very valuable reviews on them.

I have been given Triage permissions to help organize and clean up old issues and pull requests, and I am thankful for that and fine with the level of permissions. eamonnmcmanus and I had also discussed this, so I will close this issue.
