### ISSUE TITLE
Support double curly brace initialization object to json

### ISSUE THREAD

**Issue by GGGGGHT** [google/gson#2186]
# Problem solved by the feature

When I use double curly braces to instantiate an object, it will generate a anonymous subclass, and I can't convert it to a json object using GSON, so I hope this operation can be supported.

# Feature description

like i described above,Support anonymous subclass object conversion into json.

# Alternatives / workarounds

**Comment by Marcono1234** [comment]
Thank you for this feature request, though there are already issues tracking this:
Duplicates #1510
