### ISSUE TITLE
 Access restriction: The type 'TypeAdapters' is not API

### ISSUE THREAD

**Issue by megha-an** [google/gson#2194]
# Gson version

Gson version 2.9.1

# Java / Android version

java version 11.0.6

# Used tools

- [x] Maven; version: 3.6.3

# Description

we are using gson package in the maven project , it was working fine but from yesterday we are facing this issue while building the application 

issue:
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:1.5.0:compile (default-compile) on project com.googlecode.goclipse.tooling: Compilation failure: Compilation failure: 
[ERROR] /home/bundles/plugin_tooling/src-lang/melnorme/lang/utils/gson/JsonParserX.java:[21] 
[ERROR] 	import com.google.gson.internal.bind.TypeAdapters;
[ERROR] 	       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] Access restriction: The type 'TypeAdapters' is not API (restriction on classpath entry '/home/.m2/repository/p2/osgi/bundle/com.google.gson/2.9.1/com.google.gson-2.9.1.jar')
[ERROR] /home/bundles/plugin_tooling/src-lang/melnorme/lang/utils/gson/JsonParserX.java:[64] 
[ERROR] 	return TypeAdapters.JSON_ELEMENT.read(reader);
[ERROR] 	       ^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] Access restriction: The type 'TypeAdapters' is not API (restriction on classpath entry '/home/.m2/repository/p2/osgi/bundle/com.google.gson/2.9.1/com.google.gson-2.9.1.jar')
[ERROR] /home/bundles/plugin_tooling/src-lang/melnorme/lang/utils/gson/JsonParserX.java:[64] 
[ERROR] 	return TypeAdapters.JSON_ELEMENT.read(reader);
[ERROR] 	                    ^^^^^^^^^^^^
[ERROR] Access restriction: The field 'TypeAdapters.JSON_ELEMENT' is not API (restriction on classpath entry '/home/.m2/repository/p2/osgi/bundle/com.google.gson/2.9.1/com.google.gson-2.9.1.jar')

can anyone help, how to resolve the issue?

**Comment by Marcono1234** [comment]
This is intended; as the package name `com.google.gson.internal.bind` suggests the class `TypeAdapters` is internal. You should be able to achieve the same behavior by obtaining the `TypeAdapter` like this:
```java
TypeAdapter<JsonElement> adapter = new Gson().getAdapter(JsonElement.class);
```
This adapter is the same one you obtained from the internal `TypeAdapters` class, and you can safely store it in a `static final` field if you want to.
