### ISSUE TITLE
JsonReader API call to determine whether Number was specified as whole number (no period) or floating-point (period)

### ISSUE THREAD

**Issue by jernst** [google/gson#2217]
I'd like to be able to tell the difference between
``
{   "x" : 17 }
``
and
``
{   "x" : 17.0 }
``
You internally distinguish between those two, but there is no API that exposes this. It might be as simple as adding a call:
``
boolean peekIsWholeNumber()
``

**Comment by Marcono1234** [comment]
Possibly a duplicate of #1621

Are you really working directly with `JsonReader` or are you using one of the `Gson` methods and actually want to deserialize a `Number` (or `Object`)? In the latter case you can probably use `ToNumberStrategy` / `ToNumberPolicy` introduced by #1290.

If you are working directly with a `JsonReader` you could use its `nextString()` method. This will also work for JSON numbers and lets you determine whether the number is an integer or a floating point number and perform the parsing yourself.

It would be good if you could explain your use case a bit more in detail or provide the code you have so far.

**Comment by jernst** [comment]
I'm attempting to make best possible sense out of a wide variety of JSON files whose provenance is not entirely clear, and there is no documentation. First thing I need is to faithfully "read it in" so then I can throw some smarts at it to figure out what it might possibly mean. If the first step is already losing information, the second steps become harder. 

I read through the code and I'm now attempting to read as Long, and if that throws, I retry as Double. That gives me a workaround.

**Comment by Marcono1234** [comment]
> I read through the code and I'm now attempting to read as Long, and if that throws, I retry as Double. That gives me a workaround.

Your workaround might not work as desired when the number has 0 as decimal place, such as the 17.0 in your example. `nextLong()` internally falls back to reading as `Double`:
https://github.com/google/gson/blob/e614e71ee43ca7bc1cb466bd1eaf4d85499900d9/gson/src/main/java/com/google/gson/stream/JsonReader.java#L976-L980

I think checking first for `peek() == JsonToken.NUMBER` and then calling `nextString()` as proposed above would give you better results. You could then also check if the number has an exponent, maybe that provides further insight into the structure of your data.

**Comment by jernst** [comment]
Gotcha. You are right :-)

**Comment by Marcono1234** [comment]
Do you think this issue can be closed? I think for inspecting the exact number format the approach of checking `nextString()` is the most versatile one.

One issue with a `peekIsWholeNumber()` method (or similar) is that its name might be misleading; for example one might consider 17.0 a whole number, but in your use case that is not desired.

I am not sure what other situations exist where it is really necessary to peek the number type. In all cases the `nextString()` approach will likely give you more possibilities and allows you to decide how to parse it, e.g. as `BigDecimal`. `peekIsWholeNumber()` might also give the wrong impression that calling `nextDouble()` will succeed while it could in theory be the case that the number is too large for a `double`, causing precision loss.

**Comment by jernst** [comment]
Whatever I can suggest now would break the existing API, and so I won't. Ok, closing.
