### ISSUE TITLE
Aaa

### ISSUE THREAD

**Issue by tifund** [google/gson#2218]
# Gson version

# Java / Android version

# Used tools

- [ ] Maven; version: 
- [ ] Gradle; version: 
- [ ] ProGuard (attach the configuration file please); version: 
- [ ] ...

# Description

## Actual behavior

# Reproduction steps

1. ...
2. ...

# Exception stack trace

```

```

**Comment by Marcono1234** [comment]
Please provide all requested information when creating an issue.
