### ISSUE TITLE
Is there a limit for Kotlin data class number of properties to be parsed by Gson ?

### ISSUE THREAD

**Issue by slimaniiyassine** [google/gson#2240]
# Java / Android version
All Android versions 

I have a data class with Kotlin that is working fine when parsing by Gson.   
  
I use : 

```
 val parsed = Gson().fromJson<T>(json, classT)
 
```

Everything is working fine.   
  
But now when I try to add one more property to the class It cannot be parsed and I get the following error : 

```
 Unable to create instance of class xxx.xxxx.xxxx.ClassT Registering an InstanceCreator or a TypeAdapter for this type, or adding a no-args constructor may fix this problem.
 
```

  
My Class is as following : 

```
data class ClassT(
    @SerializedName("firstType")
    var typeA: ClassTResponse? = null,
    @SerializedName("secondType")
    var typeB: ClassTResponse? = null
) : Serializable

```

```
data class ClassTResponse(
    @SerializedName("XXXX")
    val xxxx: String? = null 

//The class contains 254 properties 

all of them are String? = null

```

With this implementation everything is working fine but once I add one more property the exception is received. 

```
 Unable to create instance of class xxx.xxxx.xxxx.ClassT Registering an InstanceCreator or a TypeAdapter for this type, or adding a no-args constructor may fix this problem.
 
```

  
My Question is the following :   
  
Is there any limit to Gson to be able to parse a data class ?   
  
How to make it work ?   
  
Thanks in advance. 

GSON version used 2.10.

I was trying to parse a data class with Gson Library and once I added one more property to the class it raise an exception.

**Comment by Marcono1234** [comment]
The exception with the message "Unable to create instance of..." should have a cause set (see [code](https://github.com/google/gson/blob/3f1e62d1e1b43f1d76af5106f9484e940bf74606/gson/src/main/java/com/google/gson/internal/ConstructorConstructor.java#L373-L375)). Could you please include the cause and its strack trace as well? It starts with `Caused by: `.

**Comment by eamonnmcmanus** [comment]
Seconding the request for the exception cause. But you're probably running into [JVM limits](https://docs.oracle.com/javase/specs/jvms/se19/html/jvms-4.html#jvms-4.3.3). A Java or Kotlin constructor cannot have more than 254 parameters (255 in all including the implicit `this`). I'm not sure you can successfully define a data class with more than 254 values.

**Comment by slimaniiyassine** [comment]
Hello @eamonnmcmanus 

Thank You for Your reply, yes the issue was the JVM limit indeed. 

Had to do a second constructor with a normal class that takes a map to make it work.

Regards,
