### ISSUE TITLE
User guide "TOC-" section anchors don't work anymore

### ISSUE THREAD

**Issue by Marcono1234** [google/gson#2286]
# Description
It looks like the custom anchors such as `<a name="TOC-Overview">` in `UserGuide.md` don't work anymore. For example when clicking on any of the links in the "Overview" section nothing happens.

Would be good if someone else could check this as well in case there is an issue with my browsers (tested Firefox and Edge).

Maybe we should then simply edit the user guide (and any other documents referring to it) to use the automatically generated anchors instead.

**Comment by eamonnmcmanus** [comment]
Yes, I am seeing the same thing with Chrome.

**Comment by Marcono1234** [comment]
Apparently the uppercase letters in the anchors (`TOC`) are causing this issue, using only lowercase letters still seems to work. Though I am not sure if it is worth adding them back to the user guide.

Have also created https://github.com/orgs/community/discussions/50962 to ask if this is actually an officially supported feature.
