### ISSUE TITLE
GsonBuilder setDateFormat ignored

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gson#230]
```
What steps will reproduce the problem?
1. Build a gson with setDateFormat
Date date = new Date();
Gson gson = new GsonBuilder().setDateFormat("MM/dd/yyyy").create();
System.out.println(gson.toJson(date));

What is the expected output? What do you see instead?
Expected is "08/27/2010"
Date results in standard format: "Aug 27, 2010 10:21:32 AM"

What version of the product are you using? On what operating system?
1.5

Please provide any additional information below.
It works ok in 1.4 but when I change to 1.5 it ignores the setDateFormat() 
method
```

Original issue reported on code.google.com by `tradefie...@gmail.com` on 27 Aug 2010 at 2:38

**Comment by esimioni** [comment]
In which versions was this fixed? I have the exact same problem in version 2.3.1.

**Comment by pdavid0** [comment]
I have the same issue with 2.8.0 : 
2.8 -> "startDateTime":"Dec 12, 2016 18:00:00"
2.7 -> "startDateTime":"2016-12-12T18:00:00.000"

Looked at the Diff and nothing related to dateFormat seem to come up .

**Comment by Markandayan1518** [comment]
In which versions was this fixed? I have the exact same problem in version 2.80
