### ISSUE TITLE
Malformed Unicode escape sequence causes `NumberFormatException` instead of `MalformedJsonException`

### ISSUE THREAD

**Issue by Marcono1234** [google/gson#2334]
# Gson version
2.10.1

# Description
`JsonReader` throws a `NumberFormatException` instead of a `MalformedJsonException` when it encounters a malformed Unicode escape sequence in the JSON data.
This actually works as designed:
https://github.com/google/gson/blob/19983737ae5e45f90cbc50cbd7b70a0db9ed7a83/gson/src/main/java/com/google/gson/stream/JsonReader.java#L1590-L1591

However, it is questionable whether that design is really a good choice because a `MalformedJsonException` seems to fit better here, especially since other malformed escape sequences do cause a `MalformedJsonException`.

Note that `NumberFormatException` being thrown is apparently not publicly documented, so changing this should be rather safe to do.

## Expected behavior
A `MalformedJsonException` is thrown for malformed Unicode escape sequences.

## Actual behavior
A `NumberFormatException` is thrown.

# Reproduction steps
```java
Reader reader = new StringReader("\"\\uXYZ\"");
JsonReader jsonReader = new JsonReader(reader);
jsonReader.nextString();
```

**Comment by eamonnmcmanus** [comment]
I agree. It's weird to throw `NumberFormatException` here yet `MalformedJsonException` when for example there are fewer than 4 characters after the `\u`. I also agree that this is unlikely to affect anyone in practice, other than tests that might have been expecting the current exception.
