### ISSUE TITLE
Support unmodifiable object by annotation

### ISSUE THREAD

**Issue by votoanthuan** [google/gson#2343]
# Problem solved by the feature
To protect the object's data (Collection, List, Map, NavigableMap, Set, SortedMap, SortedSet) from being changed during use.

Let example, I parse config from json into class like this. I need to make this member public but I don't want anyone to modify its 
```
public class Config {
    public Map<Integer, Integer> mapExp;
}
```

# Feature description
We can add annotation like this
```
public class Config {
    @Unmodifiable
    public Map<Integer, Integer> mapExp;
}
```

In gson, after parse object, we use unmodifiable object in java.util.Collections to protect this member

# Alternatives / workarounds

**Comment by eamonnmcmanus** [comment]
You could fairly easily make a `TypeAdapterFactory` that [delegates](https://javadoc.io/static/com.google.code.gson/gson/2.10.1/com.google.gson/com/google/gson/Gson.html#getDelegateAdapter(com.google.gson.TypeAdapterFactory,com.google.gson.reflect.TypeToken)) to the existing factories for `Map` and `Collection` and then wraps the result _always_. Do you have a situation where you _sometimes_ want maps deserialized from Gson to be modifiable and sometimes not? If so, perhaps your fields should have type [`ImmutableMap<...>`](https://javadoc.io/static/com.google.guava/guava/31.1-jre/com/google/common/collect/ImmutableMap.html) or the like, and you could have a `TypeAdapterFactory` for that?

**Comment by votoanthuan** [comment]
I sometime want maps deserialized from Gson to be modifiable and sometimes not. However that a great idea to use ImmutableMap and TypeAdapterFactory.

Thank you for your support.

**Comment by eamonnmcmanus** [comment]
I think we've seen that we already have decent enough ways of doing what was originally described, so I'm going to close this.
