### ISSUE TITLE
convert large arraylist to string is throwing errors

### ISSUE THREAD

**Issue by RahulSoni0** [google/gson#2367]
# Gson version

GSON 2.8.2

# Java / Android version

Android Studio

# Used tools

- [ ] Maven; version: 
- [ ] Gradle; version: 
- [ ] ProGuard (attach the configuration file please); version: 
- [ ] ...

# Description

## Actual behavior

# Reproduction steps

1. ...
2. ...

# Exception stack trace

```

```

**Comment by eamonnmcmanus** [comment]
Hi, I think we need more detail. What errors do you see? What does your code look like? What does the input look like?

**Comment by Marcono1234** [comment]
I am going to close this because no answer has been provided. If you still experience this with the latest Gson version, feel free to comment here again with more details.
