### ISSUE TITLE
Gson toJson HashMap put

### ISSUE THREAD

**Issue by ChiBenshuo** [google/gson#2402]
# Gson version 2.10.1

# Java  version 17

# description

`
        System.out.println(new Gson().toJson(new HashMap<String, String>() {{
            put("a", "b");
        }})); // print null

        String map2 = new Gson().toJson(new HashMap<String, String>() {{
            put("a", "b");
        }});
        System.out.println(map2); // print null

        Map<String, String> map = new HashMap<>();
        map.put("a", "b");
        System.out.println(new Gson().toJson(map)); // print {"a":"b"}
`

**Comment by eamonnmcmanus** [comment]
See #2023 and #298, among others. The short summary, to quote #298: "Don't use double brace initialization. It prevents serialization and Gson is designed for symmetric serialization and serialization."

Since you're using Java 17, `Map.of` or `Map.ofEntries` are much better alternatives.
