### ISSUE TITLE
`JsonWriter.name` does not throw exception when not inside JSON object

### ISSUE THREAD

**Issue by Marcono1234** [google/gson#2407]
# Gson version
2.10.1

# Java / Android version
Java 17

# Description
Calling `JsonWriter.name` (and maybe also `JsonTreeWriter.name`) when not inside a JSON object does not fail.

## Expected behavior
An `IllegalStateException` should be thrown

## Actual behavior
No exception is thrown

# Reproduction steps
```java
JsonWriter jsonWriter = new JsonWriter(new StringWriter());
// Should throw exception
jsonWriter.name("a");
```

**Comment by eamonnmcmanus** [comment]
Seems like we should fix this. You _will_ get an exception if you write pretty much anything else after the `.name`, but it would be better to get it exactly at the point where the mistake was made.

**Comment by shivam-sehgal** [comment]
Hi, just wanted to ask, if anyone not working on this, would like to contribute on this issue

**Comment by Marcono1234** [comment]
@shivam-sehgal, thanks for asking! To my knowledge no one is working on this yet. Though before you start, please have a look at the [contributing guide](https://github.com/google/.github/blob/master/CONTRIBUTING.md) and also at the [pull request checklist](https://github.com/google/gson/blob/main/.github/pull_request_template.md#checklist).

**Comment by shivam-sehgal** [comment]
> @shivam-sehgal, thanks for asking! To my knowledge no one is working on this yet. Though before you start, please have a look at the [contributing guide](https://github.com/google/.github/blob/master/CONTRIBUTING.md) and also at the [pull request checklist](https://github.com/google/gson/blob/main/.github/pull_request_template.md#checklist).

Thanks @Marcono1234 , for letting me know the status of the bug, and the docs, have done the needful by signing the CLA and going through the PR checklist, and will look into this issue.

**Comment by shivam-sehgal** [comment]
Hello @Marcono1234,
I wanted to inform you that I've submitted a [Pull Request](https://github.com/google/gson/pull/2475) addressing this issue. Your valuable feedback would be greatly appreciated.
Thank you!
