### ISSUE TITLE
java.lang.IllegalStateException: Expected a boolean but was NUMBER at line 23 column 34 path $.. /i have this problem when i install mod waila

### ISSUE THREAD

**Issue by Honicoorn** [google/gson#2419]
# Gson version

# Java / Android version

# Used tools

- [ ] Maven; version: 
- [ ] Gradle; version: 
- [ ] ProGuard (attach the configuration file please); version: 
- [ ] ...

# Description

## Expected behavior

[crash-2023-06-14_20.28.06-fml.txt](https://github.com/google/gson/files/11746356/crash-2023-06-14_20.28.06-fml.txt)

## Actual behavior

# Reproduction steps

1. ...
2. ...

# Exception stack trace

```

```

**Comment by eamonnmcmanus** [comment]
I think we need more information than this. Are you able to say what the JSON string was and how you would expect it to be parsed? Also, though I'm not aware of any changes that might affect this, I do notice that your version of Gson is 2.8.0 which is from 2016.

**Comment by Marcono1234** [comment]
I am going to close this because no answer has been provided. If you still experience this with the latest Gson version, feel free to comment here again with more details.
