### ISSUE TITLE
java.lang.ClassCastException: com.google.gson.internal.LinkedTreeMap cannot be cast to io.realm.RealmModel

### ISSUE THREAD

**Issue by sharawanan** [google/gson#2427]

**Comment by Marcono1234** [comment]
Please provide more information about the issue you experiencing, basically everything which was originally requested in the [issue template](https://github.com/google/gson/blob/main/.github/ISSUE_TEMPLATE/bug_report.md).

Please also have a look at the [`ClassCastException` section of the Troubleshooting Guide](https://github.com/google/gson/blob/main/Troubleshooting.md#class-cast-exception) and let us know if that helped.

**Comment by Marcono1234** [comment]
> thanks, now I'm adding this line it's working

That is good to hear! Is this issue solved then and can be closed?

Note that future Gson versions will include a default R8 configuration (see [`META-INF/proguard/gson.pro`](https://github.com/google/gson/blob/main/gson/src/main/resources/META-INF/proguard/gson.pro)), so maybe once the next Gson version is released you can simplify your R8 / ProGuard configuration a bit. You can then also try changing `android.enableR8.fullMode` to `true`.

**Comment by P1NG2WIN** [comment]
Have same issue. After update to AGP 8 start to get `ClassCastException: com.google.gson.internal.LinkedTreeMap cannot be cast...` exception.
