### ISSUE TITLE
JsonSerializers are constructed multiple times when associated with SerializedName with alternate names but only one is used

### ISSUE THREAD

**Issue by d-william** [google/gson#2438]
# Gson version
2.10.1

# Java / Android version
Java 17

# Used tools
- [ ] Maven; version: 3.8.1

# Description
When a class has a field with : 
 - @SerializedName annotation with alternate names
 - and with @JsonAdapter indicating a JsonSerializer class to use
 
Then a new JsonSerializer will instanciate for each alternate names, even if they will never be used ([serialize](https://github.com/google/gson/blob/6d9c3566b71900c54644a9f71ce028696ee5d4bd/gson/src/main/java/com/google/gson/internal/bind/ReflectiveTypeAdapterFactory.java#L167) is always false because of [this](https://github.com/google/gson/blob/6d9c3566b71900c54644a9f71ce028696ee5d4bd/gson/src/main/java/com/google/gson/internal/bind/ReflectiveTypeAdapterFactory.java#L301))

## Expected behavior
Instanciante a new JsonSerializer only for the main name, because created one can be an heavy operation.

## Actual behavior
A new JsonSerializer will instanciate for each alternate names

# Reproduction steps
Run the following code
```java
public static class Pojo {

        @SerializedName(value = "field1", alternate = {"field2", "field3"})
        @JsonAdapter(StringSerializer.class)
        public final String str;

        public Pojo(String str) {
            this.str = str;
        }

}

public static class StringSerializer implements JsonSerializer<String> {

        private static int count = 0;

        private final int c;

        public StringSerializer() {
            this.c = count;
            System.out.println("new StringSerializer " + this.c);
            count++;
        }

        @Override
        public JsonElement serialize(String value, Type type, JsonSerializationContext context) {
            System.out.println("serialize " + this.c);
            return new JsonPrimitive(value);
        }

}

public static void main(String[] args) {
        TypeAdapter<Pojo> adapter = new Gson().getAdapter(Pojo.class);
        Pojo pojo1 = new Pojo("my value 1");
        Pojo pojo2 = new Pojo("my value 2");
        adapter.toJson(pojo1);
        adapter.toJson(pojo2);
}
```

# Dev hint
Maybe we can give `serialize` value to [this](https://github.com/google/gson/blob/6d9c3566b71900c54644a9f71ce028696ee5d4bd/gson/src/main/java/com/google/gson/internal/bind/ReflectiveTypeAdapterFactory.java#L158) method call and used it in some way ? 

OR

Create [this](https://github.com/google/gson/blob/6d9c3566b71900c54644a9f71ce028696ee5d4bd/gson/src/main/java/com/google/gson/internal/bind/ReflectiveTypeAdapterFactory.java#L158) type adapter before [here](https://github.com/google/gson/blob/6d9c3566b71900c54644a9f71ce028696ee5d4bd/gson/src/main/java/com/google/gson/internal/bind/ReflectiveTypeAdapterFactory.java#L299)

**Comment by Marcono1234** [comment]
Thanks for the report and for the hints on how this could be improved!

It looks like it is possible to even move the complete creation of the `BoundField` outside the loop, so you only have one `BoundField` per field (regardless of whether `@SerializedName` is used or not), see #2440.

**Comment by Marcono1234** [comment]
> Instanciante a new JsonSerializer only for the main name, because created one can be an heavy operation.

As workaround you can specify a custom `InstanceCreator` which returns an existing instance of the serializer (respectively a singleton instance), for example:

 ```java
Gson gson = new GsonBuilder()
    .registerTypeAdapter(MySerializer.class, (InstanceCreator<?>) t -> MySerializer.INSTANCE)
    .create();
```

It appears this is unfortunately not properly documented yet, see also #2442.
