### ISSUE TITLE
Error on compose multiplatform release package (enabled proguard)

### ISSUE THREAD

**Issue by SudoDios** [google/gson#2503]
# Gson version
Latest version 

I use gson in my project. Everything works fine until i release package & get this error :
`Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: org/apache/logging/log4j/LogManager at proguard.optimize.gson._GsonUtil.<clinit>(_GsonUtil.java:45)`

**Comment by Marcono1234** [comment]
This seems to be a bug in ProGuard (https://github.com/Guardsquare/proguard/issues/326) and is not directly related to or caused by Gson. This is apparently fixed in ProGuard version [7.4.0-beta02](https://github.com/Guardsquare/proguard/releases/tag/v7.4.0-beta02).

**Comment by SudoDios** [comment]
Thank you
