### ISSUE TITLE
Reflection error using Desire HD with Froyo (2.2)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gson#255]
```
What steps will reproduce the problem?
1. Using any nested beans, look at the TwitterTrends GSON example on the net
2. Only happens using desire HD with Froyo 2.2
3.

What is the expected output? What do you see instead?

Get a stacktrace saying cannot find the class declaration for the nested type

What version of the product are you using? On what operating system?

From memory thing it's GSON 1.5 on a HTC desire HD with 2.2


Please provide any additional information below.

Works on HTC Magic with 1.6, Emulator with 2.2 and Nexus One with 2.2.1

```

Original issue reported on code.google.com by `dorian.c...@gtempaccount.com` on 26 Oct 2010 at 9:21

**Comment by Marcono1234** [comment]
Is someone still experiencing this with recent Android devices and the latest Gson versions? Based on the comments above it sounds like this was an Android bug specific to certain HTC devices and unrelated to Gson.

**Comment by Marcono1234** [comment]
I am going to close this because no answer has been provided. If you still experience this with the latest Gson version, feel free to comment here again with more details.
