### ISSUE TITLE
Hua

### ISSUE THREAD

**Issue by stefanajons** [google/gson#2568]
# Gson version

# Java / Android version

# Used tools

- [ ] Maven; version: 
- [ ] Gradle; version: 
- [ ] ProGuard (attach the configuration file please); version: 
- [ ] ...

# Description

## Actual behavior

# Reproduction steps

1. ...
2. ...

# Exception stack trace

```

```

**Comment by eamonnmcmanus** [comment]
@stefanajons this is the third meaningless issue you have logged in two days. Is there a reason behind it?
