### ISSUE TITLE
打个广告 gson 10倍速度提升 https://github.com/NBXXF/gson_plugin

### ISSUE THREAD

**Issue by NBXXF** [google/gson#2574]
gson 10倍速度提升 https://github.com/NBXXF/gson_plugin

**Comment by Marcono1234** [comment]
If you have specific suggestions for how Gson's performance can be improved, we would be happy if you can provide them, either here, in a separate issue or as pull request.

But otherwise I think this issue is in its current form is not that helpful for this project, so I am going to close it.
