### ISSUE TITLE
Possible typo at gson readme.md in main branch

### ISSUE THREAD

**Issue by seujorgenochurras** [google/gson#2617]
# Gson version

No

# Java / Android version

No

# Used tools

- [ ] Maven; version: 
- [ ] Gradle; version: 
- [ ] ProGuard (attach the configuration file please); version: 
- [X] Nada

# Description

Gson main branch, readme.md third paragraph, there is an `i` in the first letter

## Expected behavior

First letter of third paragraph in readme.md having any sense at all

## Actual behavior

First letter of third paragraph did not make any sense ;-;

# Reproduction steps

1. Open [gson main branch](https://github.com/google/gson)
2. Read readme.md file
3. Look at first letter of third paragraph

# Exception stack trace

```
Nop
```

**Comment by seujorgenochurras** [comment]
My friend opened this readme on Windows and it seems to be an emoji, I guess that is not your fault so

**Comment by Marcono1234** [comment]
Thanks for reporting this problem! We have adjusted the formatting of this section in the README now and removed the 'ℹ️' emoji.
