### ISSUE TITLE
Javascript

### ISSUE THREAD

**Issue by khaouitiabdelhakim** [google/gson#2622]
# Problem solved by the feature

# Feature description

Why GSON is not available in the web world like in javascript?

# Alternatives / workarounds

**Comment by Marcono1234** [comment]
> Why GSON is not available in the web world like in javascript?

Can you please clarify what you mean by that? Gson is a Java library; Java and JavaScript are completely different languages. Do you want to use a library similar to Gson in JavaScript running in the browser?

**Comment by JeremiahRanen7** [comment]
Could you kindly clarify your request further? Providing additional details would enable me to assist you more effectively.

**Comment by khaouitiabdelhakim** [comment]
Hi, I would like to ask you if such a library exists in javascript. Because I have an android app that uses this library and I am expanding it to the web.
Is there any alternative.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by JeremiahRanen7** [comment]
As of my knowledge , there is **no library** called gson in **JavaScript** but in **java** , _there is a library called gson_ .

**In Java :**
It is used like , for _parsing json strings to json objects and stringifies json objects to json strings._
It does _serialization and deserialization of the json objects_.
Mostly used for **transferring data** between _server and clients_ in the form of _network requests._

Now , if you want to expand the android app to the web , you can use built in json methods of JavaScript like the below:

![image](https://github.com/google/gson/assets/141173239/c776d9c2-5d28-400b-af0b-e18ba2462a85)

You can refer to the below link on how to use the stringify and parse methods. It would really be helpful.
https://www.digitalocean.com/community/tutorials/js-json-parse-stringify

But if you want to work with dedicated json libraries , I would recommend you to use FastJson , lodash , underscore.js , etc.;
There are a lots of libraries in JavaScript that work with JSON.

I hope this helps you.
If you still have doubts , you can ask me about it.

**Comment by JeremiahRanen7** [comment]
I also wanted to tell you that gson was developed by google.
👍 Hope you find out your requirement.

**Comment by khaouitiabdelhakim** [comment]
I want really to thank you so much for such a huge amount of information my friend.

Yes, that's why I have asked. I have a great android app like Spotify it is called Faborfy which means the free Spotify (you can find it on Google play) and I used to use gson, so all the data are stored in Firebase using the stringfy of gson. So when I tried to use json parsing in the web (react+ vite) I found like the normal json is not understanding the string that I get from firebase.

And that is the reason why I asked if there is any gson like for the web.

Best,
KHAOUITI.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by JeremiahRanen7** [comment]
That's great to here from you my friend.
Really happy to see that you have found something helpful 👍 
Best wishes to complete the web app soon 💯 
Jeremiah Ranen R.

**Comment by khaouitiabdelhakim** [comment]
I want also to tell you that gson in Kotlin undertands the new line breaker \n inside a string, in my case I have so much \n s in lyrics key , but this in json (web) throws an error. It is unable to oarse that characters and a lot of disimilaties.

I hope you get my point.

And thanks in advance for all.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by JeremiahRanen7** [comment]
Ok , I understand your need!
But may I know where this json data comes from ?
Is it from an external source like an API or a file in your local storage?
This would be helpful.

Also it would be helpful if you could give me a sample json data that you use!!

**Comment by khaouitiabdelhakim** [comment]
This is my app

https://play.go<https://play.google.com/store/apps/details?id=com.abdelhakim.faborfy>ogle.com/store/apps/details?id=com.abdelhakim.faborf<https://play.google.com/store/apps/details?id=com.abdelhakim.faborfy>y

It is like chrome but with the design of Spotify-like.

I have a class data class Music (title, artist, lyrics.....) and I have for example the favorite songs which is an ArrayList of Music objects. So with gson in my kotlin android app I use it to save the favorite to the realtime database of firebase as a string and do it the inverse way to retrieve my arraylist of Music.


Example

[{"artUrl":"https://cdns-images.dzcdn.net/images/cover/d78f12a2402dfbb1026e0c709f02b401/500x500.jpg","isSongRight":false,"lyric":"Her şey bitermiş zamanla \nİçinde kalmasın söyle bilelim \nBana layık soğuk vedansa \nUnuttum artık herkes gibisin \n\nHer şey bitermiş zamanla \nİçinde kalmasın söyle bilelim \nBana layık soğuk vedansa \nUnuttum artık herkes gibisin \n\nNe ara bu duruma düştük? Saftı gönlüm çabuk kaçtı elimden \nBoşa geçti gördüm ömrümden çaldığın o günler \nKırıkları vardır elbet yaşamın bir parçasıydı herşey \nUmut edip anılanlar, yakılanlar, yıkılanlar \nFaydası yok sözlerin her nefeste başa sarar Özlem\u0027in \nBeni yoran bu kasveti tutamadım Erken çözüldü dizlerim \n\nHer şey bitermiş zamanla \nİçinde kalmasın söyle bilelim \nBana layık soğuk vedansa \nUnuttum artık herkes gibisin \n\nHer şey bitermiş zamanla \nİçinde kalmasın söyle bilelim \nBana layık soğuk vedansa \nUnuttum artık herkes gibisin \n\nHer şey bitermiş zamanla \nİçinde kalmasın söyle bilelim \nBana layık soğuk vedansa \nUnuttum artık herkes gibisin \n\nNe ara bu duruma düştük? Saftı gönlüm çabuk kaçtı elimden \nBoşa geçti gördüm ömrümden çaldığın o günler \nKırıkları vardır elbet yaşamın bir parçasıydı herşey \nUmut edip anılanlar, yakılanlar, yıkılanlar \nFaydası yok sözlerin her nefeste başa sarar Özlem\u0027in \nBeni yoran bu kasveti tutamadım Erken çözüldü dizlerim \n\nHer şey bitermiş zamanla \nİçinde kalmasın söyle bilelim \nBana layık soğuk vedansa \nUnuttum artık herkes gibisin \n\nHer şey bitermiş zamanla \nİçinde kalmasın söyle bilelim \nBana layık soğuk vedansa \nUnuttum artık herkes gibisin \n\n","playCount":4,"source":"dl.musicdel.ir","title":"Herkes Gibisin Semicenk","url":"https://dl.musicdel.ir/Music/1401/03/semicenk_herkes_gibisin%20128.mp3"},{"artUrl":"https://i1.sndcdn.com/artworks-1URmYrFXyqSO9Mcd-mqvweg-t500x500.jpg","isSongRight":false,"lyric":"Daha çok değil üstünden, seneler geçmedi ki \nYorgunum, \"Artık bu son!\" deyip geçebildik mi? \n\nDerin bir iz bıraktı içimde taze yaran \nBir gün elbet kapanır \nKapandı yarım kalan sayfamız mümkün değil \nBu son değil \n\nAyrılığın acısı \nSorulur mu yanana? \nAşka düştüm düşeli \nKül oldu bahtım kara \n\nAyrılığın acısı \nSorulur mu yanana? \nAşka düştüm düşeli \nKül oldu bahtım kara \n\nDerin bir iz bıraktı içimde taze yaran \nBir gün elbet kapanır \nKapandı yarım kalan sayfamız mümkün değil \nBu son değil \n\nAyrılığın acısı \nSorulur mu yanana? \nAşka düştüm düşeli \nKül oldu bahtım kara \n\nAyrılığın acısı \nSorulur mu yanana? \nAşka düştüm düşeli \nKül oldu bahtım kara \n\nAyrılığın acısı \nSorulur mu yanana? \nAşka düştüm düşeli \n\n","playCount":4,"source":"mp3indirdur.life","title":"Kül Merve Özbey","url":"https://mp3indirdur.life/Merve-Ozbey-Ayriligin-Acisi-115577?dinle\u003d1"},{"artUrl":"https://m.media-amazon.com/images/I/41MXxIR-aCL._UXNaN_FMjpg_QL85_.jpg","isSongRight":false,"lyric":"Gidene dur demem başkası olsa \nBir yanım buz gibiydi ateş oldun \nUnutma her şeyi yoluna koy\u0027cam \nOlmadın inatla, dinle iki dak\u0027ka \n\nHer şey üst üste geldi çok yoruldum \nDuydum onunla ner\u0027de ne konuştun \nUğruna derdim oldu yüküm arttı \nKavgaya karıştım söyle bu gurur mu? \n\nBile bile bana yine zehir ediyo\u0027n \nNe sandın beni be, kendime yetiyo\u0027m \nDünya kadar derdim çok ama yine deniyo\u0027m \nBi nedenimiz yok inan sevenimiz yok, gülüm \n\nBile bile bana yine zehir ediyo\u0027n \nNe sandın beni be, kendime yetiyo\u0027m \nDünya kadar derdim çok ama yine deniyo\u0027m \nBi nedenimiz yok inan sevenimiz yok, gülüm \n\nBi yanım olsan, gönlümde yerin olsan \nN\u0027aparım sensiz yoksan bir an düşünemiyo\u0027m \nGeceleri biten şişelerin hiç hesabı yok \nBi neden mi arıyo\u0027n bitirmek için \nAma benim zararım var \nUnutmak için gün sayıyo\u0027m \nBi neden söyle bana de sevmedim hiçbir zaman \nOlmazdı dostumu satmazdım \nKader \nYüzüme bakmazdı zaten ilk değilsin giden \n\nHer şeyden geçtim cano \nBi\u0027 de senden geçsem tamam \nİnadım var düşmem daha \nAğlatmam kansızlara \nSeni asla bilmeyeceksin \nBelki de beni görmeyeceksin \nBenden önce ölmeyeceksin \nAma şunu bil \nBenim kadar sevmeyeceksin \n\nBile bile bana yine zehir ediyo\u0027n \nNe sandın beni be, kendime yetiyo\u0027m \nDünya kadar derdim çok ama yine deniyo\u0027m \nBi nedenimiz yok inan sevenimiz yok, gülüm \n\nBile bile bana yine zehir ediyo\u0027n \nNe sandın beni be, kendime yetiyo\u0027m \nDünya kadar derdim çok ama yine deniyo\u0027m \nBi nedenimiz yok inan sevenimiz yok, gülüm \n\nAlo, alo \n\n","playCount":11,"source":"grand.az","title":"Ayaz Erdoğan - Gülüm","url":"https://grand.az/uploads/files/2023-08/1691264641_ayaz-erdogan-gulum-2023.mp3"},{"artUrl":"https://cdns-images.dzcdn.net/images/cover/6769498eadcb208af8201d101453c942/500x500.jpg","isSongRight":false,"lyric":"Bana el salla baharlarımı çaldığın bu hayattan \nBurda geçilmiyor ne kar ne kış ne ayazdan \nHiçbir farkı kalmamış umudumun bir bataktan \nArtık güneş yerine ay doğar bu şafaktan \n\nBana kalbinde kurduğun barikattan \nKalan sadece yıkık enkazlar \nGeleceği göremedim seninle \nGeçmişe biriken toz topraktan \n\nDayanır kapıma kapıma gece gece vurur aşk \nSabaha kadar eder yine gönlümü darp \nHem yanına hem yarına kâr kalır ah \nBana düşen de biten hasrete yas \n\nDayanır kapıma kapıma gece gece vurur aşk \nSabaha kadar eder yine gönlümü darp \nHem yanına hem yarına kâr kalır ah \nBana düşen de biten hasrete yas \n\nBana kalbinde kurduğun barikattan \nKalan sadece yıkık enkazlar \nGeleceği göremedim seninle \nGeçmişe biriken toz topraktan \n\nDayanır kapıma kapıma gece gece vurur aşk \nSabaha kadar eder yine gönlümü darp \nHem yanına hem yarına kâr kalır ah \nBana düşen de biten hasrete yas \n\nDayanır kapıma kapıma gece gece vurur aşk \nSabaha kadar eder yine gönlümü darp \nHem yanına hem yarına kâr kalır ah \nBana düşen de biten hasrete yas \n\n","playCount":34,"source":"mp3indirdur.life","title":"Irmak Arici Yas","url":"https://mp3indirdur.life/Irmak-Arici-Yas-feat-Doganay-Karadeniz-212956?dinle\u003d1"},{"artUrl":"https://artwork.anghcdn.co/webp/?id\u003d79006105\u0026size\u003d320","isSongRight":false,"lyric":"اللي يبي يزعل خله يزعل تعبت اسامح اسال\nقلبي كافي تحمل هموم هموم\nمحد فيني ابد حاس شايل هم الناس\nمن اليوم ولله خلاص هموم هموم\nو بعد بعد بعد مالي مالي شغل باحد\nو ابد ابد بعد ما اهتم ولا احس باحد\nمو كافي اذيه فيكم ماعليه\nحملتوني اسيه بعيش لنفسي اليوم\nاحرق بدمي و اراضي و اساعد على الفاضي\nترضاها ياقاضي اعيش انا مظلوم\nلمى تروح المصالح الحلو يصير مالح\nمن اليوم و رايح خلاص ماني ملزوم\nلا بطيبهم ولا بشرهم انا قلبي اكتفه\nماعاد ابي شي منهم مابي هالمعرفه\nاللي يبي يزعل خله يزعل تعبت اسامح اسال\nقلبي كافي تحمل هموم هموم\nمحد فيني ابد حاس شايل هم الناس\nمن اليوم ولله خلاص هموم هموم\nو بعد بعد بعد مالي مالي شغل باحد\nو ابد ابد بعد ما اهتم ولا احس باحد\nمو كافي اذيه فيكم ماعليه\nحملتوني اسيه بعيش لنفسي اليوم\nاحرق بدمي و اراضي و اساعد على الفاضي\nترضاها ياقاضي اعيش انا مظلوم\nلمى تروح المصالح الحلو يصير مالح\nمن اليوم و رايح خلاص ماني ملزوم\nلا بطيبهم ولا بشرهم انا قلبي اكتفه\nماعاد ابي شي منهم مابي هالمعرفه\n","playCount":26,"source":"cdn1.esm3.com","title":"اللي يبي يزعل سيف الفيصل","url":"https://cdn1.esm3.com/music/4558/m280244.mp3"}]

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by JeremiahRanen7** [comment]
Ok , when you try to use this data in the web , first check whether you have formatted your json correctly because **_each "\n" within a string should be formatted well like "\\n"_**.
It should be properly escaped.

Ok try this out and tell me!
I am just telling you to correct your json data if you have formatted it wrong
use json validators in the internet for free

**Comment by khaouitiabdelhakim** [comment]
I did not get you! Could you please explain further more? Because it is that way that gson has formatted the arraylist it is great working with me on mobile.

I do not know if gson format the arraylist to another version of json or just the standard one?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by khaouitiabdelhakim** [comment]
I did not see the difference between the 2 \n in your answer each "\n" within a string should be formatted well like "\n".

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by khaouitiabdelhakim** [comment]
I do not get data from an api, I’m suing gson only to store the data of the user toward and back from firebase using gson
and I want to do the same for the web
so the json must understand the string saved in firebase as it is, else I should have 2 entries in the realtime database one for mobile and another for pc, but this is not what I want. I want the same string should be great for gson (Kotlin) and also works for json (web)

**Comment by khaouitiabdelhakim** [comment]
When the user sign in I got all their saved data

currentUserRef.addListenerForSingleValueEvent(object : ValueEventListener {
    override fun onDataChange(dataSnapshot: DataSnapshot) {
        val userData = dataSnapshot.value as? Map<*, *>

        // Retrieve favorites
        val favouriteSongsJson = userData?.get("favorites") as? String
        if (favouriteSongsJson != null) {
            FavouriteActivity.favouriteSongs =
                GsonBuilder().create().fromJson(favouriteSongsJson, MainActivity.typeToken1)
        }
        editor.putString("favouriteSongs", GsonBuilder().create().toJson(FavouriteActivity.favouriteSongs))


and when the user want to save it I save it as

private fun saveChangesToFirebase(){
    val user = mAuth.currentUser
    if (isThereInternet(this) && user!=null) {
        val currentUser = database.child("users").child(user.uid)
        val playedSongString = GsonBuilder().create().toJson(JustPlayActivity.ListOfSongs)
        val favoriteSongString = GsonBuilder().create().toJson(FavouriteActivity.favouriteSongs)
        val playlistsString = GsonBuilder().create().toJson(PlaylistsActivity.musicPlaylistList)
        val searchString = GsonBuilder().create().toJson(JustPlayActivity.searchHistory)

        val userData = User(
            id = user.uid,
            played = playedSongString,
            favorites = favoriteSongString,
            playlists = playlistsString,
            search =  searchString
        )

        currentUser.setValue(userData)

        Log.i("savingChangesToFirebase", "savingChangesToFirebase")
    }
}

**Comment by JeremiahRanen7** [comment]
So you need a consistent JSON Structure and you also want to maintain compatibility between the JSON format used in your Kotlin Android app with Gson and the JSON format used in your web application?
Right , well then 
give me some time , I will come up with an idea
Because we need to come up with a tool that should be compatible with the JSON Structure that you use in the kotlin app
we also need a tool or any plugin / feature / anything which ensures that the data saved in Firebase from the Android app can be correctly read and interpreted by your web application, and vice versa.
Give me some time . buddy!! 👍

**Comment by khaouitiabdelhakim** [comment]
You have all the time, I want to deeply thank you for your time. I really appreciate it

best regards, buddy

**Comment by eamonnmcmanus** [comment]
I'm going to close this since it doesn't seem to be an issue with Gson as such. Feel free to continue the discussion here, though. I've also just enabled [Discussions](https://github.com/google/gson/discussions) here, which might be a more appropriate place for future discussions.

**Comment by khaouitiabdelhakim** [comment]
Thanks Eamonn.
________________________________

**Comment by khaouitiabdelhakim** [comment]
No yet friend

On Feb 22, 2024 16:43, Jeremiah Ranen R ***@***.***> wrote:

Hi hakim , did you come up with a solution ?
Did you solve a problem?
