### ISSUE TITLE
Just a Question for nested JSON

### ISSUE THREAD

**Issue by NicosNicolaou16** [google/gson#2705]
Hello,
Is there a way to serialize a three times nested JSON as a flat, I mean to get the specific value directly to avoid create nested models?
I searched about it but I didn't find anything clear!
Thank you!

**Comment by eamonnmcmanus** [comment]
This kind of question is probably better asked on somewhere like StackOverflow. One thing you can try is something like `new Gson().fromJson(myString, JsonElement.class)`, which will give you a `JsonElement`. You can then explore that `JsonElement` via its [methods](https://javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/JsonElement.html) to get to the data you are interested in.

**Comment by NicosNicolaou16** [comment]
Thank you for your response
