### ISSUE TITLE
Yes can confirm this; it looks like this was indeed introduced by 3e3266cf48f132928225e1561a6ae4cb5503d08f (by accident):

### ISSUE THREAD

**Issue by Brandylee24** [google/gson#2707]
Yes can confirm this; it looks like this was indeed introduced by 3e3266cf48f132928225e1561a6ae4cb5503d08f (by accident):
There is only `JsonWriter.value(long)`, so the adapters for all other integral primitive types (`byte`, `short`, `int`) actually call `value(long)`.

Sorry for that. Maybe it would make sense to (partially) revert that commit.

It seems `AtomicInteger` is affected as well, but it's adapter always behaved this way, that a `Long` instead of the `AtomicInteger` is stored in the `JsonPrimitive`. However, this might be a good thing since it is mutable and might cause confusing behavior if it was stored in `JsonPrimitive`.

_Originally posted by @Marcono1234 in https://github.com/google/gson/issues/2680#issuecomment-2125875766_

**Comment by eamonnmcmanus** [comment]
I don't know what this means.
