### ISSUE TITLE
Failure to simultaneously resolve two consumers using each of v2.10.1 and v2.11.0 together in Eclipse IDE 

### ISSUE THREAD

**Issue by scottkurz** [google/gson#2725]
# Gson version
v2.10.1 and v2.11.0, together in an OSGi runtime

# Java / Android version
Java 21

# Used tools
Eclipse IDE 2024-06 release, "Enterprise Java" package

# Description

As described in https://github.com/eclipse-jdtls/eclipse.jdt.ls/issues/3236#issuecomment-2275809952

I'm trying to load two versions of the same bundle, one which uses gson v2.10.1 and the other using gson v2.11.0.

In more detail, first, there is lsp4j v0.22.0 with
`Import-Package: com.google.gson;version="[2.9.1,2.11)",com.google.gson.a
 nnotations;version="[2.9.1,2.11)",` 

(shown here as part of a bigger excerpt of the bundle MF):
```
Bundle-SymbolicName: org.eclipse.lsp4j
...
Export-Package: org.eclipse.lsp4j;uses:="com.google.gson.annotations,org
 .eclipse.lsp4j.adapters,org.eclipse.lsp4j.jsonrpc.messages,org.eclipse.
 lsp4j.jsonrpc.validation";version="0.22.0",org.eclipse.lsp4j.adapters;u
 ses:="com.google.gson,com.google.gson.reflect,com.google.gson.stream,or
 g.eclipse.lsp4j,org.eclipse.lsp4j.jsonrpc.messages";version="0.22.0",or
 g.eclipse.lsp4j.launch;uses:="org.eclipse.lsp4j.jsonrpc,org.eclipse.lsp
 4j.services";version="0.22.0",org.eclipse.lsp4j.services;uses:="org.ecl
 ipse.lsp4j,org.eclipse.lsp4j.adapters,org.eclipse.lsp4j.jsonrpc.json,or
 g.eclipse.lsp4j.jsonrpc.messages,org.eclipse.lsp4j.jsonrpc.services";ve
 rsion="0.22.0",org.eclipse.lsp4j.util;uses:="org.eclipse.lsp4j";version
 ="0.22.0"
Import-Package: com.google.gson;version="[2.9.1,2.11)",com.google.gson.a
 nnotations;version="[2.9.1,2.11)",com.google.gson.reflect;version="[2.9
 .1,2.11)",com.google.gson.stream;version="[2.9.1,2.11)",java.io,java.la
 ng,java.lang.invoke,java.lang.reflect,java.util,java.util.concurrent,ja
 va.util.function,org.eclipse.lsp4j,org.eclipse.lsp4j.adapters,org.eclip
 se.lsp4j.jsonrpc;version="[0.22,1)",org.eclipse.lsp4j.jsonrpc.json;vers
 ion="[0.22,1)",org.eclipse.lsp4j.jsonrpc.json.adapters;version="[0.22,1
 )",org.eclipse.lsp4j.jsonrpc.messages;version="[0.22,1)",org.eclipse.ls
 p4j.jsonrpc.services;version="[0.22,1)",org.eclipse.lsp4j.jsonrpc.util;
 version="[0.22,1)",org.eclipse.lsp4j.jsonrpc.validation;version="[0.22,
 1)",org.eclipse.lsp4j.services
```

Next,  there is lsp4j v0.23.1 with
`Import-Package: com.google.gson;version="[2.9.1,3.0)",com.google.gson.an
 notations;version="[2.9.1,3.0)"` 

(Bigger bundle MF excerpt here:)
```
Export-Package: org.eclipse.lsp4j;uses:="com.google.gson.annotations,org
 .eclipse.lsp4j.adapters,org.eclipse.lsp4j.jsonrpc.messages,org.eclipse.
 lsp4j.jsonrpc.validation";version="0.23.1",org.eclipse.lsp4j.adapters;u
 ses:="com.google.gson,com.google.gson.reflect,com.google.gson.stream,or
 g.eclipse.lsp4j,org.eclipse.lsp4j.jsonrpc.messages";version="0.23.1",or
 g.eclipse.lsp4j.launch;uses:="org.eclipse.lsp4j.jsonrpc,org.eclipse.lsp
 4j.services";version="0.23.1",org.eclipse.lsp4j.services;uses:="org.ecl
 ipse.lsp4j,org.eclipse.lsp4j.adapters,org.eclipse.lsp4j.jsonrpc.json,or
 g.eclipse.lsp4j.jsonrpc.messages,org.eclipse.lsp4j.jsonrpc.services";ve
 rsion="0.23.1",org.eclipse.lsp4j.util;uses:="org.eclipse.lsp4j";version
 ="0.23.1"
Import-Package: com.google.gson;version="[2.9.1,3.0)",com.google.gson.an
 notations;version="[2.9.1,3.0)",com.google.gson.reflect;version="[2.9.1
 ,3.0)",com.google.gson.stream;version="[2.9.1,3.0)",java.io,java.lang,j
 ava.lang.invoke,java.lang.reflect,java.util,java.util.concurrent,java.u
 til.function,org.eclipse.lsp4j,org.eclipse.lsp4j.adapters,org.eclipse.l
 sp4j.jsonrpc;version="[0.23,1)",org.eclipse.lsp4j.jsonrpc.json;version=
 "[0.23,1)",org.eclipse.lsp4j.jsonrpc.json.adapters;version="[0.23,1)",o
 rg.eclipse.lsp4j.jsonrpc.messages;version="[0.23,1)",org.eclipse.lsp4j.
 jsonrpc.services;version="[0.23,1)",org.eclipse.lsp4j.jsonrpc.util;vers
 ion="[0.23,1)",org.eclipse.lsp4j.jsonrpc.validation;version="[0.23,1)",
 org.eclipse.lsp4j.services
```

Though I have gson v2.10.1 and 2.11.0 installed I can't resolve both versions of lsp4j.  The OSGi console in Eclipse shows:

```
g! lb com.google.gson

   15|Resolved   |    4|Gson (2.11.0)|2.11.0
 1011|Resolved   |    4|Gson (2.10.1)|2.10.1

g! lb org.eclipse.lsp4j
 
  621|Resolved   |    4|org.eclipse.lsp4j (0.23.1.v20240521-1815)|0.23.1.v20240521-1815
 1024|Installed  |    4|org.eclipse.lsp4j (0.22.0.v20240213-2011)|0.22.0.v20240213-2011

g! diag 1024
org.eclipse.lsp4j [1024]
  Unresolved requirement: Import-Package: com.google.gson.annotations; version="[2.9.1,2.11.0)"
```

As noted in [this](https://github.com/eclipse-jdtls/eclipse.jdt.ls/issues/3236#issuecomment-2276399714) issue response, the problem seems likely related to the way in which the `com.google.gson` imports **com.google.gson.annotations** without any qualifications on the version.   

# Reproduction steps

Besides the [original recreate](https://github.com/eclipse-jdtls/eclipse.jdt.ls/issues/3236#issuecomment-2275809952), a simpler method would be:

1. Install 2024-06 Eclipse, using the Enterprise Java package (this has both the org.eclipse.tips.json v0.3.400 plugin using gson v2.11.0 and it also has the OSGi console, for convenience).
2. Install https://download.eclipse.org/lsp4j/updates/releases/0.22.0
**Help -> Install New Software**  then click **Add** button.
For  **Location** field add `https://download.eclipse.org/lsp4j/updates/releases/0.22.0` then click **Add**.
3. Check the "Lsp4j" check box, and complete the install, and restart.
4. Open OSGi console:  
**Window->Show View->Console**, select "Host OSGi Console" from drop-down
5. From console prompt type:
`lb org.eclipse.lsp4j`
You'll see something like:
```
  621|Resolved   |    4|org.eclipse.lsp4j (0.23.1.v20240521-1815)|0.23.1.v20240521-1815
 ...
 1013|Installed  |    4|org.eclipse.lsp4j (0.22.0.v20240213-2011)|0.22.0.v20240213-2011
```
6.  Type:  `diag 1013` (or whatever bundle # you see in the prev. cmd):
You'll see something like:
```
org.eclipse.lsp4j [1013]
  Unresolved requirement: Import-Package: com.google.gson.annotations; version="[2.9.1,2.11.0)"
```

**Comment by Marcono1234** [comment]
(Disclaimer: I am not very familiar with OSGi)

Maybe related to #1001

Gson does not explicitly define `Import-Package: com.google.gson.annotations` in its `MANIFEST.MF`; instead it defines `Import-Package: *` (and manually sets `sun.misc` as optional). This way bnd-maven-plugin determines the imported packages.
The concept of both exporting and importing the same package seems intentional and is probably done to enable [substitution (OSGi Core 8 §3.6.6)](https://docs.osgi.org/specification/osgi.core/8.0.0/framework.module.html#i3238802).

I guess we could remove these self imports by writing something like:
```
Import-Package: sun.misc;resolution:=optional, !com.google.gson, !com.google.gson.*, *
```

But I am not sure if omitting the import could have any negative side effect. Or if alternatively it is possible to specify the version for the import, and if that has any negative side effect.
Maybe we should raise this issue at https://github.com/bndtools/bnd?

**Comment by scottkurz** [comment]
> Or if alternatively it is possible to specify the version for the import, and if that has any negative side effect.

This was the suggestion in the comment from @rgrunber in:  https://github.com/eclipse-jdtls/eclipse.jdt.ls/issues/3236#issuecomment-2276399714  noting another packaging of this bundle: https://git.eclipse.org/r/plugins/gitiles/orbit/orbit-recipes/+/refs/heads/master/google/com.google.gson_2.10.1/osgi.bnd
using 
```
Import-Package: \
  | com.google.gson.*;version="${range;[==,+);${package-version}}", \
  | *;resolution:=optional
```

I'm not too familiar with either the history or the bnd syntax here even, just making the connection there in noting that.

**Comment by rgrunber** [comment]
The self import is fine to keep as long as the range is tight enough so as to never include a package from another version of that library. The current self-import is unbounded. You could probably make the range even tighter with `${range;[==,=+)` (so instead of the proposed `[2.10.0, 3)` it will be `[2.10.0, 2.11.0)`

**Comment by Marcono1234** [comment]
I have created https://github.com/bndtools/bnd/issues/6220 to clarify if bnd-maven-plugin should generate these version ranges on its own by default (and to clarify what they think the correct behavior should be). But while trying to change this locally for Gson I noticed some rather strange behavior of the plugin, https://github.com/bndtools/bnd/issues/6221. It seems the `range` macro is not expanded in all cases; not sure if there is a way to work around this. Otherwise it might be necessary to wait until that is fixed.

**Comment by rgrunber** [comment]
Some older discussion on the situation : https://bugs.eclipse.org/bugs/show_bug.cgi?id=183595 .

**Comment by chrisrueger** [comment]
In https://github.com/bndtools/bnd/issues/6220#issuecomment-2312660794 it was proposed to add `-noimport:=true` to all Exports which should not be imported. This would remove the self-imports in `Import-Package` instruction.

e.g. in the bnd section of gson's [pom.xml](https://github.com/google/gson/blob/main/gson/pom.xml#L150)

```
Import-Package: sun.misc;resolution:=optional, *

-exportcontents:\
    com.google.gson.annotations;-noimport:=true
```

Maybe it can even be done for all the gson packages currently exported.

I'll try to create a PR for this.
