### ISSUE TITLE
Gson is incorrectly deserializing default fields in Kotlin

### ISSUE THREAD

**Issue by htommaso** [google/gson#2728]
# Gson version
2.11.0 (on Maven Central)

# Java / Android version
Java 21, Kotlin 1.9.24

# Used tools

- [X ] Gradle; version: 8.10 (from `brew install gradle`)

# Description
Create a project with the following Kotlin example file:

```
import com.google.gson.Gson
data class DeserializeTest(
    val id: String,
    val body: String? = null,
    val shouldEnableTesting: Boolean = true
)

fun main() {
    val serialData = "{\"id\": \"123\", \"body\": \"hello\"}"
    System.out.println(Gson().fromJson(serialData, DeserializeTest::class.java))
}
```

## Expected behavior
The code should print `DeserializeTest(id=123, body=hello, shouldEnableTesting=true)`

## Actual behavior
The code prints `DeserializeTest(id=123, body=hello, shouldEnableTesting=false)`
(Notice how the `shouldEnableTesting` flag ignores the default value in the constructor which is explicitly specified as true)

# Reproduction steps
1. `brew install gradle` (on Mac)
2. Run `gradle init`, and add this to the build.gradle.kts file in the dependencies: `implementation("com.google.code.gson:gson:2.11.0")` (note that I used Maven Central)
3. Copy paste the above code snippet into the main file
4. Run `gradle run` and observe the result

# Exception stack trace
No stack trace, this is an incorrect output and not an exception

**Comment by eamonnmcmanus** [comment]
I do think it would be good if Gson did a better job with Kotlin data classes. That would require special support which we don't currently have or plan to have. We do currently document the situation in the README:

> Gson's main focus is on Java. Using it with other JVM languages such as Kotlin or Scala might work fine in many cases, but language-specific features such as Kotlin's non-null types or constructors with default arguments are not supported. This can lead to confusing and incorrect behavior.
When using languages other than Java, prefer a JSON library with explicit support for that language.

I'm going to close this issue since it is covered by #1657 (and probably a bunch of other existing issues).
