### ISSUE TITLE
Type type = TypeToken.getParameterized(clazz, typeOfResult).getType();  Exception in thread "main" java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by 12zyhh** [google/gson#2741]
# Gson version

2.9.1

# Java / Android version

Jdk8

# Used tools

maven

# Description

When dealing with parameter types:
```
Type type = TypeToken.getParameterized(clazz, typeOfResult).getType();
```
And its thrown a exception:
```
Exception in thread "main" java.lang.IllegalArgumentException
	at com.google.gson.internal.$Gson$Preconditions.checkArgument($Gson$Preconditions.java:46)
	at com.google.gson.internal.$Gson$Types$ParameterizedTypeImpl.<init>($Gson$Types.java:494)
	at com.google.gson.internal.$Gson$Types.newParameterizedTypeWithOwner($Gson$Types.java:59)
	at com.google.gson.reflect.TypeToken.getParameterized(TypeToken.java:324)
	at cn.iocoder.lushang.module.infra.test.biz.util.JsonConvertUtil.convertJsonToEntity(JsonConvertUtil.java:59)
	at cn.iocoder.lushang.module.infra.test.biz.util.JsonConvertUtil.main(JsonConvertUtil.java:227)
```

## Expected behavior

Got a correct Type

## Actual behavior

thrown a exception: Exception in thread "main" java.lang.IllegalArgumentException

# Reproduction steps
    @Data
    class A<T> {
        private String code;
        private String swift_number;
        private String code_detail;

        private String flag;

        private T publicOpinion;

        private int costTime;
    }

    public static void main(String[] args) {
        String jsonStr = "{\n" +
                "    \"code\": \"00\",\n" +
                "    \"swift_number\": \"3031789_20230424132029_45321246A18\",\n" +
                "    \"code_detail\": {\n" +
                "        \"PublicOpinion\": \"600000\"\n" +
                "    },\n" +
                "    \"Flag\": {\n" +
                "        \"publicopinion\": \"1\",\n" +
                "        \"infoverification\": \"1\"\n" +
                "    },\n" +
                "    \"PublicOpinion\": {\n" +
                "        \"data\": {\n" +
                "            \"involvedGambling\": {\n" +
                "                \"lastLogin\": \"无数据\",\n" +
                "                \"isAgent\": \"N\",\n" +
                "                \"regWebsiteCount\": \"N\",\n" +
                "                \"isReg\": 0,\n" +
                "                \"isBindBankCard\": \"N\",\n" +
                "                \"gambleFunds\": \"0\"\n" +
                "            },\n" +
                "            \"involvedPorn\": {\n" +
                "                \"lastLogin\": \"无数据\",\n" +
                "                \"isReg\": 0\n" +
                "            },\n" +
                "            \"pyramidScheme\": {\n" +
                "                \"lastLogin\": \"无数据\",\n" +
                "                \"regTime\": \"1\",\n" +
                "                \"regWebsiteCount\": \"N\",\n" +
                "                \"isReg\": 0,\n" +
                "                \"isBindBankCard\": \"N\"\n" +
                "            }\n" +
                "        },\n" +
                "        \"costTime\": 386\n" +
                "    }\n" +
                "}";

        Type type = new TypeToken<Map<String, Object>>(){}.getType();
        A<Map<String, Object>> model = JsonConvertUtil.convertJsonToEntity(jsonStr, "publicOpinion", "data", type, A.class);
        System.out.println(model);
    }

    public static <T> T convertJsonToEntity(String jsonString
            , String resultField, String dataField, Type typeOfResult, Class<T> clazz) {
        JsonObject rootObject = parseAndTransformJson(jsonString);

        JsonElement resultElement = rootObject.get(resultField);
        if (resultElement != null) {
            JsonElement transformedResult = handleResultElement(resultElement, dataField);
            rootObject.add(resultField, transformedResult);
        }

        Type type = TypeToken.getParameterized(clazz, typeOfResult).getType();
        return GSON.fromJson(rootObject, type);
    }

# Exception stack trace

```
Exception in thread "main" java.lang.IllegalArgumentException
	at com.google.gson.internal.$Gson$Preconditions.checkArgument($Gson$Preconditions.java:46)
	at com.google.gson.internal.$Gson$Types$ParameterizedTypeImpl.<init>($Gson$Types.java:494)
	at com.google.gson.internal.$Gson$Types.newParameterizedTypeWithOwner($Gson$Types.java:59)
	at com.google.gson.reflect.TypeToken.getParameterized(TypeToken.java:324)
	at cn.iocoder.lushang.module.infra.test.biz.util.JsonConvertUtil.convertJsonToEntity(JsonConvertUtil.java:59)
	at cn.iocoder.lushang.module.infra.test.biz.util.JsonConvertUtil.main(JsonConvertUtil.java:227)

```

**Comment by Marcono1234** [comment]
Can you please try making your `A` class `static`? It looks like currently it is a non-`static` inner class and in that case an 'owner type' is required (which is not supported by the `TypeToken#getParameterized` method though).

Also, could you please try the latest Gson version (currently 2.11.0)? At least the exception message should be more descriptive there.

**Comment by 12zyhh** [comment]
> Can you please try making your `A` class `static`? It looks like currently it is a non-`static` inner class and in that case an 'owner type' is required (which is not supported by the `TypeToken#getParameterized` method though).
> 
> Also, could you please try the latest Gson version (currently 2.11.0)? At least the exception message should be more descriptive there.
1

**Comment by 12zyhh** [comment]
thank you very much!! it's right that A.class it's not a **static inner class...** because non-static inner class whll implicitly hold references to external class instancees when instantiating or they cannot exist independently and can only be accessed through external class instances if i remove static, it is necessary to provide ownerType  but **TypeToken#getParameterized** do not support it 

```
    public static TypeToken<?> getParameterized(Type rawType, Type... typeArguments) {
        return new TypeToken(Types.newParameterizedTypeWithOwner((Type)null, rawType, typeArguments));
    } // ownerType is null

    public static ParameterizedType newParameterizedTypeWithOwner(Type ownerType, Type rawType, Type... typeArguments) {
        return new ParameterizedTypeImpl(ownerType, rawType, typeArguments);
    }

 boolean isStaticOrTopLevelClass = Modifier.isStatic(rawTypeAsClass.getModifiers()) || rawTypeAsClass.getEnclosingClass() == null;
                Preconditions.checkArgument(ownerType != null || isStaticOrTopLevelClass);
```
can I extend TypeAdapterFactory to handle ownerType myself?

**Comment by Marcono1234** [comment]
Were you able to solve this issue? Based on your comment it sounds like this is not resolved, but on the other hand you closed this issue as "completed".

I think making `A` `static` (or a top-level class) is the proper solution here. The other issue with using a non-`static` class is that all its constructors always have an implicit parameter for the instance of the enclosing class.
This means there is no no-args constructor, and therefore Gson cannot call its constructor during deserialization and instead uses `Unsafe`, which can have undesired side effects, see [`GsonBuilder#disableJdkUnsafe()`](https://javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/GsonBuilder.html#disableJdkUnsafe()).

**Comment by 12zyhh** [comment]
sorry for the fact that it took so long to see the message.
only for my bug, 
  1. A  can be corrected, either with a **static** modifier or as a top-level class
  2. use a custom deserializer to manually provide an instance of the outer class at the time of deserialization (I feel that this method is unnecessary and too cumbersome....)

####  A.class
```
    @Data
    class A<T> {
        private String code;
        private String swift_number;
        private Map<String, Object> code_detail;

        private Map<String, Object> flag;

        private T publicOpinion;

        private int costTime;
    }
```
#### CustomDeserializer
```
public class CustomDeserializer <T> implements JsonDeserializer<JsonConvertUtil.A<T>> {
    private final Class<T> typeOfT;
    private final JsonConvertUtil outerInstance;

    public CustomDeserializer(Class<T> typeOfT, JsonConvertUtil outerInstance) {
        this.typeOfT = typeOfT;
        this.outerInstance = outerInstance;
    }



    @Override
    public JsonConvertUtil.A<T> deserialize(JsonElement jsonElement, Type type, JsonDeserializationContext jsonDeserializationContext) throws JsonParseException {
        JsonObject jso = jsonElement.getAsJsonObject();

        // inner class A
        JsonConvertUtil.A<T> aInstance = outerInstance.new A<>();

        Field[] fields = aInstance.getClass().getDeclaredFields();
        for (Field f : fields) {
            f.setAccessible(true);

            String fName = f.getName();
            if (jso.has(fName)) {
                try {
                    // dynamic set field
                    if (f.getType() == String.class) {
                        f.set(aInstance, jso.get(fName).getAsString());
                    } else if (f.getType() == int.class || f.getType() == Integer.class) {
                        f.set(aInstance, jso.get(fName).getAsInt());
                    } else if (f.getType() == Map.class) {
                        Type mapType = new TypeToken<Map<String, Object>>(){}.getType();
                        Map<String, Object> mapVal = jsonDeserializationContext.deserialize(jso.get(fName), mapType);
                        f.set(aInstance, mapVal);
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }

        // handle T
        JsonObject publicOpinionObj = jso.getAsJsonObject("PublicOpinion").getAsJsonObject("data");
        T publicOpinionData = jsonDeserializationContext.deserialize(publicOpinionObj, typeOfT);
        aInstance.setPublicOpinion(publicOpinionData);

        return aInstance;
    }
}
```
#### main
```
        // create outer instance
        JsonConvertUtil outerInstance = new JsonConvertUtil();


        GsonBuilder gsonBuilder = new GsonBuilder();

        // register custom deserializer
        gsonBuilder.registerTypeAdapter(
                new TypeToken<JsonConvertUtil.A<Map<String, Object>>>(){}.getType(),
                new CustomDeserializer<>(Map.class, outerInstance)
        );
        Gson gson = gsonBuilder.create();

        // deserialize
        JsonConvertUtil.A<Map<String, Object>> aInstance = gson.fromJson(jsonStr, new TypeToken<JsonConvertUtil.A<Map<String, Object>>>(){}.getType());
        System.out.println(aInstance);
```
