### ISSUE TITLE
Allow serialization of anonymous and local classes

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gson#298]
```
What steps will reproduce the problem?

        Gson gson = new Gson();
        String json = gson.toJson(new Object() {
            String url = "http://localhost:10080/live/list";
            String[] names = new String[] {"dsc0001","dsc0002","dsc0003"};
        });
        System.out.println(json);

What is the expected output?
{"url":"http://localhost:10080/live/list","name":[{"dsc0001","dsc0002","dsc0003"
]}

What do you see instead?
blank line

What version of the product are you using? On what operating system?
1.6

Please provide any additional information below.
I understand that there are default exclusion strategies that prevent the 
serialization of objects belonging to an anonymous or local class, but it would 
be great if these could be bypassed to allow the above notation.


```

Original issue reported on code.google.com by `robby...@gmail.com` on 17 Mar 2011 at 2:14

**Comment by codeblooded** [comment]
I see this closed, but I don't see a reason.  Can we reopen or provide clarification?  It sounds like this thread seemed in overwhelming support for anonymous class serialization.

**Comment by mintern** [comment]
This is especially problematic with Java 8. I've tried to create a TypeAdapterFactory for serializing Streams, but my `create` method never even gets called because `ReferencePipeline$2` is anonymous, so the Excluder just returns null.

**Comment by lyubomyr-shaydariv** [comment]
@mintern

> This is especially problematic with Java 8. I've tried to create a TypeAdapterFactory for serializing Streams, but my `create` method never even gets called because `ReferencePipeline$2` is anonymous, so the Excluder just returns null.

It should work if you provide a type to the `toJson()` method:

```java
... = gson.toJson(stringStream, new TypeToken<Stream<String>>() {}.getType());
```

----

I think that this issue should be reopened, because it's possible to serialize and deserialize an anonymous/local class object, if the class does not have its outer class reference `this$0`, for example, if declared in a static method (don't think it has much practical use, though).
