### ISSUE TITLE
Serializing and Deserializing Generic Types - toJson() works!

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gson#348]
```
What steps will reproduce the problem?
1. Write a vanilla java class and declare a field of type List<String>
2. Populate the list with some arbitrary string values and call toJson()
3. It serializes the object and generates a correctly formatted JSON string

What is the expected output? What do you see instead?
It should throw a runtime exception as per the user guide

What version of the product are you using? On what operating system?
1.7.1

Please provide any additional information below.
Either something is wrong with my code / the user guide needs to be updated
```

Original issue reported on code.google.com by `ray.may...@gmail.com` on 22 Jul 2011 at 3:50

**Comment by spellsleeper** [comment]
Hi, I created a full generic Pojo with which I want realize to push some data to files. But my Problem is that Gson dont works with deep combined generic collections like this 'List<SubResultPojo<String, List<Double[]>>>'. If I've got only one Collection with nativ types like this 'List<SubResultPojo<String,Integer>>' gson works fine. Is their a solution to fix it? I tried tthis but it was no solution 
... Type resultType=new TypeToken<List<SubResultPojo<String, List<Double[]>>>>(){}.getType();
            System.out.println(new Gson().toJson(list.getDataList(), resultType));

**Comment by Marcono1234** [comment]
Can probably be closed since as pointed out in https://github.com/google/gson/issues/348#issuecomment-83704505 this was a misunderstanding of the documentation.
