### ISSUE TITLE
the XMLGregorianCalendar datatype is not supported by gson API

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gson#368]
```
What steps will reproduce the problem?
1. If a POJO has a variable of the XMLGregorianCalendar datatype, the result is 
null.
2.
3.

What is the expected output? What do you see instead?
It should be Date.

What version of the product are you using? On what operating system?
gSon 1.2.3 and Windows 7

Please provide any additional information below.


I have application from which XML can be converted to json and vice versa. The 
following variable in my POJO with the datatype of XMLGregorianCalendar for 
date is null in my output.

protected XMLGregorianCalendar doj;

Please help me ASAP.

Regards,
Harish
```

Original issue reported on code.google.com by `swarab...@gmail.com` on 10 Oct 2011 at 8:01

**Comment by lgrousset** [comment]
With gson v2.5 and java 8 :

public class XMLGregorianCalendarConverter {
	public static class Serializer implements JsonSerializer<XMLGregorianCalendar> {
		@Override
		public JsonElement serialize(XMLGregorianCalendar xmlGregorianCalendar, Type type, JsonSerializationContext jsonSerializationContext) {
			return new JsonPrimitive(xmlGregorianCalendar.toXMLFormat());
		}
	}

	public static class Deserializer implements JsonDeserializer<XMLGregorianCalendar> {
		@Override
		public XMLGregorianCalendar deserialize(JsonElement jsonElement, Type type,
				JsonDeserializationContext jsonDeserializationContext) {
			try {
				return DatatypeFactory.newInstance().newXMLGregorianCalendar(jsonElement.getAsString());
			} catch (Exception e) {
				e.printStackTrace();
				return null;
			}
		}
	}
}

**Comment by sushmitha11** [comment]
Thank you. So helpful.
