### ISSUE TITLE
Populate existing object

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gson#431]
```
It would be great is gson supported the population of existing objects. There 
was a post a while back alluding to this behavior, but it doesn't exist now:

http://groups.google.com/group/google-gson/browse_thread/thread/ab97b754c1f3c53a
?pli=1

The rationale is that this would prevent users from having to create 
TypeAdapters or InstanceCreators for every object that requires custom 
construction, particularly since gson doesn't support the notion of a global 
InstanceCreator at the moment.
```

Original issue reported on code.google.com by `pacesysj...@gmail.com` on 8 Apr 2012 at 5:12

**Comment by augustbering** [comment]
Something like this seems to work well for me. I might have missed something but so far, so good...

```Java
	/**
	 * updates @target object from the @json object. Only fields existing in @json are affected
	 * @param target
	 * @param json
	 * @throws Exception
	 */
	public static  void update(Object target, JsonObject json) throws Exception {

		Class<? > class1 = target.getClass();
		
		Set<Entry<String, JsonElement>> entrySet = json.entrySet();
		for (Entry<String, JsonElement> entry : entrySet) {
			String key = entry.getKey();
			Field field = class1.getDeclaredField(key);
			Type genType = field.getGenericType();

			field.set(target,
					gson.fromJson(entry.getValue(),genType));
		}

	}
```

**Comment by Xerosigma** [comment]
For the love of source do NOT use the snippet above as is.

But yes - This is a much needed feature. Just came across a very unfortunate use case.

**Comment by diskzzokejs** [comment]
Any update on this?

**Comment by bennylut** [comment]
Why this issue was closed? is this became a planned feature? is it rejected?

**Comment by inder123** [comment]
You can implement this using InstanceCreators.

```java
final Foo existing;
InstanceCreator<Foo> creator = new InstanceCreator<Foo>() {
  public Foo createInstance(Type type) { return existing; }
}

Gson gson = new GsonBuilder().registerTypeAdapter(Foo.class, creator).create();
Foo value = gson.fromJson(jsonString, Foo.class);
// value should be same as existing
```

**Comment by Psidium** [comment]
I needed to update a managed JPA object with a JSON from the web service, this is the solution I've found (I needed to use the local instance of appConfig):

```java
AppConfiguration appConfig = AppConfigurationDAO.getInstance().read(Long.parseLong(req.params(":id")));

InstanceCreator<AppConfiguration> creator = new InstanceCreator<AppConfiguration>() {
    private AppConfiguration appConfig;

    public AppConfiguration createInstance(Type type) {
        return appConfig;
    }

    public InstanceCreator<AppConfiguration> withValue(AppConfiguration appConfig) {
        this.appConfig = appConfig;
        return this;
    }

}.withValue(appConfig);

Gson gson = new GsonBuilder().registerTypeAdapter(AppConfiguration.class, creator).create();
appConfig = gson.fromJson(req.body(), AppConfiguration.class);

return AppConfigurationDAO.getInstance().update(appConfig);
```

I then stated to wonder: can't we have a `InstanceUpdater` class? It could have a implementation like this:
 
```java
import com.google.gson.InstanceCreator;
import java.lang.reflect.Type;

public class InstanceUpdater<T> implements InstanceCreator<T> {

    private T object;

    public T createInstance(Type type) {
        return object;
    }

    public InstanceUpdater(T object) {
        this.object = object;
    }

}
```
Then I can use with something like this:
```java
InstanceCreator<AppConfiguration> creator = new InstanceUpdater<AppConfiguration>(appConfig);
```

But I'm not sure, I feel there may be a better way of doing this, and it would be amazing to have something inside Gson to manage this for me.

**Comment by Robertiano** [comment]
Why this issue was closed? is this became a planned feature? is it rejected?

**Comment by inder123** [comment]
@Robertiano At the moment there is a workaround as outlined above with InstanceCreator.
We are still searching for an elegant proposal.

**Comment by eyal-rounds** [comment]
Apparently i need this as well, InstanceCreator is a bad option as if i want to make an extendable class static creators will need to be overwritten since there is no inheritance for that.
Typeadapter creates the object, i seriously think that only copying field without object creation should be easy, if not at least can you supply a static method that can copy the fields using reflection ?

**Comment by CreamyCookie** [comment]
`TypeAdapter` worked well for populating an existing object. Just return the instance in the `read` method. Here's an example: http://www.javacreed.com/gson-typeadapter-example/

**Comment by derwaldgeist** [comment]
Would love to see this, too.

**Comment by redmondgiant** [comment]
For posterity, if this is ever addressed:

Take into account nested reuse of existing objects at any level of the deserialization, not just the root object. Then you can see why InstanceCreator doesn't work.

You would need to pass in the containing object (which itself went through the usual process to be obtained), perhaps the InstanceUpdater<T> where it passes along the containing object as context mainly so it can choose to reuse the T hanging off of it and continue on.

I have use cases (multiple) where I have all sorts of state like event handlers hanging off of important levels of a large tree of objects, and I want essentially all the unimportant "leaf fields" overwritten with incoming values but the important object scaffolding itself remains unchanged at all levels.
