### ISSUE TITLE
Attempting to parse an empty string returns null instead of throwing JsonSyntaxException

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gson#457]
```
The following test case illustrates what I think the parser should be doing in 
the event of an immediate EOF:

    @Test
    public void testEmptyStreamBehaviour()
    {
        Gson gson = new Gson();
        try
        {
            gson.fromJson(new StringReader(""), String.class);
            fail("Expected JsonSyntaxException");
        }
        catch (JsonSyntaxException e)
        {
            // Expected.
        }
    }

What really happens is that it returns null. This resulted in an incredibly 
difficult to track down bug which turned out to just be someone sending no data 
instead of sending JSON.

```

Original issue reported on code.google.com by `trejkaz` on 2 Jul 2012 at 1:49

**Comment by mbroshi** [comment]
The suggested workaround doesn't seem to work if there is a custom type adapter registered for the class, because that type adapter code never gets hit. A slight modification of the OP's code with the suggested fix still fails:

    @Test
    public void testEmptyStreamBehaviour()
    {
        Gson gson = new GsonBuilder().registerTypeAdapter(String.class, new JsonDeserializer<String>() {
            @Override
            public String deserialize(JsonElement json, Type typeOfT, JsonDeserializationContext context) throws JsonParseException {
                throw new JsonSyntaxException("Never gets here");
            }
        }).create();
        try
        {
            gson.getAdapter(String.class).fromJson("");
            fail("Expected JsonSyntaxException");
        }
        catch (JsonSyntaxException | IOException e)
        {
            // Expected.
        }
    }

**Comment by Marcono1234** [comment]
@mbroshi, you have to use a `TypeAdapter` instead of a `JsonDeserializer` because that is automatically made `null`-safe, see #1697.
