### ISSUE TITLE
Support Throwable and Exception for serializing/deserializing

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gson#469]
```
https://groups.google.com/d/topic/google-gson/fGTi5EEc9jM/discussion
```

Original issue reported on code.google.com by `in...@trymph.com` on 6 Sep 2012 at 10:58

**Comment by Marcono1234** [comment]
There original issue here had a different cause and was fixed more than 8 years ago. It probably does not make sense to reopen this, and you created a new issue already anyways (#2352).
