### ISSUE TITLE
gson-stream deprecation

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gson#502]
```
Please provide some explanation why gson-stream library is deprecated and what 
do you recommend to use instead? I'm very happy using it in my Android project 
and don't want to replace it with 500K+ full gson jar
```

Original issue reported on code.google.com by `bost...@gmail.com` on 20 Feb 2013 at 6:11

**Comment by Marcono1234** [comment]
It looks like for a long time already Gson has been published only as a single library. And given that Gson is now in maintenance mode, it seems unlikely that it will be split into a separate stream parser library. Though maybe the project members think differently about this.

**Comment by eamonnmcmanus** [comment]
Agree with the assessment from @Marcono1234.
