### ISSUE TITLE
Deserialization with Gson.fromJson() should *ignore* missing fields

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gson#513]
```
What steps will reproduce the problem?

1. Create a simple *non-static* class which initializes default values for some 
fields:

    public class Test {

        int x = -1;
        String s = "Hello";
    }

2. Create new Gson and call `fromJson()` with missing fields:

    Test t = new Gson().fromJson("{}", Test.class);
    System.out.println(String.format("x=[%s] s=[%s]", t.x, t.s));

>> Results: x=[0] s=[null]

    Test t = new Gson().fromJson("{\"x\": 1}", Test.class);
    System.out.println(String.format("x=[%s] s=[%s]", t.x, t.s));

>> Results: x=[1] s=[null]

What is the expected output? What do you see instead?

As the test cases, I would like to expect default value for each field to be 
the one that the class initializes. For instance with the first test case, `x` 
should be `-1` and `s` should be "Hello".

What version of the product are you using? On what operating system?

 - Gson 2.2.3
 - OSes:
   + Fedora 18, 64 bit with OpenJDK 1.7.0_19;
   + Android API 4 and API 17;

Thanks,
Hai
```

Original issue reported on code.google.com by `haibison...@gmail.com` on 5 May 2013 at 8:23

**Comment by tommiller1** [comment]
This is still a problem, is anyone looking into this? How do we prevent null fields from being deserialized?

**Comment by VyshnavKR** [comment]
Ya man...i'm also stuck with this

**Comment by stayclean** [comment]
Is it solved? 2016 Nov, missing field should have method to get ignored.

**Comment by VyshnavKR** [comment]
@stayclean
I don't remember the solution but I have done it all well. 
Will this help?
stackoverflow.com/questions/33435683/deserialize-with-gson-and-null-values

**Comment by VyshnavKR** [comment]
www.stackoverflow.com/questions/33435683/deserialize-with-gson-and-null-values

**Comment by anubiann00b** [comment]
I'm having the same problem right now. That link does not help, it's about something else @VyshnavKR

**Comment by VyshnavKR** [comment]
Have you posted in StackOverflow? If not kindly post it there and share the link here. Let's discuss it there.

**Comment by MiralDesai** [comment]
How has this not been fixed it? Is it still being looked at? It's a big problem. 

Fields that have nothing to do with the JSON return should not be modified at all.

**Comment by tntu** [comment]
Any update on this?

**Comment by Begro** [comment]
I tried in gson 2.8.1,it is already fixed.
`public class User {
    String name = "username";
    int x = -1;
}`
`public static void main(String[] args) {
        User u = new Gson().fromJson("{}", User.class);
        System.out.println(String.format("x=[%s] s=[%s]", u.name,u.x));
 }`
result:x=[username] s=[-1]

**Comment by pysaumont** [comment]
Not working for me with 2.8.1.

```
  public class User {
    String name = "username";
    int x = -1;
  }

  public static void main(String[] args) {
    User u = new Gson().fromJson("{}", User.class);
    System.out.println(String.format("x=[%s] s=[%s]", u.name,u.x));
  }
```
result:

```
x=[null] s=[0]
```

**Comment by Begro** [comment]
I am sorry for my poor Engilsh.
I found somecode in gson.
` TypeAdapter<T> typeAdapter = getAdapter(typeToken);

  T object = typeAdapter.read(reader);`
And I go into the class 
`ReflectiveTypeAdapterFactory`
and the method,I found 
` T instance = constructor.construct();
     try {
        in.beginObject();
        while (in.hasNext()) {
          String name = in.nextName();
          BoundField field = boundFields.get(name);
          if (field == null || !field.deserialized) {
            in.skipValue();
          } else {
            field.read(in, instance);
          }
        }`

First,the code user the java reflect Constructor.newInstance(Object... args),
although args ==null  ,the instance initialize its parameter.
In my case,the name is initialize to username.
And in.hasNext() == false , return instance.
The result is username not null.

**Comment by pysaumont** [comment]
Do you mean you find some code and used it in you own application? Perhaps you have registered a type adapter somewhere before. If so, can you post a working example? (To preserve formatting, insert you code examples between two lines containing only three backticks (`), such as:

<pre>
```
public class User {
    String name = "username";
    int x = -1;
}
```
</pre>

**Comment by Begro** [comment]
Thank you.
I didn't describe clearly.
I debug the Gson source code.And I found why my result is username not null.
You can follow the call chain,you will found the method in Gson.java
```
public <T> T fromJson(JsonReader reader, Type typeOfT) throws JsonIOException, JsonSyntaxException {
    boolean isEmpty = true;
   boolean oldLenient = reader.isLenient();
   reader.setLenient(true);
   try {
     reader.peek();
     isEmpty = false;
     TypeToken<T> typeToken = (TypeToken<T>) TypeToken.get(typeOfT);
     TypeAdapter<T> typeAdapter = getAdapter(typeToken);
     T object = typeAdapter.read(reader);
     return object;
   } 
  ```
and the typeAdapter is instanceof  Adapter in ReflectiveTypeAdapterFactory.
and the method read() is
``` 
T instance = constructor.construct();

      try {
        in.beginObject();
        while (in.hasNext()) {
          String name = in.nextName();
          BoundField field = boundFields.get(name);
          if (field == null || !field.deserialized) {
            in.skipValue();
          } else {
            field.read(in, instance);
          }
        }
      }
     return instance;
 
``` 
'T instance = constructor.construct();'  After this,instance is initialize its parameter.
In my code, the parameter 'name' is initialize to 'username'.
And in.hasNext()==false, so the method just return instance.
For more detail, the code ' constructor.construct()' user the java reflect 
``` 
Constructor.newInstance(Object... args)
``` 
although 'args ==null' ,the instance initialize its parameter with default value.
I did in jdk1.7 and jdk1.8 .
Did I describe clearly ? I tried my best.
Sorry , I will improve my English.

**Comment by ahoyland** [comment]
This is still a problem.  I'm going to have to use a different library because of this.  Very disappointing...

**Comment by bulldozer75** [comment]
Works in 2.8.2. Declare the User class static or define it outside of another class.

**Comment by mario222k** [comment]
For me it works with 2.8.5 only if all fields have defaults

```
    private data class Foo(
        @SerializedName("claus") val santa: Boolean = false
        @SerializedName("norris") val chuck: Boolean = true
    )

   val foo = Gson().fromJson<Foo>("{}", Foo::class.java) // --> Foo(santa=false, chuck=true)
```

but when one has no default

```
    private data class Foo(
        @SerializedName("claus") val santa: Boolean
        @SerializedName("norris") val chuck: Boolean = true
    )

   val foo = Gson().fromJson<Foo>("{}", Foo::class.java) // --> Foo(santa=false, chuck=false)
```

**Comment by Sdghasemi** [comment]
However I'm disappointed, I'm currently using this approach:
```
public class Test {
    @SerializedName("f")
    private int foo;
    @SerializedName("b")
    private int bar;
    
    public Test() {
        bar = -1;    // Uses -1 as default value for bar variable when it's not present in the JSON
    }
    ...
}
```

**Comment by transilvlad** [comment]
I changed the logic of my code to have a defaults JSON file that then gets mapped over and adds values where missing.

**Comment by lll-01** [comment]
modify [ReflectiveTypeAdapterFactory](https://github.com/google/gson/blob/9d44cbc19a73b45971c4ecb33c8d34d673afa210/gson/src/main/java/com/google/gson/internal/bind/ReflectiveTypeAdapterFactory.java#L129)

```
 @Override
 void read(JsonReader reader, Object value)
         throws IOException, IllegalAccessException {
     Object fieldValue = typeAdapter.read(reader);
     if (fieldValue == null && !context.deserializeNulls()) return;// Do not write null value
     if (fieldValue != null || !isPrimitive) {
         field.set(value, fieldValue);
     }
 }
```
add deserializeNulls  to [GsonBuilder](https://github.com/google/gson/blob/9d44cbc19a/gson/src/main/java/com/google/gson/GsonBuilder.java#L192)  and Gson
```
/**
 * Configure Gson to deserialize null fields. By default, Gson omits all fields that are null
 * during deserialization.
 *
 * @return a reference to this {@code GsonBuilder} object to fulfill the "Builder" pattern
 * @since 1.2
 */
public GsonBuilder deserializeNulls() {
    this.deserializeNulls = true;
    return this;
}
```

**Comment by moodi1999** [comment]
> This is still a problem. I'm going to have to use a different library because of this. Very disappointing...

did you find solution in other lib?
if you did please mention it.🙏🏻

**Comment by mochadwi** [comment]
any actual updates for this?

**Comment by mochadwi** [comment]
> modify [ReflectiveTypeAdapterFactory](https://github.com/google/gson/blob/9d44cbc19a73b45971c4ecb33c8d34d673afa210/gson/src/main/java/com/google/gson/internal/bind/ReflectiveTypeAdapterFactory.java#L129)
> 
> ```
>  @Override
>  void read(JsonReader reader, Object value)
>          throws IOException, IllegalAccessException {
>      Object fieldValue = typeAdapter.read(reader);
>      if (fieldValue == null && !context.deserializeNulls()) return;// Do not write null value
>      if (fieldValue != null || !isPrimitive) {
>          field.set(value, fieldValue);
>      }
>  }
> ```
> 
> add deserializeNulls to [GsonBuilder](https://github.com/google/gson/blob/9d44cbc19a/gson/src/main/java/com/google/gson/GsonBuilder.java#L192) and Gson
> 
> ```
> /**
>  * Configure Gson to deserialize null fields. By default, Gson omits all fields that are null
>  * during deserialization.
>  *
>  * @return a reference to this {@code GsonBuilder} object to fulfill the "Builder" pattern
>  * @since 1.2
>  */
> public GsonBuilder deserializeNulls() {
>     this.deserializeNulls = true;
>     return this;
> }
> ```

the `ReflectiveTypeAdapterFactory` is final, we cannot inherit it. any other approach? @lll-01

**Comment by a1573595** [comment]
Still a problem.

**Comment by Nnaoma** [comment]
Still a problem

**Comment by eamonnmcmanus** [comment]
The 2020 [comment](https://github.com/google/gson/issues/513#issuecomment-678654077) from @Marcono1234 remains correct. If you are seeing this problem for a class that is _not an inner class_ (it's a top-level class, or it's `static`) and that _has a no-arg constructor_, then please open a separate bug with a minimal test case that reproduces the problem. Otherwise, the solution is probably to register a [`TypeAdapter`](https://www.javadoc.io/static/com.google.code.gson/gson/2.9.0/com.google.gson/com/google/gson/TypeAdapter.html) for your class.

Concerning Kotlin, it doesn't work if some but not all fields in a `data class` have default values. If all fields do have default values then the Kotlin compiler [generates a no-arg constructor](https://kotlinlang.org/docs/classes.html#secondary-constructors):

> On the JVM, if all of the primary constructor parameters have default values, the compiler will generate an additional parameterless constructor which will use the default values. This makes it easier to use Kotlin with libraries such as Jackson or JPA that create class instances through parameterless constructors.

**Comment by kevinjmh** [comment]
In case of using Scala, I found a way to get what we want.
Instead of :
```
class Test {
    var x = -1
    var s = "Hello"
}
 val t = new Gson().fromJson("{}", classOf[Test])
 println(t.x, t.s)
```
Try this:
```
class Test {
    def x = -1
    def s = "Hello"
}
 val t = new Gson().fromJson("{}", classOf[Test])
 println(t.x, t.s)
```

As mentioned above, constructor is the key point.
