### ISSUE TITLE
Support direct url as input

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gson#518]
```
I think that gson should support url as input.
Something like the JSONParser `.getJSONFromUrl(url);` function.
```

Original issue reported on code.google.com by `fabioloc...@gmail.com` on 5 Jun 2013 at 9:43

**Comment by Marcono1234** [comment]
This would certainly make certain use cases simpler, but the main problem might be that Gson would have to guess (or infer) how to convert the `InputStream` from the connection to a `Reader`, see also #1259. So it is a bit unlikely that the project members will add such a method.

**Comment by eamonnmcmanus** [comment]
A second question would be whether to use `java.net.URL` or `java.net.URI`. :-)
On the whole I think it is easy enough for users to read data from URLs themselves, and it means we don't have to solve the tricky questions that @Marcono1234 alludes to.
