### ISSUE TITLE
List of generic interfaces

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gson#519]
```
Hi, i have a problem in Gson serialization.
When i try to serialize an object with a list of generic interfaces, the list 
is empty.

I have find a solution to create an adapter with registerTypeAdapter but i 
think that is just a bug in Gson lib.

In the code if you remove 
gsonBuilder.registerTypeAdapter(IPClass.class, new IPClassAdapter());
the list is not serialized.

The IPClassAdapter is just a SUPER.serialize via context.serialize.
```

Original issue reported on code.google.com by `fouache2...@gmail.com` on 6 Jun 2013 at 2:32

Attachments:
- [listOfParametrizedInterfaces.txt](https://storage.googleapis.com/google-code-attachments/google-gson/issue-519/comment-0/listOfParametrizedInterfaces.txt)

**Comment by Marcono1234** [comment]
Closing this because the attached source code is unfortunately not available anymore and this issue is most likely no longer relevant given that it was created 9 years ago.
