### ISSUE TITLE
Expose StringPool

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gson#520]
```
It would be nice if StringPool can be exposed outside of JsonReader so it can 
be injected. It will be useful in the case that you have to parse a lot of 
different JSON documents that have the same structure/schema and there is there 
is a need to reduce memory consumption.
```

Original issue reported on code.google.com by `nat.lu...@gmail.com` on 11 Jun 2013 at 4:42

**Comment by Marcono1234** [comment]
Probably obsolete because the `StringPool` class does not exist anymore (for a long time already), see also 70f9280cb64aeec323a8675871579687ab66f9c6.

**Comment by eamonnmcmanus** [comment]
Thanks, I think we can close this then.
