### ISSUE TITLE
LinkedHashTreeMap comparator problem

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gson#521]
```
What steps will reproduce the problem?
Run the attached java code with the gson library attached. 

What is the expected output? What do you see instead?
When getting the "key" key from the map, this map gives null, however when I 
iterate through its entryset, both the key and value is contained. For 
double-check, the JDK hashmap gives back the proper value. 

What version of the product are you using? On what operating system?
Gson 2.2.3 on both windows 7 and redhat and ubuntu linux. 

Please provide any additional information below.
Run it, and the problem will be visible from the standard output. Quite serious 
I think...
```

Original issue reported on code.google.com by `d.biszt...@googlemail.com` on 12 Jun 2013 at 9:06

Attachments:
- [HashMagic.java](https://storage.googleapis.com/google-code-attachments/google-gson/issue-521/comment-0/HashMagic.java)

**Comment by Marcono1234** [comment]
The previous comments suggest this was fixed and also the changelog [mentions that a hashing bug was fixed](https://github.com/google/gson/blob/241044d70912a34ec7326b7bf41a83b643d49f14/CHANGELOG.md?plain=1#L182). Additionally that class does not exist anymore since #1992.
