### ISSUE TITLE
google-gson ECCN

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gson#558]
```
HI,

I am using gson 2.2.2 

I need to know the Export Control Classification Number gor gson.
Can you provide me such information ?

Thanks in advance

Eric
```

Original issue reported on code.google.com by `dampierr...@gmail.com` on 6 Feb 2014 at 2:55

**Comment by 324881** [comment]
I have this same need - I expect that the GSON library implements no encryption but a statement from the project owners on this issue would be very helpful.  Other Google projects have done this; e.g., https://github.com/google/protobuf/issues/376  Thanks in advance!

**Comment by inder123** [comment]
Please provide steps on how we obtain ECCN for Gson.

**Comment by 324881** [comment]
To determine the applicable Export Control Classification Number (ECCN) for a piece of software, you read the Commerce Control List (CCL) (Supplement No. 1 to Part 774 of the EAR) and try to figure out where the software fits.  In the best case, you will find an exemption (this is better than an exception) that applies to your situation and therefore that piece of software is not subject to export control, and has an ECCN of "EAR-99" (the holy grail in this sort of thing).  You may wind up writing a statement something like this:

> The [XYX Software] primary functions do not include information security; sending, receiving or storing information; or networking; and it is not a computer, operating system, or parts or components therefor.  Hence, [XYZ Software], excluding 3rd party software, is not controlled for export per Note 4 to Category 5, Part 2 (Supplement No 1 to Part 774)

This may help:

https://www.bis.doc.gov/index.php/licensing/commerce-control-list-classification/export-control-classification-number-eccn

HTH

**Comment by inder123** [comment]
We are willing to write a statement like this. Can you (or someone else who needs and knows this) write down a step-by-step process that we can follow?

**Comment by 324881** [comment]
Thanks for your attention to this!  Determining an ECCN is a manual, tedious process with no shortcuts that I can offer to you. I am doing the same as part of determining the effective ECCN for a package to be released as open source. Because the package uses many third-party jars including GSON, I need to include the library classifications in the analysis.

**Comment by inder123** [comment]
As much I would like to do this work on my own, I simply don't have cycles.
Someone (preferably who needs this most) needs to do the majority of the work figuring this out, and at least lay out clear steps for us to follow.

**Comment by 324881** [comment]
In the case of GSON the process should be straightforward. As far as I can tell, the GSON jar is not designed to use cryptography, nor does it contain cryptography.  Stated differently, the code does not use encryption/decryption features provided by an operating system or by a third-party library; further the code does not implement any encryption/decryption features. Therefore none of the export controls that address information security should apply.

Here is the link to the original document (Part 774, Supplement 1, Category 5, Part 2):

    https://www.bis.doc.gov/index.php/forms-documents/doc_view/335-supplement-no-1-to-part-774-category-5-part-ii-information-security

I sympathize that it's extremely difficult to read.

**Comment by hemantmakhijani** [comment]
Did we find ECCN for google/gson ?
If its ECCN 5D002 or 5D992 , we also require CCATS certificate which should have been taken from U.S. for export control.

**Comment by eamonnmcmanus** [comment]
I'm afraid I can only echo the sentiments of @inder123 in 2016. The project maintainers don't know anything about ECCNs or CCATSs. If you need that for Gson then you are going to have to do the research for it yourself. My _completely uninformed_ opinion is that this is publicly-available software that does not bundle any encryption, so you probably shouldn't need these things. But I would advise consulting an expert if anything important depends on it.

**Comment by hemantmakhijani** [comment]
HI @inder123, @324881 
Did you get any more opportunity in figuring out the ECCN for gson ?
