### ISSUE TITLE
Error While Serializing java.nio.file.Path object

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gson#595]
```
What steps will reproduce the problem?
1. I am serializing an object with java.nio.file.Path object
2. registered registerTypeAdapter(Path.class, new PathConverter())

What is the expected output? What do you see instead?
Seeing attached error

What version of the product are you using? On what operating system?
using gson 2.2.4

Please provide any additional information below.
I am running on windows and the runtimeType is coming as sun.nio.fs.WindowsPath 
object and it is not converting the path value into JSON.
```

Original issue reported on code.google.com by `raghu.ye...@gmail.com` on 12 Sep 2014 at 1:44

Attachments:
- [error1.txt](https://storage.googleapis.com/google-code-attachments/google-gson/issue-595/comment-0/error1.txt)

**Comment by nordfalk** [comment]
See https://stackoverflow.com/questions/36964995/how-to-serialize-java-nio-file-path-with-gson

Gson gson = new GsonBuilder().registerTypeHierarchyAdapter(Path.class, new MyGsonPathConverter()).create();


import com.google.gson.*;

import java.lang.reflect.Type;
import java.nio.file.Path;
import java.nio.file.Paths;

public class MyGsonPathConverter implements JsonDeserializer<Path>, JsonSerializer<Path> {

 
    @Override
    public Path deserialize(JsonElement jsonElement, Type type, JsonDeserializationContext jsonDeserializationContext) throws JsonParseException {
        return Paths.get(jsonElement.getAsString());
    }

    @Override
    public JsonElement serialize(Path path, Type type, JsonSerializationContext jsonSerializationContext) {
        return new JsonPrimitive(path.toString());
    }
}

**Comment by pabx06** [comment]
hello. 

The above fix did fix a few of the many errors i had.
but i am still stuck with this error.

i am trying to serialize a third party library's bytecode instrumentation with gson.

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.gson.internal.reflect.UnsafeReflectionAccessor to field java.io.File.path
WARNING: Please consider reporting this to the maintainers of com.google.gson.internal.reflect.UnsafeReflectionAccessor
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
java.lang.NullPointerException
	at javassist.CtBehavior.addCatch(CtBehavior.java:1077)
	at javassist.CtBehavior.addCatch(CtBehavior.java:1054)
	at io.asgards.MyTransformer.transform(MyTransformer.java:269)
```

**Comment by Marcono1234** [comment]
It looks like the original question was answered in the above https://github.com/google/gson/issues/595#issuecomment-586208896. Gson has no built-in adapter for `Path` at the moment so you need to write one yourself.
