### ISSUE TITLE
Gson serialized/deserialized issue when proguard enabled

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gson#609]
```
When proguard is enabled following json is generated (used gson.toJson(<class 
objectName>)
"{\"a\":\"google\",\"b\":\"19\",\"c\":\"Nexus 5\",\"d\":\"123459056012048\"}"

I am looking for 
"{\"architecture\":\"SGH-I747M\",\"os\":\"samsung\",\"osVersion\":\"16\",\"uniqu
eId\":\"123459056012048\"}"


```

Original issue reported on code.google.com by `vi...@guusto.com` on 13 Nov 2014 at 7:31

**Comment by Marcono1234** [comment]
The [android-proguard-example](https://github.com/google/gson/tree/master/examples/android-proguard-example) also shows how ProGuard can be configured to not rename the fields.

This usage question can probably closed given that it had already been answered.
