### ISSUE TITLE
Unexpected slashes

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gson#610]
```
What steps will reproduce the problem?
1. Run code from https://gist.github.com/disconsented/98db2ab2008d14bfeba6

What is the expected output? What do you see instead?
https://gist.github.com/disconsented/5aee387fac943183e0fb
I am expecting the "\n"'s to be new lines and the rest of the slashes to not be 
in the file

What version of the product are you using? On what operating system?
gson-2.2.4, W8.1 Pro

Please provide any additional information below.
Dummy perk class https://gist.github.com/disconsented/15ce678077c4ed270d12

```

Original issue reported on code.google.com by `Disconse...@gmail.com` on 19 Nov 2014 at 8:24

**Comment by Marcono1234** [comment]
The GitHub Gist files don't exist anymore. Not completely sure if that answers this issue, but JSON does not permit line breaks in JSON string values, therefore Gson must escape them as `\n`.

Though since this issue was created 8 years ago, I assume this is no longer relevant.
