### ISSUE TITLE
Patch for /trunk/extras/src/main/java/com/google/gson/typeadapters/RuntimeTypeAdapterFactory.java

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gson#614]
```
Inserted nullcheck for value, so null fields will not crash at line 217 
(value.getClass()) when writing to json.
```

Original issue reported on code.google.com by `oliver.k...@gmail.com` on 30 Nov 2014 at 8:49

Attachments:
- [RuntimeTypeAdapterFactory.java.patch](https://storage.googleapis.com/google-code-attachments/google-gson/issue-614/comment-0/RuntimeTypeAdapterFactory.java.patch)

**Comment by Marcono1234** [comment]
Unfortunately the original patch file is not available anymore, but I assume this was fixed by #681.
