### ISSUE TITLE
caching object keys

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gson#618]
```
Can a maintainer please check if the JSONObject keys are being cached while 
parsing strings?

I remember till two years ago the org.JSON library was duplicating all those 
keys in memory, instead of using a reference to a cached value. 

For example: 
[{"id": 1, "name": "rafa"}, {"id": 2, "name": "Silvia"}]

In that case, we should have only one copy of "id" and "name" in memory. 

If this array has 10000000 elements, the memory to allocate the field name is 
higher than the actual data.

thanks
```

Original issue reported on code.google.com by `mufumb...@gmail.com` on 31 Dec 2014 at 8:42

**Comment by mufumbo** [comment]
hello, anyone was able to have a look into this?

**Comment by inder123** [comment]
This translates into interning the strings used in Gson.
Probably a good idea but I will be worried about the performance penalty.
See http://stackoverflow.com/questions/10624232/performance-penalty-of-string-intern

**Comment by inder123** [comment]
@swankjesse @JakeWharton  What do you think of interning all the strings by default? 
How about doing that in Moshi?

**Comment by JakeWharton** [comment]
We briefly discussed a way of comparing keys directly in the buffer without creating string objects for every one.

**Comment by Marcono1234** [comment]
It looks like old versions of Gson had a `StringPool`, but that was removed again by 70f9280cb64aeec323a8675871579687ab66f9c6.
As workaround the solution described in https://github.com/square/retrofit/issues/2305#issuecomment-298440909 could probably be used.

**Comment by eamonnmcmanus** [comment]
It's unlikely that we will do anything specific to address this in Gson, which is in maintenance mode.
