### ISSUE TITLE
convert string to JSON with special character \u

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gson#629]
```
What steps will reproduce the problem?
Run this java code:
JsonParser parser = new JsonParser();
 JsonElement element = parser.parse("{\"description\":\"c:\\userDescription.txt\"}");
 JsonObject attributes = element.getAsJsonObject();
 System.out.println(attributes);

Expected output:
{"description":"c:\userDescription.txt"}

but actually, I see:
Exception in thread "main" com.google.gson.JsonSyntaxException: 
java.lang.NumberFormatException: For input string: "serD"



 I use Gson 1.5.

Please provide any additional information below.

```

Original issue reported on code.google.com by `nhutnguy...@gmail.com` on 3 Mar 2015 at 4:34

**Comment by javadev** [comment]
+1

**Comment by Marcono1234** [comment]
This is probably intended, `"\\user..."` is a Java String containing an escaped backslash, so the actual value is `\user...`. However, this is not a valid [JSON escape sequence](https://datatracker.ietf.org/doc/html/rfc8259#section-7). The proper solution is to write `"\\\\user..."` this way the JSON value contains `\\user...`, which is properly escaped.

**Comment by javadev** [comment]
`"{"description":"c:\\userDescription.txt"}` is valid json.

**Comment by eamonnmcmanus** [comment]
> `{"description":"c:\\userDescription.txt"}` is valid json.

Right, but that's not what the code above produces, as @Marcono1234 notes.
