### ISSUE TITLE
UI ISSUE IN DROPDOWN LIST

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gson#632]
```
UI ISSUE IN DROPDOWN LIST

Thanks 
Anurag Dikshit
```

Original issue reported on code.google.com by `dixit.an...@gmail.com` on 12 Mar 2015 at 8:49

Attachments:
* [UI issue.png](https://storage.googleapis.com/google-code-attachments/google-gson/issue-632/comment-0/UI issue.png)

**Comment by JakeWharton** [comment]
Not relevant anymore, nor was even a Gson bug in the first place.
