### ISSUE TITLE
Throw errors when essential field missing

### ISSUE THREAD

**Issue by zhangqianliang** [google/gson#635]
I got a class, like:

class Resource {
    private final String res;
    public Resource(String res) {
        if (res == null) {
            throw new IllegalArgumentException("resource can not be null");
        }
    }
}

Gson gson = new Gson();
Resource res = gson.fromJson(json, Resource .class);
How can Gson throw error when "res" not given?

**Comment by inder123** [comment]
You will need to write a custom type adapter for Gson to achieve this.
Son currently doesn't provide a callback after an object is created.
