### ISSUE TITLE
SerializedName should allow multiple names to be matched to a single name for input

### ISSUE THREAD

**Issue by inder123** [google/gson#639]

**Comment by ikkyu0319** [comment]
+1

**Comment by fahimk** [comment]
@inder123 @ikkyu0319 Do you mean something like this (this isn't available yet) ?

```java
@SerializedName({"name", "firstName", "userName"})
public String name;

@SerializedName("id")
public String id;
```

where the idea is to re-use a model for multiple API endpoints but the attribute returned has a different name?

**Comment by ikkyu0319** [comment]
Yes~ I need this~~

**Comment by inder123** [comment]
To maintain backward compatibility, I revised it to:

@SerializedName(value="default_name", alternate={"name", "firstName", "userName"})
public String name;

Let me know if you see a problem with this.

**Comment by JakeWharton** [comment]
This shipped in 2.4

**Comment by fahimk** [comment]
@inder123 this is great, thanks for working on it.

**Comment by inder123** [comment]
@fahimk great. Looking forward to learning how it worked for you.

**Comment by GaniduAsh** [comment]
How can i use this in kotlin  ? 
 @SerializedName(value="name", alternate={"person", "user"})
this gives me unexpected token error

**Comment by JakeWharton** [comment]
Use arrayOf

**Comment by GaniduAsh** [comment]
yes found it thanks

**Comment by iballan** [comment]
Can we let the alternative or on of the alternatives get chosen when serializing object that will be sent to server ?

**Comment by sivabe35** [comment]
For Kotlin ` @SerializedName(value="firstName", alternate= ["userName"])`

**Comment by sunil965** [comment]
> To maintain backward compatibility, I revised it to:
> 
> @SerializedName(value="default_name", alternate={"name", "firstName", "userName"})
> public String name;
> 
> Let me know if you see a problem with this.

Hi, does the "default_name" should me the one among {"name", "firstName", "userName"} ?

**Comment by sunil965** [comment]
I am trying this, but it's not working.
@SerializedName(value = "text", alternate = {"text", "image", "document", "voice", "audio", "video", "location", "contacts"})
    private String content;

**Comment by akinsete** [comment]
@sunil965 alternate should be an array not object.

**Comment by AungHtetKyawWho** [comment]
What up? May i help u.?

**Comment by rajatsharma16** [comment]
Doesn't seem to work if there is a space:
`@SerializedName(value = "american express", alternate = {"AmericanExpress", "AMERICAN EXPRESS"})`

**Comment by te-umerabidin** [comment]
> I am trying this, but it's not working. @SerializedName(value = "text", alternate = {"text", "image", "document", "voice", "audio", "video", "location", "contacts"}) private String content;
> 
> @inder123, any suggestion ?

use [] instead of {} for array declaration of arrayOf() function

**Comment by eamonnmcmanus** [comment]
To be clear, the advice to use `[]` or `arrayOf` applies to Kotlin ([reference](https://kotlinlang.org/docs/annotations.html#arrays-as-annotation-parameters)). With Java the syntax with `{}` is correct.

**Comment by iman2420** [comment]
@sivabe35 How to deserialize **alternate** names when convert class to JsonObject using **GsonBuilder**??
