### ISSUE TITLE
RuntimeTypeAdapterFactory removes the type field during deserialization

### ISSUE THREAD

**Issue by zaphod72** [google/gson#641]
/trunk/extras/src/main/java/com/google/gson/typeadapters/RuntimeTypeAdapterFactory.java
Line 202: JsonElement labelJsonElement = jsonElement.getAsJsonObject().remove(typeFieldName);

This seems counter-intuitive.
If registered types have the typeFieldName as a field then it will not be deserialized as expected.

**Comment by inder123** [comment]
This factory is designed to create a new fictitious field name. But I agree with you, in my usage, often I do want that field to be present as an enum.
Look at the this test class:
https://github.com/google/gson/blob/master/gson/src/test/java/com/google/gson/functional/RuntimeTypeAdapterFactoryFunctionalTest.java

The RuntimeTypeAdapterFactory in this test class implements the behavior you want.

**Comment by Ethan1983** [comment]
It looks like there is a version of factory that lets maintain factory (boolean maintainType).

https://github.com/google/gson/blob/master/extras/src/main/java/com/google/gson/typeadapters/RuntimeTypeAdapterFactory.java#L156
