### ISSUE TITLE
Allow custom objects for deserialization of Primitives

### ISSUE THREAD

**Issue by ajcrites** [google/gson#642]
Related StackOverflow question: http://stackoverflow.com/questions/30104339/deserialize-value-that-can-be-an-integer-or-string

There are times where the type you get back for a given property is not consistent and Gson should provision for you to handle this.  For example, you can have JSON that looks like

```
{"gauge": 1.0}
// or
{"gauge": "1.0-2.0"}
```

i.e. the property is either of two primitives: int or String.

If `gauge` were an Object there wouldn't necessarily be a problem, but the issue is that when you define your own class for `Gauge`, Gson expects the JSON to have an object each time.  For example:

```
public class Capabilities {
    private Range gauge;
}

gson.FromJson("{\"gauge\":1.0}", Capabilities.class)
```

> `Expected BEGIN_OBJECT but was STRING`

**Comment by JakeWharton** [comment]
Annotate either the field or the class with @JsonAdapter and use a
TypeAdapter to conditionally deserialize the field as the correct type by
peeking at it before parsing.

**Comment by Marcono1234** [comment]
Or alternatively just directly register a `TypeAdapter` on the `GsonBuilder`:
```
registerTypeAdapter(Range.class, ...)
```
Either way, this usage question seems to be answered (and might not be relevant anymore anyway).
