### ISSUE TITLE
toJson stops with work still to do

### ISSUE THREAD

**Issue by Parker8283** [google/gson#646]
This is quite the interesting one, but I can't seem to figure out why this is happening...

Whenever I try to serialize a List<${myCustomObject}>, it serializes just fine...to a point. At some point, it just stops, in the middle of a value:
```json
    "question": "CELEBRITY TWEET! 2:49 PM - 15 Nov 13 Richard Simmons\u0027 Twitter handle @TheWeightSaint tweeted: \"At the airport ____ everyone.\"",
    "truth": "Hugging"
  },
  {
    "keyword": "Smuggle",
    "question": "In 2010, Customs officers on the Morway-Sweden border intercepted a 
```
The file just ends there. I can't seem to figure out why.

My Gson object is created like so:
```java
    public static final Gson GSON = new GsonBuilder().registerTypeAdapter(Question.class, new JsonQuestion()).setPrettyPrinting().create();
```

Where JsonQuestion is a custom object implementing JsonDeserializer and JsonSerializer.

I invoke it like so:
```java
Constants.GSON.toJson(questionsToWrite, new FileWriter(jsonFile));
```

Where jsonFile is a File object, and questionsToWrite is the List.

Again, it works fine, but stops randomly with a good 20-30 elements to go in the list.

Using Gson 2.3.1

**Comment by inder123** [comment]
To isolate the problem, can you read your file in a String first, and then pass it through Gson?

**Comment by Parker8283** [comment]
I'm not sure I'm understanding what you're asking...

**Comment by inder123** [comment]
Sorry, I miswrote.
Since you are serializing, can you do String json = toJson(questionsToWrite) and then see if the serialization produced correct output.

**Comment by Parker8283** [comment]
Ah, I see. Yes, I will try that next opportunity I get.

**Comment by swankjesse** [comment]
You're probably forgetting to close the JsonWriter or stream.

**Comment by Parker8283** [comment]
You mean the file writer that I construct upon calling toJson?

**Comment by swankjesse** [comment]
Yeah, that or whatever `JsonWriter`/`OutputStreamWriter` you're wrapping it with.

**Comment by Parker8283** [comment]
I'm not wrapping it with anything. I put all the gson code in the issue. The serializers work for all the elements prior to that one spot. And the one spot changes sometimes.

**Comment by swankjesse** [comment]
Yeah, you're doing it wrong. You need to do this:

```
FileWriter fileWriter = new FileWriter(jsonFile);
Constants.GSON.toJson(questionsToWrite, fw);
fileWriter.close();
```
