### ISSUE TITLE
How to decode JsonObject in JsonObject?

### ISSUE THREAD

**Issue by booker0108** [google/gson#651]
Hi, all.

I am a newbie to GSON and I would like to ask how can I decode below object into my custom class object.

{
        "uid": "2",
        "title": "TITLE_HERE",
        "description": "DES_HERE",
        "type": "1",
        "message_type": "7",
        "option_1": [
          {
            "option_1": "Q1",
            "option_1_1": "Q11",
            "option_1_2": "Q12",
            "option_1_3": "Q13"
          }
        ],
        "option_2": [
          {
            "option_2": "Q2",
            "option_2_1": "Q21",
            "option_2_2": "Q22",
            "option_2_3": "Q23"
          }
        ],
        "option_3": [
          {
            "option_3": "Q3",
            "option_3_1": "Q31",
            "option_3_2": "Q32",
            "option_3_3": "Q33"
          }
        ],
        "option_other": "",
        "status": "3",
        "read": "0",
        "att_get": "0",
        "attachment": "0"
      }

How can I decode those "options"?

**Comment by inder123** [comment]
Please post questions like this to: https://groups.google.com/forum/#!forum/google-gson
