### ISSUE TITLE
Add the plain, basic visitor pattern to JsonElement and children

### ISSUE THREAD

**Issue by ogregoire** [google/gson#654]
I'm trying to develop several utilities to extend gson, mostly based on `JsonElement`, meaning that I don't parse directly to an object.

I'm referring to the following kind of extensions: an xpath-like mechanism, a css-like selector, batch modifications (avoiding the cost of reflection), etc.

Technically I can do without, as I've made a 20+ lines external implementation using only the `JsonElement` and its four public children but still, I feel like it's something that misses as a hierarchical data structure.

**Comment by inder123** [comment]
When we first wrote Gson, we did add a visitor pattern for it. It was quite unsatisfying though, so we removed it from the final release. Now, I am not sure what is a good design for it: is it a visitor, or an xpath like mechanism. If you have a proposal, please share. Thanks.

**Comment by ogregoire** [comment]
Well, the visitor pattern is, in my view, the very base for everything that uses a tree. A selection mechanism like xpath is interesting and might be more user friendly (that's why I'm implementing it) but to do so I need to be able to traverse the element tree.

How I would do it?

The base is rather clear: an interface `JsonVisitor`:

```Java
public interface JsonTraverser {
  default public void visit(JsonObject jsonObject) { }
  default public void visit(JsonArray jsonArray) { }
  default public void visit(JsonPrimitive jsonPrimitive) { }
  default public void visit(JsonNull jsonNull) { }
}
```

Then in `JsonElement`, there'd exist the "accept" method: `visiting(JsonTraverser traverser)`.

```Java
public abstract class JsonElement {
  ...
  void visiting(JsonTraverser traverser) { throw new RuntimeException("Not implemented"); }
  ...
}
```

Then each implementation extends the `visiting` method:

`JsonObject`
```Java
  @Override void visiting(JsonTraverser traverser) {
    traverser.visit(this);
    this.entrySet().forEach(e -> e.getValue().visiting(traverser));
  }
```

`JsonArray`
```Java
  @Override void visiting(JsonTraverser traverser) {
    traverser.visit(this);
    this.forEach(e -> e.visiting(traverser));
  }
```

`JsonPrimitive`
```Java
  @Override void visiting(JsonTraverser traverser) { traverser.visit(this); }
```

`JsonNull`
```Java
  @Override void visiting(JsonVisitor traverser) { traverser.visit(this); }
```

Now the question of the entry point. That's a bit fuzzy. As you've seen the methods are package-private, that's to avoid showing too much. So I'd add the following:

```Java
public final class JsonTraversers {
  private JsonTraversers () { }
  public static void traverse(JsonElement element, JsonTraverser traverser) {
    element.visiting(traverser);
  }
}
```

With this approach and in terms of API, none of the 5 classes are impacted: only an interface and the entry point are added.

The only actual impact is if somehow there exist other `JsonElement` implementations (since the default constructor is public for some reason). In that case, making all the methods public as well isn't an issue (though, I'd reduce the visibility of the `JsonElement` constructor if it were up to me).


With such an implementation, it's become very easy to implement the functionalities I'm developing like the xpath selector, the batch modifications, etc.

**Comment by inder123** [comment]
Thanks for the detailed explanation. We had something similar to this. It was an unsatisfying approach. Adds too much API code for a minor use-case. We decided to let the third-parties write such a visitor themselves.

**Comment by ogregoire** [comment]
Thanks for considering, even though I'm not really sure I understand the reasons of refusal given the facts that none of the existing API is touched and that,  you said it yourself, each person has to write it him/herself. The pattern itself is quite discreet and isn't really a minor use-case given that `JsonElement` is exposed.

Anyways, as I mentioned, I've already an implementation that uses the existing API so it's no big deal for me.

**Comment by inder123** [comment]
It adds some conceptual weight to the API. The names of class and methods are a little unsatisfying.
Also, when you talk about traversal, why support only Depth-first traversal? Why not breadth-first as well?
Actually, in your implementation, JsonTraverser needs only one method instead of four.
visit(JsonElement element);
Why did you consider one for each sub-class of JsonElement.

**Comment by ogregoire** [comment]
*Unsatisfying class names*: I'm not a native English speaker. If you have better names, I'm entirely open.

*Depth-first vs. Breadth-first*: This was written quickly without any other consideration in order to answer your question.

*One method per subclass*: That's the goal of the visitor pattern. A few known implementations in a hierarchical standard are perfect for it. You implement only the methods for what you want to visit. All the Primitives ? Ok, implmeent only one method. All the containers? Right, implement only the JsonArray and JsonObject methods. Future implementations come in? Well, there's only one default method to add instead of all implementation to adapt to make sure we're still compatible with everything without breaking the existing visitors.

But it seems you've made your mind a long time ago. So unless you're really thinking about doing it, I suggest to close this issue.

**Comment by inder123** [comment]
You are partly right: I made up my mind a long time ago, and was hoping that someone will come up with a much better rendition of the visitor pattern that I did. So far, it is elusive, though yours is somewhat better than mine.
