### ISSUE TITLE
Create a generalized serializer/deserializer that can interpret AutoValue types and do the right thing.

### ISSUE THREAD

**Issue by cgruber** [google/gson#665]
Autovalue is massively convenient, and GSON is very convenient.  Having some ways to ease integration between the two might prove quite powerful.

Serialization is largely taken care of, since an AutoValue instance has its generated private fields which can be read and written out.  AutoValue ensures fields are in property-declaration-order in the generated subclass, so as long as Java keeps field order in reflection consistent, it's fine. 

The more pertinent issue is creation/deserialization

I see two approaches: 

What I have in mind right now is an automatic deserializer which would reflectively figure out the constructor based on field order (which is declaration order for AutoValue, and aligns with the constructor.  A variant could detect whether there was a builder and use that.

An alternative would be an autovalue plugin which generated a gson serializer/deserializer as it was generating the autovalue implementation. That might be better in several respects, but requires that autovalue support pluggable extensions.  Not sure if it is there yet. (@eamonnmcmanus ?)

**Comment by eamonnmcmanus** [comment]
@rharter is currently working on AutoValue extensibility in https://github.com/google/auto/pull/237.

**Comment by swankjesse** [comment]
It's almost trivial to build a Gson TypeAdapterFactory that supports all AutoValue types. In fact, here it is:

```
    class AutoValueTypeAdapterFactory implements TypeAdapterFactory {
      @Override public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
        TypeToken<?> autoValueClass = autoValueClass(type);
        if (autoValueClass != null) {
          return (TypeAdapter<T>) gson.getDelegateAdapter(this, autoValueClass);
        }
        return null; // Not an AutoValue type.
      }

      /** Returns the generated implementation type for {@code type} if it has one. */
      private TypeToken<?> autoValueClass(TypeToken<?> type) {
        // TODO: does AutoValue have an API for this or do I need to do it manually?
      }
    }
```

**Comment by cgruber** [comment]
Im sorry... How exactly does this adapter as written create the autovalue?

**Comment by JakeWharton** [comment]
Gson creates it reflectively. Here's a full-working copy from a year ago: https://gist.github.com/JakeWharton/0d67d01badcee0ae7bc9

**Comment by JakeWharton** [comment]
If you don't want reflection, write your own annotation processor to code gen type adapters and/or a type adapter factory.

**Comment by cgruber** [comment]
Sorry... I didn't actually realize that we were generating a no-args constructor in auto-value generated classes.  Otherwise, the above would have made total sense when I looked at it.   I'm slightly surprised that we do, actually.

**Comment by cgruber** [comment]
Do you even need `@AutoGson` @JakeWharton?  Can't you just use `@JsonAdapter(YourAutoValueTypeAdapterFactory.class)` ?

**Comment by cgruber** [comment]
And reflection is fine for my purposes.

**Comment by JakeWharton** [comment]
Yeah that works too. I've never used the linked gist, just wrote it to stop people complaining that AutoValue / AutoParcel needed explicit Gson support.

**Comment by swankjesse** [comment]
@cgruber there's no no-args constructor. Gson is magic.

**Comment by swankjesse** [comment]
(Here's the [latest incarnation](https://github.com/square/moshi/blob/master/moshi/src/main/java/com/squareup/moshi/ClassFactory.java) of such magic, if you're curious)

**Comment by eamonnmcmanus** [comment]
So it'll basically make an instance using Unsafe.allocateInstance and then bang the values into the final fields using Field.setAccessible? I don't think that guarantees safe publication of the field values to other threads, does it? Also, since it doesn't execute the constructor logic, it doesn't verify that every field was actually present, which means that non-`@Nullable` fields could be null, violating their contract. And of course it won't work in environments where either Unsafe or Field.setAccessible are unavailable (App Engine, for one). So, it's way better than nothing, but not quite as good as what we might have with explicit support.

I think one fairly simple way to make this work cleanly would be an adapter that constructs the builder for the AutoValue type and sets each of its properties. That can be done without any Unsafe nastiness and will correctly invoke validation logic, including user-written validation. It's a bit more work for the user because they have to write the abstract builder, but on the whole I think it would be better.

**Comment by swankjesse** [comment]
The threading is safe because the allocated instance is thread-confined. If you can show me a counterexample, I'll be impressed!

**Comment by eamonnmcmanus** [comment]
If I instantiate an AutoValue object and put a reference to it in a volatile field or an AtomicReference, then another thread can see it. That seems like a reasonable thing for a worker thread to do to communicate its results, for example. Then I am asking if there is any guarantee that the AutoValue's field values will be seen by the other thread.

To be clear, though, this is not what bothers me the most. The fact that the constructor isn't executed and therefore there can be missing properties is more concerning. Could an adapter verify that every non-`@Nullable` property is present?
