### ISSUE TITLE
Provide an annotation which can be used to register Serializer/Deserializers, instead of just adapters.

### ISSUE THREAD

**Issue by cgruber** [google/gson#666]
Allow @JsonAdapter to supply Serializer and Deserializers as well as TypeAdapters, or provide an alternative annotation, e.g. 

```java
@JsonSerializable(adapters = Foo.Deserializer.class, forHierarchy = true)
class Foo {
    ...

    static class Deserializer implements JsonDeserializer<Foo> {
      @Override Foo deserialize(...) { ... }
    }
}
```

This permits one to package a type, it's serializer, and all the configuration bits together and elides the need for `Gson.builder().registerTypeHierarchyAdapter(...)`, etc.

Recommended that the `.registerTypehierarchyAdapter(...)` supercede any annotated configuration.

**Comment by cgruber** [comment]
Oooh! I got the issue of the beast!

**Comment by swankjesse** [comment]
This exists.
```
 @JsonAdapter(UserJsonAdapter.class)
```

**Comment by swankjesse** [comment]
The beast!

**Comment by cgruber** [comment]
How does this exist?  What I described doesn't exist - what the issue states is insufficient exists. 

`@JsonAdapter` lets you register a type adapter, not a serializer and/or deserializer.  Looking at TypeAdapter, I don't think I want one.  I don't get context in a TypeAdapter, which I need to deserialize bits of complex types.  I don't see how a JsonReader (what I do get) is sufficient to do nested complex types, without manually digging deep into the json message.

**Comment by swankjesse** [comment]
It gives you a `TypeAdapterFactory`, which offers phenomenal cosmic power. It lets you compose a type adapter by delegation. And if you don't love that API because it's pretty reflective, I've been working on Moshi's adapter methods which are even better.
https://github.com/square/moshi#custom-type-adapters

**Comment by JakeWharton** [comment]
You can also do custom types easily by asking the Gson instance for a type adapter of whatever type you want and handing it the given reader.

**Comment by cgruber** [comment]
I think I hadn't yet understood the full power of TypeAdapterFactory, as I"m pretty new to Json.  Just TypeAdapter.  I see now a bit better how to do this (and both you and Jake did a good chunk of what I was intending to do in the other thread). 

I'll look at Moshi, but for my purposes, reflective creation and assignment is fine.
