### ISSUE TITLE
Maven release?

### ISSUE THREAD

**Issue by adamtanner** [google/gson#668]
Just wondering if you have any upcoming plans to do a Maven release. I'm happy to help if I can.

Thanks!

**Comment by inder123** [comment]
Any specific feature/bug that you are looking forward to?

**Comment by adamtanner** [comment]
Yeah, we're looking to use the `jsonValue` feature I just added in #667 for a Java client we're writing for [Martian Proxy](https://www.github.com/google/martian). I was going to wait, but it seemed like releases are few and far between so I figured I'd ask. :smile:

Thanks!

**Comment by adamtanner** [comment]
Bump. Just wondering what your thoughts are on this. We want to release and I need to know if I should rework the library to work without this feature or wait a bit longer.

**Comment by inder123** [comment]
I do want to cut a release. @swankjesse @JakeWharton @joel-leitch 
Shall we do a review of the proposed changes so far?

**Comment by JakeWharton** [comment]
Looks like history was rewritten but the tags weren't updated?

https://github.com/google/gson/compare/gson-2.3.1...master

**Comment by inder123** [comment]
Ok. Do you know what to do to update the tags? If so, go ahead. Thanks.

**Comment by johnbarr** [comment]
I too would like a new release to use this same change.

**Comment by JakeWharton** [comment]
Haven't gotten around to updating the tags. Here's the commit list though: https://github.com/google/gson/compare/eba6825a...master

**Comment by JakeWharton** [comment]
Let's get this done before October 1st?

**Comment by swankjesse** [comment]
Yes! @inder123 ready to sign off?
https://github.com/google/gson/blob/master/CHANGELOG.md

**Comment by inder123** [comment]
I am comfortable with a new release. However, do we want to do a quick
review of pending pull requests and filed issues?

On Sat, Sep 26, 2015 at 4:48 PM, Jesse Wilson <notifications@github.com>
wrote:

> Yes! @inder123 <https://github.com/inder123> ready to sign off?
> https://github.com/google/gson/blob/master/CHANGELOG.md
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/gson/issues/668#issuecomment-143505867>.
>



-- 
http://www.singhinderjeet.com/

**Comment by JakeWharton** [comment]
I did a few. Will try to get to more soon.

**Comment by advayDev1** [comment]
Just a +1 for another release.  We want a stable release for https://github.com/j2objc-contrib/j2objc-common-libs-e2e-test/issues/35#issuecomment-143769534, and some of the unit tests at tag 2.3.1 fail (which you have fixed in the mean time).

cc @brunobowden

**Comment by JakeWharton** [comment]
It will be this week, in all likelihood.

**Comment by inder123** [comment]
@JakeWharton @swankjesse  Shall I go ahead and cut a new release?

**Comment by JakeWharton** [comment]
Sounds good to me!

**Comment by swankjesse** [comment]
Yes please!

**Comment by inder123** [comment]
Just cut and pushed a new release to Maven Central. Also, published Javadocs on GitHub pages.

**Comment by advayDev1** [comment]
will this populate to jcenter as well?
https://bintray.com/inder123/maven/com.google.code.gson%3Agson/view

it is the default for android builds.

**Comment by JakeWharton** [comment]
It's published to Maven Central which JCenter (which is not what you
linked) proxies.
