### ISSUE TITLE
publish proto to Maven central?

### ISSUE THREAD

**Issue by borud** [google/gson#690]
While waiting for protobuf version 3 to get support for JSON I've started using Gson to transform protobuffers into JSON and I found `ProtoTypeAdapter` written by Inderjeet Singh under the `proto` directory.  However this does not appear to be part of Gson proper (wouldn't hurt that much if it was) and it does not appear to be pushed to Maven central.

In my project I've just included the code in the source, but I'm not really comfortable with that.  I'd like to get it from somewhere that is being properly maintained.

Would you consider moving this code into the `gson` proper or pushing this artifact to Maven central?

**Comment by inder123** [comment]
Hi. Proto is not a very popular technology and will not make into Gson proper. We may publish an additional maven sub-project. However, I haven't maintained this version after writing it.
I think you did the right thing by including the source code.

**Comment by borud** [comment]
OK, thanks for the quick response @inder123!

**Comment by tobegit3hub** [comment]
com.google.code.gson.proto is needed in our project. Now we need to copy the source code to use and it would be much better if we can rely to the maven repo with compatible version. @borud @inder123
