### ISSUE TITLE
Documentation for strict/non-lenient mode

### ISSUE THREAD

**Issue by laktak** [google/gson#695]
I was a bit surprised that Gson parses invalid JSON by default. The [user guide](https://sites.google.com/site/gson/gson-user-guide) does not mention this pitfall.

I found `getAdapter` in #457 by accident. Is `new Gson().getAdapter(Map.class).fromJson(json)` the correct way to parse in strict mode? Could you update the documentation?

**Comment by inder123** [comment]
Gson philosophy is to accept JSON leniently, but emit strictly. This is not a bug. If you want specific documentation edits, consider sending a pull request with changes.
