### ISSUE TITLE
Pro-guard issue

### ISSUE THREAD

**Issue by TonyTangAndroid** [google/gson#713]
I don't believe that the following code snippets should be added in the proguard.cfg.

-keep public class * {
    public protected *;
}

It will cause all methods will included.

**Comment by JakeWharton** [comment]
Who told you to add it?

**Comment by TonyTangAndroid** [comment]
Sorry, I had thought that I added the link. The code is  from the following link:

https://github.com/google/gson/blob/master/examples/android-proguard-example/proguard.cfg

As it is from official example, it could be misleading for beginners. And I did not pay attention to it when I was copying the pro guard snippet.

**Comment by JakeWharton** [comment]
Ah, ok. I looked in a few places but couldn't find it! Yeah we should get that changed.

**Comment by TonyTangAndroid** [comment]
Good to know that. Thank you very much for getting back to this issue so quickly.
