### ISSUE TITLE
can use gson to convert json into nested map ?

### ISSUE THREAD

**Issue by lytasky** [google/gson#727]
like that:
 {"result": {
      "update": {
           "title": "双11抢10亿现金券啦",
            "msg": "峰峰说，升级新版之后双十一抢购杠杠的！新版还有不一样的峰峰彩蛋哦",
},
     "ts": 1446446129,
}
Map<String,Object> resultMap = new  HashMap<>();
Map<String,Object> map1 = new  HashMap<>();
map1.put("title","双11抢10亿现金券啦");
map1.put("msg","峰峰说，升级新版之后双十一抢购杠杠的！新版还有不一样的峰峰彩蛋哦");
resultMap.put("update",map1);
resultMap.put("ts","1446446129");

can gson do it above directly？

**Comment by cgruber** [comment]
If your type is Map<String, Map<String, String>> I can't imagine why not.
You'd need to use a Type rather than a Class, obtained from TypeToken,
since you're tryign to deserialize a parameterized type.

```
Type typeOfT = new TypeToken<Map<String, Map<String,
String>>>(){}.getType();
Map<String, Map<String, String>> map = gson.fromJson(jsonString, typeOfT);
```

**Comment by lytasky** [comment]
my type is  Map<String,Map<String,Map<String,Map<String,String>>>> , map in map, the level is  indefinitely ，only the deepest map is Map<String,String > ， can gson do this ？
