### ISSUE TITLE
Ability to ignore a property if value is already set (Deserialization).

### ISSUE THREAD

**Issue by gintechsystems** [google/gson#741]
I have been using GSON for awhile and it is a great library, however I ran into one major issue for me. If I have an object in my application and I set its values from a JSON string, it is working as intended but if I pull in another JSON string with updated values but one of the values is missing from the string, it overwrites it and sets the value to null to a property that already had a value set beforehand. I found this from the GSON documentation but don't think there is an easy workaround.

From the documentation of GSON:
While deserialization, a missing entry in JSON results in setting the corresponding field in the object to null.

**Comment by inder123** [comment]
It's a feature. A missing field indicates it is set to null.
Your option is to define an InstanceCreator for your type and set it to whichever default value you want.

**Comment by gintechsystems** [comment]
Can you give an example please?

**Comment by inder123** [comment]
https://github.com/google/gson/blob/master/gson/src/test/java/com/google/gson/functional/InstanceCreatorTest.java
