### ISSUE TITLE
Serialize a list of POJOs doesn't keep the order of items

### ISSUE THREAD

**Issue by CyborTronik** [google/gson#750]
Hi,
I'm implementing a REST API and I have sorting functionality,
So I give an ordered list to Gson, but it gets serialized with random order of items.
Is there any work around for that?

**Comment by inder123** [comment]
AFAIK, Gson maintains strict ordering of a list. 
Can you send us a pull request with a JUnit test that illustrates this issue?

**Comment by ysqchris** [comment]
Hello, I would like to ask a question, Gson will be inside the key values in dictionary order sort?
Is there a way to avoid this sort?

**Comment by Sumanth-istar** [comment]
any luck to resolve this issue?

**Comment by danorton2** [comment]
There is no actual example of this failure, but countless examples where it works. (Perhaps the OP expects JsonObject field order to be preserved, which is not -- and should not be -- supported.)

**Comment by Marcono1234** [comment]
Closing this because no example code was provided showing this issue. Feel free to create a new issue if you still experience this with the latest Gson version, but in that case please provide a short self-contained example demonstrating the issue.
