### ISSUE TITLE
if I use the gson, how can I write the proguard-rules.pro? or nothing to do? 

### ISSUE THREAD

**Issue by caixuejian** [google/gson#753]
if I add the following proguard content , It will work well?

-keepattributes Signature
-keepattributes *Annotation*

-keep class sun.misc.Unsafe { *; }
-keep class com.google.gson.stream.** { *; }

**Comment by JakeWharton** [comment]
They're here: https://github.com/google/gson/blob/master/examples/android-proguard-example/proguard.cfg
