### ISSUE TITLE
toJson on android some times send false argument as ?e\u0000\u0000

### ISSUE THREAD

**Issue by b2mdevelopment** [google/gson#759]
I am using gson-2.2 on android aplication to convert object to json in order to send it to server

example:
class Event {
private boolean flag;
public Event(boolean flag) {
this.flag = flag
}
public boolean getFlag() {
        return this.flag;
    }
}

Event event = new Event(false);
String json = new Gson().toJson(event);

Randomly the json received as {\"flag\":?e\u0000\u0000}

any ideas!

**Comment by Marcono1234** [comment]
Might be memory corruption, similar to #2093. Though given that this was reported 7 years ago, this is probably no longer relevant.
