### ISSUE TITLE
Anonymous Map initialization does not serialize correctly.

### ISSUE THREAD

**Issue by f2prateek** [google/gson#762]
Here's a sample to demonstrate the issue:
```java    
HashMap<String, String> context = new HashMap<String, String>() {{
  put("city", "Toronto");
}};
Gson gson = new Gson();
System.out.println("context - " + context);
System.out.println("JSON - " + gson.toJson(context));
```

Output:
```
context - {City=Toronto}
JSON - null
```

Initializing the map with the code below works fine:
```java
HashMap<String, String> context = new HashMap<String, String>();
context.put("city", "Toronto");
```

While the first method is obviously a wasteful way to initialize a map, is this serialization behaviour for anonymous initialization expected? If so, can you clarify why?

The closest reference I could find to this was https://github.com/google/gson/issues/298, which is about fields in anonymous classes.

**Comment by swankjesse** [comment]
This is working as designed. Anonymous classes cannot be deserialized & for symmetry we forbid serialization also. You should get the expected result if you hung the actual Map.class type.

**Comment by f2prateek** [comment]
Ah so serialization is forbidden for anonymous classes in general, not just fields declared in anonymous classes!
