### ISSUE TITLE
Provide a way to deserialize null values

### ISSUE THREAD

**Issue by spacitron** [google/gson#766]
I have the following json object: 

```javascript
"elements":[{
    {
        "read_only": false, 
        "required": true, 
        "id": "12", 
        "type": "TimeDay", 
        "options": [
          {
            "name": "Peter", 
            "value": 11
          }, 
          {
            "name": "George", 
            "value": 13
          }, 
          {
            "name": "Laura", 
            "value": 14
          }
        ]
      }]
    }
```
Which is correctly maps to the following class:

```java
 public class Response{

     List<Element> elements
     public class Element {

        boolean read_only;
        boolean required;
        String id;
        String type;
        List<Option> options;

        class Option {
            String name;
            int value;
        }
    }
}
```

The problem however starts when I meet the following: 

```javascript
"elements":[{
{
    "read_only": false, 
    "required": true, 
    "id": "12", 
    "type": "TimeDay", 
    "options": null
  }]
}
```

Here Gson complaints that there is a String where it expects to find an Array, indicating that it is parsing the null value as a String with the value of "null" rather than setting my list to null. I searched everywhere for a way around this and all I found was to write my custom deserializer. So I did this:

```java
         class NullCollectionDeserializer implements JsonDeserializer<List> {
            @Override
            public List deserialize(JsonElement json, Type typeOfT, JsonDeserializationContext context) throws JsonParseException {

                if (json.isJsonNull()) {
                    return null;
                }
                return new Gson().fromJson(json, typeOfT);
            }
        }
```

Not only I find it odd that I have to write a custom solution to provide what should be standard functionality but - due to the fact that the "options" list is nested within another list - the above code does not even work. This is because the deserialize method will be called when Gson meets the "elements" list, asking the new Gson instance at the end of the method to parse its contents, which in turn may contain the null list. Because this instance does not know how to handle null lists, the result is that Gson again complaints about finding a String where it expected to find an Array.

**Comment by inder123** [comment]
I am surprised at the behavior, we have plenty of tests that ensure that null behavior is correct in Gson.
https://github.com/google/gson/tree/master/gson/src/test/java/com/google/gson/functional

Can you send a pull request with a test that replicates this behavior?

**Comment by spacitron** [comment]
Wrote a test and it passed. After further investigation I finally realised that the problem was with my api as in some cases the options array would be mistakenly wrapped in double quotes, thereby turning it into a string. Thank you for your help. I'll close this issue.
