### ISSUE TITLE
Convert integer 1 & 0 to the boolean true & false when parsing

### ISSUE THREAD

**Issue by maheshwarLigade** [google/gson#774]
I have JSON response which contains the object of user, which also  has the status as 1 & 0 which says that the value is true or false. please let me know how to parse the integer value to boolean.

I have the Custom object Users. From API I am getting the {"status":1}, I need to convert it into the boolean i.e true, But I am not interested to serialise  all the other fields, they are as it is, I just need the solution for only boolean.

**Comment by swankjesse** [comment]
You can write a type adapter. See the part about `@ToJson` on the readme for an example.
