### ISSUE TITLE
HI

### ISSUE THREAD

**Issue by ikkyu0319** [google/gson#777]
> {
  "id": 234,
  "users": [
    {
      "age": 11,
      "name": "ddd"
    },
    {
      "age": 22,
      "name": "ccc"
    }
  ]
 > } 
  
I want Bean is 

> String id；
   String users；

but 

> java.lang.IllegalArgumentException: field com.qyer.android.plan.bean.Bean xxxx  has type java.lang.String, got java.util.ArrayList 

how do about it？ please help！！

**Comment by ikkyu0319** [comment]
@willnorris @adamtanner @vogella

**Comment by JakeWharton** [comment]
The `users` key is an array in the JSON, not a string. You need to use the type `List<User>` for the `users` field and create a `User` object which has both `age` and `name` fields.

For more help in the future, please ask a questions on StackOverflow with the 'gson' tag. There's a lot of helpful people over there and it usually results in a much faster answer.

**Comment by ikkyu0319** [comment]
Yes ，I know List<User> is OK，but I want Use string  and save the string，Can I do that?

**Comment by JakeWharton** [comment]
As in, you want the JSON array to be stored as a raw String?

**Comment by ikkyu0319** [comment]
yes~~ so i use "string users"

**Comment by JakeWharton** [comment]
Gson does not support that. You can use `JsonArray` as the type which will represent the array in a simple object model form.
