### ISSUE TITLE
Setting lenient in Retrofit-2

### ISSUE THREAD

**Issue by maxblumental** [google/gson#778]
How about make this setting through providing an optional argument to the factory. I can't see a short way to that now. Here's a more detailed description of my problem and attempt to solve it: http://stackoverflow.com/questions/35072287/gsonconverterfactory-for-retrofit2-lenient-setting

**Comment by JakeWharton** [comment]
Leniency has been added to `GsonBuilder` for the next release (https://github.com/google/gson/pull/771) and will be supported in Retrofit after release (https://github.com/square/retrofit/issues/1465).
