### ISSUE TITLE
not able to manage cookies in android using retrofit2 and okhttp3

### ISSUE THREAD

**Issue by abhishekgargg** [google/gson#780]
I am sending a POST login request which gets me a jSessionId, and I want to add this jSessionId in my consecutive requests to fetch logged in data.

I think this kind of task is handled by cookies in android, and I have found a couple of solutions for the same, but most of the solutions are either not compatible with okhttp3 OR don't work.

Can anyone please help me out with any suggestions or a small working sample that works with okhttp3 and retrofit2?

**Comment by JakeWharton** [comment]
Gson is a JSON serializer and has nothing to do with cookies or either of these libraries. This type of question is best suited for StackOverflow using tags of the libraries you mention.
