### ISSUE TITLE
Gson converts \/ to \\/

### ISSUE THREAD

**Issue by ZkHaider** [google/gson#781]
How can I fix this? I am trying to pass a request with `Retrofit`, something like this:

    http:\/\/something.com\/something\/else.json

But `Gson` converts this into:

    http:\\/\\/something.com\\/something\\/else.json

**Comment by JakeWharton** [comment]
The JSON RFC dictates this in section 7: https://tools.ietf.org/html/rfc7159#section-7, emphasis added.

> All Unicode characters may be placed within the quotation marks, **except for the characters that must be escaped**: quotation mark, **reverse solidus**, and the control characters (U+0000 through U+001F).

The reverse solidus is the `\` character and must be escaped inside strings.
