### ISSUE TITLE
Simple Gson Java sample yields null

### ISSUE THREAD

**Issue by bruce-osnexus** [google/gson#785]
The simplest sample code, as shown on several sites, doesn't seem to work as shown. Disclaimer - I am very new to Java. Scratching my head, it looks like I'm doing it exactly as shown in the simplest of simple examples.
Here is what I am trying:

       class BagOfPrimitives {
              private int value1 = 1;
              private String value2 = "abc";
    		  private transient int value3 = 3;
              BagOfPrimitives() {
                  // no-args constructor
              }
        }
        BagOfPrimitives obj = new BagOfPrimitives();
        Gson gson1 = new Gson();
        String jsonStr = gson1.toJson(obj);   
        System.out.println( "jsonStr = " + jsonStr );

And it prints: 
    jsonStr = 

Similarly, trying to go the other way:

     class testClass {
    		public String vendorId = "foo";
    		public String productId = "bar";
    		testClass() {}
    	}
        testClass myInst2 = new testClass();    // Could or should be "null"?
    	String inpStr = "{\"vendorId\": \"Acme\",\"productId\": \"WhizBang\"}";
    	myInst2 = gson.fromJson( inpStr, testClass.class );
        System.out.println( "    vendorId = " + myInst2.vendorId );
        System.out.println( "    productId = " + myInst2.productId );
And it prints:
    vendorId = null
    productId = null

**Comment by inder123** [comment]
All of these examples should work as long as BagOfPrimitives and testClass are not inner classes.
Static inner classes are just fine.

Look at these tests for examples of what works:
https://github.com/google/gson/tree/master/gson/src/test/java/com/google/gson/functional

**Comment by bruce-osnexus** [comment]
Thanks for the quick reply.> BagOfPrimitives and testClass are not inner classesThat was it. I had those classes defined inside my test method. Putting those outside as "public" (still inside the main test class) made it work.Thanks!!-bBruce LoweOS NEXUS Engineeringbruce.lowe@osnexus.comhttp://www.osnexus.com


-------- Original Message --------
Subject: Re: [gson] Simple Gson Java sample yields null (#785)
