### ISSUE TITLE
How can I custom deserialize some fields only?

### ISSUE THREAD

**Issue by burakkilic** [google/gson#803]
My shop json is:

     "shop":{
    "name" : {
        "en" : "My Shop",
        "es" : "Mi Tienda" 
    }, 
    "order" : 0
    }

And shop model is:

    class Shop{
        public String name;
       public int order
    }

So how can I deserialize that kind of Json to this model? Can I write a custom serializer for only "name" field?

**Comment by JakeWharton** [comment]
You can use the [`@JsonAdapter`][1] annotation on the first for which you want to deserialize using custom logic. In your example, you would write a `TypeAdapter` or `TypeAdapterFactory` which handled selecting the correct language from the object and return the string value.

 [1]: https://google-gson.googlecode.com/svn/trunk/gson/docs/javadocs/com/google/gson/annotations/JsonAdapter.html

**Comment by burakkilic** [comment]
Thank you,

I wrote this:

`public class MultilingualStringAdapter extends TypeAdapter<String> {


    @Override
    public void write(JsonWriter out, String value) throws IOException {
        Log.d("multilingual test", value);
    }

    @Override
    public String read(JsonReader in) throws IOException {
        String result = "";
        in.beginObject();
        while(in.hasNext()){
            if(in.nextName().equals("en")){
                result = in.nextString();
                break;
            }
        }
        return result;
    }
}`

But it gives error 

    java.lang.IllegalStateException: Expected a string but was NAME at line 1 column 12759 path $.name.

how can i solve that?
