### ISSUE TITLE
List of Tuples is parsed as LinkedTreeMap

### ISSUE THREAD

**Issue by bes1002t** [google/gson#805]
I have a Nested construct named Tuple<String, Object>(String left, Object right). So it has a left side and a right side. In my Application this structure looks like:
Tuple(left=1, right=List(Tuple(left=2, right=Tuple(left=3, right="test")), Tuple(left=4, right="test2"))))

It's just an example but you get the idea. It's a random nested structure of Tuples and the right var at the bottom of the structure is everytime a String. 

Now the Problem: Encoding and Decoding with Gson works. The first layer of the structure is accessable as Tuple. I can also access the List of Tuples by casting it to a List of Objects.  BUT if I try to cast one of the List entries to Tuple I get an java.lang.ClassCastException: com.google.gson.internal.LinkedTreeMap cannot be cast to com.my.package.name.Tuple.

I can not explain this behavior except that Gson internally creates a map structur with that list of tuples (because a map is nothing else than a list of tuples). But why do I get an error by casting the list entries and not by casting the list? And is there a way to avoid this behavior? My Tuple already implements Serializable but this fact has no effect.

**Comment by inder123** [comment]
Write an appropriate InstanceCreator?

**Comment by bes1002t** [comment]
Thanks for your quick reply, but an instance creator changed nothing. The reason for this is, that before I encode my structure, the Tuple is (String, Object) so while decoding it, gson will just see the object at this place, even if it's actually a Tuple. I need to do this, because the right side of my Tuple could be another Tuple, a List of Tuples or a String.

**Comment by JakeWharton** [comment]
If the types on the right are finite you can annotate the field with
@JsonAdapter(TupleRightTypeAdapter.class) and write a type adapter which
deserializes one of the three types you expect based on whether the JSON
indicates a scalar string, list, or Tuple object.

**Comment by bes1002t** [comment]
Thanks for your suggestions, I tried both but finally I used the JsonDeserializer<Tuple> and it worked really good.
