### ISSUE TITLE
Request For Comments: How about annotation processing?

### ISSUE THREAD

**Issue by gfx** [google/gson#807]
I'm writing a Gson extension, which uses annotation processing to generate type adapter factories: 

* https://github.com/gfx/StaticGson

This is faster than the reflection based adapters which gson has. In fact, even faster than Moshi.

And here is a question: should I develop this extension as a standalone library? Or should I make a pull-request to Gson as a `processor` module?

P.S. here is a benchmark result. "dynamic gson" is the original reflection based with Gson 2.6.2, "static gson" is StaticGson, and moshi is Moshi v1.1.0:

```
D/XXX : start benchmarking dynamic gson
D/XXX : dynamic gson in serialization: 318ms
D/XXX : dynamic gson in deserialization: 298ms

D/XXX : start benchmarking static gson
D/XXX : static gson in serialization: 141ms
D/XXX : static gson in deserialization: 177ms

D/XXX : start benchmarking moshi
D/XXX : moshi in serialization: 204ms
D/XXX : moshi in deserialization: 449ms
```

**Comment by swankjesse** [comment]
Sounds similar to [Logan Square](https://github.com/bluelinelabs/LoganSquare). My preference is as a standalone project.

**Comment by gfx** [comment]
I will developing this project as a standalone. Thanks.

BTW, Logan Square is great. It seems fastest in serialization.

Interestingly, however, static gson is faster than Logan Square in deserialization. 

Added LoganSquare benchmark to the StaticGson with the same JSON data:

```
D/XXX: start benchmarking LoganSquare
D/XXX: LoganSquare in serialization: 82ms
D/XXX: LoganSquare in deserialization: 243ms
```

**Comment by inder123** [comment]
@gfx Yes, makes sense to develop as a standalone project, and as it matures, we can consider borrowing some features in Gson core.

Great idea, BTW. I wasn't familiar with Logan Square either. Looking forward to more documentation/tutorial on your project page and trying it out.

**Comment by lachlanm** [comment]
@gfx Wow, this is pretty crazy timing. I was looking for a project that did this over a week ago.

Since you hadn't posted this at the time, I have also started working on a very similar project:
- https://github.com/lachlanm/gsonpath

My project generates type adapters as well. I have also added a very basic json path generator as part of the project.

Did you have any plans to implement something similar? Or is the main focus to keep it fairly simplistic?

**Comment by gfx** [comment]
@lachlanm OMM. If I knew your project, I wouldn't make Static Gson. lol.

JSON path style seems interesting although I didn't have a plan yet. My first aim is to use Static Gson in my projects with least effort. JSON path will be the second milestone.

**Comment by gfx** [comment]
StaticGson starts is released as an independent artifact: https://bintray.com/gfx/maven/static-gson/

Thanks.
