### ISSUE TITLE
Garbage collection pressure for escaped html

### ISSUE THREAD

**Issue by qwwdfsad** [google/gson#815]
Currently JsonWriter#string uses String#format to escape html characters one by one. 
It is extremely costly due to format method internals (because it's general purpose mechanism for formatting): it creates at least Formatter object, Matcher object (for large regexp, see formatSpecifier + usages of this matcher), multiple new StringBuilder+toString() inside of FormatSpecifier (methods justify and print), not well-sized ArrayLists (with expanding and array cloning) and finally new StringBuilder+toString as a result. For one symbol encoding it's way too much, in my case this is one of the biggest garbage sources at all. Guess format method is not very fast either (it is one of the hottest method in my application profile, but profiler is sampling and calls are near IO code so this can be imprecise).

Format method call can be replaced from this 
```java   
 out.write(String.format("\\u%04x", (int) c));
```

with something like this: 
```java    
out.write("\\u");
out.write(HEX_DIGITS[(c >> 12) & 15]);
out.write(HEX_DIGITS[(c >> 8) & 15]);
out.write(HEX_DIGITS[(c >> 4) & 15]);
out.write(HEX_DIGITS[c & 15]);
```

If my arguments seem reasonable I'm ready to create pull request with proper tests+benchmarks

**Comment by swankjesse** [comment]
Please send a PR!

**Comment by qwwdfsad** [comment]
Sorry, I've got overlapped older version of GSON due to my mistake. In current version this issue was fixed, so issue could be closed.
