### ISSUE TITLE
Parsing SparseArray return empty result

### ISSUE THREAD

**Issue by PaulProject** [google/gson#822]
I trying parse SparseArray, but gson return empty SparseArray, not null, just empty. What am I doing wrong?

**Comment by JakeWharton** [comment]
You need to write a custom TypeAdapter / JsonDeserializer for SparseArray since it is a collection type that Gson doesn't know about. There are some details on how to do this here: https://github.com/google/gson/blob/master/UserGuide.md#TOC-Custom-Serialization-and-Deserialization.
