### ISSUE TITLE
Lint: unused declarations

### ISSUE THREAD

**Issue by frakc** [google/gson#825]
If  `@SerializedName("id") @Expose private Integer id;` is assigned only via gson.fromJson Lint will warn, that field id is never assigned.
How to make lint know about such assignment or specificly ignore all checks if field is ever assigned, if field is annotated with `@SerializedName` ?

**Comment by marcosalis** [comment]
If you're using Android Studio, _Alt+Enter_ on the field warning, you'll find among other options "Suppress for fields annotated with `com.google.gson.annotations.SerializedName`".
You only need to do this once, but you'll have to export some of your Studio settings to the version control system for the rest of your team to adopt it automatically if necessary.

**Comment by inder123** [comment]
You can also use @SuppressWarnings("unused") on the class or the field.
