### ISSUE TITLE
Serialising "Bundle" in Android

### ISSUE THREAD

**Issue by kushaldr** [google/gson#842]
When tried to serialise a Model which contains Bundle as a member, Serialisation fails and run out of memory.

Code Snippet below:

[TempModel.java.zip](https://github.com/google/gson/files/246375/TempModel.java.zip)
           
TempModel t = new TempModel();

            Bundle b = new Bundle();
            b.putString("A", "a");

            t.setDataBundle(b);
            t.setId("A");

            Gson gs = new Gson();

            String jsonContent = gs.toJson(t, TempModel.class);
            Log.i("DF", "Temp Model -> New JSON : " + jsonContent);

**Comment by inder123** [comment]
You need to use a BundleTypeAdapterFactory. Something like this: 
https://github.com/google-gson/typeadapters/blob/master/android/src/main/java/BundleTypeAdapterFactory.java
