### ISSUE TITLE
gson-extras not available in The Central Repository

### ISSUE THREAD

**Issue by mfulton26** [google/gson#845]
Searching [The Central Repository](http://search.maven.org/) for [g:com.google.code.gson a:gson-extras](http://search.maven.org/#search%7Cga%7C1%7Cg%3Acom.google.code.gson%20a%3Agson-extras) reveals no results.

Is/will `gson-extras` be published? I'd like to be able to use the `UtcDateTypeAdapter` along with other extras.

Thank you.

**Comment by JakeWharton** [comment]
It's intentionally not published because we make not guarantees about API stability or compatibility. It exists so that you can copy them into your project and adapt as needed.

**Comment by mfulton26** [comment]
Okay. Thanks @JakeWharton for the explanation.
