### ISSUE TITLE
Bug: (De)Serialization of java.io.File

### ISSUE THREAD

**Issue by SteppXXL** [google/gson#849]
Hi there,

you have a bug while (de)serialization of java.io.File. There is a flag prefixLength that is not deserialized. For absolute files it must be greater than 0. Erroneously an absolute file that was serialized and deserialized is recognized as a relative file.

Easily reproducable with

gson(new File("/tmp/foo.txt"));

on

 private static void gson(File file) {
        System.out.println("++++++++++++ gson ++++++++++++");
        Gson gson = new Gson();
        System.out.println("file = " + file + " (absolute = " + file.getAbsoluteFile() + ")");
        String serialization = gson.toJson(file);
        File deserialization = gson.fromJson(serialization, File.class);
        System.out.println("deserialization = " + deserialization + " (absolute = "
                + deserialization.getAbsoluteFile() + ")");
    }

> ++++++++++++ gson ++++++++++++
> file = /tmp/foo.txt (absolute = /tmp/foo.txt)
> deserialization = /tmp/foo.txt (absolute = /home/stephan/zTest.Art.Id/tmp/foo.txt)

Regards
Stephan

**Comment by JakeWharton** [comment]
Java platform types should not be serialized like this since you are relying on their internals which are implementation details. Register a TypeAdapter which writes out `File.toString()` when serializing a `File` and reads the string an invokes `new File(String)` when deserializing.

**Comment by SteppXXL** [comment]
Well, I don't agree. File implements Serializable thus I expect GSON to be able to serialize it, too. But ok... 

Which java platform types are supported by GSON? At least it's String. Something else? E.g. java.lang.Integer.

By the way: On Unix serialize(new File(...).toString()) and on Windows new File(deserialize(...)) won't work because of the different file separator: '/' vs '\'.

**Comment by JakeWharton** [comment]
Serializable has nothing to do with JSON nor Gson. It's Java's native
(terrible) binary format.

As far as which platform types are supported, the answer is far too many.
There's a bunch of historical weakness in the types that contain native
adapters which needlessly bloats Gson and creates an endless stream of
people wanting more types added.

You'll want to stick to int, long, double, Integer, Long, Double, and
String as well as List and arrays of those types. These are the primitives
of JSON and thus those which map easily and directly. For anything else,
register your own type adapter to provide a sane, stable format which can
be dictated by your application requirements.

**Comment by SteppXXL** [comment]
Alright. Thanx for your reply.
