### ISSUE TITLE
No autocomplete with Eclipse

### ISSUE THREAD

**Issue by nyg** [google/gson#855]
Hello all,

I've made a very simple maven project in Eclipse, adding only one dependency, gson. For some reason I can't get any autocompletion for gson and Eclipse's Organize imports feature doesn't seem to be aware of the gson library. If I manually write the `import` statements and create a `Gson` using `GsonBuilder` then doing a `mvn clean package` from the command line will compile everything. It seems I have this problem only with gson.

Here's my POM:

```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    
    <groupId>edu.self.gson</groupId>
    <artifactId>gson-test</artifactId>
    <version>1.0-SNAPSHOT</version>
    
    <dependencies>
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.6.2</version>
        </dependency>
    </dependencies>
</project>
```

```java
package edu.self.gson.test;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

public class Main {

    public static void main(String[] args) {
        Gson gson = new GsonBuilder().create();
    }
}
```

Thanks for your help.

java 1.8.0_66
mvn 3.3.9
Eclipse Mars.2 JEE edition
OS X 10.11.4

**Comment by inder123** [comment]
Please don't ask questions like this on GitHub. StackOverflow is the right place.

Your local maven repo could be screwed up.
