### ISSUE TITLE
a little question while use Retrofi2 with gsonconvet

### ISSUE THREAD

**Issue by jiaruiz** [google/gson#856]
hi, android big big ~ I have a little question while i use **retrofit2** with **Gson** .here two kind repsones
One is
data : {"**response**":{"sex":"","phone":"","account_id":122,"status":0,
     "session_timeout":"","account_reg_type":1,"nick_name":"","time":"20160510174922",
      "weixin":"","address":"","email":"","session":"",
      "name":"","head":"","weibo":""},"time":"20160510174922"}

anthor is
"data":{"**response**":"","time":"20160517104147"} 

you konw,it will Expected BEGIN_OBJECT but was STRING at line 1 column 54 path.
i wish ,maybe gson can atuo ingore the type of responese while is empty string.or how fix it just in android not modify response format
excuse me, my engilish is poor

**Comment by JakeWharton** [comment]
You can use @JsonAdapter to write a TypeAdapterFactory which conditionally
deserializes the response either as an object or as a string.
