### ISSUE TITLE
Use gson with Proguard encouter some strange problem 

### ISSUE THREAD

**Issue by zhEdward** [google/gson#858]
tool : gson 2.6.2

My situation is : already append offical  examples  'proguard.cfg' content to my project and replace  this
`-keep class com.google.gson.examples.android.model.** { *; }`
 to myself  like
 `-keep class fxyy.lx.ktjxstu.bean.** { *; }`

when use ADT generate apk(obscured) and use `jadx-gui` to looking for `fxyy.lx.ktjxstu.bean` package  ,can't find it  ,It's strange that in project `mapping.txt` file. I sure this package classes didn't obscured  look this snippet:

<pre> fxyy.lx.ktjxstu.bean.Obj_Patch -> fxyy.lx.ktjxstu.bean.Obj_Patch:
    java.lang.String name -> name
    boolean hasloat -> hasloat
    java.lang.String getName() -> getName
    void setName(java.lang.String) -> setName
    boolean isHasloat() -> isHasloat
    void setHasloat(boolean) -> setHasloat
</pre>

My class snippet is：the class `variant` is the same as json `key`

<pre>
package fxyy.lx.ktjxstu.bean; 
/**
 * @author Administrator
 */
public class Obj_Patch {
    private String name;
    private boolean hasloat = false;
    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }
    public boolean isHasloat() {
        return hasloat;
    }
    public void setHasloat(boolean hasloat) {
        this.hasloat = hasloat;
    }
}
</pre>

Question: install apk to device when deserialized classes fail,   method `getName()` return null ,use try-catch can't get any relative error/waring log.

What  should i do ?

**Comment by zhEdward** [comment]
is my fault when i clean project ,is ok

**Comment by Marcono1234** [comment]
Sounds a bit like a ProGuard usage question; and given how old this issue is, it might not be relevant anymore.
