### ISSUE TITLE
Complex JSON deserialization

### ISSUE THREAD

**Issue by bkmlkc** [google/gson#859]
> How can I deserialize this complex JSON . 
> I want to access all Strings, objects. 
> For example SelectionId and AdditionalPriceInfo fields by indexing. 
> get(0).getSelectionId() --> d51d38c9-6e51-473c-b843-f24fef632f89

```
{
	"Status": 0,
	"Message": "",
	"Result": {
		"HasMore": "False",
		"Itineraries": [{
			"SelectionId": "d51d38c9-6e51-473c-b843-f24fef632f89",
			"AdditionalPriceInfo": null

		}, {
			"SelectionId": "dda40b80-d8e4-4b76-9f78-83297b52afe9",
			"AdditionalPriceInfo": null
		}]
	}
}
```

**Comment by inder123** [comment]
Ask this question on stackoverflow or on https://groups.google.com/forum/#!forum/google-gson
