### ISSUE TITLE
a bug at android phone(moto xt1085,android 5.1) about date

### ISSUE THREAD

**Issue by zgmf0757** [google/gson#866]
`String json = "{\"icon\":\"icon_warning_0201\",\"title1\":\"暴雨蓝色预警信号\",\"title2\":\"防御指南\",\"content\":\"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\",\"content2\":\"1.政府及相关部门按照职责做好防暴雨准备工作；2.学校、幼儿园采取适当措施，保证学生和幼儿安全；3.驾驶人员应当注意道路积水和交通阻塞，确保安全；4.检查城市、农田、鱼塘排水系统，做好排涝准备。\",\"valid\":\"May 29, 2016 6:17:13 PM\",\"video\":\"rain.mp4\"}";`
`java.lang.reflect.Type type1 = new TypeToken<Warning>() {}.getType();`
`Warning w = (Warning) new Gson().fromJson(json, type1);`
`System.out.println(w.getValid());`

In JSON String the date "May 29, 2016 6:17:13 PM" to java oject would be decoded as "May 29, 2016 6:17:13 AM"

It seems works good at which phone' system version lower then 5.0

**Comment by zgmf0757** [comment]
I find it can solve by ”new GsonBuilder().setDateFormat("pattern").create();“
But what's the pattern of "May 29, 2016 6:17:13 PM"

**Comment by zgmf0757** [comment]
Solve by this...
Gson gson = new GsonBuilder().setDateFormat("MMM d,yyyy h:m:s a").create();

**Comment by zshift** [comment]
@zgmf0757 since the issue was solved by forcing the date format, can you close the issue?
