### ISSUE TITLE
java.lang.StackOverflowError  com.google.gson.internal.$Gson$Types.resolve() @ Line: 372 in $Gson$Types.java

### ISSUE THREAD

**Issue by jikun2008** [google/gson#868]
android:  gson 1.7.1 do not have this bug,. but the higher have.   look at this log

com.google.gson.internal    $Gson$Types.java line 372 in com.google.gson.internal.$Gson$Types.resolve()
com.google.gson.internal    $Gson$Types.java line 376 in com.google.gson.internal.$Gson$Types.resolve()
com.google.gson.internal    $Gson$Types.java line 381 in com.google.gson.internal.$Gson$Types.resolve()
com.google.gson.internal    $Gson$Types.java line 376 in com.google.gson.internal.$Gson$Types.resolve()
com.google.gson.internal    $Gson$Types.java line 381 in com.google.gson.internal.$Gson$Types.resolve()
com.google.gson.internal    $Gson$Types.java line 376 in com.google.gson.internal.$Gson$Types.resolve()
com.google.gson.internal    $Gson$Types.java line 381 in com.google.gson.internal.$Gson$Types.resolve()
com.google.gson.internal    $Gson$Types.java line 376 in com.google.gson.internal.$Gson$Types.resolve()
com.google.gson.internal    $Gson$Types.java line 381 in com.google.gson.internal.$Gson$Types.resolve()
com.google.gson.internal    $Gson$Types.java line 376 in com.google.gson.internal.$Gson$Types.resolve()
com.google.gson.internal    $Gson$Types.java line 381 in com.google.gson.internal.$Gson$Types.resolve()
com.google.gson.internal    $Gson$Types.java line 376 in com.google.gson.internal.$Gson$Types.resolve()
com.google.gson.internal    $Gson$Types.java line 381 in com.google.gson.internal.$Gson$Types.resolve()
com.google.gson.internal    $Gson$Types.java line 376 in com.google.gson.internal.$Gson$Types.resolve()
com.google.gson.internal    $Gson$Types.java line 381 in com.google.gson.internal.$Gson$Types.resolve()
com.google.gson.internal    $Gson$Types.java line 376 in com.google.gson.internal.$Gson$Types.resolve()
com.google.gson.internal    $Gson$Types.java line 381 in com.google.gson.internal.$Gson$Types.resolve()
com.google.gson.internal    $Gson$Types.java line 376 in com.google.gson.internal.$Gson$Types.resolve()
com.google.gson.internal    $Gson$Types.java line 381 in com.google.gson.internal.$Gson$Types.resolve()
com.google.gson.internal    $Gson$Types.java line 376 in com.google.gson.internal.$Gson$Types.resolve()
com.google.gson.internal    $Gson$Types.java line 381 in com.google.gson.internal.$Gson$Types.resolve()
com.google.gson.internal    $Gson$Types.java line 376 in com.google.gson.internal.$Gson$Types.resolve()
com.google.gson.internal    $Gson$Types.java line 381 in com.google.gson.internal.$Gson$Types.resolve()
com.google.gson.internal    $Gson$Types.java line 376 in com.google.gson.internal.$Gson$Types.resolve()
com.google.gson.internal    $Gson$Types.java line 381 in com.google.gson.internal.$Gson$Types.resolve()
com.google.gson.internal    $Gson$Types.java line 376 in com.google.gson.internal.$Gson$Types.resolve()
com.google.gson.internal    $Gson$Types.java line 381 in com.google.gson.internal.$Gson$Types.resolve()
com.google.gson.internal    $Gson$Types.java line 376 in com.google.gson.internal.$Gson$Types.resolve()
com.google.gson.internal    $Gson$Types.java line 381 in com.google.gson.internal.$Gson$Types.resolve()
com.google.gson.internal    $Gson$Types.java line 376 in com.google.gson.internal.$Gson$Types.resolve()
com.google.gson.internal    $Gson$Types.java line 381 in com.google.gson.internal.$Gson$Types.resolve()
com.google.gson.internal    $Gson$Types.java line 376 in com.google.gson.internal.$Gson$Types.resolve()
com.google.gson.internal    $Gson$Types.java line 381 in com.google.gson.internal.$Gson$Types.resolve()
com.google.gson.internal    $Gson$Types.java line 376 in com.google.gson.internal.$Gson$Types.resolve()
com.google.gson.internal    $Gson$Types.java line 356 in com.google.gson.internal.$Gson$Types.resolve()
com.google.gson.internal.bind   ReflectiveTypeAdapterFactory.java line 141 in com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields()
com.google.gson.internal.bind   ReflectiveTypeAdapterFactory.java line 83 in com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create()
com.google.gson Gson.java line 359 in com.google.gson.Gson.getAdapter()
com.google.gson.internal.bind   ReflectiveTypeAdapterFactory.java line 122 in com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getFieldAdapter(

**Comment by JakeWharton** [comment]
What type are you serializing?

**Comment by jikun2008** [comment]
Class Object{
View view;  
}
View   is  import android.view.View;


I think View   cause  this Bug  right?
