### ISSUE TITLE
Brief Question About Google Gson Internal Interface

### ISSUE THREAD

**Issue by alinebrito** [google/gson#874]
Dear Google Gson developers,

I am a master student at UFMG, Brazil. Currently, I am researching the use of internal interfaces by client projects. I mean, public interfaces for use only by internal modules (e.g., com.google.gson.internal.Streams).

In my research, I found 54 internal interfaces in Google Gson (see the list at: [Internal Interfaces Google Gson](https://www.dropbox.com/s/3yap9k2nnsysjm6/)). By mining data provided by the [Boa Language and Infrastructure](http://boa.cs.iastate.edu/), I also found 147 client projects that are using these internal interfaces. Therefore, these internal interfaces are usual in other projects.

1. Did you know that internal interfaces are used by clients?
2. From the presented interfaces, there is some interface that is a candidate to be promoted to the public one?

**Comment by inder123** [comment]
Interesting info about the use of internal APIs, Aline.
I didn't quite know this, but am not very surprised.

None of these are candidates for promotion to public APIs.

**Comment by alinebrito** [comment]
Hi @inder123 

Thanks for the answer! It is very useful for my research.
