### ISSUE TITLE
GSON flagging Json Object as String

### ISSUE THREAD

**Issue by xelarmutz** [google/gson#877]
This is my Json {"success"=1} but I am getting this error : com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $.

I don't get it.

**Comment by JakeWharton** [comment]
Please provide an executable test case that shows the problem. You omitted your model object so it's impossible to know what you're doing.

**Comment by inder123** [comment]
Note that = is not valid JSON, you should use ":"

This question is not appropriate as a GitHub issue. Post on StackOverflow or on Gson Google Group.

**Comment by xelarmutz** [comment]
My bad. Thanks though, Got it to work. Cheers.
