### ISSUE TITLE
Make JsonPrimitive setValue public

### ISSUE THREAD

**Issue by Twilit-Soul** [google/gson#880]
Why is this method class protected?

I've been working with unpredictable json, so I can't put it into specific Java objects. I'm working with basic JsonElement objects and such. Everything was working fine up to the point where I tried to modify the primitive, so I could then deserialize it again later...but I can't directly modify primitive values. Simply having access to this method would let my program work perfectly, or even extending JsonPrimitive to make it public myself, but the class is final so I can't even do that.

**Comment by JakeWharton** [comment]
`JsonPrimitive` is immutable. If you need to change the value, create a new instance with the new value and replace it in the parent object.

**Comment by inder123** [comment]
@JakeWharton @swankjesse Well, JsonObject and JsonArray are not immutable, so we should consider this request.

**Comment by JakeWharton** [comment]
Those are collection types equivalent to `Map` and `List` though. `JsonPrimitive` is like `String` or `Long`.

**Comment by Twilit-Soul** [comment]
Gotcha. It's a bit of a pain to keep track of the parent each primitive is
part of rather than the way I had a reference to each primitive stored, but
I can see the reasoning behind it if Primitive is meant to be like String.
