### ISSUE TITLE
Implement NullObject pattern for JsonObject, JsonArray, JsonPrimitive

### ISSUE THREAD

**Issue by samiuelson** [google/gson#886]
There is `JsonNull` class extending JsonElement. But I'd find it very useful if the null object pattern was applied to JsonObject, JsonArray, JsonPrimitive classes as well. 
1. It'd introduce classes: `JsonObject.Empty` extending `JsonObject`, `JsonArray.Empty` extending `JsonObject` and `JsonPrimitive.Empty` extending `JsonPrimitive`. 
2. Create `isEmpty()` methods for JsonObject, JsonArray, JsonPrimitive

What do you think?

**Comment by JakeWharton** [comment]
Aside from the fact that this would be a major behavior change that
couldn't happen until a hypothetical Gson v3, these types are meant to
model the JSON data that's was parsed. Thischange  would make it impossible
to distinguish from an absent value and one that was present but empty (in
the case of array/object).

**Comment by samiuelson** [comment]
Ok, I see.
