### ISSUE TITLE
Gson interprets number as String

### ISSUE THREAD

**Issue by dzharikhin** [google/gson#894]
public class User {
    public String department;
}
User user = new Gson().fromJson("{\"department\": 123}", User.class); //user.department = "123";

and it should throw JsonSyntaxException

**Comment by swankjesse** [comment]
Use a TypeAdapter which is not lenient by default.
```
gson.getAdapter(User.class).read(...);
```

**Comment by dzharikhin** [comment]
Nope

**Comment by zshift** [comment]
Your `department` field needs to be changed to an int in order for it to be processed as an int. 

Change 
```
public class User {
    public String department;
}
```
to
```
public class User {
    public int department;
}
```

**Comment by inder123** [comment]
This is by design. Many Gson users prefer lenient behavior.
