### ISSUE TITLE
Unable to parse below JSON using GSON.

### ISSUE THREAD

**Issue by bloggersumitsoni** [google/gson#898]
I need to parse this json string and want to map it with my bean class.
Also I don't need to parse it via key index as index of the key might change.

{"keyobject": {"keyarray": ["key1", "key2", "key3"]},
"valueobject": [{"valuearray": ["arr1_val1", "arr1_val2","arr1_val3"]},
{"valuearray": ["arr2_val1", "arr2_val2","arr2_val3"]}]}

Please suggest.

**Comment by swankjesse** [comment]
Please use StackOverflow for usage questions.

**Comment by bloggersumitsoni** [comment]
I have first tried stackoverflow then on google gson group but no response from anyone.
Finally I have to try it here.

**Comment by swankjesse** [comment]
You'll need to study the Gson documentation and source code!

**Comment by bloggersumitsoni** [comment]
I tried to read the gson documentation but I didn't found a way to parse the above json format using GSON in which keys are all together and array of values are all together.
Any hint or suggestion will be highly appreciated.

**Comment by inder123** [comment]
point us to the StackOverflow thread and we will try to answer there.

**Comment by bloggersumitsoni** [comment]
The question has marked as duplicate on stackoverflow. Though I have posted a new one.
http://stackoverflow.com/questions/38877535/unable-to-parse-different-json-format-string-via-gson

Also find the similar question on google gson group through this link-
https://groups.google.com/forum/#!topic/google-gson/5P7H8GP1nfw
