### ISSUE TITLE
About gson.fromJson Question

### ISSUE THREAD

**Issue by pfzsteven** [google/gson#912]
Hi , I have a question about `gson.fromJson` .

`@SuppressWarnings("unchecked")
  public <T> T fromJson(Reader json, Type typeOfT) throws JsonIOException, JsonSyntaxException {
    JsonReader jsonReader = newJsonReader(json);
    T object = (T) fromJson(jsonReader, typeOfT);
    assertFullConsumption(object, jsonReader);
    return object;
  }`

So `JsonReader` not need close finally when it used?  Thank you .

**Comment by lwhiteley** [comment]
I have the same question.

This is leaving traces of json in memory.

Whats the reason for not closing the reader and writer?

**Comment by Marcono1234** [comment]
That method only wraps the given `Reader` in a `JsonReader`, it does _not_ close either of the readers. The caller has to call `close()` on the `Reader` to make sure all resources are released.
