### ISSUE TITLE
Enums

### ISSUE THREAD

**Issue by l3eta** [google/gson#914]
Enums always return null. 

`public static class EnumDeserial implements JsonDeserializer<Enum> {

	@Override
	public Enum deserialize(JsonElement je, Type type, JsonDeserializationContext jdc) throws JsonParseException {
		try {
			return Enum.valueOf((Class<Enum>) Class.forName(type.getTypeName()), je.getAsString());
		} catch (Exception ex) {
			throw new JsonParseException(ex.getMessage());
		}
	}

}`

Along with this of course 
`
b.registerTypeHierarchyAdapter(Enum.class, new EnumDeserial());
`

Example of why they don't work

I believe Java 1.5 is around your support target so this would be the patch to fix, I would figure out where this would go on your side but not my job :)

**Comment by JakeWharton** [comment]
We have tests proving that enums work: https://github.com/google/gson/blob/master/gson/src/test/java/com/google/gson/functional/EnumTest.java. If you believe there is a bug, please provide a failing test case.

**Comment by l3eta** [comment]
How do I get code mark up to work?

**Comment by JakeWharton** [comment]
https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/

**Comment by l3eta** [comment]
The problem came from incoming json was "val: upper" instead of "val: UPPER" I do believe returning null should be a JsonParseException
