### ISSUE TITLE
Gson.instance

### ISSUE THREAD

**Issue by piegamesde** [google/gson#915]
I often use `new Gson().xxx();` for quick serialization. How about a `Gson.instance` or a `Gson.instance()` to re-use that object easily? 
People are [doing it already](http://stackoverflow.com/questions/21709219/should-gson-be-declared-as-static-final) so I think the Gson class should add the line

     public static final Gson GSON= new Gson();

somewhere. I did not create a pull request since a) a pull request for only one line? and b) someone familiar to the API should say how to implement it exactly.

**Comment by JakeWharton** [comment]
The difference between projects declaring their own instance and Gson exposing a singleton instance is that when it's done in individual projects the user can choose the configuration options that they want.

**Comment by piegamesde** [comment]
But many times the Gson is used without any special configuration. Could adding this line do any damage elsewhere?

**Comment by inder123** [comment]
We have plenty of usecases where we use multiple instances of Gson. Having a single Gson.instance() method sets incorrect expectations and will cause confusion. You are not even typing more characters by using new Gson() instead of Gson.getInstance()
