### ISSUE TITLE
Gson Contexts should allow storing some state

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gson#92]
```
See discussion at http://groups.google.com/group/google-
gson/browse_thread/thread/2850010691ea09fb?hl=en
```

Original issue reported on code.google.com by `inder123` on 10 Jan 2009 at 4:24

**Comment by ziorufus** [comment]
Can anyone "attach the recipe on how to use `ThreadLocal`"?

**Comment by lgvr123** [comment]
For ThreadLocal example, see http://www.javacreed.com/gson-deserialiser-example/
