### ISSUE TITLE
java.lang.IllegalArgumentException: class java.text.DecimalFormat declares multiple JSON fields named maximumFractionDigits

### ISSUE THREAD

**Issue by digitalbuddha** [google/gson#920]
Similar to a closed issue https://github.com/google/gson/issues/399 but workaround mentioned by @JakeWharton does not work in this case.  

Hey guys I'm having same problem a bit more specific to android and can't get around it with `Exclusions`or `TypeAdapters`.  The problem stems from version upgrade of Android from M to N having an Class that contains  a `Map<String,T>` where `T` contains an instance of SimpleDateFormat.  

Consider following classes

```
public class Foo{
     Map<String, Bar> items;
}

public class Bar{
 SimpleDateFormat SIMPLE_DATE_FORMAT = new SimpleDateFormat(DATE_FMT, Locale.US);
}
```

We had a procedure that would create json from the above `Foo` class and save it to disk (when offline).  When the phone restarts it would inflate the model and sync to server.  Recently we started see crash logs due to 

```
java.lang.IllegalArgumentException: class java.text.DecimalFormat declares multiple JSON fields named maximumFractionDigits. 
```

 This issue arises only on phones that were upgrade to Android N. Digging deeper we saw that there was an implementation change in DateFormat under sdk 24 (Android N) which now causes the above exception.  If someone had a json string that was encoded with 23 and then decoded with 24 the parser bombs.  Now for the tricker problems.  We tried create a type adapter but because of generic type erasure our type adapter was not used for the `items` map.  Similar using an ExclusionStrategy also did not seem to make any difference.  I get that Type Adapters would work if Foo had a field of `SimpleDateFormat` but because we are using a generic map I can't seem to find a way to have our Type Adapter run.

Would appreciate help and apologies if this should instead by on the Android Tracker.

**Comment by swankjesse** [comment]
Why isn’t `SIMPLE_DATE_FORMAT` static?

**Comment by digitalbuddha** [comment]
Because of bad developers that should feel bad. Making the field static would fix this particular problem. The behavior in general is at issue. If a generic is used in a collection contained in another object, there does not seem to be a way to register a type adapter or exclusion strategy.  DateFormat could very well be any external dependency with a parent containing same field.   Ideally there should be a way to pass type tokens for collection<T> within another object in a similar manner that I can pass type token if I am just marshaling Collection<T>

**Comment by mr-e-** [comment]
I am seeing this issue as well in Android N. Any workarounds yet?

**Comment by Marcono1234** [comment]
Probably similar to https://github.com/google/gson/issues/399#issuecomment-180433206, you have to write a custom `TypeAdapter` for external classes. Otherwise you run into issues such as this one where a library or framework changes the internal structure of the class between versions and suddenly your serialization or deserialization code does not work anymore.
