### ISSUE TITLE
Add @Documented annotation to @SerializedName to help with generating javadoc

### ISSUE THREAD

**Issue by anagri** [google/gson#921]
All the retrofit methods have `@Documented` annotation, so they are documented when a javadoc is generated. It will be useful if we have `@Documented` annotation for `@SerializedName`, `@Expose`, `@Since`, `@Until` annotations in gson.

**Comment by inder123** [comment]
Yes, this is a good idea

**Comment by inder123** [comment]
https://github.com/google/gson/pull/922
