### ISSUE TITLE
Prevent Proguard from stripping interface info from TypeAdapterFactory implementations

### ISSUE THREAD

**Issue by ChaitanyaPramod** [google/gson#925]
Proguard strips away interface information from `TypeAdapterFactory` implementations. This leaves `@JsonAdapter(MyTypeAdapterFactory.class)` useless as `JsonAdapterAnnotationTypeAdapterFactory` doesn't detect the class to be a `TypeAdapterFactory` instance. See https://github.com/google/gson/blob/193349f4aa7eecf43cc6ebf104e218e704db21d9/gson/src/main/java/com/google/gson/internal/bind/JsonAdapterAnnotationTypeAdapterFactory.java#L60

The solution would involve updating the proguard snippet to keep all `TypeAdapterFactory` implementations

**Comment by ChaitanyaPramod** [comment]
Now that I think about it, this applies to `JsonSerializer` and `JsonDeserializer` instances as well

**Comment by inder123** [comment]
Ok. Can you send another PR? Thanks.

**Comment by ChaitanyaPramod** [comment]
The merged PR #926 already keeps `JsonSerializer` and `JsonDeserializer` implementations.
Cheers! 😊
