### ISSUE TITLE
Self-reference tests are inconsistent

### ISSUE THREAD

**Issue by w4bo** [google/gson#927]
Self-reference is not supported by gson serialization (see [CircularReferenceTest.java](https://github.com/google/gson/blob/master/gson/src/test/java/com/google/gson/functional/CircularReferenceTest.java)). However, it is required in gson-extras (see [GraphAdapterBuilderTest.java](https://github.com/google/gson/blob/ee8d6be59ff6f2466d65be746b96ccf07ddb9ddf/extras/src/test/java/com/google/gson/graph/GraphAdapterBuilderTest.java)).

Test "testSerializationDirectSelfReference" in [GraphAdapterBuilderTest.java](https://github.com/google/gson/blob/ee8d6be59ff6f2466d65be746b96ccf07ddb9ddf/extras/src/test/java/com/google/gson/graph/GraphAdapterBuilderTest.java) is inconsistent with "testSelfReferenceIgnoredInSerialization" in [CircularReferenceTest.java](https://github.com/google/gson/blob/master/gson/src/test/java/com/google/gson/functional/CircularReferenceTest.java). Fixing the former breaks the latter.

**Comment by swankjesse** [comment]
How do both sets of tests pass?

**Comment by w4bo** [comment]
That is the fact. They do not pass together as they are complementary, so why keeping both? 

I try to give a better explanation: gson-extras depends on gson. The former has a test which asserts that _direct self-reference_ serialization works (_testSerializationDirectSelfReference_). The latter has a test which asserts that self-reference is not supported (_testSelfReferenceIgnoredInSerialization_). If _testSelfReferenceIgnoredInSerialization_ passes, then _testSerializationDirectSelfReference_ must fail.

Is it useful to open a pull request to make gson-extras support direct self-serialization? This solution may impact the gson main project.

**Comment by swankjesse** [comment]
They _do_ both pass.

**Comment by cuibg** [comment]
:+1:

**Comment by amogilev** [comment]
gson-extra's version works because it registers a custom adapter (see GraphAdapterBuilder), which does support limited self-references in the reigistered types ('Roshambo.class' in the test). Without that adapter, the test would fail.
So, it all works as expected.
