### ISSUE TITLE
useDefaultManifestFile deprecated in Maven JAR Plugin

### ISSUE THREAD

**Issue by enhdless** [google/gson#928]
[Maven JAR Plugin 3.0](https://maven.apache.org/plugins/maven-jar-plugin/) removes useDefaultManifestFile, which is currently used in [pom.xml](https://github.com/google/gson/blob/master/pom.xml). The file should be updated or a version number should be added.

**Comment by inder123** [comment]
Thanks. Can you send a pull request to fix?
