### ISSUE TITLE
Problems with Gson library. Passing Info in Intent

### ISSUE THREAD

**Issue by jose920405** [google/gson#929]
Have a bug with `Gson` when call `fromJson` func the object come bad. 

I'm passing `toJson`a `Video` object, model from youtube. 

**Code:**

When pass:

    Gson gson = new Gson();
    String myJson = gson.toJson(ytVideo); //ytvideo ==> com.google.api.services.youtube.model.Video
    i.putExtra("youtubeVideo", myJson);

When Receive:

    Gson gson = new Gson();
    youtubeVideo = gson.fromJson(getIntent().getStringExtra("youtubeVideo"), Video.class);

The error is
>field `com.google.api.services.youtube.model.Video.contentDetails` has type `com.google.api.services.youtube.model.VideoContentDetails`, got `com.google.gson.internal.LinkedTreeMap` .

 I suppose that `Gson` fails when trying to repair my object Video.

http://stackoverflow.com/questions/39535222/problems-with-gson-library-passing-info-in-intent

**Comment by JakeWharton** [comment]
StackOverflow is the right place for usage questions. This isn't a bug with the library. This happens when you have a generic type (presumably `Video`) and are not passing generic information with a `TypeToken`.
