### ISSUE TITLE
Security scan reported problem with com.google.gson.internal.StringMap

### ISSUE THREAD

**Issue by venusjain10** [google/gson#933]
We are using GSON APIs in our project and security scan on our code has reported following problem. Could you please let me know if this is of any concern or it can be fixed in new version of this API.

**Problem:** Standard random number generators do not provide a sufficient amount of entropy when used for security purposes. Attackers can brute force the output of pseudorandom number generators such as rand().
**Recommendations (Generated by tool)**
If this random number is used where security is a concern, such as generating a session identifier or cryptographic key, use a trusted cryptographic random number generator instead

com.google.gson.internal.StringMap

**Comment by JakeWharton** [comment]
This type no longer exists.

**Comment by abhisheksharma43** [comment]
Does that mean switching to the latest API version would resolve the issue?

**Comment by JakeWharton** [comment]
It means whatever issue you purport to have found doesn't exist in the
latest version and thus is hard to access.
