### ISSUE TITLE
Security scan reported problem with com.google.gson.stream.JsonReader 

### ISSUE THREAD

**Issue by venusjain10** [google/gson#934]
We are using GSON APIs in our project and security scan on our code has reported following problem. Could you please let me know if this is of any concern or it can be fixed in new version of this API.

**Problem:** Using '==' to compare two strings for equality or '!=' for inequality actually compares the object references rather than their values. It is unlikely that this reflects the intended application logic.

**Recommendations (Generated by tool)**
Use the equals() method to compare strings, not the '==' or '!=' operator

**Class:**
 com.google.gson.stream.JsonReader

**Comment by JakeWharton** [comment]
There are no string comparisons. Only char or int.
