### ISSUE TITLE
Serialization randomly hangs with Retrofit

### ISSUE THREAD

**Issue by NoHarmDan** [google/gson#939]
Hello,

When using Retrofit's Gson Converter, the serialization sometimes randomly hangs as [described in this StackOverflow question](http://stackoverflow.com/questions/34735639/retrofit-realmlist-gson-stuck-in-a-loop-until-out-of-memory). With the only difference that it doesn't run out of memory but ultimately after several minutes (3-7) sends the request and gets response normally.

I blamed it on Realm, [as described in this Retrofit issue thread](https://github.com/square/retrofit/issues/2040), but it turns out the same issue happens with the simplest POJOs as well. There are no circular references and I wouldn't expect lists, inheritance and object attributes to be the cause (happens also with objects that only have the simplest attribute types, for example integers and strings).

I'm using Retrofit v2.1.0, build tools v23.0.3, target SDK v23 and compile SDK v24. I have tried older versions of Gson Converter and other SDK combinations to no effect - although it seems this problem didn't start happening until about a week ago, after a release of an SDK update (I'm uncertain about that though, because we started noticing the problem very slowly and can't really tell the circumstances of when it started to happen.)

**Comment by JakeWharton** [comment]
Please provide a test case

**Comment by NoHarmDan** [comment]
When using Retrofit 2.1.1 snapshot and not trying to convert RealmObjects, all works just fine. It was probably a combination of issues with Realm and Retrofit not closing all connections. (Curiously trying to convert Json into a RealmObject works with no issues whatsoever.)

**Comment by inder123** [comment]
I have seen that the current InputStreamReader hangs if the response is too big.
Retrofit should consider wrapping it in BufferedReader, @JakeWharton.

**Comment by JakeWharton** [comment]
Retrofit uses Okio not java.io. There's already a layer of buffering
beneath the Reader we pass to Gson.
