### ISSUE TITLE
"type" field in RuntimeTypeAdapterFactory is getting removed from JSON

### ISSUE THREAD

**Issue by aravinds03** [google/gson#940]
Hi,
In https://github.com/google/gson/blob/master/extras/src/main/java/com/google/gson/typeadapters/RuntimeTypeAdapterFactory.java#L202, I see that "type" field is getting removed while reading JSON. 

Hence, I am not able to identify exact subType without using this field now. Instead, I have to use "instanceof" to identify what exact sub-class is de-serialized from gson lib.

Is there any reason why you are altering the JSON?
If yes, what is the best way to identify the exact sub-class after retrieving the object ?

**Comment by inder123** [comment]
Look at the class RuntimeTypeAdapterFactory in 
https://github.com/google/gson/blob/master/gson/src/test/java/com/google/gson/functional/RuntimeTypeAdapterFactoryFunctionalTest.java that does what you are asking for.

**Comment by aravinds03** [comment]
Are you saying that I should copy-paste the RuntimeTypeAdapterFactory class defined in FunctionalTest file?

Shouldn't be fixed in extras package itself?
