### ISSUE TITLE
GsonDesignDocument question

### ISSUE THREAD

**Issue by voipp** [google/gson#947]
In https://github.com/google/gson/blob/master/GsonDesignDocument.md you stated that "Some Json libraries use the getters of a type to deduce the Json elements". Why do they do that ?

**Comment by inder123** [comment]
This is similar to past serialization approaches, such as hibernate.

**Comment by Marcono1234** [comment]
Closing since this question was answered, and it would probably make more sense to ask that the authors of the other JSON libraries.
