### ISSUE TITLE
ReflectiveTypeAdapterFactory not tolerant to duplicate static fields across superclasses

### ISSUE THREAD

**Issue by Dico200** [google/gson#949]
Example:
If a class extends Serializable multiple times, through superclasses, and throughout the class and its superclasses the static field serialVersionUID is specified more than once (there's a duplicate field), the factory will throw an exception for it if both are to be serialized.

**Comment by Marcono1234** [comment]
Do you really need to serialize / deserialize static fields or are your field exclusion modifiers possibly by accident missing an exclusion for static fields? It is rather uncommon that you have to serialize static fields (and deserialization of static fields is pretty error-prone).
Additionally, do you really need to serialize `serialVersionUID`? If not, then maybe you should set an exclusion strategy which [ignores that field](https://javadoc.io/static/com.google.code.gson/gson/2.9.0/com.google.gson/com/google/gson/ExclusionStrategy.html#shouldSkipField(com.google.gson.FieldAttributes)).

**Comment by Dico200** [comment]
I have no answers to that, I'm gonna go ahead and close this issue assuming irrelevance after 6 years.
