### ISSUE TITLE
Objects as keys extension

### ISSUE THREAD

**Issue by SoniEx2** [google/gson#952]
GSON already supports comments. Can we get [objects as keys](http://stackoverflow.com/questions/40296396/how-can-i-use-objects-as-keys-in-a-json)? They'd be very nice to have.

**Comment by niusounds** [comment]
I don't think it is good to support this syntax. It's not JSON.

**Comment by SoniEx2** [comment]
It's a nice syntax.

**Comment by Marcono1234** [comment]
Gson supports [serializing `Map` instances with complex keys as JSON array](https://javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/GsonBuilder.html#enableComplexMapKeySerialization()). Though I assume the project members will be reluctant to make lenient mode even more lenient to allow the syntax you are proposing.

**Comment by eamonnmcmanus** [comment]
Indeed, the primary purpose of Gson is to serialize and deserialize JSON. Lenient mode is at best questionable, and we certainly aren't interested in adding new non-compliant syntaxes.
