### ISSUE TITLE
GSON release 2.8.0 JAR is not an OSGI bundle

### ISSUE THREAD

**Issue by iamrakesh** [google/gson#957]
Hi,
GSON release 2.8.0 JAR published to/available from maven repository is not an OSGI bundle; MANIFEST file doesn't contain OSGI specific info.

2.8.0 JAR MANIFEST.MF contains

`Manifest-Version: 1.0
Archiver-Version: Plexus Archiver
Built-By: jwilson
Created-By: Apache Maven 3.2.3
Build-Jdk: 1.8.0_92
`

where as 2.7.0 JAR MANIFEST.MF contains

`Manifest-Version: 1.0
Bundle-Description: Gson JSON library
Bundle-SymbolicName: com.google.gson
Archiver-Version: Plexus Archiver
Built-By: inder
Bnd-LastModified: 1465948546904
Bundle-ManifestVersion: 2
Bundle-RequiredExecutionEnvironment: J2SE-1.5, JavaSE-1.6, JavaSE-1.7,
  JavaSE-1.8
Bundle-Vendor: Google Gson Project
Import-Package: com.google.gson.annotations
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.6))"
Bundle-ContactAddress: https://github.com/google/gson
Tool: Bnd-3.1.0.201512181341
Export-Package: com.google.gson;uses:="com.google.gson.reflect,com.goo
 gle.gson.stream";version="2.7.0",com.google.gson.annotations;version=
 "2.7.0",com.google.gson.reflect;version="2.7.0",com.google.gson.strea
 m;version="2.7.0"
Bundle-Name: Gson
Bundle-Version: 2.7.0
Created-By: 1.8.0_91 (Oracle Corporation)
Build-Jdk: 1.8.0_91
`
Regards,
Rakesh.A

**Comment by cameronoxley** [comment]
+1

**Comment by roedll** [comment]
+1

**Comment by inder123** [comment]
Please send a pull request @iamrakesh

**Comment by Singleton06** [comment]
Is there any reason that the manifest generated through the bnd-maven-plugin[1] isn't getting used in the released JAR?  I'm not overly familiar with all that GSON does for their development practice, but I have noticed that there are certain versions of the gson do not have a manifest at all (such as the above).

[1] - https://github.com/google/gson/blob/master/gson/pom.xml#L34-L47

**Comment by iamrakesh** [comment]
If understand the documentation for 'bnd-maven-plugin', available at https://github.com/bndtools/bnd/tree/master/maven/bnd-maven-plugin correctly; add this plugin generates 'MANIFEST.MF' with all OSGI information and places it in output directory.
If we want to use this manifest file, we've to change the way JAR plugin is configured, See - https://github.com/bndtools/bnd/tree/master/maven/bnd-maven-plugin#important-note
It seems GSON Jar is generated with the generated MANIFEST some times and sometimes not.

**Comment by Singleton06** [comment]
Yes, you would have to update the maven-jar-plugin to always use the manifest created by the maven-bnd-plugin. I'm not sure of a situation where you wouldn't want it, but I might not be aware of other consumers that this would influence...

**Comment by bosschaert** [comment]
+1 for getting this issue resolved.

**Comment by larsp** [comment]
👍

**Comment by cristcost** [comment]
+1 for this issue. I exclusively use GSON in osgi environment...

**Comment by cristcost** [comment]
It seems the 2.8.1-SNAPSHOT now has OSGi headers back, right?

![image](https://cloud.githubusercontent.com/assets/2135798/24207624/a4bce20c-0f21-11e7-95c0-5e28b78d397e.png)

it also seems ok if installed into Karaf

![image](https://cloud.githubusercontent.com/assets/2135798/24207658/c180f90a-0f21-11e7-8594-113fa52e9d04.png)

**Comment by iamrakesh** [comment]
It seems [this](https://github.com/google/gson/commit/08c7bffba0e93611162cadfaf2ee03e3d143e7d1#diff-b870e20e5600e8e051854b3fa6a8a1b5) check-in makes it work.

Though I have one observation on the generated MANIFEST.MF -
'Import-Package' manifest entry is not correct, I think it should be 'Private-Package'.

**Comment by Marcono1234** [comment]
Looks like this was fixed by #994.
