### ISSUE TITLE
Design Document links to old site, which links back to Github

### ISSUE THREAD

**Issue by gatchi** [google/gson#958]
The link to the Design Document on the User Guide on github links to an old site for this project (https://sites.google.com/site/gson/gson-design-document), which links to the same github the User Guide is hosted on (https://github.com/google/gson/blob/master/GsonDesignDocument.md).  Might as well link directly instead using a beautiful, giant "**THIS PAGE HAS BEEN MOVED TO GITHUB AT**:" indirect redirect.

**Comment by inder123** [comment]
Thanks for the bug report.
