### ISSUE TITLE
null-valued properties are not serialized

### ISSUE THREAD

**Issue by jedwards1211** [google/gson#959]
```java
JsonObject obj = new JsonObject();
obj.add("hello", JsonNull.INSTANCE);
System.out.println(new Gson().toJson(obj));
```
Expected output: `{"hello": null}`
Actual output: `{}`
GSON 2.8.0

**Comment by ytRino** [comment]
By default, `null` fields are ignored.
See https://github.com/google/gson/blob/master/UserGuide.md#TOC-Null-Object-Support

**Comment by jedwards1211** [comment]
Oh, okay, thanks for letting me know.  Is this the default for any other JSON libraries?  I know it's not the default for `JSON.stringify` in JS.

**Comment by JakeWharton** [comment]
It's the default for all of the big ones for Java for surem
