### ISSUE TITLE
Escaping throws exception when escaping a non special character

### ISSUE THREAD

**Issue by laxika** [google/gson#960]
Escaping throws a MalformedJsonException when trying to escape a character that's not special and doesn't require escaping.

Example:
`
{
  "property": "123456\!@"
}
`

As far as I know the [RFC ](https://tools.ietf.org/html/rfc7159#section-7)says that:

> "Any character may be escaped."

It's broke first in 2.7 in the https://github.com/google/gson/commit/3f8726ecafe9c40498255eed1d1893fd665e237b commit.

This is a problem for us because we have a huge amount of json files to read and can't replace the occurrence of this ambiguous escaping because it happens a LOT of times.

**Comment by swankjesse** [comment]
When the spec says “any character may be escaped” it means that any character may be replaced with a `\u0000` escape. It doesn’t mean that any character can be preceded by a `\`.
