### ISSUE TITLE
Expected BEGIN_OBJECT but was STRING

### ISSUE THREAD

**Issue by lby1992** [google/gson#965]
I'm using Gson lib to deserialize the json stirng into Java object, but there is a error occurs.<br>
below is the json string:
<pre>
<code>
{
    "pageInfo": [
      {
        "detail": "{\"key1\":\"value1\",\"key2\":\"value2\"}",
        "id": 4,
        "type": 0
      }]
}
</code>
</pre>
and the java class:
<pre>
<code>
public java.util.List<CreditDetailItem> pageInfo;
class CreditDetailItem {
    public String id;
    public int type;
    public String detail;
}
</code>
</pre>
And then an exception thrown: ‘Expected BEGIN_OBJECT but was STRING’ on the 'detail' property.
<p>
Is there any one can help me?

**Comment by lby1992** [comment]
Sorry, I didn't build the project after, it runs fine when I rebuild the project.

**Comment by leafseelight** [comment]
You could use fastjson, it can solve the problem.
