### ISSUE TITLE
@JsonAdapter's documentation does not mention support for JsonSerializer and JsonDeserializer

### ISSUE THREAD

**Issue by kevinmost** [google/gson#975]
The documentation [here](https://github.com/google/gson/blob/master/gson/src/main/java/com/google/gson/annotations/JsonAdapter.java#L79) and further down the page [here](https://github.com/google/gson/blob/master/gson/src/main/java/com/google/gson/annotations/JsonAdapter.java#L94) only mentions that `TypeAdapter` and `TypeAdapterFactory` are supported at the moment. 

However, according to the [changelog](https://github.com/google/gson/blob/master/CHANGELOG.md#version-27), as of version 2.7, `JsonSerializer` and `JsonDeserializer` are also supported. 

I'm happy to submit a pull request and add this documentation if it's useful.

**Comment by inder123** [comment]
Yes, please send a PR. Thanks.

**Comment by kevinmost** [comment]
@inder123 #976
