### ISSUE TITLE
convert java object to json (writeValue)

### ISSUE THREAD

**Issue by dataSQL** [google/gson#978]
Hello, please:

How may I accomplish converting a POJO into a JSON (writeValue) with BOTH a Model bean and a managed bean that connects the MODEL to a remote MySQL data source?

[http://stackoverflow.com/questions/41142802/jsf-managed-bean-accessing-mysql-remote-database-how-to-create-json-array-to-f](url)

Any suggestions greatly appreciated.

Jon

**Comment by Marcono1234** [comment]
The StackOverflow links says "This question was voluntarily removed by its author.", so I assume this is no longer relevant?
