### ISSUE TITLE
Reading strings with white spaces - JsonReader

### ISSUE THREAD

**Issue by rmpt** [google/gson#981]
I'm using read method of TypeAdapter to read a Json message where some values consists of strings with white spaces. 
It seems that readString, skipValue or any method to consume the json value (with white spaces) do not work correctly and drives the app to a MalFormedException trying to consume next characters.
Debugging the app I found that pointer position is in the white space when the exception occure, so it seems that for some reason the parser assumes that the end of the value is in the space and not in the the next comma. Requesting the data from the browser I see that all names and values are wrapped in double quotes, but on JsonReader there's no double quotes. There's some property that I must change? Lenient property is set to true, I cannot find any other property to change this behavior.

Can you please check it out? JsonReader is a great tool but this little issue is very prohibitive. Thanks

**Comment by hgschwibbe** [comment]
Same problem in our project. We use Gson 2.7.

**Comment by osip-000** [comment]
Try this. It's fix for me
`gson.fromJson(gson.toJson(<your_data>), YourClassName::class.java)`

**Comment by perkins4j2** [comment]
mark

**Comment by sachithKay** [comment]
you can try 'quoting' the text.
```
"\"VALUE_1 VALUE_2\""
```

**Comment by Marcono1234** [comment]
I am going to close this because no specific example has been provided (it seems sachithKay only provided a way how to solve this).

If you still experience this with the latest Gson version, feel free to comment here or create a new Issue or Discussion.
