### ISSUE TITLE
not initialize int fields with zero

### ISSUE THREAD

**Issue by mahermeg17** [google/gson#985]
Hi,

I have an int field in my object but not defined into the json string.
when Gson create objects from the json, it initiate the int field by zero even it's initiated into the class definition [ int x= -1; ]
I need to initiate it with (-1).

any way to do that ? (without setting the field by a setter after parsing)

Thanks in advance,

**Comment by JakeWharton** [comment]
Add a no-args constructor to the type.

**Comment by mahermeg17** [comment]
thanks. it works.
