### ISSUE TITLE
JsonReader accepts Booleans regardless of case, with no way to find original value.

### ISSUE THREAD

**Issue by toddobryan** [google/gson#988]
Contrary to the spec at http://www.ietf.org/rfc/rfc7159.txt, the `JsonReader` class accepts not only `true` and `false` as valid Boolean values, but `TRUE` and `FALSE`, `True` and `False`, and even `TrUe` and `fAlSe`. This occurs no matter what the value of `lenient` is set to.

In writing my own `TypeAdapter`, I'd like to be able to decide whether I'll only accept `true` and `false` or whether other mixtures of case would be acceptable, but there's no `public` method I can find that will let me access the next token itself.

It seems like it should be possible to have `peek()` only return a `JsonToken.BOOLEAN` if the next value is really `true` or `false` and then have a `JsonToken.UNQUOTED_VALUE` that people could check for if they wanted to accept alternate cased versions.

Is this an oversight, a conscious design decision, or something no one else has complained about?

**Comment by Marcono1234** [comment]
This is at least now mentioned in the documentation for `JsonReader.setLenient` (see #2122) but that does not necessarily mean that this behavior is desired.

(though I am not a direct project member)

**Comment by Marcono1234** [comment]
The new `Strictness` API added in Gson 2.11.0 can be used to disallow these non-confirming JSON boolean values, see [`JsonReader#setStrictness`](https://www.javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/stream/JsonReader.html#setStrictness(com.google.gson.Strictness)).
