### ISSUE TITLE
Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT

### ISSUE THREAD

**Issue by gdutxiaoxu** [google/gson#990]
When I use Gson,I'm trying to parse a JSON string like this one

```
{"showapi_res_code": 0,
  "showapi_res_error": "1",
  "showapi_res_body": {
    "totalNum": 44,
    "ret_code": 0
   }
 }
```

When I use this like below,it is ok

Bean bean = gson.fromJson(stringFromSource, 
				Bean.class);

```
public class Bean{
    int showapi_res_code;
    String showapi_res_error;
    Body showapi_res_body;
    
    public static class Body{
        int totalNum;
        int ret_code;
    }
}
```

But when I use this like follow

	Bean1 bean1 = gson.fromJson(stringFromSource, Bean1.class);

```
public class Bean1 {
	int showapi_res_code;
    String showapi_res_error;
    String showapi_res_body;
    
   
}
```

It is error

> Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 3 column 24 path $.showapi_res_body

What should I to to suppport this style for Gson? Tanke you very mush.

**Comment by JakeWharton** [comment]
Why are you trying to use the second version? `showapi_res_body` is clearly not a string in the response, it's an object with two key/value pairs?

Please ask usage questions on StackOverflow using the 'gson' tag. This issue tracker is for bugs and feature requests only.

**Comment by leafseelight** [comment]
You could use fastjson, it can solve the problem.
