### ISSUE TITLE
serialize UsbDevice

### ISSUE THREAD

**Issue by mneckoee** [google/gson#991]
I can serialize UsbDevice with Gson  (too slowly) but cannot deserialize it !

**Comment by JakeWharton** [comment]
`UsbDevice` is a platform type from Android. There's no guarantee that its fields can be serialized or that it can be deserialized. You should not try to serialize it directly, but instead use an alternate representation that you control.

Unfortunately it's far too late to prevent serializing `java.*` and `android.*` types with Gson, but ideally that's what you should be doing.
